# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_initdef', [dirname(__file__)])
        except ImportError:
            import _initdef
            return _initdef
        if fp is not None:
            try:
                _mod = imp.load_module('_initdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _initdef = swig_import_helper()
    del swig_import_helper
else:
    import _initdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_initdef.INIT_K_DENSITY_800_BPI_swigconstant(_initdef)
INIT_K_DENSITY_800_BPI = _initdef.INIT_K_DENSITY_800_BPI

_initdef.INIT_K_DENSITY_1600_BPI_swigconstant(_initdef)
INIT_K_DENSITY_1600_BPI = _initdef.INIT_K_DENSITY_1600_BPI

_initdef.INIT_K_DENSITY_6250_BPI_swigconstant(_initdef)
INIT_K_DENSITY_6250_BPI = _initdef.INIT_K_DENSITY_6250_BPI

_initdef.INIT_K_DENSITY_SINGLE_DISK_swigconstant(_initdef)
INIT_K_DENSITY_SINGLE_DISK = _initdef.INIT_K_DENSITY_SINGLE_DISK

_initdef.INIT_K_DENSITY_DOUBLE_DISK_swigconstant(_initdef)
INIT_K_DENSITY_DOUBLE_DISK = _initdef.INIT_K_DENSITY_DOUBLE_DISK

_initdef.INIT_K_DENSITY_DD_DISK_swigconstant(_initdef)
INIT_K_DENSITY_DD_DISK = _initdef.INIT_K_DENSITY_DD_DISK

_initdef.INIT_K_DENSITY_HD_DISK_swigconstant(_initdef)
INIT_K_DENSITY_HD_DISK = _initdef.INIT_K_DENSITY_HD_DISK

_initdef.INIT_K_DENSITY_COMPACT_swigconstant(_initdef)
INIT_K_DENSITY_COMPACT = _initdef.INIT_K_DENSITY_COMPACT

_initdef.INIT_K_DENSITY_ED_DISK_swigconstant(_initdef)
INIT_K_DENSITY_ED_DISK = _initdef.INIT_K_DENSITY_ED_DISK

_initdef.INIT_K_HOMEBLOCKS_GEOMETRY_swigconstant(_initdef)
INIT_K_HOMEBLOCKS_GEOMETRY = _initdef.INIT_K_HOMEBLOCKS_GEOMETRY

_initdef.INIT_K_HOMEBLOCKS_FIXED_swigconstant(_initdef)
INIT_K_HOMEBLOCKS_FIXED = _initdef.INIT_K_HOMEBLOCKS_FIXED

_initdef.INIT_K_HOMEBLOCKS_CONTIGUOUS_swigconstant(_initdef)
INIT_K_HOMEBLOCKS_CONTIGUOUS = _initdef.INIT_K_HOMEBLOCKS_CONTIGUOUS

_initdef.INIT_S_BADBLOCKS_LBN_DEF_swigconstant(_initdef)
INIT_S_BADBLOCKS_LBN_DEF = _initdef.INIT_S_BADBLOCKS_LBN_DEF

_initdef.INIT_S_BADBLOCKS_SEC_DEF_swigconstant(_initdef)
INIT_S_BADBLOCKS_SEC_DEF = _initdef.INIT_S_BADBLOCKS_SEC_DEF

_initdef.INIT__ACCESSED_swigconstant(_initdef)
INIT__ACCESSED = _initdef.INIT__ACCESSED

_initdef.INIT__BADBLOCKS_LBN_swigconstant(_initdef)
INIT__BADBLOCKS_LBN = _initdef.INIT__BADBLOCKS_LBN

_initdef.INIT__BADBLOCKS_SEC_swigconstant(_initdef)
INIT__BADBLOCKS_SEC = _initdef.INIT__BADBLOCKS_SEC

_initdef.INIT__CLUSTERSIZE_swigconstant(_initdef)
INIT__CLUSTERSIZE = _initdef.INIT__CLUSTERSIZE

_initdef.INIT__COMPACTION_swigconstant(_initdef)
INIT__COMPACTION = _initdef.INIT__COMPACTION

_initdef.INIT__NO_COMPACTION_swigconstant(_initdef)
INIT__NO_COMPACTION = _initdef.INIT__NO_COMPACTION

_initdef.INIT__DENSITY_swigconstant(_initdef)
INIT__DENSITY = _initdef.INIT__DENSITY

_initdef.INIT__DIRECTORIES_swigconstant(_initdef)
INIT__DIRECTORIES = _initdef.INIT__DIRECTORIES

_initdef.INIT__ERASE_swigconstant(_initdef)
INIT__ERASE = _initdef.INIT__ERASE

_initdef.INIT__NO_ERASE_swigconstant(_initdef)
INIT__NO_ERASE = _initdef.INIT__NO_ERASE

_initdef.INIT__EXTENSION_swigconstant(_initdef)
INIT__EXTENSION = _initdef.INIT__EXTENSION

_initdef.INIT__FPROT_swigconstant(_initdef)
INIT__FPROT = _initdef.INIT__FPROT

_initdef.INIT__HEADERS_swigconstant(_initdef)
INIT__HEADERS = _initdef.INIT__HEADERS

_initdef.INIT__HIGHWATER_swigconstant(_initdef)
INIT__HIGHWATER = _initdef.INIT__HIGHWATER

_initdef.INIT__NO_HIGHWATER_swigconstant(_initdef)
INIT__NO_HIGHWATER = _initdef.INIT__NO_HIGHWATER

_initdef.INIT__INDEX_BEGINNING_swigconstant(_initdef)
INIT__INDEX_BEGINNING = _initdef.INIT__INDEX_BEGINNING

_initdef.INIT__INDEX_BLOCK_swigconstant(_initdef)
INIT__INDEX_BLOCK = _initdef.INIT__INDEX_BLOCK

_initdef.INIT__INDEX_END_swigconstant(_initdef)
INIT__INDEX_END = _initdef.INIT__INDEX_END

_initdef.INIT__INDEX_MIDDLE_swigconstant(_initdef)
INIT__INDEX_MIDDLE = _initdef.INIT__INDEX_MIDDLE

_initdef.INIT__INTERCHANGE_swigconstant(_initdef)
INIT__INTERCHANGE = _initdef.INIT__INTERCHANGE

_initdef.INIT__NO_INTERCHANGE_swigconstant(_initdef)
INIT__NO_INTERCHANGE = _initdef.INIT__NO_INTERCHANGE

_initdef.INIT__LABEL_ACCESS_swigconstant(_initdef)
INIT__LABEL_ACCESS = _initdef.INIT__LABEL_ACCESS

_initdef.INIT__LABEL_VOLO_swigconstant(_initdef)
INIT__LABEL_VOLO = _initdef.INIT__LABEL_VOLO

_initdef.INIT__MAXFILES_swigconstant(_initdef)
INIT__MAXFILES = _initdef.INIT__MAXFILES

_initdef.INIT__OVR_ACCESS_swigconstant(_initdef)
INIT__OVR_ACCESS = _initdef.INIT__OVR_ACCESS

_initdef.INIT__NO_OVR_ACCESS_swigconstant(_initdef)
INIT__NO_OVR_ACCESS = _initdef.INIT__NO_OVR_ACCESS

_initdef.INIT__OVR_EXP_swigconstant(_initdef)
INIT__OVR_EXP = _initdef.INIT__OVR_EXP

_initdef.INIT__NO_OVR_EXP_swigconstant(_initdef)
INIT__NO_OVR_EXP = _initdef.INIT__NO_OVR_EXP

_initdef.INIT__OVR_VOLO_swigconstant(_initdef)
INIT__OVR_VOLO = _initdef.INIT__OVR_VOLO

_initdef.INIT__NO_OVR_VOLO_swigconstant(_initdef)
INIT__NO_OVR_VOLO = _initdef.INIT__NO_OVR_VOLO

_initdef.INIT__OWNER_swigconstant(_initdef)
INIT__OWNER = _initdef.INIT__OWNER

_initdef.INIT__READCHECK_swigconstant(_initdef)
INIT__READCHECK = _initdef.INIT__READCHECK

_initdef.INIT__NO_READCHECK_swigconstant(_initdef)
INIT__NO_READCHECK = _initdef.INIT__NO_READCHECK

_initdef.INIT__SIZE_swigconstant(_initdef)
INIT__SIZE = _initdef.INIT__SIZE

_initdef.INIT__STRUCTURE_LEVEL_1_swigconstant(_initdef)
INIT__STRUCTURE_LEVEL_1 = _initdef.INIT__STRUCTURE_LEVEL_1

_initdef.INIT__STRUCTURE_LEVEL_2_swigconstant(_initdef)
INIT__STRUCTURE_LEVEL_2 = _initdef.INIT__STRUCTURE_LEVEL_2

_initdef.INIT__STRUCTURE_LEVEL_2_SUB_0_swigconstant(_initdef)
INIT__STRUCTURE_LEVEL_2_SUB_0 = _initdef.INIT__STRUCTURE_LEVEL_2_SUB_0

_initdef.INIT__USER_NAME_swigconstant(_initdef)
INIT__USER_NAME = _initdef.INIT__USER_NAME

_initdef.INIT__VERIFIED_swigconstant(_initdef)
INIT__VERIFIED = _initdef.INIT__VERIFIED

_initdef.INIT__NO_VERIFIED_swigconstant(_initdef)
INIT__NO_VERIFIED = _initdef.INIT__NO_VERIFIED

_initdef.INIT__VPROT_swigconstant(_initdef)
INIT__VPROT = _initdef.INIT__VPROT

_initdef.INIT__WINDOW_swigconstant(_initdef)
INIT__WINDOW = _initdef.INIT__WINDOW

_initdef.INIT__WRITECHECK_swigconstant(_initdef)
INIT__WRITECHECK = _initdef.INIT__WRITECHECK

_initdef.INIT__NO_WRITECHECK_swigconstant(_initdef)
INIT__NO_WRITECHECK = _initdef.INIT__NO_WRITECHECK

_initdef.INIT__MIN_CLASS_swigconstant(_initdef)
INIT__MIN_CLASS = _initdef.INIT__MIN_CLASS

_initdef.INIT__MAX_CLASS_swigconstant(_initdef)
INIT__MAX_CLASS = _initdef.INIT__MAX_CLASS

_initdef.INIT__NO_PROTECTION_swigconstant(_initdef)
INIT__NO_PROTECTION = _initdef.INIT__NO_PROTECTION

_initdef.INIT__HOMEBLOCKS_swigconstant(_initdef)
INIT__HOMEBLOCKS = _initdef.INIT__HOMEBLOCKS

_initdef.INIT__STRUCTURE_LEVEL_5_swigconstant(_initdef)
INIT__STRUCTURE_LEVEL_5 = _initdef.INIT__STRUCTURE_LEVEL_5

_initdef.INIT__SHADOW_swigconstant(_initdef)
INIT__SHADOW = _initdef.INIT__SHADOW

_initdef.INIT__HARDLINKS_swigconstant(_initdef)
INIT__HARDLINKS = _initdef.INIT__HARDLINKS

_initdef.INIT__ACCESS_DATES_swigconstant(_initdef)
INIT__ACCESS_DATES = _initdef.INIT__ACCESS_DATES

_initdef.INIT__SPARE_swigconstant(_initdef)
INIT__SPARE = _initdef.INIT__SPARE

_initdef.INIT__VOLUME_LIMIT_swigconstant(_initdef)
INIT__VOLUME_LIMIT = _initdef.INIT__VOLUME_LIMIT

_initdef.INIT__GPT_swigconstant(_initdef)
INIT__GPT = _initdef.INIT__GPT

_initdef.INIT__NO_GPT_swigconstant(_initdef)
INIT__NO_GPT = _initdef.INIT__NO_GPT

_initdef.INIT__ERASE_ON_DELETE_swigconstant(_initdef)
INIT__ERASE_ON_DELETE = _initdef.INIT__ERASE_ON_DELETE

_initdef.INIT__ERASE_ON_INIT_swigconstant(_initdef)
INIT__ERASE_ON_INIT = _initdef.INIT__ERASE_ON_INIT

_initdef.INIT__STRUCTURE_LEVEL_6_swigconstant(_initdef)
INIT__STRUCTURE_LEVEL_6 = _initdef.INIT__STRUCTURE_LEVEL_6

_initdef.INIT__LOGSIZE_swigconstant(_initdef)
INIT__LOGSIZE = _initdef.INIT__LOGSIZE

_initdef.INIT__SPECIAL_FILES_swigconstant(_initdef)
INIT__SPECIAL_FILES = _initdef.INIT__SPECIAL_FILES

_initdef.INIT__NO_SPECIAL_FILES_swigconstant(_initdef)
INIT__NO_SPECIAL_FILES = _initdef.INIT__NO_SPECIAL_FILES

_initdef.INIT__LAST_INIT_ITEM_swigconstant(_initdef)
INIT__LAST_INIT_ITEM = _initdef.INIT__LAST_INIT_ITEM

_initdef.INIT__MAX_ITEM_CODE_swigconstant(_initdef)
INIT__MAX_ITEM_CODE = _initdef.INIT__MAX_ITEM_CODE

_initdef.INIT_S_USER_NAME_swigconstant(_initdef)
INIT_S_USER_NAME = _initdef.INIT_S_USER_NAME

_initdef.INIT_S_DEVICE_NAME_swigconstant(_initdef)
INIT_S_DEVICE_NAME = _initdef.INIT_S_DEVICE_NAME

_initdef.INIT_C_MIN_SECURITY_BLKCNT_swigconstant(_initdef)
INIT_C_MIN_SECURITY_BLKCNT = _initdef.INIT_C_MIN_SECURITY_BLKCNT

_initdef.INIT_C_MIN_GPT_BLKCNT_swigconstant(_initdef)
INIT_C_MIN_GPT_BLKCNT = _initdef.INIT_C_MIN_GPT_BLKCNT
# This file is compatible with both classic and new-style classes.


