# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rmsdef', [dirname(__file__)])
        except ImportError:
            import _rmsdef
            return _rmsdef
        if fp is not None:
            try:
                _mod = imp.load_module('_rmsdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _rmsdef = swig_import_helper()
    del swig_import_helper
else:
    import _rmsdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_rmsdef.RMS__FACILITY_swigconstant(_rmsdef)
RMS__FACILITY = _rmsdef.RMS__FACILITY

_rmsdef.RMS_V_STVSTATUS_swigconstant(_rmsdef)
RMS_V_STVSTATUS = _rmsdef.RMS_V_STVSTATUS

_rmsdef.RMS__SUC_swigconstant(_rmsdef)
RMS__SUC = _rmsdef.RMS__SUC

_rmsdef.RMS__NORMAL_swigconstant(_rmsdef)
RMS__NORMAL = _rmsdef.RMS__NORMAL

_rmsdef.RMS__STALL_swigconstant(_rmsdef)
RMS__STALL = _rmsdef.RMS__STALL

_rmsdef.RMS__PENDING_swigconstant(_rmsdef)
RMS__PENDING = _rmsdef.RMS__PENDING

_rmsdef.RMS__OK_DUP_swigconstant(_rmsdef)
RMS__OK_DUP = _rmsdef.RMS__OK_DUP

_rmsdef.RMS__OK_IDX_swigconstant(_rmsdef)
RMS__OK_IDX = _rmsdef.RMS__OK_IDX

_rmsdef.RMS__OK_RLK_swigconstant(_rmsdef)
RMS__OK_RLK = _rmsdef.RMS__OK_RLK

_rmsdef.RMS__OK_RRL_swigconstant(_rmsdef)
RMS__OK_RRL = _rmsdef.RMS__OK_RRL

_rmsdef.RMS__KFF_swigconstant(_rmsdef)
RMS__KFF = _rmsdef.RMS__KFF

_rmsdef.RMS__OK_ALK_swigconstant(_rmsdef)
RMS__OK_ALK = _rmsdef.RMS__OK_ALK

_rmsdef.RMS__OK_DEL_swigconstant(_rmsdef)
RMS__OK_DEL = _rmsdef.RMS__OK_DEL

_rmsdef.RMS__OK_RNF_swigconstant(_rmsdef)
RMS__OK_RNF = _rmsdef.RMS__OK_RNF

_rmsdef.RMS__OK_LIM_swigconstant(_rmsdef)
RMS__OK_LIM = _rmsdef.RMS__OK_LIM

_rmsdef.RMS__OK_NOP_swigconstant(_rmsdef)
RMS__OK_NOP = _rmsdef.RMS__OK_NOP

_rmsdef.RMS__OK_WAT_swigconstant(_rmsdef)
RMS__OK_WAT = _rmsdef.RMS__OK_WAT

_rmsdef.RMS__CRE_STM_swigconstant(_rmsdef)
RMS__CRE_STM = _rmsdef.RMS__CRE_STM

_rmsdef.RMS__OK_RULK_swigconstant(_rmsdef)
RMS__OK_RULK = _rmsdef.RMS__OK_RULK

_rmsdef.RMS__SYNCH_swigconstant(_rmsdef)
RMS__SYNCH = _rmsdef.RMS__SYNCH

_rmsdef.RMS__OK_ACT_swigconstant(_rmsdef)
RMS__OK_ACT = _rmsdef.RMS__OK_ACT

_rmsdef.RMS__OK_NOCURTID_swigconstant(_rmsdef)
RMS__OK_NOCURTID = _rmsdef.RMS__OK_NOCURTID

_rmsdef.RMS__CONTROLC_swigconstant(_rmsdef)
RMS__CONTROLC = _rmsdef.RMS__CONTROLC

_rmsdef.RMS__CONTROLO_swigconstant(_rmsdef)
RMS__CONTROLO = _rmsdef.RMS__CONTROLO

_rmsdef.RMS__CONTROLY_swigconstant(_rmsdef)
RMS__CONTROLY = _rmsdef.RMS__CONTROLY

_rmsdef.RMS__CREATED_swigconstant(_rmsdef)
RMS__CREATED = _rmsdef.RMS__CREATED

_rmsdef.RMS__SUPERSEDE_swigconstant(_rmsdef)
RMS__SUPERSEDE = _rmsdef.RMS__SUPERSEDE

_rmsdef.RMS__OVRDSKQUOTA_swigconstant(_rmsdef)
RMS__OVRDSKQUOTA = _rmsdef.RMS__OVRDSKQUOTA

_rmsdef.RMS__FILEPURGED_swigconstant(_rmsdef)
RMS__FILEPURGED = _rmsdef.RMS__FILEPURGED

_rmsdef.RMS__BOF_swigconstant(_rmsdef)
RMS__BOF = _rmsdef.RMS__BOF

_rmsdef.RMS__RNL_swigconstant(_rmsdef)
RMS__RNL = _rmsdef.RMS__RNL

_rmsdef.RMS__RTB_swigconstant(_rmsdef)
RMS__RTB = _rmsdef.RMS__RTB

_rmsdef.RMS__TMO_swigconstant(_rmsdef)
RMS__TMO = _rmsdef.RMS__TMO

_rmsdef.RMS__TNS_swigconstant(_rmsdef)
RMS__TNS = _rmsdef.RMS__TNS

_rmsdef.RMS__BES_swigconstant(_rmsdef)
RMS__BES = _rmsdef.RMS__BES

_rmsdef.RMS__PES_swigconstant(_rmsdef)
RMS__PES = _rmsdef.RMS__PES

_rmsdef.RMS__ACT_swigconstant(_rmsdef)
RMS__ACT = _rmsdef.RMS__ACT

_rmsdef.RMS__DEL_swigconstant(_rmsdef)
RMS__DEL = _rmsdef.RMS__DEL

_rmsdef.RMS__INCOMPSHR_swigconstant(_rmsdef)
RMS__INCOMPSHR = _rmsdef.RMS__INCOMPSHR

_rmsdef.RMS__DNR_swigconstant(_rmsdef)
RMS__DNR = _rmsdef.RMS__DNR

_rmsdef.RMS__EOF_swigconstant(_rmsdef)
RMS__EOF = _rmsdef.RMS__EOF

_rmsdef.RMS__FEX_swigconstant(_rmsdef)
RMS__FEX = _rmsdef.RMS__FEX

_rmsdef.RMS__FLK_swigconstant(_rmsdef)
RMS__FLK = _rmsdef.RMS__FLK

_rmsdef.RMS__FNF_swigconstant(_rmsdef)
RMS__FNF = _rmsdef.RMS__FNF

_rmsdef.RMS__PRV_swigconstant(_rmsdef)
RMS__PRV = _rmsdef.RMS__PRV

_rmsdef.RMS__REX_swigconstant(_rmsdef)
RMS__REX = _rmsdef.RMS__REX

_rmsdef.RMS__RLK_swigconstant(_rmsdef)
RMS__RLK = _rmsdef.RMS__RLK

_rmsdef.RMS__RNF_swigconstant(_rmsdef)
RMS__RNF = _rmsdef.RMS__RNF

_rmsdef.RMS__WLK_swigconstant(_rmsdef)
RMS__WLK = _rmsdef.RMS__WLK

_rmsdef.RMS__EXP_swigconstant(_rmsdef)
RMS__EXP = _rmsdef.RMS__EXP

_rmsdef.RMS__NMF_swigconstant(_rmsdef)
RMS__NMF = _rmsdef.RMS__NMF

_rmsdef.RMS__SUP_swigconstant(_rmsdef)
RMS__SUP = _rmsdef.RMS__SUP

_rmsdef.RMS__RSA_swigconstant(_rmsdef)
RMS__RSA = _rmsdef.RMS__RSA

_rmsdef.RMS__CRC_swigconstant(_rmsdef)
RMS__CRC = _rmsdef.RMS__CRC

_rmsdef.RMS__WCC_swigconstant(_rmsdef)
RMS__WCC = _rmsdef.RMS__WCC

_rmsdef.RMS__IDR_swigconstant(_rmsdef)
RMS__IDR = _rmsdef.RMS__IDR

_rmsdef.RMS__LWC_swigconstant(_rmsdef)
RMS__LWC = _rmsdef.RMS__LWC

_rmsdef.RMS__UNUSED1_swigconstant(_rmsdef)
RMS__UNUSED1 = _rmsdef.RMS__UNUSED1

_rmsdef.RMS__NOVALPRS_swigconstant(_rmsdef)
RMS__NOVALPRS = _rmsdef.RMS__NOVALPRS

_rmsdef.RMS__KEY_MISMATCH_swigconstant(_rmsdef)
RMS__KEY_MISMATCH = _rmsdef.RMS__KEY_MISMATCH

_rmsdef.RMS__RUH_swigconstant(_rmsdef)
RMS__RUH = _rmsdef.RMS__RUH

_rmsdef.RMS__JND_swigconstant(_rmsdef)
RMS__JND = _rmsdef.RMS__JND

_rmsdef.RMS__BADPHASE_swigconstant(_rmsdef)
RMS__BADPHASE = _rmsdef.RMS__BADPHASE

_rmsdef.RMS__TOWDR_swigconstant(_rmsdef)
RMS__TOWDR = _rmsdef.RMS__TOWDR

_rmsdef.RMS__NEXDR_swigconstant(_rmsdef)
RMS__NEXDR = _rmsdef.RMS__NEXDR

_rmsdef.RMS__INVDRMSG_swigconstant(_rmsdef)
RMS__INVDRMSG = _rmsdef.RMS__INVDRMSG

_rmsdef.RMS__RU_ACTIVE_swigconstant(_rmsdef)
RMS__RU_ACTIVE = _rmsdef.RMS__RU_ACTIVE

_rmsdef.RMS__UNKRUFAC_swigconstant(_rmsdef)
RMS__UNKRUFAC = _rmsdef.RMS__UNKRUFAC

_rmsdef.RMS__LIMBO_swigconstant(_rmsdef)
RMS__LIMBO = _rmsdef.RMS__LIMBO

_rmsdef.RMS__IVATRACE_swigconstant(_rmsdef)
RMS__IVATRACE = _rmsdef.RMS__IVATRACE

_rmsdef.RMS__OPNOTSUP_swigconstant(_rmsdef)
RMS__OPNOTSUP = _rmsdef.RMS__OPNOTSUP

_rmsdef.RMS__EXTNOTFOU_swigconstant(_rmsdef)
RMS__EXTNOTFOU = _rmsdef.RMS__EXTNOTFOU

_rmsdef.RMS__EXT_ERR_swigconstant(_rmsdef)
RMS__EXT_ERR = _rmsdef.RMS__EXT_ERR

_rmsdef.RMS__SEMANTICS_swigconstant(_rmsdef)
RMS__SEMANTICS = _rmsdef.RMS__SEMANTICS

_rmsdef.RMS__LSCAN_swigconstant(_rmsdef)
RMS__LSCAN = _rmsdef.RMS__LSCAN

_rmsdef.RMS__ROOTSRCH_swigconstant(_rmsdef)
RMS__ROOTSRCH = _rmsdef.RMS__ROOTSRCH

_rmsdef.RMS__IDXSEARCH_swigconstant(_rmsdef)
RMS__IDXSEARCH = _rmsdef.RMS__IDXSEARCH

_rmsdef.RMS__NETBTS_swigconstant(_rmsdef)
RMS__NETBTS = _rmsdef.RMS__NETBTS

_rmsdef.RMS__NXR_swigconstant(_rmsdef)
RMS__NXR = _rmsdef.RMS__NXR

_rmsdef.RMS__EOFASY_SYNCH_swigconstant(_rmsdef)
RMS__EOFASY_SYNCH = _rmsdef.RMS__EOFASY_SYNCH

_rmsdef.RMS__ELOOP_swigconstant(_rmsdef)
RMS__ELOOP = _rmsdef.RMS__ELOOP

_rmsdef.RMS__ACC_swigconstant(_rmsdef)
RMS__ACC = _rmsdef.RMS__ACC

_rmsdef.RMS__CRE_swigconstant(_rmsdef)
RMS__CRE = _rmsdef.RMS__CRE

_rmsdef.RMS__DAC_swigconstant(_rmsdef)
RMS__DAC = _rmsdef.RMS__DAC

_rmsdef.RMS__ENT_swigconstant(_rmsdef)
RMS__ENT = _rmsdef.RMS__ENT

_rmsdef.RMS__EXT_swigconstant(_rmsdef)
RMS__EXT = _rmsdef.RMS__EXT

_rmsdef.RMS__FND_swigconstant(_rmsdef)
RMS__FND = _rmsdef.RMS__FND

_rmsdef.RMS__MKD_swigconstant(_rmsdef)
RMS__MKD = _rmsdef.RMS__MKD

_rmsdef.RMS__DPE_swigconstant(_rmsdef)
RMS__DPE = _rmsdef.RMS__DPE

_rmsdef.RMS__SPL_swigconstant(_rmsdef)
RMS__SPL = _rmsdef.RMS__SPL

_rmsdef.RMS__DNF_swigconstant(_rmsdef)
RMS__DNF = _rmsdef.RMS__DNF

_rmsdef.RMS__RUF_swigconstant(_rmsdef)
RMS__RUF = _rmsdef.RMS__RUF

_rmsdef.RMS__WRTJNL_AIJ_swigconstant(_rmsdef)
RMS__WRTJNL_AIJ = _rmsdef.RMS__WRTJNL_AIJ

_rmsdef.RMS__WRTJNL_BIJ_swigconstant(_rmsdef)
RMS__WRTJNL_BIJ = _rmsdef.RMS__WRTJNL_BIJ

_rmsdef.RMS__WRTJNL_ATJ_swigconstant(_rmsdef)
RMS__WRTJNL_ATJ = _rmsdef.RMS__WRTJNL_ATJ

_rmsdef.RMS__WRTJNL_RUJ_swigconstant(_rmsdef)
RMS__WRTJNL_RUJ = _rmsdef.RMS__WRTJNL_RUJ

_rmsdef.RMS__RRF_swigconstant(_rmsdef)
RMS__RRF = _rmsdef.RMS__RRF

_rmsdef.RMS__DDTM_ERR_swigconstant(_rmsdef)
RMS__DDTM_ERR = _rmsdef.RMS__DDTM_ERR

_rmsdef.RMS__DTFCDDREC_swigconstant(_rmsdef)
RMS__DTFCDDREC = _rmsdef.RMS__DTFCDDREC

_rmsdef.RMS__AID_swigconstant(_rmsdef)
RMS__AID = _rmsdef.RMS__AID

_rmsdef.RMS__ALN_swigconstant(_rmsdef)
RMS__ALN = _rmsdef.RMS__ALN

_rmsdef.RMS__ALQ_swigconstant(_rmsdef)
RMS__ALQ = _rmsdef.RMS__ALQ

_rmsdef.RMS__ANI_swigconstant(_rmsdef)
RMS__ANI = _rmsdef.RMS__ANI

_rmsdef.RMS__AOP_swigconstant(_rmsdef)
RMS__AOP = _rmsdef.RMS__AOP

_rmsdef.RMS__BKS_swigconstant(_rmsdef)
RMS__BKS = _rmsdef.RMS__BKS

_rmsdef.RMS__BKZ_swigconstant(_rmsdef)
RMS__BKZ = _rmsdef.RMS__BKZ

_rmsdef.RMS__BLN_swigconstant(_rmsdef)
RMS__BLN = _rmsdef.RMS__BLN

_rmsdef.RMS__BUG_swigconstant(_rmsdef)
RMS__BUG = _rmsdef.RMS__BUG

_rmsdef.RMS__BUG_DDI_swigconstant(_rmsdef)
RMS__BUG_DDI = _rmsdef.RMS__BUG_DDI

_rmsdef.RMS__BUG_DAP_swigconstant(_rmsdef)
RMS__BUG_DAP = _rmsdef.RMS__BUG_DAP

_rmsdef.RMS__BUG_RU_ACTIVE_swigconstant(_rmsdef)
RMS__BUG_RU_ACTIVE = _rmsdef.RMS__BUG_RU_ACTIVE

_rmsdef.RMS__BUG_RURECERR_swigconstant(_rmsdef)
RMS__BUG_RURECERR = _rmsdef.RMS__BUG_RURECERR

_rmsdef.RMS__BUG_FLUSH_JNL_FAILED_swigconstant(_rmsdef)
RMS__BUG_FLUSH_JNL_FAILED = _rmsdef.RMS__BUG_FLUSH_JNL_FAILED

_rmsdef.RMS__BUG_RU_ABORT_FAIL_swigconstant(_rmsdef)
RMS__BUG_RU_ABORT_FAIL = _rmsdef.RMS__BUG_RU_ABORT_FAIL

_rmsdef.RMS__BUG_RU_COMMIT_FAIL_swigconstant(_rmsdef)
RMS__BUG_RU_COMMIT_FAIL = _rmsdef.RMS__BUG_RU_COMMIT_FAIL

_rmsdef.RMS__BUG_XX6_swigconstant(_rmsdef)
RMS__BUG_XX6 = _rmsdef.RMS__BUG_XX6

_rmsdef.RMS__BUG_XX7_swigconstant(_rmsdef)
RMS__BUG_XX7 = _rmsdef.RMS__BUG_XX7

_rmsdef.RMS__BUG_XX8_swigconstant(_rmsdef)
RMS__BUG_XX8 = _rmsdef.RMS__BUG_XX8

_rmsdef.RMS__BUSY_swigconstant(_rmsdef)
RMS__BUSY = _rmsdef.RMS__BUSY

_rmsdef.RMS__CCR_swigconstant(_rmsdef)
RMS__CCR = _rmsdef.RMS__CCR

_rmsdef.RMS__CHG_swigconstant(_rmsdef)
RMS__CHG = _rmsdef.RMS__CHG

_rmsdef.RMS__CHK_swigconstant(_rmsdef)
RMS__CHK = _rmsdef.RMS__CHK

_rmsdef.RMS__COD_swigconstant(_rmsdef)
RMS__COD = _rmsdef.RMS__COD

_rmsdef.RMS__CUR_swigconstant(_rmsdef)
RMS__CUR = _rmsdef.RMS__CUR

_rmsdef.RMS__DAN_swigconstant(_rmsdef)
RMS__DAN = _rmsdef.RMS__DAN

_rmsdef.RMS__DEV_swigconstant(_rmsdef)
RMS__DEV = _rmsdef.RMS__DEV

_rmsdef.RMS__DIR_swigconstant(_rmsdef)
RMS__DIR = _rmsdef.RMS__DIR

_rmsdef.RMS__DME_swigconstant(_rmsdef)
RMS__DME = _rmsdef.RMS__DME

_rmsdef.RMS__DNA_swigconstant(_rmsdef)
RMS__DNA = _rmsdef.RMS__DNA

_rmsdef.RMS__DTP_swigconstant(_rmsdef)
RMS__DTP = _rmsdef.RMS__DTP

_rmsdef.RMS__DUP_swigconstant(_rmsdef)
RMS__DUP = _rmsdef.RMS__DUP

_rmsdef.RMS__DVI_swigconstant(_rmsdef)
RMS__DVI = _rmsdef.RMS__DVI

_rmsdef.RMS__ESA_swigconstant(_rmsdef)
RMS__ESA = _rmsdef.RMS__ESA

_rmsdef.RMS__ESS_swigconstant(_rmsdef)
RMS__ESS = _rmsdef.RMS__ESS

_rmsdef.RMS__FAB_swigconstant(_rmsdef)
RMS__FAB = _rmsdef.RMS__FAB

_rmsdef.RMS__FAC_swigconstant(_rmsdef)
RMS__FAC = _rmsdef.RMS__FAC

_rmsdef.RMS__FLG_swigconstant(_rmsdef)
RMS__FLG = _rmsdef.RMS__FLG

_rmsdef.RMS__FNA_swigconstant(_rmsdef)
RMS__FNA = _rmsdef.RMS__FNA

_rmsdef.RMS__FNM_swigconstant(_rmsdef)
RMS__FNM = _rmsdef.RMS__FNM

_rmsdef.RMS__FSZ_swigconstant(_rmsdef)
RMS__FSZ = _rmsdef.RMS__FSZ

_rmsdef.RMS__FOP_swigconstant(_rmsdef)
RMS__FOP = _rmsdef.RMS__FOP

_rmsdef.RMS__FUL_swigconstant(_rmsdef)
RMS__FUL = _rmsdef.RMS__FUL

_rmsdef.RMS__IAL_swigconstant(_rmsdef)
RMS__IAL = _rmsdef.RMS__IAL

_rmsdef.RMS__IAN_swigconstant(_rmsdef)
RMS__IAN = _rmsdef.RMS__IAN

_rmsdef.RMS__IDX_swigconstant(_rmsdef)
RMS__IDX = _rmsdef.RMS__IDX

_rmsdef.RMS__IFI_swigconstant(_rmsdef)
RMS__IFI = _rmsdef.RMS__IFI

_rmsdef.RMS__IMX_swigconstant(_rmsdef)
RMS__IMX = _rmsdef.RMS__IMX

_rmsdef.RMS__IOP_swigconstant(_rmsdef)
RMS__IOP = _rmsdef.RMS__IOP

_rmsdef.RMS__IRC_swigconstant(_rmsdef)
RMS__IRC = _rmsdef.RMS__IRC

_rmsdef.RMS__ISI_swigconstant(_rmsdef)
RMS__ISI = _rmsdef.RMS__ISI

_rmsdef.RMS__KBF_swigconstant(_rmsdef)
RMS__KBF = _rmsdef.RMS__KBF

_rmsdef.RMS__KEY_swigconstant(_rmsdef)
RMS__KEY = _rmsdef.RMS__KEY

_rmsdef.RMS__KRF_swigconstant(_rmsdef)
RMS__KRF = _rmsdef.RMS__KRF

_rmsdef.RMS__KSZ_swigconstant(_rmsdef)
RMS__KSZ = _rmsdef.RMS__KSZ

_rmsdef.RMS__LAN_swigconstant(_rmsdef)
RMS__LAN = _rmsdef.RMS__LAN

_rmsdef.RMS__RUNDOWN_swigconstant(_rmsdef)
RMS__RUNDOWN = _rmsdef.RMS__RUNDOWN

_rmsdef.RMS__LNE_swigconstant(_rmsdef)
RMS__LNE = _rmsdef.RMS__LNE

_rmsdef.RMS__DTFCVT_swigconstant(_rmsdef)
RMS__DTFCVT = _rmsdef.RMS__DTFCVT

_rmsdef.RMS__MRN_swigconstant(_rmsdef)
RMS__MRN = _rmsdef.RMS__MRN

_rmsdef.RMS__MRS_swigconstant(_rmsdef)
RMS__MRS = _rmsdef.RMS__MRS

_rmsdef.RMS__NAM_swigconstant(_rmsdef)
RMS__NAM = _rmsdef.RMS__NAM

_rmsdef.RMS__NEF_swigconstant(_rmsdef)
RMS__NEF = _rmsdef.RMS__NEF

_rmsdef.RMS__DTFQUASYN_swigconstant(_rmsdef)
RMS__DTFQUASYN = _rmsdef.RMS__DTFQUASYN

_rmsdef.RMS__NOD_swigconstant(_rmsdef)
RMS__NOD = _rmsdef.RMS__NOD

_rmsdef.RMS__NPK_swigconstant(_rmsdef)
RMS__NPK = _rmsdef.RMS__NPK

_rmsdef.RMS__ORD_swigconstant(_rmsdef)
RMS__ORD = _rmsdef.RMS__ORD

_rmsdef.RMS__ORG_swigconstant(_rmsdef)
RMS__ORG = _rmsdef.RMS__ORG

_rmsdef.RMS__PBF_swigconstant(_rmsdef)
RMS__PBF = _rmsdef.RMS__PBF

_rmsdef.RMS__PLG_swigconstant(_rmsdef)
RMS__PLG = _rmsdef.RMS__PLG

_rmsdef.RMS__POS_swigconstant(_rmsdef)
RMS__POS = _rmsdef.RMS__POS

_rmsdef.RMS__DTFQUAVAL_swigconstant(_rmsdef)
RMS__DTFQUAVAL = _rmsdef.RMS__DTFQUAVAL

_rmsdef.RMS__QUO_swigconstant(_rmsdef)
RMS__QUO = _rmsdef.RMS__QUO

_rmsdef.RMS__RAB_swigconstant(_rmsdef)
RMS__RAB = _rmsdef.RMS__RAB

_rmsdef.RMS__RAC_swigconstant(_rmsdef)
RMS__RAC = _rmsdef.RMS__RAC

_rmsdef.RMS__RAT_swigconstant(_rmsdef)
RMS__RAT = _rmsdef.RMS__RAT

_rmsdef.RMS__RBF_swigconstant(_rmsdef)
RMS__RBF = _rmsdef.RMS__RBF

_rmsdef.RMS__RFA_swigconstant(_rmsdef)
RMS__RFA = _rmsdef.RMS__RFA

_rmsdef.RMS__RFM_swigconstant(_rmsdef)
RMS__RFM = _rmsdef.RMS__RFM

_rmsdef.RMS__RHB_swigconstant(_rmsdef)
RMS__RHB = _rmsdef.RMS__RHB

_rmsdef.RMS__RLF_swigconstant(_rmsdef)
RMS__RLF = _rmsdef.RMS__RLF

_rmsdef.RMS__ROP_swigconstant(_rmsdef)
RMS__ROP = _rmsdef.RMS__ROP

_rmsdef.RMS__RRV_swigconstant(_rmsdef)
RMS__RRV = _rmsdef.RMS__RRV

_rmsdef.RMS__RVU_swigconstant(_rmsdef)
RMS__RVU = _rmsdef.RMS__RVU

_rmsdef.RMS__RSS_swigconstant(_rmsdef)
RMS__RSS = _rmsdef.RMS__RSS

_rmsdef.RMS__RST_swigconstant(_rmsdef)
RMS__RST = _rmsdef.RMS__RST

_rmsdef.RMS__RSZ_swigconstant(_rmsdef)
RMS__RSZ = _rmsdef.RMS__RSZ

_rmsdef.RMS__SEQ_swigconstant(_rmsdef)
RMS__SEQ = _rmsdef.RMS__SEQ

_rmsdef.RMS__SHR_swigconstant(_rmsdef)
RMS__SHR = _rmsdef.RMS__SHR

_rmsdef.RMS__SIZ_swigconstant(_rmsdef)
RMS__SIZ = _rmsdef.RMS__SIZ

_rmsdef.RMS__SQO_swigconstant(_rmsdef)
RMS__SQO = _rmsdef.RMS__SQO

_rmsdef.RMS__DTFSESEST_swigconstant(_rmsdef)
RMS__DTFSESEST = _rmsdef.RMS__DTFSESEST

_rmsdef.RMS__SYN_swigconstant(_rmsdef)
RMS__SYN = _rmsdef.RMS__SYN

_rmsdef.RMS__TRE_swigconstant(_rmsdef)
RMS__TRE = _rmsdef.RMS__TRE

_rmsdef.RMS__TYP_swigconstant(_rmsdef)
RMS__TYP = _rmsdef.RMS__TYP

_rmsdef.RMS__UBF_swigconstant(_rmsdef)
RMS__UBF = _rmsdef.RMS__UBF

_rmsdef.RMS__USZ_swigconstant(_rmsdef)
RMS__USZ = _rmsdef.RMS__USZ

_rmsdef.RMS__VER_swigconstant(_rmsdef)
RMS__VER = _rmsdef.RMS__VER

_rmsdef.RMS__XNF_swigconstant(_rmsdef)
RMS__XNF = _rmsdef.RMS__XNF

_rmsdef.RMS__XAB_swigconstant(_rmsdef)
RMS__XAB = _rmsdef.RMS__XAB

_rmsdef.RMS__ESL_swigconstant(_rmsdef)
RMS__ESL = _rmsdef.RMS__ESL

_rmsdef.RMS__DTFSESTER_swigconstant(_rmsdef)
RMS__DTFSESTER = _rmsdef.RMS__DTFSESTER

_rmsdef.RMS__ENV_swigconstant(_rmsdef)
RMS__ENV = _rmsdef.RMS__ENV

_rmsdef.RMS__PLV_swigconstant(_rmsdef)
RMS__PLV = _rmsdef.RMS__PLV

_rmsdef.RMS__MBC_swigconstant(_rmsdef)
RMS__MBC = _rmsdef.RMS__MBC

_rmsdef.RMS__RSL_swigconstant(_rmsdef)
RMS__RSL = _rmsdef.RMS__RSL

_rmsdef.RMS__WLD_swigconstant(_rmsdef)
RMS__WLD = _rmsdef.RMS__WLD

_rmsdef.RMS__NET_swigconstant(_rmsdef)
RMS__NET = _rmsdef.RMS__NET

_rmsdef.RMS__IBF_swigconstant(_rmsdef)
RMS__IBF = _rmsdef.RMS__IBF

_rmsdef.RMS__REF_swigconstant(_rmsdef)
RMS__REF = _rmsdef.RMS__REF

_rmsdef.RMS__IFL_swigconstant(_rmsdef)
RMS__IFL = _rmsdef.RMS__IFL

_rmsdef.RMS__DFL_swigconstant(_rmsdef)
RMS__DFL = _rmsdef.RMS__DFL

_rmsdef.RMS__KNM_swigconstant(_rmsdef)
RMS__KNM = _rmsdef.RMS__KNM

_rmsdef.RMS__IBK_swigconstant(_rmsdef)
RMS__IBK = _rmsdef.RMS__IBK

_rmsdef.RMS__KSI_swigconstant(_rmsdef)
RMS__KSI = _rmsdef.RMS__KSI

_rmsdef.RMS__LEX_swigconstant(_rmsdef)
RMS__LEX = _rmsdef.RMS__LEX

_rmsdef.RMS__SEG_swigconstant(_rmsdef)
RMS__SEG = _rmsdef.RMS__SEG

_rmsdef.RMS__SNE_swigconstant(_rmsdef)
RMS__SNE = _rmsdef.RMS__SNE

_rmsdef.RMS__SPE_swigconstant(_rmsdef)
RMS__SPE = _rmsdef.RMS__SPE

_rmsdef.RMS__UPI_swigconstant(_rmsdef)
RMS__UPI = _rmsdef.RMS__UPI

_rmsdef.RMS__ACS_swigconstant(_rmsdef)
RMS__ACS = _rmsdef.RMS__ACS

_rmsdef.RMS__STR_swigconstant(_rmsdef)
RMS__STR = _rmsdef.RMS__STR

_rmsdef.RMS__FTM_swigconstant(_rmsdef)
RMS__FTM = _rmsdef.RMS__FTM

_rmsdef.RMS__GBC_swigconstant(_rmsdef)
RMS__GBC = _rmsdef.RMS__GBC

_rmsdef.RMS__DEADLOCK_swigconstant(_rmsdef)
RMS__DEADLOCK = _rmsdef.RMS__DEADLOCK

_rmsdef.RMS__EXENQLM_swigconstant(_rmsdef)
RMS__EXENQLM = _rmsdef.RMS__EXENQLM

_rmsdef.RMS__JOP_swigconstant(_rmsdef)
RMS__JOP = _rmsdef.RMS__JOP

_rmsdef.RMS__RUM_swigconstant(_rmsdef)
RMS__RUM = _rmsdef.RMS__RUM

_rmsdef.RMS__JNS_swigconstant(_rmsdef)
RMS__JNS = _rmsdef.RMS__JNS

_rmsdef.RMS__NRU_swigconstant(_rmsdef)
RMS__NRU = _rmsdef.RMS__NRU

_rmsdef.RMS__IFF_swigconstant(_rmsdef)
RMS__IFF = _rmsdef.RMS__IFF

_rmsdef.RMS__DTFTRATBL_swigconstant(_rmsdef)
RMS__DTFTRATBL = _rmsdef.RMS__DTFTRATBL

_rmsdef.RMS__DTFUNSTYP_swigconstant(_rmsdef)
RMS__DTFUNSTYP = _rmsdef.RMS__DTFUNSTYP

_rmsdef.RMS__DTFVERMIS_swigconstant(_rmsdef)
RMS__DTFVERMIS = _rmsdef.RMS__DTFVERMIS

_rmsdef.RMS__DTFACC_swigconstant(_rmsdef)
RMS__DTFACC = _rmsdef.RMS__DTFACC

_rmsdef.RMS__BOGUSCOL_swigconstant(_rmsdef)
RMS__BOGUSCOL = _rmsdef.RMS__BOGUSCOL

_rmsdef.RMS__ERRREADCOL_swigconstant(_rmsdef)
RMS__ERRREADCOL = _rmsdef.RMS__ERRREADCOL

_rmsdef.RMS__ERRWRITECOL_swigconstant(_rmsdef)
RMS__ERRWRITECOL = _rmsdef.RMS__ERRWRITECOL

_rmsdef.RMS__SNS_swigconstant(_rmsdef)
RMS__SNS = _rmsdef.RMS__SNS

_rmsdef.RMS__NOEXTEND_swigconstant(_rmsdef)
RMS__NOEXTEND = _rmsdef.RMS__NOEXTEND

_rmsdef.RMS__DTFCRE_swigconstant(_rmsdef)
RMS__DTFCRE = _rmsdef.RMS__DTFCRE

_rmsdef.RMS__DELJNS_swigconstant(_rmsdef)
RMS__DELJNS = _rmsdef.RMS__DELJNS

_rmsdef.RMS__NOTSAMEJNL_swigconstant(_rmsdef)
RMS__NOTSAMEJNL = _rmsdef.RMS__NOTSAMEJNL

_rmsdef.RMS__SNPPF_swigconstant(_rmsdef)
RMS__SNPPF = _rmsdef.RMS__SNPPF

_rmsdef.RMS__NAML_swigconstant(_rmsdef)
RMS__NAML = _rmsdef.RMS__NAML

_rmsdef.RMS__NAMLESS_swigconstant(_rmsdef)
RMS__NAMLESS = _rmsdef.RMS__NAMLESS

_rmsdef.RMS__NAMLRSS_swigconstant(_rmsdef)
RMS__NAMLRSS = _rmsdef.RMS__NAMLRSS

_rmsdef.RMS__NAMLFSSIZ_swigconstant(_rmsdef)
RMS__NAMLFSSIZ = _rmsdef.RMS__NAMLFSSIZ

_rmsdef.RMS__NAMLFSINV_swigconstant(_rmsdef)
RMS__NAMLFSINV = _rmsdef.RMS__NAMLFSINV

_rmsdef.RMS__BADGBH_swigconstant(_rmsdef)
RMS__BADGBH = _rmsdef.RMS__BADGBH

_rmsdef.RMS__BADGBD_swigconstant(_rmsdef)
RMS__BADGBD = _rmsdef.RMS__BADGBD

_rmsdef.RMS__FOPEXTMBZ_swigconstant(_rmsdef)
RMS__FOPEXTMBZ = _rmsdef.RMS__FOPEXTMBZ

_rmsdef.RMS__INVOP_SSIO_swigconstant(_rmsdef)
RMS__INVOP_SSIO = _rmsdef.RMS__INVOP_SSIO

_rmsdef.RMS__IVSF_swigconstant(_rmsdef)
RMS__IVSF = _rmsdef.RMS__IVSF

_rmsdef.RMS__ATR_swigconstant(_rmsdef)
RMS__ATR = _rmsdef.RMS__ATR

_rmsdef.RMS__ATW_swigconstant(_rmsdef)
RMS__ATW = _rmsdef.RMS__ATW

_rmsdef.RMS__CCF_swigconstant(_rmsdef)
RMS__CCF = _rmsdef.RMS__CCF

_rmsdef.RMS__CDA_swigconstant(_rmsdef)
RMS__CDA = _rmsdef.RMS__CDA

_rmsdef.RMS__CHN_swigconstant(_rmsdef)
RMS__CHN = _rmsdef.RMS__CHN

_rmsdef.RMS__RER_swigconstant(_rmsdef)
RMS__RER = _rmsdef.RMS__RER

_rmsdef.RMS__RMV_swigconstant(_rmsdef)
RMS__RMV = _rmsdef.RMS__RMV

_rmsdef.RMS__RPL_swigconstant(_rmsdef)
RMS__RPL = _rmsdef.RMS__RPL

_rmsdef.RMS__SYS_swigconstant(_rmsdef)
RMS__SYS = _rmsdef.RMS__SYS

_rmsdef.RMS__WER_swigconstant(_rmsdef)
RMS__WER = _rmsdef.RMS__WER

_rmsdef.RMS__WPL_swigconstant(_rmsdef)
RMS__WPL = _rmsdef.RMS__WPL

_rmsdef.RMS__IFA_swigconstant(_rmsdef)
RMS__IFA = _rmsdef.RMS__IFA

_rmsdef.RMS__WBE_swigconstant(_rmsdef)
RMS__WBE = _rmsdef.RMS__WBE

_rmsdef.RMS__ENQ_swigconstant(_rmsdef)
RMS__ENQ = _rmsdef.RMS__ENQ

_rmsdef.RMS__NETFAIL_swigconstant(_rmsdef)
RMS__NETFAIL = _rmsdef.RMS__NETFAIL

_rmsdef.RMS__SUPPORT_swigconstant(_rmsdef)
RMS__SUPPORT = _rmsdef.RMS__SUPPORT

_rmsdef.RMS__CRMP_swigconstant(_rmsdef)
RMS__CRMP = _rmsdef.RMS__CRMP

_rmsdef.RMS__DTFCFGFIL_swigconstant(_rmsdef)
RMS__DTFCFGFIL = _rmsdef.RMS__DTFCFGFIL

_rmsdef.RMS__REENT_swigconstant(_rmsdef)
RMS__REENT = _rmsdef.RMS__REENT

_rmsdef.RMS__ACC_RUJ_swigconstant(_rmsdef)
RMS__ACC_RUJ = _rmsdef.RMS__ACC_RUJ

_rmsdef.RMS__TMR_swigconstant(_rmsdef)
RMS__TMR = _rmsdef.RMS__TMR

_rmsdef.RMS__ACC_AIJ_swigconstant(_rmsdef)
RMS__ACC_AIJ = _rmsdef.RMS__ACC_AIJ

_rmsdef.RMS__ACC_BIJ_swigconstant(_rmsdef)
RMS__ACC_BIJ = _rmsdef.RMS__ACC_BIJ

_rmsdef.RMS__ACC_ATJ_swigconstant(_rmsdef)
RMS__ACC_ATJ = _rmsdef.RMS__ACC_ATJ

_rmsdef.RMS__DTFDEFFIL_swigconstant(_rmsdef)
RMS__DTFDEFFIL = _rmsdef.RMS__DTFDEFFIL

_rmsdef.RMS__DTFREGFIL_swigconstant(_rmsdef)
RMS__DTFREGFIL = _rmsdef.RMS__DTFREGFIL

_rmsdef.RMS__JNLNOTAUTH_swigconstant(_rmsdef)
RMS__JNLNOTAUTH = _rmsdef.RMS__JNLNOTAUTH

_rmsdef.RMS__CRBUFOBJ_swigconstant(_rmsdef)
RMS__CRBUFOBJ = _rmsdef.RMS__CRBUFOBJ

_rmsdef.RMS__RSESTK_ALLOC_swigconstant(_rmsdef)
RMS__RSESTK_ALLOC = _rmsdef.RMS__RSESTK_ALLOC
# This file is compatible with both classic and new-style classes.


