# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_maildef', [dirname(__file__)])
        except ImportError:
            import _maildef
            return _maildef
        if fp is not None:
            try:
                _mod = imp.load_module('_maildef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _maildef = swig_import_helper()
    del swig_import_helper
else:
    import _maildef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_maildef.mail__send_spare_0_swigconstant(_maildef)
mail__send_spare_0 = _maildef.mail__send_spare_0

_maildef.mail__send_foreign_swigconstant(_maildef)
mail__send_foreign = _maildef.mail__send_foreign

_maildef.mail__send_cc_line_swigconstant(_maildef)
mail__send_cc_line = _maildef.mail__send_cc_line

_maildef.mail__send_default_name_swigconstant(_maildef)
mail__send_default_name = _maildef.mail__send_default_name

_maildef.mail__send_default_transport_swigconstant(_maildef)
mail__send_default_transport = _maildef.mail__send_default_transport

_maildef.mail__send_error_entry_swigconstant(_maildef)
mail__send_error_entry = _maildef.mail__send_error_entry

_maildef.mail__send_filename_swigconstant(_maildef)
mail__send_filename = _maildef.mail__send_filename

_maildef.mail__send_from_line_swigconstant(_maildef)
mail__send_from_line = _maildef.mail__send_from_line

_maildef.mail__send_no_default_transport_swigconstant(_maildef)
mail__send_no_default_transport = _maildef.mail__send_no_default_transport

_maildef.mail__send_pers_name_swigconstant(_maildef)
mail__send_pers_name = _maildef.mail__send_pers_name

_maildef.mail__send_record_swigconstant(_maildef)
mail__send_record = _maildef.mail__send_record

_maildef.mail__send_resultspec_swigconstant(_maildef)
mail__send_resultspec = _maildef.mail__send_resultspec

_maildef.mail__send_server_swigconstant(_maildef)
mail__send_server = _maildef.mail__send_server

_maildef.mail__send_subject_swigconstant(_maildef)
mail__send_subject = _maildef.mail__send_subject

_maildef.mail__send_success_entry_swigconstant(_maildef)
mail__send_success_entry = _maildef.mail__send_success_entry

_maildef.mail__send_to_line_swigconstant(_maildef)
mail__send_to_line = _maildef.mail__send_to_line

_maildef.mail__send_uflags_swigconstant(_maildef)
mail__send_uflags = _maildef.mail__send_uflags

_maildef.mail__send_user_data_swigconstant(_maildef)
mail__send_user_data = _maildef.mail__send_user_data

_maildef.mail__send_username_swigconstant(_maildef)
mail__send_username = _maildef.mail__send_username

_maildef.mail__send_username_type_swigconstant(_maildef)
mail__send_username_type = _maildef.mail__send_username_type

_maildef.mail__send_fid_swigconstant(_maildef)
mail__send_fid = _maildef.mail__send_fid

_maildef.mail__send_no_pers_name_swigconstant(_maildef)
mail__send_no_pers_name = _maildef.mail__send_no_pers_name

_maildef.mail__send_sigfile_swigconstant(_maildef)
mail__send_sigfile = _maildef.mail__send_sigfile

_maildef.mail__send_no_sigfile_swigconstant(_maildef)
mail__send_no_sigfile = _maildef.mail__send_no_sigfile

_maildef.mail__send_parse_quotes_swigconstant(_maildef)
mail__send_parse_quotes = _maildef.mail__send_parse_quotes

_maildef.mail__send_copy_reply_swigconstant(_maildef)
mail__send_copy_reply = _maildef.mail__send_copy_reply

_maildef.mail__send_copy_send_swigconstant(_maildef)
mail__send_copy_send = _maildef.mail__send_copy_send

_maildef.mail__send_user_swigconstant(_maildef)
mail__send_user = _maildef.mail__send_user

_maildef.mail__send_copy_forward_swigconstant(_maildef)
mail__send_copy_forward = _maildef.mail__send_copy_forward

_maildef.mail__send_recip_folder_swigconstant(_maildef)
mail__send_recip_folder = _maildef.mail__send_recip_folder

_maildef.mail__send_out_spare3_swigconstant(_maildef)
mail__send_out_spare3 = _maildef.mail__send_out_spare3

_maildef.mail__send_out_spare4_swigconstant(_maildef)
mail__send_out_spare4 = _maildef.mail__send_out_spare4

_maildef.mail__send_out_spare5_swigconstant(_maildef)
mail__send_out_spare5 = _maildef.mail__send_out_spare5

_maildef.mail_k_send_min_item_swigconstant(_maildef)
mail_k_send_min_item = _maildef.mail_k_send_min_item

_maildef.mail_k_send_max_item_swigconstant(_maildef)
mail_k_send_max_item = _maildef.mail_k_send_max_item

_maildef.mail_k_send_items_swigconstant(_maildef)
mail_k_send_items = _maildef.mail_k_send_items

_maildef.mail__mailfile_spare_0_swigconstant(_maildef)
mail__mailfile_spare_0 = _maildef.mail__mailfile_spare_0

_maildef.mail__mailfile_default_name_swigconstant(_maildef)
mail__mailfile_default_name = _maildef.mail__mailfile_default_name

_maildef.mail__mailfile_folder_routine_swigconstant(_maildef)
mail__mailfile_folder_routine = _maildef.mail__mailfile_folder_routine

_maildef.mail__mailfile_full_close_swigconstant(_maildef)
mail__mailfile_full_close = _maildef.mail__mailfile_full_close

_maildef.mail__mailfile_name_swigconstant(_maildef)
mail__mailfile_name = _maildef.mail__mailfile_name

_maildef.mail__mailfile_reclaim_swigconstant(_maildef)
mail__mailfile_reclaim = _maildef.mail__mailfile_reclaim

_maildef.mail__mailfile_user_data_swigconstant(_maildef)
mail__mailfile_user_data = _maildef.mail__mailfile_user_data

_maildef.mail__mailfile_wastebasket_name_swigconstant(_maildef)
mail__mailfile_wastebasket_name = _maildef.mail__mailfile_wastebasket_name

_maildef.mail__mailfile_collate_seq_swigconstant(_maildef)
mail__mailfile_collate_seq = _maildef.mail__mailfile_collate_seq

_maildef.mail__mailfile_in_spare2_swigconstant(_maildef)
mail__mailfile_in_spare2 = _maildef.mail__mailfile_in_spare2

_maildef.mail__mailfile_in_spare3_swigconstant(_maildef)
mail__mailfile_in_spare3 = _maildef.mail__mailfile_in_spare3

_maildef.mail__mailfile_in_spare4_swigconstant(_maildef)
mail__mailfile_in_spare4 = _maildef.mail__mailfile_in_spare4

_maildef.mail__mailfile_in_spare5_swigconstant(_maildef)
mail__mailfile_in_spare5 = _maildef.mail__mailfile_in_spare5

_maildef.mail__mailfile_in_spare6_swigconstant(_maildef)
mail__mailfile_in_spare6 = _maildef.mail__mailfile_in_spare6

_maildef.mail__mailfile_in_spare7_swigconstant(_maildef)
mail__mailfile_in_spare7 = _maildef.mail__mailfile_in_spare7

_maildef.mail__mailfile_in_spare8_swigconstant(_maildef)
mail__mailfile_in_spare8 = _maildef.mail__mailfile_in_spare8

_maildef.mail__mailfile_in_spare9_swigconstant(_maildef)
mail__mailfile_in_spare9 = _maildef.mail__mailfile_in_spare9

_maildef.mail__mailfile_in_spare10_swigconstant(_maildef)
mail__mailfile_in_spare10 = _maildef.mail__mailfile_in_spare10

_maildef.mail__mailfile_in_spare11_swigconstant(_maildef)
mail__mailfile_in_spare11 = _maildef.mail__mailfile_in_spare11

_maildef.mail__mailfile_in_spare12_swigconstant(_maildef)
mail__mailfile_in_spare12 = _maildef.mail__mailfile_in_spare12

_maildef.mail__mailfile_in_spare13_swigconstant(_maildef)
mail__mailfile_in_spare13 = _maildef.mail__mailfile_in_spare13

_maildef.mail__mailfile_in_spare14_swigconstant(_maildef)
mail__mailfile_in_spare14 = _maildef.mail__mailfile_in_spare14

_maildef.mail__mailfile_in_spare15_swigconstant(_maildef)
mail__mailfile_in_spare15 = _maildef.mail__mailfile_in_spare15

_maildef.mail__mailfile_in_spare16_swigconstant(_maildef)
mail__mailfile_in_spare16 = _maildef.mail__mailfile_in_spare16

_maildef.mail__mailfile_in_spare17_swigconstant(_maildef)
mail__mailfile_in_spare17 = _maildef.mail__mailfile_in_spare17

_maildef.mail__mailfile_in_spare18_swigconstant(_maildef)
mail__mailfile_in_spare18 = _maildef.mail__mailfile_in_spare18

_maildef.mail__mailfile_in_spare19_swigconstant(_maildef)
mail__mailfile_in_spare19 = _maildef.mail__mailfile_in_spare19

_maildef.mail__mailfile_in_spare20_swigconstant(_maildef)
mail__mailfile_in_spare20 = _maildef.mail__mailfile_in_spare20

_maildef.mail__mailfile_data_reclaim_swigconstant(_maildef)
mail__mailfile_data_reclaim = _maildef.mail__mailfile_data_reclaim

_maildef.mail__mailfile_data_scan_swigconstant(_maildef)
mail__mailfile_data_scan = _maildef.mail__mailfile_data_scan

_maildef.mail__mailfile_deleted_bytes_swigconstant(_maildef)
mail__mailfile_deleted_bytes = _maildef.mail__mailfile_deleted_bytes

_maildef.mail__mailfile_index_reclaim_swigconstant(_maildef)
mail__mailfile_index_reclaim = _maildef.mail__mailfile_index_reclaim

_maildef.mail__mailfile_mail_directory_swigconstant(_maildef)
mail__mailfile_mail_directory = _maildef.mail__mailfile_mail_directory

_maildef.mail__mailfile_messages_deleted_swigconstant(_maildef)
mail__mailfile_messages_deleted = _maildef.mail__mailfile_messages_deleted

_maildef.mail__mailfile_resultspec_swigconstant(_maildef)
mail__mailfile_resultspec = _maildef.mail__mailfile_resultspec

_maildef.mail__mailfile_total_reclaim_swigconstant(_maildef)
mail__mailfile_total_reclaim = _maildef.mail__mailfile_total_reclaim

_maildef.mail__mailfile_wastebasket_swigconstant(_maildef)
mail__mailfile_wastebasket = _maildef.mail__mailfile_wastebasket

_maildef.mail__mailfile_indexed_swigconstant(_maildef)
mail__mailfile_indexed = _maildef.mail__mailfile_indexed

_maildef.mail__mailfile_out_spare2_swigconstant(_maildef)
mail__mailfile_out_spare2 = _maildef.mail__mailfile_out_spare2

_maildef.mail__mailfile_out_spare3_swigconstant(_maildef)
mail__mailfile_out_spare3 = _maildef.mail__mailfile_out_spare3

_maildef.mail__mailfile_out_spare4_swigconstant(_maildef)
mail__mailfile_out_spare4 = _maildef.mail__mailfile_out_spare4

_maildef.mail__mailfile_out_spare5_swigconstant(_maildef)
mail__mailfile_out_spare5 = _maildef.mail__mailfile_out_spare5

_maildef.mail__mailfile_out_spare6_swigconstant(_maildef)
mail__mailfile_out_spare6 = _maildef.mail__mailfile_out_spare6

_maildef.mail__mailfile_out_spare7_swigconstant(_maildef)
mail__mailfile_out_spare7 = _maildef.mail__mailfile_out_spare7

_maildef.mail__mailfile_out_spare8_swigconstant(_maildef)
mail__mailfile_out_spare8 = _maildef.mail__mailfile_out_spare8

_maildef.mail__mailfile_out_spare9_swigconstant(_maildef)
mail__mailfile_out_spare9 = _maildef.mail__mailfile_out_spare9

_maildef.mail__mailfile_out_spare10_swigconstant(_maildef)
mail__mailfile_out_spare10 = _maildef.mail__mailfile_out_spare10

_maildef.mail__mailfile_out_spare11_swigconstant(_maildef)
mail__mailfile_out_spare11 = _maildef.mail__mailfile_out_spare11

_maildef.mail__mailfile_out_spare12_swigconstant(_maildef)
mail__mailfile_out_spare12 = _maildef.mail__mailfile_out_spare12

_maildef.mail__mailfile_out_spare13_swigconstant(_maildef)
mail__mailfile_out_spare13 = _maildef.mail__mailfile_out_spare13

_maildef.mail__mailfile_out_spare14_swigconstant(_maildef)
mail__mailfile_out_spare14 = _maildef.mail__mailfile_out_spare14

_maildef.mail__mailfile_out_spare15_swigconstant(_maildef)
mail__mailfile_out_spare15 = _maildef.mail__mailfile_out_spare15

_maildef.mail__mailfile_out_spare16_swigconstant(_maildef)
mail__mailfile_out_spare16 = _maildef.mail__mailfile_out_spare16

_maildef.mail__mailfile_out_spare17_swigconstant(_maildef)
mail__mailfile_out_spare17 = _maildef.mail__mailfile_out_spare17

_maildef.mail__mailfile_out_spare18_swigconstant(_maildef)
mail__mailfile_out_spare18 = _maildef.mail__mailfile_out_spare18

_maildef.mail__mailfile_out_spare19_swigconstant(_maildef)
mail__mailfile_out_spare19 = _maildef.mail__mailfile_out_spare19

_maildef.mail__mailfile_out_spare20_swigconstant(_maildef)
mail__mailfile_out_spare20 = _maildef.mail__mailfile_out_spare20

_maildef.mail_k_mailfile_min_item_swigconstant(_maildef)
mail_k_mailfile_min_item = _maildef.mail_k_mailfile_min_item

_maildef.mail_k_mailfile_max_item_swigconstant(_maildef)
mail_k_mailfile_max_item = _maildef.mail_k_mailfile_max_item

_maildef.mail_k_mailfile_items_swigconstant(_maildef)
mail_k_mailfile_items = _maildef.mail_k_mailfile_items

_maildef.mail__message_spare_0_swigconstant(_maildef)
mail__message_spare_0 = _maildef.mail__message_spare_0

_maildef.mail__message_back_swigconstant(_maildef)
mail__message_back = _maildef.mail__message_back

_maildef.mail__message_before_swigconstant(_maildef)
mail__message_before = _maildef.mail__message_before

_maildef.mail__message_cc_substring_swigconstant(_maildef)
mail__message_cc_substring = _maildef.mail__message_cc_substring

_maildef.mail__message_continue_swigconstant(_maildef)
mail__message_continue = _maildef.mail__message_continue

_maildef.mail__message_file_action_swigconstant(_maildef)
mail__message_file_action = _maildef.mail__message_file_action

_maildef.mail__message_folder_action_swigconstant(_maildef)
mail__message_folder_action = _maildef.mail__message_folder_action

_maildef.mail__message_default_name_swigconstant(_maildef)
mail__message_default_name = _maildef.mail__message_default_name

_maildef.mail__message_delete_swigconstant(_maildef)
mail__message_delete = _maildef.mail__message_delete

_maildef.mail__message_erase_swigconstant(_maildef)
mail__message_erase = _maildef.mail__message_erase

_maildef.mail__message_file_ctx_swigconstant(_maildef)
mail__message_file_ctx = _maildef.mail__message_file_ctx

_maildef.mail__message_filename_swigconstant(_maildef)
mail__message_filename = _maildef.mail__message_filename

_maildef.mail__message_flags_swigconstant(_maildef)
mail__message_flags = _maildef.mail__message_flags

_maildef.mail__message_folder_swigconstant(_maildef)
mail__message_folder = _maildef.mail__message_folder

_maildef.mail__message_from_substring_swigconstant(_maildef)
mail__message_from_substring = _maildef.mail__message_from_substring

_maildef.mail__message_id_swigconstant(_maildef)
mail__message_id = _maildef.mail__message_id

_maildef.mail__message_next_swigconstant(_maildef)
mail__message_next = _maildef.mail__message_next

_maildef.mail__message_since_swigconstant(_maildef)
mail__message_since = _maildef.mail__message_since

_maildef.mail__message_subj_substring_swigconstant(_maildef)
mail__message_subj_substring = _maildef.mail__message_subj_substring

_maildef.mail__message_to_substring_swigconstant(_maildef)
mail__message_to_substring = _maildef.mail__message_to_substring

_maildef.mail__message_uflags_swigconstant(_maildef)
mail__message_uflags = _maildef.mail__message_uflags

_maildef.mail__message_auto_newmail_swigconstant(_maildef)
mail__message_auto_newmail = _maildef.mail__message_auto_newmail

_maildef.mail__message_user_data_swigconstant(_maildef)
mail__message_user_data = _maildef.mail__message_user_data

_maildef.mail__message_flags_mbz_swigconstant(_maildef)
mail__message_flags_mbz = _maildef.mail__message_flags_mbz

_maildef.mail__message_min_class_swigconstant(_maildef)
mail__message_min_class = _maildef.mail__message_min_class

_maildef.mail__message_max_class_swigconstant(_maildef)
mail__message_max_class = _maildef.mail__message_max_class

_maildef.mail__message_in_spare1_swigconstant(_maildef)
mail__message_in_spare1 = _maildef.mail__message_in_spare1

_maildef.mail__message_in_spare2_swigconstant(_maildef)
mail__message_in_spare2 = _maildef.mail__message_in_spare2

_maildef.mail__message_in_spare3_swigconstant(_maildef)
mail__message_in_spare3 = _maildef.mail__message_in_spare3

_maildef.mail__message_in_spare4_swigconstant(_maildef)
mail__message_in_spare4 = _maildef.mail__message_in_spare4

_maildef.mail__message_in_spare5_swigconstant(_maildef)
mail__message_in_spare5 = _maildef.mail__message_in_spare5

_maildef.mail__message_in_spare6_swigconstant(_maildef)
mail__message_in_spare6 = _maildef.mail__message_in_spare6

_maildef.mail__message_in_spare7_swigconstant(_maildef)
mail__message_in_spare7 = _maildef.mail__message_in_spare7

_maildef.mail__message_in_spare8_swigconstant(_maildef)
mail__message_in_spare8 = _maildef.mail__message_in_spare8

_maildef.mail__message_in_spare9_swigconstant(_maildef)
mail__message_in_spare9 = _maildef.mail__message_in_spare9

_maildef.mail__message_in_spare10_swigconstant(_maildef)
mail__message_in_spare10 = _maildef.mail__message_in_spare10

_maildef.mail__message_in_spare11_swigconstant(_maildef)
mail__message_in_spare11 = _maildef.mail__message_in_spare11

_maildef.mail__message_in_spare12_swigconstant(_maildef)
mail__message_in_spare12 = _maildef.mail__message_in_spare12

_maildef.mail__message_in_spare13_swigconstant(_maildef)
mail__message_in_spare13 = _maildef.mail__message_in_spare13

_maildef.mail__message_in_spare14_swigconstant(_maildef)
mail__message_in_spare14 = _maildef.mail__message_in_spare14

_maildef.mail__message_in_spare15_swigconstant(_maildef)
mail__message_in_spare15 = _maildef.mail__message_in_spare15

_maildef.mail__message_in_spare16_swigconstant(_maildef)
mail__message_in_spare16 = _maildef.mail__message_in_spare16

_maildef.mail__message_in_spare17_swigconstant(_maildef)
mail__message_in_spare17 = _maildef.mail__message_in_spare17

_maildef.mail__message_in_spare18_swigconstant(_maildef)
mail__message_in_spare18 = _maildef.mail__message_in_spare18

_maildef.mail__message_in_spare19_swigconstant(_maildef)
mail__message_in_spare19 = _maildef.mail__message_in_spare19

_maildef.mail__message_in_spare20_swigconstant(_maildef)
mail__message_in_spare20 = _maildef.mail__message_in_spare20

_maildef.mail__message_cc_swigconstant(_maildef)
mail__message_cc = _maildef.mail__message_cc

_maildef.mail__message_current_id_swigconstant(_maildef)
mail__message_current_id = _maildef.mail__message_current_id

_maildef.mail__message_date_swigconstant(_maildef)
mail__message_date = _maildef.mail__message_date

_maildef.mail__message_extid_swigconstant(_maildef)
mail__message_extid = _maildef.mail__message_extid

_maildef.mail__message_file_created_swigconstant(_maildef)
mail__message_file_created = _maildef.mail__message_file_created

_maildef.mail__message_folder_created_swigconstant(_maildef)
mail__message_folder_created = _maildef.mail__message_folder_created

_maildef.mail__message_from_swigconstant(_maildef)
mail__message_from = _maildef.mail__message_from

_maildef.mail__message_record_swigconstant(_maildef)
mail__message_record = _maildef.mail__message_record

_maildef.mail__message_record_type_swigconstant(_maildef)
mail__message_record_type = _maildef.mail__message_record_type

_maildef.mail__message_reply_path_swigconstant(_maildef)
mail__message_reply_path = _maildef.mail__message_reply_path

_maildef.mail__message_resultspec_swigconstant(_maildef)
mail__message_resultspec = _maildef.mail__message_resultspec

_maildef.mail__message_return_flags_swigconstant(_maildef)
mail__message_return_flags = _maildef.mail__message_return_flags

_maildef.mail__message_return_uflags_swigconstant(_maildef)
mail__message_return_uflags = _maildef.mail__message_return_uflags

_maildef.mail__message_selected_swigconstant(_maildef)
mail__message_selected = _maildef.mail__message_selected

_maildef.mail__message_sender_swigconstant(_maildef)
mail__message_sender = _maildef.mail__message_sender

_maildef.mail__message_size_swigconstant(_maildef)
mail__message_size = _maildef.mail__message_size

_maildef.mail__message_subject_swigconstant(_maildef)
mail__message_subject = _maildef.mail__message_subject

_maildef.mail__message_to_swigconstant(_maildef)
mail__message_to = _maildef.mail__message_to

_maildef.mail__message_buffer_swigconstant(_maildef)
mail__message_buffer = _maildef.mail__message_buffer

_maildef.mail__message_return_class_swigconstant(_maildef)
mail__message_return_class = _maildef.mail__message_return_class

_maildef.mail__message_binary_date_swigconstant(_maildef)
mail__message_binary_date = _maildef.mail__message_binary_date

_maildef.mail__message_spare4_swigconstant(_maildef)
mail__message_spare4 = _maildef.mail__message_spare4

_maildef.mail__message_parse_quotes_swigconstant(_maildef)
mail__message_parse_quotes = _maildef.mail__message_parse_quotes

_maildef.mail__message_spare6_swigconstant(_maildef)
mail__message_spare6 = _maildef.mail__message_spare6

_maildef.mail__message_spare7_swigconstant(_maildef)
mail__message_spare7 = _maildef.mail__message_spare7

_maildef.mail__message_spare8_swigconstant(_maildef)
mail__message_spare8 = _maildef.mail__message_spare8

_maildef.mail__message_spare9_swigconstant(_maildef)
mail__message_spare9 = _maildef.mail__message_spare9

_maildef.mail__message_spare10_swigconstant(_maildef)
mail__message_spare10 = _maildef.mail__message_spare10

_maildef.mail__message_spare11_swigconstant(_maildef)
mail__message_spare11 = _maildef.mail__message_spare11

_maildef.mail__message_spare12_swigconstant(_maildef)
mail__message_spare12 = _maildef.mail__message_spare12

_maildef.mail__message_spare13_swigconstant(_maildef)
mail__message_spare13 = _maildef.mail__message_spare13

_maildef.mail__message_spare14_swigconstant(_maildef)
mail__message_spare14 = _maildef.mail__message_spare14

_maildef.mail__message_spare15_swigconstant(_maildef)
mail__message_spare15 = _maildef.mail__message_spare15

_maildef.mail__message_spare16_swigconstant(_maildef)
mail__message_spare16 = _maildef.mail__message_spare16

_maildef.mail__message_spare17_swigconstant(_maildef)
mail__message_spare17 = _maildef.mail__message_spare17

_maildef.mail__message_spare18_swigconstant(_maildef)
mail__message_spare18 = _maildef.mail__message_spare18

_maildef.mail__message_spare19_swigconstant(_maildef)
mail__message_spare19 = _maildef.mail__message_spare19

_maildef.mail__message_null_swigconstant(_maildef)
mail__message_null = _maildef.mail__message_null

_maildef.mail__message_header_swigconstant(_maildef)
mail__message_header = _maildef.mail__message_header

_maildef.mail__message_text_swigconstant(_maildef)
mail__message_text = _maildef.mail__message_text

_maildef.mail__message_spare20_swigconstant(_maildef)
mail__message_spare20 = _maildef.mail__message_spare20

_maildef.mail_k_message_min_item_swigconstant(_maildef)
mail_k_message_min_item = _maildef.mail_k_message_min_item

_maildef.mail_k_message_max_item_swigconstant(_maildef)
mail_k_message_max_item = _maildef.mail_k_message_max_item

_maildef.mail_k_message_items_swigconstant(_maildef)
mail_k_message_items = _maildef.mail_k_message_items

_maildef.mail__user_spare_0_swigconstant(_maildef)
mail__user_spare_0 = _maildef.mail__user_spare_0

_maildef.mail__user_first_swigconstant(_maildef)
mail__user_first = _maildef.mail__user_first

_maildef.mail__user_next_swigconstant(_maildef)
mail__user_next = _maildef.mail__user_next

_maildef.mail__user_username_swigconstant(_maildef)
mail__user_username = _maildef.mail__user_username

_maildef.mail__user_set_auto_purge_swigconstant(_maildef)
mail__user_set_auto_purge = _maildef.mail__user_set_auto_purge

_maildef.mail__user_set_no_auto_purge_swigconstant(_maildef)
mail__user_set_no_auto_purge = _maildef.mail__user_set_no_auto_purge

_maildef.mail__user_set_sub_directory_swigconstant(_maildef)
mail__user_set_sub_directory = _maildef.mail__user_set_sub_directory

_maildef.mail__user_set_no_sub_directory_swigconstant(_maildef)
mail__user_set_no_sub_directory = _maildef.mail__user_set_no_sub_directory

_maildef.mail__user_set_forwarding_swigconstant(_maildef)
mail__user_set_forwarding = _maildef.mail__user_set_forwarding

_maildef.mail__user_set_no_forwarding_swigconstant(_maildef)
mail__user_set_no_forwarding = _maildef.mail__user_set_no_forwarding

_maildef.mail__user_set_personal_name_swigconstant(_maildef)
mail__user_set_personal_name = _maildef.mail__user_set_personal_name

_maildef.mail__user_set_no_personal_name_swigconstant(_maildef)
mail__user_set_no_personal_name = _maildef.mail__user_set_no_personal_name

_maildef.mail__user_set_copy_send_swigconstant(_maildef)
mail__user_set_copy_send = _maildef.mail__user_set_copy_send

_maildef.mail__user_set_no_copy_send_swigconstant(_maildef)
mail__user_set_no_copy_send = _maildef.mail__user_set_no_copy_send

_maildef.mail__user_set_copy_reply_swigconstant(_maildef)
mail__user_set_copy_reply = _maildef.mail__user_set_copy_reply

_maildef.mail__user_set_no_copy_reply_swigconstant(_maildef)
mail__user_set_no_copy_reply = _maildef.mail__user_set_no_copy_reply

_maildef.mail__user_set_new_messages_swigconstant(_maildef)
mail__user_set_new_messages = _maildef.mail__user_set_new_messages

_maildef.mail__user_create_if_swigconstant(_maildef)
mail__user_create_if = _maildef.mail__user_create_if

_maildef.mail__user_set_mailplus_swigconstant(_maildef)
mail__user_set_mailplus = _maildef.mail__user_set_mailplus

_maildef.mail__user_set_no_mailplus_swigconstant(_maildef)
mail__user_set_no_mailplus = _maildef.mail__user_set_no_mailplus

_maildef.mail__user_set_transport_swigconstant(_maildef)
mail__user_set_transport = _maildef.mail__user_set_transport

_maildef.mail__user_set_no_transport_swigconstant(_maildef)
mail__user_set_no_transport = _maildef.mail__user_set_no_transport

_maildef.mail__user_set_editor_swigconstant(_maildef)
mail__user_set_editor = _maildef.mail__user_set_editor

_maildef.mail__user_set_no_editor_swigconstant(_maildef)
mail__user_set_no_editor = _maildef.mail__user_set_no_editor

_maildef.mail__user_set_queue_swigconstant(_maildef)
mail__user_set_queue = _maildef.mail__user_set_queue

_maildef.mail__user_set_no_queue_swigconstant(_maildef)
mail__user_set_no_queue = _maildef.mail__user_set_no_queue

_maildef.mail__user_set_user1_swigconstant(_maildef)
mail__user_set_user1 = _maildef.mail__user_set_user1

_maildef.mail__user_set_no_user1_swigconstant(_maildef)
mail__user_set_no_user1 = _maildef.mail__user_set_no_user1

_maildef.mail__user_set_user2_swigconstant(_maildef)
mail__user_set_user2 = _maildef.mail__user_set_user2

_maildef.mail__user_set_no_user2_swigconstant(_maildef)
mail__user_set_no_user2 = _maildef.mail__user_set_no_user2

_maildef.mail__user_set_user3_swigconstant(_maildef)
mail__user_set_user3 = _maildef.mail__user_set_user3

_maildef.mail__user_set_no_user3_swigconstant(_maildef)
mail__user_set_no_user3 = _maildef.mail__user_set_no_user3

_maildef.mail__user_set_form_swigconstant(_maildef)
mail__user_set_form = _maildef.mail__user_set_form

_maildef.mail__user_set_no_form_swigconstant(_maildef)
mail__user_set_no_form = _maildef.mail__user_set_no_form

_maildef.mail__user_set_copy_forward_swigconstant(_maildef)
mail__user_set_copy_forward = _maildef.mail__user_set_copy_forward

_maildef.mail__user_set_no_copy_forward_swigconstant(_maildef)
mail__user_set_no_copy_forward = _maildef.mail__user_set_no_copy_forward

_maildef.mail__user_set_cc_prompt_swigconstant(_maildef)
mail__user_set_cc_prompt = _maildef.mail__user_set_cc_prompt

_maildef.mail__user_set_no_cc_prompt_swigconstant(_maildef)
mail__user_set_no_cc_prompt = _maildef.mail__user_set_no_cc_prompt

_maildef.mail__user_set_sigfile_swigconstant(_maildef)
mail__user_set_sigfile = _maildef.mail__user_set_sigfile

_maildef.mail__user_set_no_sigfile_swigconstant(_maildef)
mail__user_set_no_sigfile = _maildef.mail__user_set_no_sigfile

_maildef.mail__user_in_spare1_swigconstant(_maildef)
mail__user_in_spare1 = _maildef.mail__user_in_spare1

_maildef.mail__user_in_spare2_swigconstant(_maildef)
mail__user_in_spare2 = _maildef.mail__user_in_spare2

_maildef.mail__user_in_spare3_swigconstant(_maildef)
mail__user_in_spare3 = _maildef.mail__user_in_spare3

_maildef.mail__user_in_spare4_swigconstant(_maildef)
mail__user_in_spare4 = _maildef.mail__user_in_spare4

_maildef.mail__user_in_spare5_swigconstant(_maildef)
mail__user_in_spare5 = _maildef.mail__user_in_spare5

_maildef.mail__user_in_spare6_swigconstant(_maildef)
mail__user_in_spare6 = _maildef.mail__user_in_spare6

_maildef.mail__user_in_spare7_swigconstant(_maildef)
mail__user_in_spare7 = _maildef.mail__user_in_spare7

_maildef.mail__user_in_spare8_swigconstant(_maildef)
mail__user_in_spare8 = _maildef.mail__user_in_spare8

_maildef.mail__user_in_spare9_swigconstant(_maildef)
mail__user_in_spare9 = _maildef.mail__user_in_spare9

_maildef.mail__user_in_spare10_swigconstant(_maildef)
mail__user_in_spare10 = _maildef.mail__user_in_spare10

_maildef.mail__user_in_spare11_swigconstant(_maildef)
mail__user_in_spare11 = _maildef.mail__user_in_spare11

_maildef.mail__user_in_spare12_swigconstant(_maildef)
mail__user_in_spare12 = _maildef.mail__user_in_spare12

_maildef.mail__user_in_spare13_swigconstant(_maildef)
mail__user_in_spare13 = _maildef.mail__user_in_spare13

_maildef.mail__user_in_spare14_swigconstant(_maildef)
mail__user_in_spare14 = _maildef.mail__user_in_spare14

_maildef.mail__user_in_spare15_swigconstant(_maildef)
mail__user_in_spare15 = _maildef.mail__user_in_spare15

_maildef.mail__user_in_spare16_swigconstant(_maildef)
mail__user_in_spare16 = _maildef.mail__user_in_spare16

_maildef.mail__user_in_spare17_swigconstant(_maildef)
mail__user_in_spare17 = _maildef.mail__user_in_spare17

_maildef.mail__user_in_spare18_swigconstant(_maildef)
mail__user_in_spare18 = _maildef.mail__user_in_spare18

_maildef.mail__user_in_spare19_swigconstant(_maildef)
mail__user_in_spare19 = _maildef.mail__user_in_spare19

_maildef.mail__user_in_spare20_swigconstant(_maildef)
mail__user_in_spare20 = _maildef.mail__user_in_spare20

_maildef.mail__user_mailplus_swigconstant(_maildef)
mail__user_mailplus = _maildef.mail__user_mailplus

_maildef.mail__user_transport_swigconstant(_maildef)
mail__user_transport = _maildef.mail__user_transport

_maildef.mail__user_editor_swigconstant(_maildef)
mail__user_editor = _maildef.mail__user_editor

_maildef.mail__user_queue_swigconstant(_maildef)
mail__user_queue = _maildef.mail__user_queue

_maildef.mail__user_user1_swigconstant(_maildef)
mail__user_user1 = _maildef.mail__user_user1

_maildef.mail__user_user2_swigconstant(_maildef)
mail__user_user2 = _maildef.mail__user_user2

_maildef.mail__user_user3_swigconstant(_maildef)
mail__user_user3 = _maildef.mail__user_user3

_maildef.mail__user_form_swigconstant(_maildef)
mail__user_form = _maildef.mail__user_form

_maildef.mail__user_copy_forward_swigconstant(_maildef)
mail__user_copy_forward = _maildef.mail__user_copy_forward

_maildef.mail__user_sigfile_swigconstant(_maildef)
mail__user_sigfile = _maildef.mail__user_sigfile

_maildef.mail__user_return_username_swigconstant(_maildef)
mail__user_return_username = _maildef.mail__user_return_username

_maildef.mail__user_auto_purge_swigconstant(_maildef)
mail__user_auto_purge = _maildef.mail__user_auto_purge

_maildef.mail__user_sub_directory_swigconstant(_maildef)
mail__user_sub_directory = _maildef.mail__user_sub_directory

_maildef.mail__user_full_directory_swigconstant(_maildef)
mail__user_full_directory = _maildef.mail__user_full_directory

_maildef.mail__user_new_messages_swigconstant(_maildef)
mail__user_new_messages = _maildef.mail__user_new_messages

_maildef.mail__user_forwarding_swigconstant(_maildef)
mail__user_forwarding = _maildef.mail__user_forwarding

_maildef.mail__user_personal_name_swigconstant(_maildef)
mail__user_personal_name = _maildef.mail__user_personal_name

_maildef.mail__user_copy_send_swigconstant(_maildef)
mail__user_copy_send = _maildef.mail__user_copy_send

_maildef.mail__user_copy_reply_swigconstant(_maildef)
mail__user_copy_reply = _maildef.mail__user_copy_reply

_maildef.mail__user_captive_swigconstant(_maildef)
mail__user_captive = _maildef.mail__user_captive

_maildef.mail__user_cc_prompt_swigconstant(_maildef)
mail__user_cc_prompt = _maildef.mail__user_cc_prompt

_maildef.mail__user_out_spare2_swigconstant(_maildef)
mail__user_out_spare2 = _maildef.mail__user_out_spare2

_maildef.mail__user_out_spare3_swigconstant(_maildef)
mail__user_out_spare3 = _maildef.mail__user_out_spare3

_maildef.mail__user_out_spare4_swigconstant(_maildef)
mail__user_out_spare4 = _maildef.mail__user_out_spare4

_maildef.mail__user_out_spare5_swigconstant(_maildef)
mail__user_out_spare5 = _maildef.mail__user_out_spare5

_maildef.mail__user_out_spare6_swigconstant(_maildef)
mail__user_out_spare6 = _maildef.mail__user_out_spare6

_maildef.mail__user_out_spare7_swigconstant(_maildef)
mail__user_out_spare7 = _maildef.mail__user_out_spare7

_maildef.mail__user_out_spare8_swigconstant(_maildef)
mail__user_out_spare8 = _maildef.mail__user_out_spare8

_maildef.mail__user_out_spare9_swigconstant(_maildef)
mail__user_out_spare9 = _maildef.mail__user_out_spare9

_maildef.mail__user_out_spare10_swigconstant(_maildef)
mail__user_out_spare10 = _maildef.mail__user_out_spare10

_maildef.mail__user_out_spare11_swigconstant(_maildef)
mail__user_out_spare11 = _maildef.mail__user_out_spare11

_maildef.mail__user_out_spare12_swigconstant(_maildef)
mail__user_out_spare12 = _maildef.mail__user_out_spare12

_maildef.mail__user_out_spare13_swigconstant(_maildef)
mail__user_out_spare13 = _maildef.mail__user_out_spare13

_maildef.mail__user_out_spare14_swigconstant(_maildef)
mail__user_out_spare14 = _maildef.mail__user_out_spare14

_maildef.mail__user_out_spare15_swigconstant(_maildef)
mail__user_out_spare15 = _maildef.mail__user_out_spare15

_maildef.mail__user_out_spare16_swigconstant(_maildef)
mail__user_out_spare16 = _maildef.mail__user_out_spare16

_maildef.mail__user_out_spare17_swigconstant(_maildef)
mail__user_out_spare17 = _maildef.mail__user_out_spare17

_maildef.mail__user_out_spare18_swigconstant(_maildef)
mail__user_out_spare18 = _maildef.mail__user_out_spare18

_maildef.mail__user_out_spare19_swigconstant(_maildef)
mail__user_out_spare19 = _maildef.mail__user_out_spare19

_maildef.mail__user_out_spare20_swigconstant(_maildef)
mail__user_out_spare20 = _maildef.mail__user_out_spare20

_maildef.mail_k_user_min_item_swigconstant(_maildef)
mail_k_user_min_item = _maildef.mail_k_user_min_item

_maildef.mail_k_user_max_item_swigconstant(_maildef)
mail_k_user_max_item = _maildef.mail_k_user_max_item

_maildef.mail_k_user_items_swigconstant(_maildef)
mail_k_user_items = _maildef.mail_k_user_items

_maildef.mail__noop_swigconstant(_maildef)
mail__noop = _maildef.mail__noop

_maildef.mail__nosignal_swigconstant(_maildef)
mail__nosignal = _maildef.mail__nosignal

_maildef.mail__noprobe_swigconstant(_maildef)
mail__noprobe = _maildef.mail__noprobe

_maildef.mail__tld_input_swigconstant(_maildef)
mail__tld_input = _maildef.mail__tld_input

_maildef.mail__tld_output_swigconstant(_maildef)
mail__tld_output = _maildef.mail__tld_output

_maildef.mail__to_swigconstant(_maildef)
mail__to = _maildef.mail__to

_maildef.mail__cc_swigconstant(_maildef)
mail__cc = _maildef.mail__cc

_maildef.mail__spare1_swigconstant(_maildef)
mail__spare1 = _maildef.mail__spare1

_maildef.mail__spare2_swigconstant(_maildef)
mail__spare2 = _maildef.mail__spare2

_maildef.MAIL_m_newmsg_swigconstant(_maildef)
MAIL_m_newmsg = _maildef.MAIL_m_newmsg

_maildef.MAIL_m_replied_swigconstant(_maildef)
MAIL_m_replied = _maildef.MAIL_m_replied

_maildef.MAIL_m_dwmail_swigconstant(_maildef)
MAIL_m_dwmail = _maildef.MAIL_m_dwmail

_maildef.MAIL_m_extmsg_swigconstant(_maildef)
MAIL_m_extmsg = _maildef.MAIL_m_extmsg

_maildef.MAIL_m_extfnf_swigconstant(_maildef)
MAIL_m_extfnf = _maildef.MAIL_m_extfnf

_maildef.MAIL_m_notrans_swigconstant(_maildef)
MAIL_m_notrans = _maildef.MAIL_m_notrans

_maildef.MAIL_m_extnstd_swigconstant(_maildef)
MAIL_m_extnstd = _maildef.MAIL_m_extnstd

_maildef.MAIL_m_marked_swigconstant(_maildef)
MAIL_m_marked = _maildef.MAIL_m_marked

_maildef.MAIL_m_recmode_swigconstant(_maildef)
MAIL_m_recmode = _maildef.MAIL_m_recmode

_maildef.MAIL_S_flagsdef_swigconstant(_maildef)
MAIL_S_flagsdef = _maildef.MAIL_S_flagsdef
# This file is compatible with both classic and new-style classes.


