# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ciadef', [dirname(__file__)])
        except ImportError:
            import _ciadef
            return _ciadef
        if fp is not None:
            try:
                _mod = imp.load_module('_ciadef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ciadef = swig_import_helper()
    del swig_import_helper
else:
    import _ciadef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_ciadef.CIA_K_SCAN_swigconstant(_ciadef)
CIA_K_SCAN = _ciadef.CIA_K_SCAN

_ciadef.CIA_K_DELETE_swigconstant(_ciadef)
CIA_K_DELETE = _ciadef.CIA_K_DELETE

_ciadef.CIA_K_SHOW_swigconstant(_ciadef)
CIA_K_SHOW = _ciadef.CIA_K_SHOW

_ciadef.CIA_K_PERFORMANCE_swigconstant(_ciadef)
CIA_K_PERFORMANCE = _ciadef.CIA_K_PERFORMANCE

_ciadef.CIA_K_ZERO_PERFORMANCE_swigconstant(_ciadef)
CIA_K_ZERO_PERFORMANCE = _ciadef.CIA_K_ZERO_PERFORMANCE

_ciadef.CIA_K_SCAN_EXTENDED_swigconstant(_ciadef)
CIA_K_SCAN_EXTENDED = _ciadef.CIA_K_SCAN_EXTENDED

_ciadef.CIA_K_DELETE_EXTENDED_swigconstant(_ciadef)
CIA_K_DELETE_EXTENDED = _ciadef.CIA_K_DELETE_EXTENDED

_ciadef.CIA_K_SHOW_EXTENDED_swigconstant(_ciadef)
CIA_K_SHOW_EXTENDED = _ciadef.CIA_K_SHOW_EXTENDED

_ciadef.CIA_K_MAX_CIA_CODE_swigconstant(_ciadef)
CIA_K_MAX_CIA_CODE = _ciadef.CIA_K_MAX_CIA_CODE

_ciadef.CIA_K_PERFORMANCE_LENGTH_swigconstant(_ciadef)
CIA_K_PERFORMANCE_LENGTH = _ciadef.CIA_K_PERFORMANCE_LENGTH

_ciadef.CIA_S_PERFORMANCE_swigconstant(_ciadef)
CIA_S_PERFORMANCE = _ciadef.CIA_S_PERFORMANCE

_ciadef.CIA_K_SOURCE_TERMINAL_LENGTH_swigconstant(_ciadef)
CIA_K_SOURCE_TERMINAL_LENGTH = _ciadef.CIA_K_SOURCE_TERMINAL_LENGTH

_ciadef.CIA_K_SOURCE_NODE_MAX_LENGTH_swigconstant(_ciadef)
CIA_K_SOURCE_NODE_MAX_LENGTH = _ciadef.CIA_K_SOURCE_NODE_MAX_LENGTH

_ciadef.CIA_K_USER_SPEC_MAX_LENGTH_swigconstant(_ciadef)
CIA_K_USER_SPEC_MAX_LENGTH = _ciadef.CIA_K_USER_SPEC_MAX_LENGTH

_ciadef.CIA_K_USER_STRING_MAX_LENGTH_swigconstant(_ciadef)
CIA_K_USER_STRING_MAX_LENGTH = _ciadef.CIA_K_USER_STRING_MAX_LENGTH

_ciadef.CIA_K_PASSWORD_MAX_LENGTH_swigconstant(_ciadef)
CIA_K_PASSWORD_MAX_LENGTH = _ciadef.CIA_K_PASSWORD_MAX_LENGTH

_ciadef.CIA_K_SOURCE_ADDRESS_MAX_LENGTH_swigconstant(_ciadef)
CIA_K_SOURCE_ADDRESS_MAX_LENGTH = _ciadef.CIA_K_SOURCE_ADDRESS_MAX_LENGTH

_ciadef.CIA_K_SCSNODE_LENGTH_swigconstant(_ciadef)
CIA_K_SCSNODE_LENGTH = _ciadef.CIA_K_SCSNODE_LENGTH

_ciadef.CIA_K_SCSNODE_REPLY_LENGTH_swigconstant(_ciadef)
CIA_K_SCSNODE_REPLY_LENGTH = _ciadef.CIA_K_SCSNODE_REPLY_LENGTH

_ciadef.CIA_K_USERDATA_LENGTH_swigconstant(_ciadef)
CIA_K_USERDATA_LENGTH = _ciadef.CIA_K_USERDATA_LENGTH

_ciadef.CIA_S_CIA_GENERIC_DESC_swigconstant(_ciadef)
CIA_S_CIA_GENERIC_DESC = _ciadef.CIA_S_CIA_GENERIC_DESC

_ciadef.CIAEXT_S_PACKET_swigconstant(_ciadef)
CIAEXT_S_PACKET = _ciadef.CIAEXT_S_PACKET

_ciadef.CIAEXT_S_EXTENSION_PACKET_swigconstant(_ciadef)
CIAEXT_S_EXTENSION_PACKET = _ciadef.CIAEXT_S_EXTENSION_PACKET

_ciadef.CIAEXT__USER_DATA_swigconstant(_ciadef)
CIAEXT__USER_DATA = _ciadef.CIAEXT__USER_DATA

_ciadef.CIAEXT__SCSNODE_swigconstant(_ciadef)
CIAEXT__SCSNODE = _ciadef.CIAEXT__SCSNODE

_ciadef.CIAEXT__SCSNODE_REPLY_swigconstant(_ciadef)
CIAEXT__SCSNODE_REPLY = _ciadef.CIAEXT__SCSNODE_REPLY

_ciadef.CIAEXT__IMAGE_NAME_swigconstant(_ciadef)
CIAEXT__IMAGE_NAME = _ciadef.CIAEXT__IMAGE_NAME

_ciadef.CIAEXT__MAX_CIAEXT_CODE_swigconstant(_ciadef)
CIAEXT__MAX_CIAEXT_CODE = _ciadef.CIAEXT__MAX_CIAEXT_CODE

_ciadef.CIA__SCSNODE_LIST_swigconstant(_ciadef)
CIA__SCSNODE_LIST = _ciadef.CIA__SCSNODE_LIST

_ciadef.CIA__SCSNODE_swigconstant(_ciadef)
CIA__SCSNODE = _ciadef.CIA__SCSNODE

_ciadef.CIA__OUTPUT_LIST_swigconstant(_ciadef)
CIA__OUTPUT_LIST = _ciadef.CIA__OUTPUT_LIST

_ciadef.CIA__USER_DATA_swigconstant(_ciadef)
CIA__USER_DATA = _ciadef.CIA__USER_DATA

_ciadef.CIA__USER_CRITERIAL_swigconstant(_ciadef)
CIA__USER_CRITERIAL = _ciadef.CIA__USER_CRITERIAL

_ciadef.CIA__FAILED_USERNAME_swigconstant(_ciadef)
CIA__FAILED_USERNAME = _ciadef.CIA__FAILED_USERNAME

_ciadef.CIA__IMAGE_NAME_swigconstant(_ciadef)
CIA__IMAGE_NAME = _ciadef.CIA__IMAGE_NAME

_ciadef.CIA__MAX_CIA_ITEM_swigconstant(_ciadef)
CIA__MAX_CIA_ITEM = _ciadef.CIA__MAX_CIA_ITEM

_ciadef.CIA_K_IMAGE_NAME_MAX_SIZE_swigconstant(_ciadef)
CIA_K_IMAGE_NAME_MAX_SIZE = _ciadef.CIA_K_IMAGE_NAME_MAX_SIZE

_ciadef.CIA_S_IMAGE_NAME_swigconstant(_ciadef)
CIA_S_IMAGE_NAME = _ciadef.CIA_S_IMAGE_NAME

_ciadef.CIA_S_IMAGE_STRING_swigconstant(_ciadef)
CIA_S_IMAGE_STRING = _ciadef.CIA_S_IMAGE_STRING

_ciadef.CIA_M_IGNORE_RETURN_swigconstant(_ciadef)
CIA_M_IGNORE_RETURN = _ciadef.CIA_M_IGNORE_RETURN

_ciadef.CIA_M_RESERVED_1_swigconstant(_ciadef)
CIA_M_RESERVED_1 = _ciadef.CIA_M_RESERVED_1

_ciadef.CIA_M_SUSPECTS_swigconstant(_ciadef)
CIA_M_SUSPECTS = _ciadef.CIA_M_SUSPECTS

_ciadef.CIA_M_INTRUDERS_swigconstant(_ciadef)
CIA_M_INTRUDERS = _ciadef.CIA_M_INTRUDERS

_ciadef.CIA_M_SECONDARY_PASSWORD_swigconstant(_ciadef)
CIA_M_SECONDARY_PASSWORD = _ciadef.CIA_M_SECONDARY_PASSWORD

_ciadef.CIA_M_NOAUDIT_swigconstant(_ciadef)
CIA_M_NOAUDIT = _ciadef.CIA_M_NOAUDIT

_ciadef.CIA_M_REAL_USERNAME_swigconstant(_ciadef)
CIA_M_REAL_USERNAME = _ciadef.CIA_M_REAL_USERNAME

_ciadef.CIA_M_SHOW_NODE_swigconstant(_ciadef)
CIA_M_SHOW_NODE = _ciadef.CIA_M_SHOW_NODE

_ciadef.CIA_M_ITEMLIST_swigconstant(_ciadef)
CIA_M_ITEMLIST = _ciadef.CIA_M_ITEMLIST

_ciadef.CIA_M_FILL_1_swigconstant(_ciadef)
CIA_M_FILL_1 = _ciadef.CIA_M_FILL_1

_ciadef.CIA_K_HEADER_LENGTH_swigconstant(_ciadef)
CIA_K_HEADER_LENGTH = _ciadef.CIA_K_HEADER_LENGTH

_ciadef.CIA_S_HEADER_swigconstant(_ciadef)
CIA_S_HEADER = _ciadef.CIA_S_HEADER

_ciadef.CIA_S_RESERVED_1_swigconstant(_ciadef)
CIA_S_RESERVED_1 = _ciadef.CIA_S_RESERVED_1

_ciadef.CIA_S_FILL_1_swigconstant(_ciadef)
CIA_S_FILL_1 = _ciadef.CIA_S_FILL_1

_ciadef.CIA_K_SHOW_INPUT_LENGTH_swigconstant(_ciadef)
CIA_K_SHOW_INPUT_LENGTH = _ciadef.CIA_K_SHOW_INPUT_LENGTH

_ciadef.CIA_K_DELETE_INPUT_LENGTH_swigconstant(_ciadef)
CIA_K_DELETE_INPUT_LENGTH = _ciadef.CIA_K_DELETE_INPUT_LENGTH

_ciadef.CIA_S_CONTENTS_swigconstant(_ciadef)
CIA_S_CONTENTS = _ciadef.CIA_S_CONTENTS

_ciadef.CIA_S_NAME_swigconstant(_ciadef)
CIA_S_NAME = _ciadef.CIA_S_NAME

_ciadef.CIA_K_SCAN_CONTENTS_LENGTH_swigconstant(_ciadef)
CIA_K_SCAN_CONTENTS_LENGTH = _ciadef.CIA_K_SCAN_CONTENTS_LENGTH

_ciadef.CIA_S_SCAN_CONTENTS_swigconstant(_ciadef)
CIA_S_SCAN_CONTENTS = _ciadef.CIA_S_SCAN_CONTENTS

_ciadef.CIA_S_SOURCE_TERMINAL_swigconstant(_ciadef)
CIA_S_SOURCE_TERMINAL = _ciadef.CIA_S_SOURCE_TERMINAL

_ciadef.CIA_S_SOURCE_TERM_NAME_swigconstant(_ciadef)
CIA_S_SOURCE_TERM_NAME = _ciadef.CIA_S_SOURCE_TERM_NAME

_ciadef.CIA_S_SOURCE_USER_swigconstant(_ciadef)
CIA_S_SOURCE_USER = _ciadef.CIA_S_SOURCE_USER

_ciadef.CIA_S_SOURCE_USER_NAME_swigconstant(_ciadef)
CIA_S_SOURCE_USER_NAME = _ciadef.CIA_S_SOURCE_USER_NAME

_ciadef.CIA_S_SOURCE_ADDRESS_swigconstant(_ciadef)
CIA_S_SOURCE_ADDRESS = _ciadef.CIA_S_SOURCE_ADDRESS

_ciadef.CIA_S_SOURCE_ADDRESS_NAME_swigconstant(_ciadef)
CIA_S_SOURCE_ADDRESS_NAME = _ciadef.CIA_S_SOURCE_ADDRESS_NAME

_ciadef.CIA_S_FAILED_USER_swigconstant(_ciadef)
CIA_S_FAILED_USER = _ciadef.CIA_S_FAILED_USER

_ciadef.CIA_S_FAILED_USER_NAME_swigconstant(_ciadef)
CIA_S_FAILED_USER_NAME = _ciadef.CIA_S_FAILED_USER_NAME

_ciadef.CIA_S_FAILED_PASSWORD_swigconstant(_ciadef)
CIA_S_FAILED_PASSWORD = _ciadef.CIA_S_FAILED_PASSWORD

_ciadef.CIA_S_FAILED_PASS_NAME_swigconstant(_ciadef)
CIA_S_FAILED_PASS_NAME = _ciadef.CIA_S_FAILED_PASS_NAME

_ciadef.CIA_S_PARENT_USER_swigconstant(_ciadef)
CIA_S_PARENT_USER = _ciadef.CIA_S_PARENT_USER

_ciadef.CIA_S_PARENT_USER_NAME_swigconstant(_ciadef)
CIA_S_PARENT_USER_NAME = _ciadef.CIA_S_PARENT_USER_NAME

_ciadef.CIA_S_SOURCE_NODE_swigconstant(_ciadef)
CIA_S_SOURCE_NODE = _ciadef.CIA_S_SOURCE_NODE

_ciadef.CIA_S_SOURCE_NODE_NAME_swigconstant(_ciadef)
CIA_S_SOURCE_NODE_NAME = _ciadef.CIA_S_SOURCE_NODE_NAME

_ciadef.CIA_M_INTRUDER_swigconstant(_ciadef)
CIA_M_INTRUDER = _ciadef.CIA_M_INTRUDER

_ciadef.CIA_M_SUSPECT_swigconstant(_ciadef)
CIA_M_SUSPECT = _ciadef.CIA_M_SUSPECT

_ciadef.CIA_M_NETWORK_swigconstant(_ciadef)
CIA_M_NETWORK = _ciadef.CIA_M_NETWORK

_ciadef.CIA_M_TERM_USER_swigconstant(_ciadef)
CIA_M_TERM_USER = _ciadef.CIA_M_TERM_USER

_ciadef.CIA_M_TERMINAL_swigconstant(_ciadef)
CIA_M_TERMINAL = _ciadef.CIA_M_TERMINAL

_ciadef.CIA_M_USERNAME_swigconstant(_ciadef)
CIA_M_USERNAME = _ciadef.CIA_M_USERNAME

_ciadef.CIA_M_FILL_2_swigconstant(_ciadef)
CIA_M_FILL_2 = _ciadef.CIA_M_FILL_2

_ciadef.CIA_K_SHOW_OUTPUT_LENGTH_swigconstant(_ciadef)
CIA_K_SHOW_OUTPUT_LENGTH = _ciadef.CIA_K_SHOW_OUTPUT_LENGTH

_ciadef.CIA_S_SHOW_OUTPUT_swigconstant(_ciadef)
CIA_S_SHOW_OUTPUT = _ciadef.CIA_S_SHOW_OUTPUT

_ciadef.CIA_S_EXPIRATION_TIME_swigconstant(_ciadef)
CIA_S_EXPIRATION_TIME = _ciadef.CIA_S_EXPIRATION_TIME

_ciadef.CIA_S_USER_SPEC_swigconstant(_ciadef)
CIA_S_USER_SPEC = _ciadef.CIA_S_USER_SPEC

_ciadef.CIA_S_USER_SPEC_NAME_swigconstant(_ciadef)
CIA_S_USER_SPEC_NAME = _ciadef.CIA_S_USER_SPEC_NAME

_ciadef.CIA_S_BREAKIN_BLOCK_swigconstant(_ciadef)
CIA_S_BREAKIN_BLOCK = _ciadef.CIA_S_BREAKIN_BLOCK

_ciadef.CIA_S_BREAK_TIME_swigconstant(_ciadef)
CIA_S_BREAK_TIME = _ciadef.CIA_S_BREAK_TIME

_ciadef.CIA_S_CIA_GENERIC_REPLY_swigconstant(_ciadef)
CIA_S_CIA_GENERIC_REPLY = _ciadef.CIA_S_CIA_GENERIC_REPLY
# This file is compatible with both classic and new-style classes.


