# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_uaidef', [dirname(__file__)])
        except ImportError:
            import _uaidef
            return _uaidef
        if fp is not None:
            try:
                _mod = imp.load_module('_uaidef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _uaidef = swig_import_helper()
    del swig_import_helper
else:
    import _uaidef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_uaidef.UAI__RTYPE_swigconstant(_uaidef)
UAI__RTYPE = _uaidef.UAI__RTYPE

_uaidef.UAI__VERSION_swigconstant(_uaidef)
UAI__VERSION = _uaidef.UAI__VERSION

_uaidef.UAI__USRDATOFF_swigconstant(_uaidef)
UAI__USRDATOFF = _uaidef.UAI__USRDATOFF

_uaidef.UAI__USERNAME_swigconstant(_uaidef)
UAI__USERNAME = _uaidef.UAI__USERNAME

_uaidef.UAI__USERNAME_TAG_swigconstant(_uaidef)
UAI__USERNAME_TAG = _uaidef.UAI__USERNAME_TAG

_uaidef.UAI__UIC_swigconstant(_uaidef)
UAI__UIC = _uaidef.UAI__UIC

_uaidef.UAI__MEM_swigconstant(_uaidef)
UAI__MEM = _uaidef.UAI__MEM

_uaidef.UAI__GRP_swigconstant(_uaidef)
UAI__GRP = _uaidef.UAI__GRP

_uaidef.UAI__SUB_ID_swigconstant(_uaidef)
UAI__SUB_ID = _uaidef.UAI__SUB_ID

_uaidef.UAI__PARENT_ID_swigconstant(_uaidef)
UAI__PARENT_ID = _uaidef.UAI__PARENT_ID

_uaidef.UAI__ACCOUNT_swigconstant(_uaidef)
UAI__ACCOUNT = _uaidef.UAI__ACCOUNT

_uaidef.UAI__OWNER_swigconstant(_uaidef)
UAI__OWNER = _uaidef.UAI__OWNER

_uaidef.UAI__DEFDEV_swigconstant(_uaidef)
UAI__DEFDEV = _uaidef.UAI__DEFDEV

_uaidef.UAI__DEFDIR_swigconstant(_uaidef)
UAI__DEFDIR = _uaidef.UAI__DEFDIR

_uaidef.UAI__LGICMD_swigconstant(_uaidef)
UAI__LGICMD = _uaidef.UAI__LGICMD

_uaidef.UAI__DEFCLI_swigconstant(_uaidef)
UAI__DEFCLI = _uaidef.UAI__DEFCLI

_uaidef.UAI__CLITABLES_swigconstant(_uaidef)
UAI__CLITABLES = _uaidef.UAI__CLITABLES

_uaidef.UAI__PWD_swigconstant(_uaidef)
UAI__PWD = _uaidef.UAI__PWD

_uaidef.UAI__PWD2_swigconstant(_uaidef)
UAI__PWD2 = _uaidef.UAI__PWD2

_uaidef.UAI__LOGFAILS_swigconstant(_uaidef)
UAI__LOGFAILS = _uaidef.UAI__LOGFAILS

_uaidef.UAI__SALT_swigconstant(_uaidef)
UAI__SALT = _uaidef.UAI__SALT

_uaidef.UAI__ENCRYPT_swigconstant(_uaidef)
UAI__ENCRYPT = _uaidef.UAI__ENCRYPT

_uaidef.UAI__ENCRYPT2_swigconstant(_uaidef)
UAI__ENCRYPT2 = _uaidef.UAI__ENCRYPT2

_uaidef.UAI__PWD_LENGTH_swigconstant(_uaidef)
UAI__PWD_LENGTH = _uaidef.UAI__PWD_LENGTH

_uaidef.UAI__EXPIRATION_swigconstant(_uaidef)
UAI__EXPIRATION = _uaidef.UAI__EXPIRATION

_uaidef.UAI__PWD_LIFETIME_swigconstant(_uaidef)
UAI__PWD_LIFETIME = _uaidef.UAI__PWD_LIFETIME

_uaidef.UAI__PWD_DATE_swigconstant(_uaidef)
UAI__PWD_DATE = _uaidef.UAI__PWD_DATE

_uaidef.UAI__PWD2_DATE_swigconstant(_uaidef)
UAI__PWD2_DATE = _uaidef.UAI__PWD2_DATE

_uaidef.UAI__LASTLOGIN_I_swigconstant(_uaidef)
UAI__LASTLOGIN_I = _uaidef.UAI__LASTLOGIN_I

_uaidef.UAI__LASTLOGIN_N_swigconstant(_uaidef)
UAI__LASTLOGIN_N = _uaidef.UAI__LASTLOGIN_N

_uaidef.UAI__PRIV_swigconstant(_uaidef)
UAI__PRIV = _uaidef.UAI__PRIV

_uaidef.UAI__DEF_PRIV_swigconstant(_uaidef)
UAI__DEF_PRIV = _uaidef.UAI__DEF_PRIV

_uaidef.UAI__MIN_CLASS_swigconstant(_uaidef)
UAI__MIN_CLASS = _uaidef.UAI__MIN_CLASS

_uaidef.UAI__MAX_CLASS_swigconstant(_uaidef)
UAI__MAX_CLASS = _uaidef.UAI__MAX_CLASS

_uaidef.UAI__FLAGS_swigconstant(_uaidef)
UAI__FLAGS = _uaidef.UAI__FLAGS

_uaidef.UAI__NETWORK_ACCESS_P_swigconstant(_uaidef)
UAI__NETWORK_ACCESS_P = _uaidef.UAI__NETWORK_ACCESS_P

_uaidef.UAI__NETWORK_ACCESS_S_swigconstant(_uaidef)
UAI__NETWORK_ACCESS_S = _uaidef.UAI__NETWORK_ACCESS_S

_uaidef.UAI__BATCH_ACCESS_P_swigconstant(_uaidef)
UAI__BATCH_ACCESS_P = _uaidef.UAI__BATCH_ACCESS_P

_uaidef.UAI__BATCH_ACCESS_S_swigconstant(_uaidef)
UAI__BATCH_ACCESS_S = _uaidef.UAI__BATCH_ACCESS_S

_uaidef.UAI__LOCAL_ACCESS_P_swigconstant(_uaidef)
UAI__LOCAL_ACCESS_P = _uaidef.UAI__LOCAL_ACCESS_P

_uaidef.UAI__LOCAL_ACCESS_S_swigconstant(_uaidef)
UAI__LOCAL_ACCESS_S = _uaidef.UAI__LOCAL_ACCESS_S

_uaidef.UAI__DIALUP_ACCESS_P_swigconstant(_uaidef)
UAI__DIALUP_ACCESS_P = _uaidef.UAI__DIALUP_ACCESS_P

_uaidef.UAI__DIALUP_ACCESS_S_swigconstant(_uaidef)
UAI__DIALUP_ACCESS_S = _uaidef.UAI__DIALUP_ACCESS_S

_uaidef.UAI__REMOTE_ACCESS_P_swigconstant(_uaidef)
UAI__REMOTE_ACCESS_P = _uaidef.UAI__REMOTE_ACCESS_P

_uaidef.UAI__REMOTE_ACCESS_S_swigconstant(_uaidef)
UAI__REMOTE_ACCESS_S = _uaidef.UAI__REMOTE_ACCESS_S

_uaidef.UAI__PRIMEDAYS_swigconstant(_uaidef)
UAI__PRIMEDAYS = _uaidef.UAI__PRIMEDAYS

_uaidef.UAI__PRI_swigconstant(_uaidef)
UAI__PRI = _uaidef.UAI__PRI

_uaidef.UAI__QUEPRI_swigconstant(_uaidef)
UAI__QUEPRI = _uaidef.UAI__QUEPRI

_uaidef.UAI__MAXJOBS_swigconstant(_uaidef)
UAI__MAXJOBS = _uaidef.UAI__MAXJOBS

_uaidef.UAI__MAXACCTJOBS_swigconstant(_uaidef)
UAI__MAXACCTJOBS = _uaidef.UAI__MAXACCTJOBS

_uaidef.UAI__MAXDETACH_swigconstant(_uaidef)
UAI__MAXDETACH = _uaidef.UAI__MAXDETACH

_uaidef.UAI__PRCCNT_swigconstant(_uaidef)
UAI__PRCCNT = _uaidef.UAI__PRCCNT

_uaidef.UAI__BIOLM_swigconstant(_uaidef)
UAI__BIOLM = _uaidef.UAI__BIOLM

_uaidef.UAI__DIOLM_swigconstant(_uaidef)
UAI__DIOLM = _uaidef.UAI__DIOLM

_uaidef.UAI__TQCNT_swigconstant(_uaidef)
UAI__TQCNT = _uaidef.UAI__TQCNT

_uaidef.UAI__ASTLM_swigconstant(_uaidef)
UAI__ASTLM = _uaidef.UAI__ASTLM

_uaidef.UAI__ENQLM_swigconstant(_uaidef)
UAI__ENQLM = _uaidef.UAI__ENQLM

_uaidef.UAI__FILLM_swigconstant(_uaidef)
UAI__FILLM = _uaidef.UAI__FILLM

_uaidef.UAI__SHRFILLM_swigconstant(_uaidef)
UAI__SHRFILLM = _uaidef.UAI__SHRFILLM

_uaidef.UAI__WSQUOTA_swigconstant(_uaidef)
UAI__WSQUOTA = _uaidef.UAI__WSQUOTA

_uaidef.UAI__DFWSCNT_swigconstant(_uaidef)
UAI__DFWSCNT = _uaidef.UAI__DFWSCNT

_uaidef.UAI__WSEXTENT_swigconstant(_uaidef)
UAI__WSEXTENT = _uaidef.UAI__WSEXTENT

_uaidef.UAI__PGFLQUOTA_swigconstant(_uaidef)
UAI__PGFLQUOTA = _uaidef.UAI__PGFLQUOTA

_uaidef.UAI__CPUTIM_swigconstant(_uaidef)
UAI__CPUTIM = _uaidef.UAI__CPUTIM

_uaidef.UAI__BYTLM_swigconstant(_uaidef)
UAI__BYTLM = _uaidef.UAI__BYTLM

_uaidef.UAI__PBYTLM_swigconstant(_uaidef)
UAI__PBYTLM = _uaidef.UAI__PBYTLM

_uaidef.UAI__JTQUOTA_swigconstant(_uaidef)
UAI__JTQUOTA = _uaidef.UAI__JTQUOTA

_uaidef.UAI__PROXY_LIM_swigconstant(_uaidef)
UAI__PROXY_LIM = _uaidef.UAI__PROXY_LIM

_uaidef.UAI__PROXIES_swigconstant(_uaidef)
UAI__PROXIES = _uaidef.UAI__PROXIES

_uaidef.UAI__ACCOUNT_LIM_swigconstant(_uaidef)
UAI__ACCOUNT_LIM = _uaidef.UAI__ACCOUNT_LIM

_uaidef.UAI__ACCOUNTS_swigconstant(_uaidef)
UAI__ACCOUNTS = _uaidef.UAI__ACCOUNTS

_uaidef.UAI__USER_DATA_swigconstant(_uaidef)
UAI__USER_DATA = _uaidef.UAI__USER_DATA

_uaidef.UAI__PASSWORD_swigconstant(_uaidef)
UAI__PASSWORD = _uaidef.UAI__PASSWORD

_uaidef.UAI__PASSWORD2_swigconstant(_uaidef)
UAI__PASSWORD2 = _uaidef.UAI__PASSWORD2

_uaidef.UAI__DEF_CLASS_swigconstant(_uaidef)
UAI__DEF_CLASS = _uaidef.UAI__DEF_CLASS

_uaidef.UAI__AUDIT_FLAGS_swigconstant(_uaidef)
UAI__AUDIT_FLAGS = _uaidef.UAI__AUDIT_FLAGS

_uaidef.UAI__MAX_ITEM_CODE_swigconstant(_uaidef)
UAI__MAX_ITEM_CODE = _uaidef.UAI__MAX_ITEM_CODE

_uaidef.UAI__DEFCHARGE_CODE_swigconstant(_uaidef)
UAI__DEFCHARGE_CODE = _uaidef.UAI__DEFCHARGE_CODE

_uaidef.UAI_C_AD_II_swigconstant(_uaidef)
UAI_C_AD_II = _uaidef.UAI_C_AD_II

_uaidef.UAI_C_PURDY_swigconstant(_uaidef)
UAI_C_PURDY = _uaidef.UAI_C_PURDY

_uaidef.UAI_C_PURDY_V_swigconstant(_uaidef)
UAI_C_PURDY_V = _uaidef.UAI_C_PURDY_V

_uaidef.UAI_C_PURDY_S_swigconstant(_uaidef)
UAI_C_PURDY_S = _uaidef.UAI_C_PURDY_S

_uaidef.UAI_C_PREFERED_ALGORITHM_swigconstant(_uaidef)
UAI_C_PREFERED_ALGORITHM = _uaidef.UAI_C_PREFERED_ALGORITHM

_uaidef.UAI_C_PREFERRED_ALGORITHM_swigconstant(_uaidef)
UAI_C_PREFERRED_ALGORITHM = _uaidef.UAI_C_PREFERRED_ALGORITHM

_uaidef.UAI_C_CUST_ALGORITHM_swigconstant(_uaidef)
UAI_C_CUST_ALGORITHM = _uaidef.UAI_C_CUST_ALGORITHM

_uaidef.UAI_C_MAX_PWD_LENGTH_swigconstant(_uaidef)
UAI_C_MAX_PWD_LENGTH = _uaidef.UAI_C_MAX_PWD_LENGTH

_uaidef.UAI_M_DISCTLY_swigconstant(_uaidef)
UAI_M_DISCTLY = _uaidef.UAI_M_DISCTLY

_uaidef.UAI_M_DEFCLI_swigconstant(_uaidef)
UAI_M_DEFCLI = _uaidef.UAI_M_DEFCLI

_uaidef.UAI_M_LOCKPWD_swigconstant(_uaidef)
UAI_M_LOCKPWD = _uaidef.UAI_M_LOCKPWD

_uaidef.UAI_M_RESTRICTED_swigconstant(_uaidef)
UAI_M_RESTRICTED = _uaidef.UAI_M_RESTRICTED

_uaidef.UAI_M_DISACNT_swigconstant(_uaidef)
UAI_M_DISACNT = _uaidef.UAI_M_DISACNT

_uaidef.UAI_M_DISWELCOM_swigconstant(_uaidef)
UAI_M_DISWELCOM = _uaidef.UAI_M_DISWELCOM

_uaidef.UAI_M_DISMAIL_swigconstant(_uaidef)
UAI_M_DISMAIL = _uaidef.UAI_M_DISMAIL

_uaidef.UAI_M_NOMAIL_swigconstant(_uaidef)
UAI_M_NOMAIL = _uaidef.UAI_M_NOMAIL

_uaidef.UAI_M_GENPWD_swigconstant(_uaidef)
UAI_M_GENPWD = _uaidef.UAI_M_GENPWD

_uaidef.UAI_M_PWD_EXPIRED_swigconstant(_uaidef)
UAI_M_PWD_EXPIRED = _uaidef.UAI_M_PWD_EXPIRED

_uaidef.UAI_M_PWD2_EXPIRED_swigconstant(_uaidef)
UAI_M_PWD2_EXPIRED = _uaidef.UAI_M_PWD2_EXPIRED

_uaidef.UAI_M_AUDIT_swigconstant(_uaidef)
UAI_M_AUDIT = _uaidef.UAI_M_AUDIT

_uaidef.UAI_M_DISREPORT_swigconstant(_uaidef)
UAI_M_DISREPORT = _uaidef.UAI_M_DISREPORT

_uaidef.UAI_M_DISRECONNECT_swigconstant(_uaidef)
UAI_M_DISRECONNECT = _uaidef.UAI_M_DISRECONNECT

_uaidef.UAI_M_AUTOLOGIN_swigconstant(_uaidef)
UAI_M_AUTOLOGIN = _uaidef.UAI_M_AUTOLOGIN

_uaidef.UAI_M_DISFORCE_PWD_CHANGE_swigconstant(_uaidef)
UAI_M_DISFORCE_PWD_CHANGE = _uaidef.UAI_M_DISFORCE_PWD_CHANGE

_uaidef.UAI_M_CAPTIVE_swigconstant(_uaidef)
UAI_M_CAPTIVE = _uaidef.UAI_M_CAPTIVE

_uaidef.UAI_M_DISIMAGE_swigconstant(_uaidef)
UAI_M_DISIMAGE = _uaidef.UAI_M_DISIMAGE

_uaidef.UAI_M_DISPWDDIC_swigconstant(_uaidef)
UAI_M_DISPWDDIC = _uaidef.UAI_M_DISPWDDIC

_uaidef.UAI_M_DISPWDHIS_swigconstant(_uaidef)
UAI_M_DISPWDHIS = _uaidef.UAI_M_DISPWDHIS

_uaidef.UAI_M_DEFCLSVAL_swigconstant(_uaidef)
UAI_M_DEFCLSVAL = _uaidef.UAI_M_DEFCLSVAL

_uaidef.UAI_M_EXTAUTH_swigconstant(_uaidef)
UAI_M_EXTAUTH = _uaidef.UAI_M_EXTAUTH

_uaidef.UAI_M_MIGRATEPWD_swigconstant(_uaidef)
UAI_M_MIGRATEPWD = _uaidef.UAI_M_MIGRATEPWD

_uaidef.UAI_M_VMSAUTH_swigconstant(_uaidef)
UAI_M_VMSAUTH = _uaidef.UAI_M_VMSAUTH

_uaidef.UAI_M_DISPWDSYNCH_swigconstant(_uaidef)
UAI_M_DISPWDSYNCH = _uaidef.UAI_M_DISPWDSYNCH

_uaidef.UAI_M_PWDMIX_swigconstant(_uaidef)
UAI_M_PWDMIX = _uaidef.UAI_M_PWDMIX

_uaidef.UAI_S_FLAGS_swigconstant(_uaidef)
UAI_S_FLAGS = _uaidef.UAI_S_FLAGS

_uaidef.UAI_S_PRIMEDAYS_swigconstant(_uaidef)
UAI_S_PRIMEDAYS = _uaidef.UAI_S_PRIMEDAYS
# This file is compatible with both classic and new-style classes.


