# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sjcdef', [dirname(__file__)])
        except ImportError:
            import _sjcdef
            return _sjcdef
        if fp is not None:
            try:
                _mod = imp.load_module('_sjcdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sjcdef = swig_import_helper()
    del swig_import_helper
else:
    import _sjcdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_sjcdef.SJC__ABORT_JOB_swigconstant(_sjcdef)
SJC__ABORT_JOB = _sjcdef.SJC__ABORT_JOB

_sjcdef.SJC__ADD_FILE_swigconstant(_sjcdef)
SJC__ADD_FILE = _sjcdef.SJC__ADD_FILE

_sjcdef.SJC__ALTER_JOB_swigconstant(_sjcdef)
SJC__ALTER_JOB = _sjcdef.SJC__ALTER_JOB

_sjcdef.SJC__ALTER_QUEUE_swigconstant(_sjcdef)
SJC__ALTER_QUEUE = _sjcdef.SJC__ALTER_QUEUE

_sjcdef.SJC__ASSIGN_QUEUE_swigconstant(_sjcdef)
SJC__ASSIGN_QUEUE = _sjcdef.SJC__ASSIGN_QUEUE

_sjcdef.SJC__BATCH_CHECKPOINT_swigconstant(_sjcdef)
SJC__BATCH_CHECKPOINT = _sjcdef.SJC__BATCH_CHECKPOINT

_sjcdef.SJC__BATCH_SERVICE_swigconstant(_sjcdef)
SJC__BATCH_SERVICE = _sjcdef.SJC__BATCH_SERVICE

_sjcdef.SJC__CLOSE_DELETE_swigconstant(_sjcdef)
SJC__CLOSE_DELETE = _sjcdef.SJC__CLOSE_DELETE

_sjcdef.SJC__CLOSE_JOB_swigconstant(_sjcdef)
SJC__CLOSE_JOB = _sjcdef.SJC__CLOSE_JOB

_sjcdef.SJC__CREATE_JOB_swigconstant(_sjcdef)
SJC__CREATE_JOB = _sjcdef.SJC__CREATE_JOB

_sjcdef.SJC__CREATE_QUEUE_swigconstant(_sjcdef)
SJC__CREATE_QUEUE = _sjcdef.SJC__CREATE_QUEUE

_sjcdef.SJC__DEASSIGN_QUEUE_swigconstant(_sjcdef)
SJC__DEASSIGN_QUEUE = _sjcdef.SJC__DEASSIGN_QUEUE

_sjcdef.SJC__DEFINE_CHARACTERISTIC_swigconstant(_sjcdef)
SJC__DEFINE_CHARACTERISTIC = _sjcdef.SJC__DEFINE_CHARACTERISTIC

_sjcdef.SJC__DEFINE_FORM_swigconstant(_sjcdef)
SJC__DEFINE_FORM = _sjcdef.SJC__DEFINE_FORM

_sjcdef.SJC__DELETE_CHARACTERISTIC_swigconstant(_sjcdef)
SJC__DELETE_CHARACTERISTIC = _sjcdef.SJC__DELETE_CHARACTERISTIC

_sjcdef.SJC__DELETE_FORM_swigconstant(_sjcdef)
SJC__DELETE_FORM = _sjcdef.SJC__DELETE_FORM

_sjcdef.SJC__DELETE_JOB_swigconstant(_sjcdef)
SJC__DELETE_JOB = _sjcdef.SJC__DELETE_JOB

_sjcdef.SJC__DELETE_QUEUE_swigconstant(_sjcdef)
SJC__DELETE_QUEUE = _sjcdef.SJC__DELETE_QUEUE

_sjcdef.SJC__ENTER_FILE_swigconstant(_sjcdef)
SJC__ENTER_FILE = _sjcdef.SJC__ENTER_FILE

_sjcdef.SJC__MERGE_QUEUE_swigconstant(_sjcdef)
SJC__MERGE_QUEUE = _sjcdef.SJC__MERGE_QUEUE

_sjcdef.SJC__PAUSE_QUEUE_swigconstant(_sjcdef)
SJC__PAUSE_QUEUE = _sjcdef.SJC__PAUSE_QUEUE

_sjcdef.SJC__RESET_QUEUE_swigconstant(_sjcdef)
SJC__RESET_QUEUE = _sjcdef.SJC__RESET_QUEUE

_sjcdef.SJC__START_ACCOUNTING_swigconstant(_sjcdef)
SJC__START_ACCOUNTING = _sjcdef.SJC__START_ACCOUNTING

_sjcdef.SJC__START_QUEUE_swigconstant(_sjcdef)
SJC__START_QUEUE = _sjcdef.SJC__START_QUEUE

_sjcdef.SJC__START_QUEUE_MANAGER_swigconstant(_sjcdef)
SJC__START_QUEUE_MANAGER = _sjcdef.SJC__START_QUEUE_MANAGER

_sjcdef.SJC__STOP_ACCOUNTING_swigconstant(_sjcdef)
SJC__STOP_ACCOUNTING = _sjcdef.SJC__STOP_ACCOUNTING

_sjcdef.SJC__STOP_QUEUE_swigconstant(_sjcdef)
SJC__STOP_QUEUE = _sjcdef.SJC__STOP_QUEUE

_sjcdef.SJC__STOP_QUEUE_MANAGER_swigconstant(_sjcdef)
SJC__STOP_QUEUE_MANAGER = _sjcdef.SJC__STOP_QUEUE_MANAGER

_sjcdef.SJC__SYNCHRONIZE_JOB_swigconstant(_sjcdef)
SJC__SYNCHRONIZE_JOB = _sjcdef.SJC__SYNCHRONIZE_JOB

_sjcdef.SJC__WRITE_ACCOUNTING_swigconstant(_sjcdef)
SJC__WRITE_ACCOUNTING = _sjcdef.SJC__WRITE_ACCOUNTING

_sjcdef.SJC__CONTROL_DIAGNOSTICS_swigconstant(_sjcdef)
SJC__CONTROL_DIAGNOSTICS = _sjcdef.SJC__CONTROL_DIAGNOSTICS

_sjcdef.SJC__DELETE_QUEUE_MANAGER_swigconstant(_sjcdef)
SJC__DELETE_QUEUE_MANAGER = _sjcdef.SJC__DELETE_QUEUE_MANAGER

_sjcdef.SJC__ALTER_FILE_swigconstant(_sjcdef)
SJC__ALTER_FILE = _sjcdef.SJC__ALTER_FILE

_sjcdef.SJC__STOP_ALL_QUEUES_ON_NODE_swigconstant(_sjcdef)
SJC__STOP_ALL_QUEUES_ON_NODE = _sjcdef.SJC__STOP_ALL_QUEUES_ON_NODE

_sjcdef.SJC__DISABLE_QUEUE_swigconstant(_sjcdef)
SJC__DISABLE_QUEUE = _sjcdef.SJC__DISABLE_QUEUE

_sjcdef.SJC__ENABLE_QUEUE_swigconstant(_sjcdef)
SJC__ENABLE_QUEUE = _sjcdef.SJC__ENABLE_QUEUE

_sjcdef.SJC__SYMBIONT_SERVICE_swigconstant(_sjcdef)
SJC__SYMBIONT_SERVICE = _sjcdef.SJC__SYMBIONT_SERVICE

_sjcdef.SJC__JOBCTL_SERVICE_swigconstant(_sjcdef)
SJC__JOBCTL_SERVICE = _sjcdef.SJC__JOBCTL_SERVICE

_sjcdef.SJC__ENABLE_AUTOSTART_swigconstant(_sjcdef)
SJC__ENABLE_AUTOSTART = _sjcdef.SJC__ENABLE_AUTOSTART

_sjcdef.SJC__DISABLE_AUTOSTART_swigconstant(_sjcdef)
SJC__DISABLE_AUTOSTART = _sjcdef.SJC__DISABLE_AUTOSTART

_sjcdef.SJC__SHUTDOWN_NODE_swigconstant(_sjcdef)
SJC__SHUTDOWN_NODE = _sjcdef.SJC__SHUTDOWN_NODE

_sjcdef.SJC__RESERVED_FUNC_42_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_42 = _sjcdef.SJC__RESERVED_FUNC_42

_sjcdef.SJC__RESERVED_FUNC_43_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_43 = _sjcdef.SJC__RESERVED_FUNC_43

_sjcdef.SJC__RESERVED_FUNC_44_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_44 = _sjcdef.SJC__RESERVED_FUNC_44

_sjcdef.SJC__RESERVED_FUNC_45_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_45 = _sjcdef.SJC__RESERVED_FUNC_45

_sjcdef.SJC__RESERVED_FUNC_46_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_46 = _sjcdef.SJC__RESERVED_FUNC_46

_sjcdef.SJC__RESERVED_FUNC_47_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_47 = _sjcdef.SJC__RESERVED_FUNC_47

_sjcdef.SJC__RESERVED_FUNC_48_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_48 = _sjcdef.SJC__RESERVED_FUNC_48

_sjcdef.SJC__RESERVED_FUNC_49_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_49 = _sjcdef.SJC__RESERVED_FUNC_49

_sjcdef.SJC__RESERVED_FUNC_50_swigconstant(_sjcdef)
SJC__RESERVED_FUNC_50 = _sjcdef.SJC__RESERVED_FUNC_50

_sjcdef.SJC_K_MIN_FUNC_swigconstant(_sjcdef)
SJC_K_MIN_FUNC = _sjcdef.SJC_K_MIN_FUNC

_sjcdef.SJC_K_MAX_FUNC_swigconstant(_sjcdef)
SJC_K_MAX_FUNC = _sjcdef.SJC_K_MAX_FUNC

_sjcdef.SJC__ACCOUNTING_MESSAGE_swigconstant(_sjcdef)
SJC__ACCOUNTING_MESSAGE = _sjcdef.SJC__ACCOUNTING_MESSAGE

_sjcdef.SJC__ACCOUNTING_TYPES_swigconstant(_sjcdef)
SJC__ACCOUNTING_TYPES = _sjcdef.SJC__ACCOUNTING_TYPES

_sjcdef.SJC__AFTER_TIME_swigconstant(_sjcdef)
SJC__AFTER_TIME = _sjcdef.SJC__AFTER_TIME

_sjcdef.SJC__NO_AFTER_TIME_swigconstant(_sjcdef)
SJC__NO_AFTER_TIME = _sjcdef.SJC__NO_AFTER_TIME

_sjcdef.SJC__ALIGNMENT_MASK_swigconstant(_sjcdef)
SJC__ALIGNMENT_MASK = _sjcdef.SJC__ALIGNMENT_MASK

_sjcdef.SJC__ALIGNMENT_PAGES_swigconstant(_sjcdef)
SJC__ALIGNMENT_PAGES = _sjcdef.SJC__ALIGNMENT_PAGES

_sjcdef.SJC__BASE_PRIORITY_swigconstant(_sjcdef)
SJC__BASE_PRIORITY = _sjcdef.SJC__BASE_PRIORITY

_sjcdef.SJC__BATCH_swigconstant(_sjcdef)
SJC__BATCH = _sjcdef.SJC__BATCH

_sjcdef.SJC__NO_BATCH_swigconstant(_sjcdef)
SJC__NO_BATCH = _sjcdef.SJC__NO_BATCH

_sjcdef.SJC__BATCH_INPUT_swigconstant(_sjcdef)
SJC__BATCH_INPUT = _sjcdef.SJC__BATCH_INPUT

_sjcdef.SJC__BATCH_OUTPUT_swigconstant(_sjcdef)
SJC__BATCH_OUTPUT = _sjcdef.SJC__BATCH_OUTPUT

_sjcdef.SJC__CHARACTERISTIC_NAME_swigconstant(_sjcdef)
SJC__CHARACTERISTIC_NAME = _sjcdef.SJC__CHARACTERISTIC_NAME

_sjcdef.SJC__CHARACTERISTIC_NUMBER_swigconstant(_sjcdef)
SJC__CHARACTERISTIC_NUMBER = _sjcdef.SJC__CHARACTERISTIC_NUMBER

_sjcdef.SJC__NO_CHARACTERISTICS_swigconstant(_sjcdef)
SJC__NO_CHARACTERISTICS = _sjcdef.SJC__NO_CHARACTERISTICS

_sjcdef.SJC__CHECKPOINT_DATA_swigconstant(_sjcdef)
SJC__CHECKPOINT_DATA = _sjcdef.SJC__CHECKPOINT_DATA

_sjcdef.SJC__NO_CHECKPOINT_DATA_swigconstant(_sjcdef)
SJC__NO_CHECKPOINT_DATA = _sjcdef.SJC__NO_CHECKPOINT_DATA

_sjcdef.SJC__CLI_swigconstant(_sjcdef)
SJC__CLI = _sjcdef.SJC__CLI

_sjcdef.SJC__NO_CLI_swigconstant(_sjcdef)
SJC__NO_CLI = _sjcdef.SJC__NO_CLI

_sjcdef.SJC__CPU_DEFAULT_swigconstant(_sjcdef)
SJC__CPU_DEFAULT = _sjcdef.SJC__CPU_DEFAULT

_sjcdef.SJC__NO_CPU_DEFAULT_swigconstant(_sjcdef)
SJC__NO_CPU_DEFAULT = _sjcdef.SJC__NO_CPU_DEFAULT

_sjcdef.SJC__CPU_LIMIT_swigconstant(_sjcdef)
SJC__CPU_LIMIT = _sjcdef.SJC__CPU_LIMIT

_sjcdef.SJC__NO_CPU_LIMIT_swigconstant(_sjcdef)
SJC__NO_CPU_LIMIT = _sjcdef.SJC__NO_CPU_LIMIT

_sjcdef.SJC__CREATE_START_swigconstant(_sjcdef)
SJC__CREATE_START = _sjcdef.SJC__CREATE_START

_sjcdef.SJC__DELETE_FILE_swigconstant(_sjcdef)
SJC__DELETE_FILE = _sjcdef.SJC__DELETE_FILE

_sjcdef.SJC__NO_DELETE_FILE_swigconstant(_sjcdef)
SJC__NO_DELETE_FILE = _sjcdef.SJC__NO_DELETE_FILE

_sjcdef.SJC__DESTINATION_QUEUE_swigconstant(_sjcdef)
SJC__DESTINATION_QUEUE = _sjcdef.SJC__DESTINATION_QUEUE

_sjcdef.SJC__DEVICE_NAME_swigconstant(_sjcdef)
SJC__DEVICE_NAME = _sjcdef.SJC__DEVICE_NAME

_sjcdef.SJC__DOUBLE_SPACE_swigconstant(_sjcdef)
SJC__DOUBLE_SPACE = _sjcdef.SJC__DOUBLE_SPACE

_sjcdef.SJC__NO_DOUBLE_SPACE_swigconstant(_sjcdef)
SJC__NO_DOUBLE_SPACE = _sjcdef.SJC__NO_DOUBLE_SPACE

_sjcdef.SJC__ENTRY_NUMBER_swigconstant(_sjcdef)
SJC__ENTRY_NUMBER = _sjcdef.SJC__ENTRY_NUMBER

_sjcdef.SJC__ENTRY_NUMBER_OUTPUT_swigconstant(_sjcdef)
SJC__ENTRY_NUMBER_OUTPUT = _sjcdef.SJC__ENTRY_NUMBER_OUTPUT

_sjcdef.SJC__FILE_BURST_swigconstant(_sjcdef)
SJC__FILE_BURST = _sjcdef.SJC__FILE_BURST

_sjcdef.SJC__FILE_BURST_ONE_swigconstant(_sjcdef)
SJC__FILE_BURST_ONE = _sjcdef.SJC__FILE_BURST_ONE

_sjcdef.SJC__NO_FILE_BURST_swigconstant(_sjcdef)
SJC__NO_FILE_BURST = _sjcdef.SJC__NO_FILE_BURST

_sjcdef.SJC__FILE_COPIES_swigconstant(_sjcdef)
SJC__FILE_COPIES = _sjcdef.SJC__FILE_COPIES

_sjcdef.SJC__FILE_FLAG_swigconstant(_sjcdef)
SJC__FILE_FLAG = _sjcdef.SJC__FILE_FLAG

_sjcdef.SJC__FILE_FLAG_ONE_swigconstant(_sjcdef)
SJC__FILE_FLAG_ONE = _sjcdef.SJC__FILE_FLAG_ONE

_sjcdef.SJC__NO_FILE_FLAG_swigconstant(_sjcdef)
SJC__NO_FILE_FLAG = _sjcdef.SJC__NO_FILE_FLAG

_sjcdef.SJC__FILE_IDENTIFICATION_swigconstant(_sjcdef)
SJC__FILE_IDENTIFICATION = _sjcdef.SJC__FILE_IDENTIFICATION

_sjcdef.SJC__FILE_SETUP_MODULES_swigconstant(_sjcdef)
SJC__FILE_SETUP_MODULES = _sjcdef.SJC__FILE_SETUP_MODULES

_sjcdef.SJC__NO_FILE_SETUP_MODULES_swigconstant(_sjcdef)
SJC__NO_FILE_SETUP_MODULES = _sjcdef.SJC__NO_FILE_SETUP_MODULES

_sjcdef.SJC__FILE_SPECIFICATION_swigconstant(_sjcdef)
SJC__FILE_SPECIFICATION = _sjcdef.SJC__FILE_SPECIFICATION

_sjcdef.SJC__FILE_TRAILER_swigconstant(_sjcdef)
SJC__FILE_TRAILER = _sjcdef.SJC__FILE_TRAILER

_sjcdef.SJC__FILE_TRAILER_ONE_swigconstant(_sjcdef)
SJC__FILE_TRAILER_ONE = _sjcdef.SJC__FILE_TRAILER_ONE

_sjcdef.SJC__NO_FILE_TRAILER_swigconstant(_sjcdef)
SJC__NO_FILE_TRAILER = _sjcdef.SJC__NO_FILE_TRAILER

_sjcdef.SJC__FIRST_PAGE_swigconstant(_sjcdef)
SJC__FIRST_PAGE = _sjcdef.SJC__FIRST_PAGE

_sjcdef.SJC__NO_FIRST_PAGE_swigconstant(_sjcdef)
SJC__NO_FIRST_PAGE = _sjcdef.SJC__NO_FIRST_PAGE

_sjcdef.SJC__FORM_DESCRIPTION_swigconstant(_sjcdef)
SJC__FORM_DESCRIPTION = _sjcdef.SJC__FORM_DESCRIPTION

_sjcdef.SJC__FORM_LENGTH_swigconstant(_sjcdef)
SJC__FORM_LENGTH = _sjcdef.SJC__FORM_LENGTH

_sjcdef.SJC__FORM_MARGIN_BOTTOM_swigconstant(_sjcdef)
SJC__FORM_MARGIN_BOTTOM = _sjcdef.SJC__FORM_MARGIN_BOTTOM

_sjcdef.SJC__FORM_MARGIN_LEFT_swigconstant(_sjcdef)
SJC__FORM_MARGIN_LEFT = _sjcdef.SJC__FORM_MARGIN_LEFT

_sjcdef.SJC__FORM_MARGIN_RIGHT_swigconstant(_sjcdef)
SJC__FORM_MARGIN_RIGHT = _sjcdef.SJC__FORM_MARGIN_RIGHT

_sjcdef.SJC__FORM_MARGIN_TOP_swigconstant(_sjcdef)
SJC__FORM_MARGIN_TOP = _sjcdef.SJC__FORM_MARGIN_TOP

_sjcdef.SJC__FORM_NAME_swigconstant(_sjcdef)
SJC__FORM_NAME = _sjcdef.SJC__FORM_NAME

_sjcdef.SJC__FORM_NUMBER_swigconstant(_sjcdef)
SJC__FORM_NUMBER = _sjcdef.SJC__FORM_NUMBER

_sjcdef.SJC__FORM_SETUP_MODULES_swigconstant(_sjcdef)
SJC__FORM_SETUP_MODULES = _sjcdef.SJC__FORM_SETUP_MODULES

_sjcdef.SJC__NO_FORM_SETUP_MODULES_swigconstant(_sjcdef)
SJC__NO_FORM_SETUP_MODULES = _sjcdef.SJC__NO_FORM_SETUP_MODULES

_sjcdef.SJC__FORM_SHEET_FEED_swigconstant(_sjcdef)
SJC__FORM_SHEET_FEED = _sjcdef.SJC__FORM_SHEET_FEED

_sjcdef.SJC__NO_FORM_SHEET_FEED_swigconstant(_sjcdef)
SJC__NO_FORM_SHEET_FEED = _sjcdef.SJC__NO_FORM_SHEET_FEED

_sjcdef.SJC__FORM_STOCK_swigconstant(_sjcdef)
SJC__FORM_STOCK = _sjcdef.SJC__FORM_STOCK

_sjcdef.SJC__FORM_TRUNCATE_swigconstant(_sjcdef)
SJC__FORM_TRUNCATE = _sjcdef.SJC__FORM_TRUNCATE

_sjcdef.SJC__NO_FORM_TRUNCATE_swigconstant(_sjcdef)
SJC__NO_FORM_TRUNCATE = _sjcdef.SJC__NO_FORM_TRUNCATE

_sjcdef.SJC__FORM_WIDTH_swigconstant(_sjcdef)
SJC__FORM_WIDTH = _sjcdef.SJC__FORM_WIDTH

_sjcdef.SJC__FORM_WRAP_swigconstant(_sjcdef)
SJC__FORM_WRAP = _sjcdef.SJC__FORM_WRAP

_sjcdef.SJC__NO_FORM_WRAP_swigconstant(_sjcdef)
SJC__NO_FORM_WRAP = _sjcdef.SJC__NO_FORM_WRAP

_sjcdef.SJC__GENERIC_QUEUE_swigconstant(_sjcdef)
SJC__GENERIC_QUEUE = _sjcdef.SJC__GENERIC_QUEUE

_sjcdef.SJC__NO_GENERIC_QUEUE_swigconstant(_sjcdef)
SJC__NO_GENERIC_QUEUE = _sjcdef.SJC__NO_GENERIC_QUEUE

_sjcdef.SJC__GENERIC_SELECTION_swigconstant(_sjcdef)
SJC__GENERIC_SELECTION = _sjcdef.SJC__GENERIC_SELECTION

_sjcdef.SJC__NO_GENERIC_SELECTION_swigconstant(_sjcdef)
SJC__NO_GENERIC_SELECTION = _sjcdef.SJC__NO_GENERIC_SELECTION

_sjcdef.SJC__GENERIC_TARGET_swigconstant(_sjcdef)
SJC__GENERIC_TARGET = _sjcdef.SJC__GENERIC_TARGET

_sjcdef.SJC__HOLD_swigconstant(_sjcdef)
SJC__HOLD = _sjcdef.SJC__HOLD

_sjcdef.SJC__NO_HOLD_swigconstant(_sjcdef)
SJC__NO_HOLD = _sjcdef.SJC__NO_HOLD

_sjcdef.SJC__JOB_BURST_swigconstant(_sjcdef)
SJC__JOB_BURST = _sjcdef.SJC__JOB_BURST

_sjcdef.SJC__NO_JOB_BURST_swigconstant(_sjcdef)
SJC__NO_JOB_BURST = _sjcdef.SJC__NO_JOB_BURST

_sjcdef.SJC__JOB_COPIES_swigconstant(_sjcdef)
SJC__JOB_COPIES = _sjcdef.SJC__JOB_COPIES

_sjcdef.SJC__JOB_FLAG_swigconstant(_sjcdef)
SJC__JOB_FLAG = _sjcdef.SJC__JOB_FLAG

_sjcdef.SJC__NO_JOB_FLAG_swigconstant(_sjcdef)
SJC__NO_JOB_FLAG = _sjcdef.SJC__NO_JOB_FLAG

_sjcdef.SJC__JOB_LIMIT_swigconstant(_sjcdef)
SJC__JOB_LIMIT = _sjcdef.SJC__JOB_LIMIT

_sjcdef.SJC__JOB_NAME_swigconstant(_sjcdef)
SJC__JOB_NAME = _sjcdef.SJC__JOB_NAME

_sjcdef.SJC__JOB_RESET_MODULES_swigconstant(_sjcdef)
SJC__JOB_RESET_MODULES = _sjcdef.SJC__JOB_RESET_MODULES

_sjcdef.SJC__NO_JOB_RESET_MODULES_swigconstant(_sjcdef)
SJC__NO_JOB_RESET_MODULES = _sjcdef.SJC__NO_JOB_RESET_MODULES

_sjcdef.SJC__JOB_SIZE_MAXIMUM_swigconstant(_sjcdef)
SJC__JOB_SIZE_MAXIMUM = _sjcdef.SJC__JOB_SIZE_MAXIMUM

_sjcdef.SJC__NO_JOB_SIZE_MAXIMUM_swigconstant(_sjcdef)
SJC__NO_JOB_SIZE_MAXIMUM = _sjcdef.SJC__NO_JOB_SIZE_MAXIMUM

_sjcdef.SJC__JOB_SIZE_MINIMUM_swigconstant(_sjcdef)
SJC__JOB_SIZE_MINIMUM = _sjcdef.SJC__JOB_SIZE_MINIMUM

_sjcdef.SJC__NO_JOB_SIZE_MINIMUM_swigconstant(_sjcdef)
SJC__NO_JOB_SIZE_MINIMUM = _sjcdef.SJC__NO_JOB_SIZE_MINIMUM

_sjcdef.SJC__JOB_SIZE_SCHEDULING_swigconstant(_sjcdef)
SJC__JOB_SIZE_SCHEDULING = _sjcdef.SJC__JOB_SIZE_SCHEDULING

_sjcdef.SJC__NO_JOB_SIZE_SCHEDULING_swigconstant(_sjcdef)
SJC__NO_JOB_SIZE_SCHEDULING = _sjcdef.SJC__NO_JOB_SIZE_SCHEDULING

_sjcdef.SJC__JOB_STATUS_OUTPUT_swigconstant(_sjcdef)
SJC__JOB_STATUS_OUTPUT = _sjcdef.SJC__JOB_STATUS_OUTPUT

_sjcdef.SJC__JOB_TRAILER_swigconstant(_sjcdef)
SJC__JOB_TRAILER = _sjcdef.SJC__JOB_TRAILER

_sjcdef.SJC__NO_JOB_TRAILER_swigconstant(_sjcdef)
SJC__NO_JOB_TRAILER = _sjcdef.SJC__NO_JOB_TRAILER

_sjcdef.SJC__LAST_PAGE_swigconstant(_sjcdef)
SJC__LAST_PAGE = _sjcdef.SJC__LAST_PAGE

_sjcdef.SJC__NO_LAST_PAGE_swigconstant(_sjcdef)
SJC__NO_LAST_PAGE = _sjcdef.SJC__NO_LAST_PAGE

_sjcdef.SJC__LIBRARY_SPECIFICATION_swigconstant(_sjcdef)
SJC__LIBRARY_SPECIFICATION = _sjcdef.SJC__LIBRARY_SPECIFICATION

_sjcdef.SJC__NO_LIBRARY_SPECIFICATION_swigconstant(_sjcdef)
SJC__NO_LIBRARY_SPECIFICATION = _sjcdef.SJC__NO_LIBRARY_SPECIFICATION

_sjcdef.SJC__LOG_DELETE_swigconstant(_sjcdef)
SJC__LOG_DELETE = _sjcdef.SJC__LOG_DELETE

_sjcdef.SJC__NO_LOG_DELETE_swigconstant(_sjcdef)
SJC__NO_LOG_DELETE = _sjcdef.SJC__NO_LOG_DELETE

_sjcdef.SJC__LOG_QUEUE_swigconstant(_sjcdef)
SJC__LOG_QUEUE = _sjcdef.SJC__LOG_QUEUE

_sjcdef.SJC__LOG_SPECIFICATION_swigconstant(_sjcdef)
SJC__LOG_SPECIFICATION = _sjcdef.SJC__LOG_SPECIFICATION

_sjcdef.SJC__NO_LOG_SPECIFICATION_swigconstant(_sjcdef)
SJC__NO_LOG_SPECIFICATION = _sjcdef.SJC__NO_LOG_SPECIFICATION

_sjcdef.SJC__LOG_SPOOL_swigconstant(_sjcdef)
SJC__LOG_SPOOL = _sjcdef.SJC__LOG_SPOOL

_sjcdef.SJC__NO_LOG_SPOOL_swigconstant(_sjcdef)
SJC__NO_LOG_SPOOL = _sjcdef.SJC__NO_LOG_SPOOL

_sjcdef.SJC__LOWERCASE_swigconstant(_sjcdef)
SJC__LOWERCASE = _sjcdef.SJC__LOWERCASE

_sjcdef.SJC__NO_LOWERCASE_swigconstant(_sjcdef)
SJC__NO_LOWERCASE = _sjcdef.SJC__NO_LOWERCASE

_sjcdef.SJC__NEW_VERSION_swigconstant(_sjcdef)
SJC__NEW_VERSION = _sjcdef.SJC__NEW_VERSION

_sjcdef.SJC__NEXT_JOB_swigconstant(_sjcdef)
SJC__NEXT_JOB = _sjcdef.SJC__NEXT_JOB

_sjcdef.SJC__NOTE_swigconstant(_sjcdef)
SJC__NOTE = _sjcdef.SJC__NOTE

_sjcdef.SJC__NO_NOTE_swigconstant(_sjcdef)
SJC__NO_NOTE = _sjcdef.SJC__NO_NOTE

_sjcdef.SJC__NOTIFY_swigconstant(_sjcdef)
SJC__NOTIFY = _sjcdef.SJC__NOTIFY

_sjcdef.SJC__NO_NOTIFY_swigconstant(_sjcdef)
SJC__NO_NOTIFY = _sjcdef.SJC__NO_NOTIFY

_sjcdef.SJC__OPERATOR_REQUEST_swigconstant(_sjcdef)
SJC__OPERATOR_REQUEST = _sjcdef.SJC__OPERATOR_REQUEST

_sjcdef.SJC__NO_OPERATOR_REQUEST_swigconstant(_sjcdef)
SJC__NO_OPERATOR_REQUEST = _sjcdef.SJC__NO_OPERATOR_REQUEST

_sjcdef.SJC__OWNER_UIC_swigconstant(_sjcdef)
SJC__OWNER_UIC = _sjcdef.SJC__OWNER_UIC

_sjcdef.SJC__PAGE_HEADER_swigconstant(_sjcdef)
SJC__PAGE_HEADER = _sjcdef.SJC__PAGE_HEADER

_sjcdef.SJC__NO_PAGE_HEADER_swigconstant(_sjcdef)
SJC__NO_PAGE_HEADER = _sjcdef.SJC__NO_PAGE_HEADER

_sjcdef.SJC__PAGE_SETUP_MODULES_swigconstant(_sjcdef)
SJC__PAGE_SETUP_MODULES = _sjcdef.SJC__PAGE_SETUP_MODULES

_sjcdef.SJC__NO_PAGE_SETUP_MODULES_swigconstant(_sjcdef)
SJC__NO_PAGE_SETUP_MODULES = _sjcdef.SJC__NO_PAGE_SETUP_MODULES

_sjcdef.SJC__PAGINATE_swigconstant(_sjcdef)
SJC__PAGINATE = _sjcdef.SJC__PAGINATE

_sjcdef.SJC__NO_PAGINATE_swigconstant(_sjcdef)
SJC__NO_PAGINATE = _sjcdef.SJC__NO_PAGINATE

_sjcdef.SJC__PARAMETER_1_swigconstant(_sjcdef)
SJC__PARAMETER_1 = _sjcdef.SJC__PARAMETER_1

_sjcdef.SJC__PARAMETER_2_swigconstant(_sjcdef)
SJC__PARAMETER_2 = _sjcdef.SJC__PARAMETER_2

_sjcdef.SJC__PARAMETER_3_swigconstant(_sjcdef)
SJC__PARAMETER_3 = _sjcdef.SJC__PARAMETER_3

_sjcdef.SJC__PARAMETER_4_swigconstant(_sjcdef)
SJC__PARAMETER_4 = _sjcdef.SJC__PARAMETER_4

_sjcdef.SJC__PARAMETER_5_swigconstant(_sjcdef)
SJC__PARAMETER_5 = _sjcdef.SJC__PARAMETER_5

_sjcdef.SJC__PARAMETER_6_swigconstant(_sjcdef)
SJC__PARAMETER_6 = _sjcdef.SJC__PARAMETER_6

_sjcdef.SJC__PARAMETER_7_swigconstant(_sjcdef)
SJC__PARAMETER_7 = _sjcdef.SJC__PARAMETER_7

_sjcdef.SJC__PARAMETER_8_swigconstant(_sjcdef)
SJC__PARAMETER_8 = _sjcdef.SJC__PARAMETER_8

_sjcdef.SJC__NO_PARAMETERS_swigconstant(_sjcdef)
SJC__NO_PARAMETERS = _sjcdef.SJC__NO_PARAMETERS

_sjcdef.SJC__PASSALL_swigconstant(_sjcdef)
SJC__PASSALL = _sjcdef.SJC__PASSALL

_sjcdef.SJC__NO_PASSALL_swigconstant(_sjcdef)
SJC__NO_PASSALL = _sjcdef.SJC__NO_PASSALL

_sjcdef.SJC__PRIORITY_swigconstant(_sjcdef)
SJC__PRIORITY = _sjcdef.SJC__PRIORITY

_sjcdef.SJC__PROCESSOR_swigconstant(_sjcdef)
SJC__PROCESSOR = _sjcdef.SJC__PROCESSOR

_sjcdef.SJC__NO_PROCESSOR_swigconstant(_sjcdef)
SJC__NO_PROCESSOR = _sjcdef.SJC__NO_PROCESSOR

_sjcdef.SJC__PROTECTION_swigconstant(_sjcdef)
SJC__PROTECTION = _sjcdef.SJC__PROTECTION

_sjcdef.SJC__QUEUE_swigconstant(_sjcdef)
SJC__QUEUE = _sjcdef.SJC__QUEUE

_sjcdef.SJC__QUEUE_FILE_SPECIFICATION_swigconstant(_sjcdef)
SJC__QUEUE_FILE_SPECIFICATION = _sjcdef.SJC__QUEUE_FILE_SPECIFICATION

_sjcdef.SJC__RELATIVE_PAGE_swigconstant(_sjcdef)
SJC__RELATIVE_PAGE = _sjcdef.SJC__RELATIVE_PAGE

_sjcdef.SJC__REQUEUE_swigconstant(_sjcdef)
SJC__REQUEUE = _sjcdef.SJC__REQUEUE

_sjcdef.SJC__RESTART_swigconstant(_sjcdef)
SJC__RESTART = _sjcdef.SJC__RESTART

_sjcdef.SJC__NO_RESTART_swigconstant(_sjcdef)
SJC__NO_RESTART = _sjcdef.SJC__NO_RESTART

_sjcdef.SJC__RETAIN_ALL_JOBS_swigconstant(_sjcdef)
SJC__RETAIN_ALL_JOBS = _sjcdef.SJC__RETAIN_ALL_JOBS

_sjcdef.SJC__RETAIN_ERROR_JOBS_swigconstant(_sjcdef)
SJC__RETAIN_ERROR_JOBS = _sjcdef.SJC__RETAIN_ERROR_JOBS

_sjcdef.SJC__NO_RETAIN_JOBS_swigconstant(_sjcdef)
SJC__NO_RETAIN_JOBS = _sjcdef.SJC__NO_RETAIN_JOBS

_sjcdef.SJC__SCSNODE_NAME_swigconstant(_sjcdef)
SJC__SCSNODE_NAME = _sjcdef.SJC__SCSNODE_NAME

_sjcdef.SJC__SEARCH_STRING_swigconstant(_sjcdef)
SJC__SEARCH_STRING = _sjcdef.SJC__SEARCH_STRING

_sjcdef.SJC__SWAP_swigconstant(_sjcdef)
SJC__SWAP = _sjcdef.SJC__SWAP

_sjcdef.SJC__NO_SWAP_swigconstant(_sjcdef)
SJC__NO_SWAP = _sjcdef.SJC__NO_SWAP

_sjcdef.SJC__TERMINAL_swigconstant(_sjcdef)
SJC__TERMINAL = _sjcdef.SJC__TERMINAL

_sjcdef.SJC__NO_TERMINAL_swigconstant(_sjcdef)
SJC__NO_TERMINAL = _sjcdef.SJC__NO_TERMINAL

_sjcdef.SJC__TOP_OF_FILE_swigconstant(_sjcdef)
SJC__TOP_OF_FILE = _sjcdef.SJC__TOP_OF_FILE

_sjcdef.SJC__USER_IDENTIFICATION_swigconstant(_sjcdef)
SJC__USER_IDENTIFICATION = _sjcdef.SJC__USER_IDENTIFICATION

_sjcdef.SJC__WSDEFAULT_swigconstant(_sjcdef)
SJC__WSDEFAULT = _sjcdef.SJC__WSDEFAULT

_sjcdef.SJC__NO_WSDEFAULT_swigconstant(_sjcdef)
SJC__NO_WSDEFAULT = _sjcdef.SJC__NO_WSDEFAULT

_sjcdef.SJC__WSEXTENT_swigconstant(_sjcdef)
SJC__WSEXTENT = _sjcdef.SJC__WSEXTENT

_sjcdef.SJC__NO_WSEXTENT_swigconstant(_sjcdef)
SJC__NO_WSEXTENT = _sjcdef.SJC__NO_WSEXTENT

_sjcdef.SJC__WSQUOTA_swigconstant(_sjcdef)
SJC__WSQUOTA = _sjcdef.SJC__WSQUOTA

_sjcdef.SJC__NO_WSQUOTA_swigconstant(_sjcdef)
SJC__NO_WSQUOTA = _sjcdef.SJC__NO_WSQUOTA

_sjcdef.SJC__ACCOUNT_NAME_swigconstant(_sjcdef)
SJC__ACCOUNT_NAME = _sjcdef.SJC__ACCOUNT_NAME

_sjcdef.SJC__UIC_swigconstant(_sjcdef)
SJC__UIC = _sjcdef.SJC__UIC

_sjcdef.SJC__USERNAME_swigconstant(_sjcdef)
SJC__USERNAME = _sjcdef.SJC__USERNAME

_sjcdef.SJC__BUFFER_COUNT_swigconstant(_sjcdef)
SJC__BUFFER_COUNT = _sjcdef.SJC__BUFFER_COUNT

_sjcdef.SJC__EXTEND_QUANTITY_swigconstant(_sjcdef)
SJC__EXTEND_QUANTITY = _sjcdef.SJC__EXTEND_QUANTITY

_sjcdef.SJC__RECORD_BLOCKING_swigconstant(_sjcdef)
SJC__RECORD_BLOCKING = _sjcdef.SJC__RECORD_BLOCKING

_sjcdef.SJC__NO_RECORD_BLOCKING_swigconstant(_sjcdef)
SJC__NO_RECORD_BLOCKING = _sjcdef.SJC__NO_RECORD_BLOCKING

_sjcdef.SJC__QUEMAN_RESTART_swigconstant(_sjcdef)
SJC__QUEMAN_RESTART = _sjcdef.SJC__QUEMAN_RESTART

_sjcdef.SJC__NO_QUEMAN_RESTART_swigconstant(_sjcdef)
SJC__NO_QUEMAN_RESTART = _sjcdef.SJC__NO_QUEMAN_RESTART

_sjcdef.SJC__DEFAULT_FORM_NAME_swigconstant(_sjcdef)
SJC__DEFAULT_FORM_NAME = _sjcdef.SJC__DEFAULT_FORM_NAME

_sjcdef.SJC__DEFAULT_FORM_NUMBER_swigconstant(_sjcdef)
SJC__DEFAULT_FORM_NUMBER = _sjcdef.SJC__DEFAULT_FORM_NUMBER

_sjcdef.SJC__SECURITY_CLASSIFICATION_swigconstant(_sjcdef)
SJC__SECURITY_CLASSIFICATION = _sjcdef.SJC__SECURITY_CLASSIFICATION

_sjcdef.SJC__QUEUE_SUPPORT_swigconstant(_sjcdef)
SJC__QUEUE_SUPPORT = _sjcdef.SJC__QUEUE_SUPPORT

_sjcdef.SJC__JOB_COMPLETION_STATUS_swigconstant(_sjcdef)
SJC__JOB_COMPLETION_STATUS = _sjcdef.SJC__JOB_COMPLETION_STATUS

_sjcdef.SJC__DIAGNOSTIC_BUFFER_OUTPUT_swigconstant(_sjcdef)
SJC__DIAGNOSTIC_BUFFER_OUTPUT = _sjcdef.SJC__DIAGNOSTIC_BUFFER_OUTPUT

_sjcdef.SJC__OPEN_QUEUE_swigconstant(_sjcdef)
SJC__OPEN_QUEUE = _sjcdef.SJC__OPEN_QUEUE

_sjcdef.SJC__CLOSE_QUEUE_swigconstant(_sjcdef)
SJC__CLOSE_QUEUE = _sjcdef.SJC__CLOSE_QUEUE

_sjcdef.SJC__SERVER_swigconstant(_sjcdef)
SJC__SERVER = _sjcdef.SJC__SERVER

_sjcdef.SJC__PRINTER_swigconstant(_sjcdef)
SJC__PRINTER = _sjcdef.SJC__PRINTER

_sjcdef.SJC__UPDATE_ORB_swigconstant(_sjcdef)
SJC__UPDATE_ORB = _sjcdef.SJC__UPDATE_ORB

_sjcdef.SJC__NO_QUEUE_DESCRIPTION_swigconstant(_sjcdef)
SJC__NO_QUEUE_DESCRIPTION = _sjcdef.SJC__NO_QUEUE_DESCRIPTION

_sjcdef.SJC__JOB_RETAIN_swigconstant(_sjcdef)
SJC__JOB_RETAIN = _sjcdef.SJC__JOB_RETAIN

_sjcdef.SJC__JOB_ERROR_RETAIN_swigconstant(_sjcdef)
SJC__JOB_ERROR_RETAIN = _sjcdef.SJC__JOB_ERROR_RETAIN

_sjcdef.SJC__JOB_DEFAULT_RETAIN_swigconstant(_sjcdef)
SJC__JOB_DEFAULT_RETAIN = _sjcdef.SJC__JOB_DEFAULT_RETAIN

_sjcdef.SJC__NOTIFY_ON_INTERRUPT_swigconstant(_sjcdef)
SJC__NOTIFY_ON_INTERRUPT = _sjcdef.SJC__NOTIFY_ON_INTERRUPT

_sjcdef.SJC__NO_RAD_swigconstant(_sjcdef)
SJC__NO_RAD = _sjcdef.SJC__NO_RAD

_sjcdef.SJC__ACCEPT_ALL_ATTRIBUTES_swigconstant(_sjcdef)
SJC__ACCEPT_ALL_ATTRIBUTES = _sjcdef.SJC__ACCEPT_ALL_ATTRIBUTES

_sjcdef.SJC__DIAGNOSTIC_FLAGS_swigconstant(_sjcdef)
SJC__DIAGNOSTIC_FLAGS = _sjcdef.SJC__DIAGNOSTIC_FLAGS

_sjcdef.SJC__QUEUE_DESCRIPTION_swigconstant(_sjcdef)
SJC__QUEUE_DESCRIPTION = _sjcdef.SJC__QUEUE_DESCRIPTION

_sjcdef.SJC__CHECKPOINT_FREQUENCY_swigconstant(_sjcdef)
SJC__CHECKPOINT_FREQUENCY = _sjcdef.SJC__CHECKPOINT_FREQUENCY

_sjcdef.SJC__DISPLAY_USERNAME_swigconstant(_sjcdef)
SJC__DISPLAY_USERNAME = _sjcdef.SJC__DISPLAY_USERNAME

_sjcdef.SJC__FILE_NUMBER_swigconstant(_sjcdef)
SJC__FILE_NUMBER = _sjcdef.SJC__FILE_NUMBER

_sjcdef.SJC__FILE_ATTRIBUTE_swigconstant(_sjcdef)
SJC__FILE_ATTRIBUTE = _sjcdef.SJC__FILE_ATTRIBUTE

_sjcdef.SJC__JOB_ATTRIBUTE_swigconstant(_sjcdef)
SJC__JOB_ATTRIBUTE = _sjcdef.SJC__JOB_ATTRIBUTE

_sjcdef.SJC__QUEUE_ATTRIBUTE_swigconstant(_sjcdef)
SJC__QUEUE_ATTRIBUTE = _sjcdef.SJC__QUEUE_ATTRIBUTE

_sjcdef.SJC__REMOVE_ATTRIBUTE_swigconstant(_sjcdef)
SJC__REMOVE_ATTRIBUTE = _sjcdef.SJC__REMOVE_ATTRIBUTE

_sjcdef.SJC__QUEUE_MANAGER_NAME_swigconstant(_sjcdef)
SJC__QUEUE_MANAGER_NAME = _sjcdef.SJC__QUEUE_MANAGER_NAME

_sjcdef.SJC__QUEUE_MANAGER_NODES_swigconstant(_sjcdef)
SJC__QUEUE_MANAGER_NODES = _sjcdef.SJC__QUEUE_MANAGER_NODES

_sjcdef.SJC__AUTOSTART_ON_swigconstant(_sjcdef)
SJC__AUTOSTART_ON = _sjcdef.SJC__AUTOSTART_ON

_sjcdef.SJC__RESERVED_OUTPUT_196_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_196 = _sjcdef.SJC__RESERVED_OUTPUT_196

_sjcdef.SJC__RESERVED_OUTPUT_197_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_197 = _sjcdef.SJC__RESERVED_OUTPUT_197

_sjcdef.SJC__RESERVED_OUTPUT_198_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_198 = _sjcdef.SJC__RESERVED_OUTPUT_198

_sjcdef.SJC__RESERVED_OUTPUT_199_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_199 = _sjcdef.SJC__RESERVED_OUTPUT_199

_sjcdef.SJC__SET_CONDITION_VECTOR_swigconstant(_sjcdef)
SJC__SET_CONDITION_VECTOR = _sjcdef.SJC__SET_CONDITION_VECTOR

_sjcdef.SJC__NOTIFY_MESSAGE_swigconstant(_sjcdef)
SJC__NOTIFY_MESSAGE = _sjcdef.SJC__NOTIFY_MESSAGE

_sjcdef.SJC__DEFINE_FILE_ATTRIBUTES_swigconstant(_sjcdef)
SJC__DEFINE_FILE_ATTRIBUTES = _sjcdef.SJC__DEFINE_FILE_ATTRIBUTES

_sjcdef.SJC__DEFINE_JOB_ATTRIBUTES_swigconstant(_sjcdef)
SJC__DEFINE_JOB_ATTRIBUTES = _sjcdef.SJC__DEFINE_JOB_ATTRIBUTES

_sjcdef.SJC__DEFINE_QUEUE_ATTRIBUTES_swigconstant(_sjcdef)
SJC__DEFINE_QUEUE_ATTRIBUTES = _sjcdef.SJC__DEFINE_QUEUE_ATTRIBUTES

_sjcdef.SJC__AGENT_PROFILE_swigconstant(_sjcdef)
SJC__AGENT_PROFILE = _sjcdef.SJC__AGENT_PROFILE

_sjcdef.SJC__ADD_QUEUE_MANAGER_swigconstant(_sjcdef)
SJC__ADD_QUEUE_MANAGER = _sjcdef.SJC__ADD_QUEUE_MANAGER

_sjcdef.SJC__OUTSTANDING_JOBS_swigconstant(_sjcdef)
SJC__OUTSTANDING_JOBS = _sjcdef.SJC__OUTSTANDING_JOBS

_sjcdef.SJC__NO_INITIAL_FF_swigconstant(_sjcdef)
SJC__NO_INITIAL_FF = _sjcdef.SJC__NO_INITIAL_FF

_sjcdef.SJC__NO_NO_INITIAL_FF_swigconstant(_sjcdef)
SJC__NO_NO_INITIAL_FF = _sjcdef.SJC__NO_NO_INITIAL_FF

_sjcdef.SJC__DELETE_FILE_ALWAYS_swigconstant(_sjcdef)
SJC__DELETE_FILE_ALWAYS = _sjcdef.SJC__DELETE_FILE_ALWAYS

_sjcdef.SJC__NO_DELETE_FILE_ALWAYS_swigconstant(_sjcdef)
SJC__NO_DELETE_FILE_ALWAYS = _sjcdef.SJC__NO_DELETE_FILE_ALWAYS

_sjcdef.SJC__RESERVED_BOOLEAN_212_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_212 = _sjcdef.SJC__RESERVED_BOOLEAN_212

_sjcdef.SJC__RESERVED_BOOLEAN_213_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_213 = _sjcdef.SJC__RESERVED_BOOLEAN_213

_sjcdef.SJC__RESERVED_BOOLEAN_214_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_214 = _sjcdef.SJC__RESERVED_BOOLEAN_214

_sjcdef.SJC__RESERVED_BOOLEAN_215_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_215 = _sjcdef.SJC__RESERVED_BOOLEAN_215

_sjcdef.SJC__RESERVED_BOOLEAN_216_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_216 = _sjcdef.SJC__RESERVED_BOOLEAN_216

_sjcdef.SJC__RESERVED_BOOLEAN_217_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_217 = _sjcdef.SJC__RESERVED_BOOLEAN_217

_sjcdef.SJC__RESERVED_BOOLEAN_218_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_218 = _sjcdef.SJC__RESERVED_BOOLEAN_218

_sjcdef.SJC__RESERVED_BOOLEAN_219_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_219 = _sjcdef.SJC__RESERVED_BOOLEAN_219

_sjcdef.SJC__RESERVED_BOOLEAN_220_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_220 = _sjcdef.SJC__RESERVED_BOOLEAN_220

_sjcdef.SJC__RESERVED_BOOLEAN_221_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_221 = _sjcdef.SJC__RESERVED_BOOLEAN_221

_sjcdef.SJC__RESERVED_BOOLEAN_222_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_222 = _sjcdef.SJC__RESERVED_BOOLEAN_222

_sjcdef.SJC__RESERVED_BOOLEAN_223_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_223 = _sjcdef.SJC__RESERVED_BOOLEAN_223

_sjcdef.SJC__RESERVED_BOOLEAN_224_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_224 = _sjcdef.SJC__RESERVED_BOOLEAN_224

_sjcdef.SJC__RESERVED_BOOLEAN_225_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_225 = _sjcdef.SJC__RESERVED_BOOLEAN_225

_sjcdef.SJC__RESERVED_BOOLEAN_226_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_226 = _sjcdef.SJC__RESERVED_BOOLEAN_226

_sjcdef.SJC__RESERVED_BOOLEAN_227_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_227 = _sjcdef.SJC__RESERVED_BOOLEAN_227

_sjcdef.SJC__RESERVED_BOOLEAN_228_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_228 = _sjcdef.SJC__RESERVED_BOOLEAN_228

_sjcdef.SJC__RESERVED_BOOLEAN_229_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_229 = _sjcdef.SJC__RESERVED_BOOLEAN_229

_sjcdef.SJC__RESERVED_BOOLEAN_230_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_230 = _sjcdef.SJC__RESERVED_BOOLEAN_230

_sjcdef.SJC__RESERVED_BOOLEAN_231_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_231 = _sjcdef.SJC__RESERVED_BOOLEAN_231

_sjcdef.SJC__RESERVED_BOOLEAN_232_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_232 = _sjcdef.SJC__RESERVED_BOOLEAN_232

_sjcdef.SJC__RESERVED_BOOLEAN_233_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_233 = _sjcdef.SJC__RESERVED_BOOLEAN_233

_sjcdef.SJC__RESERVED_BOOLEAN_234_swigconstant(_sjcdef)
SJC__RESERVED_BOOLEAN_234 = _sjcdef.SJC__RESERVED_BOOLEAN_234

_sjcdef.SJC__JOB_RETAIN_TIME_swigconstant(_sjcdef)
SJC__JOB_RETAIN_TIME = _sjcdef.SJC__JOB_RETAIN_TIME

_sjcdef.SJC__MANAGER_ATTRIBUTE_swigconstant(_sjcdef)
SJC__MANAGER_ATTRIBUTE = _sjcdef.SJC__MANAGER_ATTRIBUTE

_sjcdef.SJC__RAD_swigconstant(_sjcdef)
SJC__RAD = _sjcdef.SJC__RAD

_sjcdef.SJC__RESERVED_INPUT_238_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_238 = _sjcdef.SJC__RESERVED_INPUT_238

_sjcdef.SJC__RESERVED_INPUT_239_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_239 = _sjcdef.SJC__RESERVED_INPUT_239

_sjcdef.SJC__RESERVED_INPUT_240_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_240 = _sjcdef.SJC__RESERVED_INPUT_240

_sjcdef.SJC__RESERVED_INPUT_241_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_241 = _sjcdef.SJC__RESERVED_INPUT_241

_sjcdef.SJC__RESERVED_INPUT_242_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_242 = _sjcdef.SJC__RESERVED_INPUT_242

_sjcdef.SJC__RESERVED_INPUT_243_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_243 = _sjcdef.SJC__RESERVED_INPUT_243

_sjcdef.SJC__RESERVED_INPUT_244_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_244 = _sjcdef.SJC__RESERVED_INPUT_244

_sjcdef.SJC__RESERVED_INPUT_245_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_245 = _sjcdef.SJC__RESERVED_INPUT_245

_sjcdef.SJC__RESERVED_INPUT_246_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_246 = _sjcdef.SJC__RESERVED_INPUT_246

_sjcdef.SJC__RESERVED_INPUT_247_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_247 = _sjcdef.SJC__RESERVED_INPUT_247

_sjcdef.SJC__RESERVED_INPUT_248_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_248 = _sjcdef.SJC__RESERVED_INPUT_248

_sjcdef.SJC__RESERVED_INPUT_249_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_249 = _sjcdef.SJC__RESERVED_INPUT_249

_sjcdef.SJC__RESERVED_INPUT_250_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_250 = _sjcdef.SJC__RESERVED_INPUT_250

_sjcdef.SJC__RESERVED_OUTPUT_251_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_251 = _sjcdef.SJC__RESERVED_OUTPUT_251

_sjcdef.SJC__RESERVED_OUTPUT_252_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_252 = _sjcdef.SJC__RESERVED_OUTPUT_252

_sjcdef.SJC__RESERVED_OUTPUT_253_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_253 = _sjcdef.SJC__RESERVED_OUTPUT_253

_sjcdef.SJC__RESERVED_OUTPUT_254_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_254 = _sjcdef.SJC__RESERVED_OUTPUT_254

_sjcdef.SJC__RESERVED_OUTPUT_255_swigconstant(_sjcdef)
SJC__RESERVED_OUTPUT_255 = _sjcdef.SJC__RESERVED_OUTPUT_255

_sjcdef.SJC_K_MIN_ITEM_swigconstant(_sjcdef)
SJC_K_MIN_ITEM = _sjcdef.SJC_K_MIN_ITEM

_sjcdef.SJC_K_MAX_ITEM_swigconstant(_sjcdef)
SJC_K_MAX_ITEM = _sjcdef.SJC_K_MAX_ITEM

_sjcdef.SJC__CHARGE_CODE_swigconstant(_sjcdef)
SJC__CHARGE_CODE = _sjcdef.SJC__CHARGE_CODE

_sjcdef.SJC__RESERVED_INPUT_187_swigconstant(_sjcdef)
SJC__RESERVED_INPUT_187 = _sjcdef.SJC__RESERVED_INPUT_187

_sjcdef.SJC__QUEUE_DIRECTORY_swigconstant(_sjcdef)
SJC__QUEUE_DIRECTORY = _sjcdef.SJC__QUEUE_DIRECTORY

_sjcdef.SJC__SERVICE_INPUT_swigconstant(_sjcdef)
SJC__SERVICE_INPUT = _sjcdef.SJC__SERVICE_INPUT

_sjcdef.SJC__SERVICE_OUTPUT_swigconstant(_sjcdef)
SJC__SERVICE_OUTPUT = _sjcdef.SJC__SERVICE_OUTPUT

_sjcdef.SJC_M_ACCT_PROCESS_swigconstant(_sjcdef)
SJC_M_ACCT_PROCESS = _sjcdef.SJC_M_ACCT_PROCESS

_sjcdef.SJC_M_ACCT_IMAGE_swigconstant(_sjcdef)
SJC_M_ACCT_IMAGE = _sjcdef.SJC_M_ACCT_IMAGE

_sjcdef.SJC_M_ACCT_INTERACTIVE_swigconstant(_sjcdef)
SJC_M_ACCT_INTERACTIVE = _sjcdef.SJC_M_ACCT_INTERACTIVE

_sjcdef.SJC_M_ACCT_LOGIN_FAILURE_swigconstant(_sjcdef)
SJC_M_ACCT_LOGIN_FAILURE = _sjcdef.SJC_M_ACCT_LOGIN_FAILURE

_sjcdef.SJC_M_ACCT_SUBPROCESS_swigconstant(_sjcdef)
SJC_M_ACCT_SUBPROCESS = _sjcdef.SJC_M_ACCT_SUBPROCESS

_sjcdef.SJC_M_ACCT_DETACHED_swigconstant(_sjcdef)
SJC_M_ACCT_DETACHED = _sjcdef.SJC_M_ACCT_DETACHED

_sjcdef.SJC_M_ACCT_BATCH_swigconstant(_sjcdef)
SJC_M_ACCT_BATCH = _sjcdef.SJC_M_ACCT_BATCH

_sjcdef.SJC_M_ACCT_NETWORK_swigconstant(_sjcdef)
SJC_M_ACCT_NETWORK = _sjcdef.SJC_M_ACCT_NETWORK

_sjcdef.SJC_M_ACCT_PRINT_swigconstant(_sjcdef)
SJC_M_ACCT_PRINT = _sjcdef.SJC_M_ACCT_PRINT

_sjcdef.SJC_M_ACCT_MESSAGE_swigconstant(_sjcdef)
SJC_M_ACCT_MESSAGE = _sjcdef.SJC_M_ACCT_MESSAGE

_sjcdef.SJC_M_ACCT_ACM_FUNC_swigconstant(_sjcdef)
SJC_M_ACCT_ACM_FUNC = _sjcdef.SJC_M_ACCT_ACM_FUNC

_sjcdef.SJC_M_ACCT_ACM_SYS_swigconstant(_sjcdef)
SJC_M_ACCT_ACM_SYS = _sjcdef.SJC_M_ACCT_ACM_SYS

_sjcdef.SJC_M_ACCT_CCAENAB_swigconstant(_sjcdef)
SJC_M_ACCT_CCAENAB = _sjcdef.SJC_M_ACCT_CCAENAB

_sjcdef.SJC_M_ACCT_CCVENAB_swigconstant(_sjcdef)
SJC_M_ACCT_CCVENAB = _sjcdef.SJC_M_ACCT_CCVENAB

_sjcdef.SJC_S_ACCOUNTING_TYPES_swigconstant(_sjcdef)
SJC_S_ACCOUNTING_TYPES = _sjcdef.SJC_S_ACCOUNTING_TYPES

_sjcdef.SJC_S_ACCT_UNUSED_swigconstant(_sjcdef)
SJC_S_ACCT_UNUSED = _sjcdef.SJC_S_ACCT_UNUSED

_sjcdef.SJC_M_DIAG_COPY_QF_swigconstant(_sjcdef)
SJC_M_DIAG_COPY_QF = _sjcdef.SJC_M_DIAG_COPY_QF

_sjcdef.SJC_M_DIAG_CREATE_MF_swigconstant(_sjcdef)
SJC_M_DIAG_CREATE_MF = _sjcdef.SJC_M_DIAG_CREATE_MF

_sjcdef.SJC_M_DIAG_CLOSE_MF_swigconstant(_sjcdef)
SJC_M_DIAG_CLOSE_MF = _sjcdef.SJC_M_DIAG_CLOSE_MF

_sjcdef.SJC_M_DIAG_OPEN_MF_swigconstant(_sjcdef)
SJC_M_DIAG_OPEN_MF = _sjcdef.SJC_M_DIAG_OPEN_MF

_sjcdef.SJC_M_DIAG_CLEAR_FLAGS_swigconstant(_sjcdef)
SJC_M_DIAG_CLEAR_FLAGS = _sjcdef.SJC_M_DIAG_CLEAR_FLAGS

_sjcdef.SJC_M_DIAG_LOG_ALL_TRANS_swigconstant(_sjcdef)
SJC_M_DIAG_LOG_ALL_TRANS = _sjcdef.SJC_M_DIAG_LOG_ALL_TRANS

_sjcdef.SJC_M_DIAG_JOURNAL_PUTS_swigconstant(_sjcdef)
SJC_M_DIAG_JOURNAL_PUTS = _sjcdef.SJC_M_DIAG_JOURNAL_PUTS

_sjcdef.SJC_M_DIAG_DUMP_DIAG_BUFFER_swigconstant(_sjcdef)
SJC_M_DIAG_DUMP_DIAG_BUFFER = _sjcdef.SJC_M_DIAG_DUMP_DIAG_BUFFER

_sjcdef.SJC_M_DIAG_INIT_DIAG_BUFFER_swigconstant(_sjcdef)
SJC_M_DIAG_INIT_DIAG_BUFFER = _sjcdef.SJC_M_DIAG_INIT_DIAG_BUFFER

_sjcdef.SJC_S_DIAGNOSTIC_FLAGS_swigconstant(_sjcdef)
SJC_S_DIAGNOSTIC_FLAGS = _sjcdef.SJC_S_DIAGNOSTIC_FLAGS

_sjcdef.SJC_S_DIAG_UNUSED_swigconstant(_sjcdef)
SJC_S_DIAG_UNUSED = _sjcdef.SJC_S_DIAG_UNUSED
# This file is compatible with both classic and new-style classes.


