# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_quidef', [dirname(__file__)])
        except ImportError:
            import _quidef
            return _quidef
        if fp is not None:
            try:
                _mod = imp.load_module('_quidef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _quidef = swig_import_helper()
    del swig_import_helper
else:
    import _quidef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_quidef.QUI__CANCEL_OPERATION_swigconstant(_quidef)
QUI__CANCEL_OPERATION = _quidef.QUI__CANCEL_OPERATION

_quidef.QUI__DISPLAY_CHARACTERISTIC_swigconstant(_quidef)
QUI__DISPLAY_CHARACTERISTIC = _quidef.QUI__DISPLAY_CHARACTERISTIC

_quidef.QUI__DISPLAY_FILE_swigconstant(_quidef)
QUI__DISPLAY_FILE = _quidef.QUI__DISPLAY_FILE

_quidef.QUI__DISPLAY_FORM_swigconstant(_quidef)
QUI__DISPLAY_FORM = _quidef.QUI__DISPLAY_FORM

_quidef.QUI__DISPLAY_JOB_swigconstant(_quidef)
QUI__DISPLAY_JOB = _quidef.QUI__DISPLAY_JOB

_quidef.QUI__DISPLAY_QUEUE_swigconstant(_quidef)
QUI__DISPLAY_QUEUE = _quidef.QUI__DISPLAY_QUEUE

_quidef.QUI__TRANSLATE_QUEUE_swigconstant(_quidef)
QUI__TRANSLATE_QUEUE = _quidef.QUI__TRANSLATE_QUEUE

_quidef.QUI__DISPLAY_ENTRY_swigconstant(_quidef)
QUI__DISPLAY_ENTRY = _quidef.QUI__DISPLAY_ENTRY

_quidef.QUI__DISPLAY_QMAN_swigconstant(_quidef)
QUI__DISPLAY_QMAN = _quidef.QUI__DISPLAY_QMAN

_quidef.QUI__DISPLAY_MANAGER_swigconstant(_quidef)
QUI__DISPLAY_MANAGER = _quidef.QUI__DISPLAY_MANAGER

_quidef.QUI_K_MIN_FUNC_swigconstant(_quidef)
QUI_K_MIN_FUNC = _quidef.QUI_K_MIN_FUNC

_quidef.QUI_K_MAX_FUNC_swigconstant(_quidef)
QUI_K_MAX_FUNC = _quidef.QUI_K_MAX_FUNC

_quidef.QUI__ACCOUNT_NAME_swigconstant(_quidef)
QUI__ACCOUNT_NAME = _quidef.QUI__ACCOUNT_NAME

_quidef.QUI__AFTER_TIME_swigconstant(_quidef)
QUI__AFTER_TIME = _quidef.QUI__AFTER_TIME

_quidef.QUI__ASSIGNED_QUEUE_NAME_swigconstant(_quidef)
QUI__ASSIGNED_QUEUE_NAME = _quidef.QUI__ASSIGNED_QUEUE_NAME

_quidef.QUI__BASE_PRIORITY_swigconstant(_quidef)
QUI__BASE_PRIORITY = _quidef.QUI__BASE_PRIORITY

_quidef.QUI__CHARACTERISTIC_NAME_swigconstant(_quidef)
QUI__CHARACTERISTIC_NAME = _quidef.QUI__CHARACTERISTIC_NAME

_quidef.QUI__CHARACTERISTIC_NUMBER_swigconstant(_quidef)
QUI__CHARACTERISTIC_NUMBER = _quidef.QUI__CHARACTERISTIC_NUMBER

_quidef.QUI__CHARACTERISTICS_swigconstant(_quidef)
QUI__CHARACTERISTICS = _quidef.QUI__CHARACTERISTICS

_quidef.QUI__CHECKPOINT_DATA_swigconstant(_quidef)
QUI__CHECKPOINT_DATA = _quidef.QUI__CHECKPOINT_DATA

_quidef.QUI__CLI_swigconstant(_quidef)
QUI__CLI = _quidef.QUI__CLI

_quidef.QUI__COMPLETED_BLOCKS_swigconstant(_quidef)
QUI__COMPLETED_BLOCKS = _quidef.QUI__COMPLETED_BLOCKS

_quidef.QUI__CONDITION_VECTOR_swigconstant(_quidef)
QUI__CONDITION_VECTOR = _quidef.QUI__CONDITION_VECTOR

_quidef.QUI__CPU_DEFAULT_swigconstant(_quidef)
QUI__CPU_DEFAULT = _quidef.QUI__CPU_DEFAULT

_quidef.QUI__CPU_LIMIT_swigconstant(_quidef)
QUI__CPU_LIMIT = _quidef.QUI__CPU_LIMIT

_quidef.QUI__DEVICE_NAME_swigconstant(_quidef)
QUI__DEVICE_NAME = _quidef.QUI__DEVICE_NAME

_quidef.QUI__ENTRY_NUMBER_swigconstant(_quidef)
QUI__ENTRY_NUMBER = _quidef.QUI__ENTRY_NUMBER

_quidef.QUI__FILE_COPIES_swigconstant(_quidef)
QUI__FILE_COPIES = _quidef.QUI__FILE_COPIES

_quidef.QUI__FILE_COPIES_CHKPT_swigconstant(_quidef)
QUI__FILE_COPIES_CHKPT = _quidef.QUI__FILE_COPIES_CHKPT

_quidef.QUI__FILE_COPIES_DONE_swigconstant(_quidef)
QUI__FILE_COPIES_DONE = _quidef.QUI__FILE_COPIES_DONE

_quidef.QUI__FILE_FLAGS_swigconstant(_quidef)
QUI__FILE_FLAGS = _quidef.QUI__FILE_FLAGS

_quidef.QUI__FILE_SETUP_MODULES_swigconstant(_quidef)
QUI__FILE_SETUP_MODULES = _quidef.QUI__FILE_SETUP_MODULES

_quidef.QUI__FILE_SPECIFICATION_swigconstant(_quidef)
QUI__FILE_SPECIFICATION = _quidef.QUI__FILE_SPECIFICATION

_quidef.QUI__FILE_STATUS_swigconstant(_quidef)
QUI__FILE_STATUS = _quidef.QUI__FILE_STATUS

_quidef.QUI__FIRST_PAGE_swigconstant(_quidef)
QUI__FIRST_PAGE = _quidef.QUI__FIRST_PAGE

_quidef.QUI__FORM_DESCRIPTION_swigconstant(_quidef)
QUI__FORM_DESCRIPTION = _quidef.QUI__FORM_DESCRIPTION

_quidef.QUI__FORM_FLAGS_swigconstant(_quidef)
QUI__FORM_FLAGS = _quidef.QUI__FORM_FLAGS

_quidef.QUI__FORM_LENGTH_swigconstant(_quidef)
QUI__FORM_LENGTH = _quidef.QUI__FORM_LENGTH

_quidef.QUI__FORM_MARGIN_BOTTOM_swigconstant(_quidef)
QUI__FORM_MARGIN_BOTTOM = _quidef.QUI__FORM_MARGIN_BOTTOM

_quidef.QUI__FORM_MARGIN_LEFT_swigconstant(_quidef)
QUI__FORM_MARGIN_LEFT = _quidef.QUI__FORM_MARGIN_LEFT

_quidef.QUI__FORM_MARGIN_RIGHT_swigconstant(_quidef)
QUI__FORM_MARGIN_RIGHT = _quidef.QUI__FORM_MARGIN_RIGHT

_quidef.QUI__FORM_MARGIN_TOP_swigconstant(_quidef)
QUI__FORM_MARGIN_TOP = _quidef.QUI__FORM_MARGIN_TOP

_quidef.QUI__FORM_NAME_swigconstant(_quidef)
QUI__FORM_NAME = _quidef.QUI__FORM_NAME

_quidef.QUI__FORM_NUMBER_swigconstant(_quidef)
QUI__FORM_NUMBER = _quidef.QUI__FORM_NUMBER

_quidef.QUI__FORM_SETUP_MODULES_swigconstant(_quidef)
QUI__FORM_SETUP_MODULES = _quidef.QUI__FORM_SETUP_MODULES

_quidef.QUI__FORM_STOCK_swigconstant(_quidef)
QUI__FORM_STOCK = _quidef.QUI__FORM_STOCK

_quidef.QUI__FORM_WIDTH_swigconstant(_quidef)
QUI__FORM_WIDTH = _quidef.QUI__FORM_WIDTH

_quidef.QUI__GENERIC_TARGET_swigconstant(_quidef)
QUI__GENERIC_TARGET = _quidef.QUI__GENERIC_TARGET

_quidef.QUI__INTERVENING_BLOCKS_swigconstant(_quidef)
QUI__INTERVENING_BLOCKS = _quidef.QUI__INTERVENING_BLOCKS

_quidef.QUI__INTERVENING_JOBS_swigconstant(_quidef)
QUI__INTERVENING_JOBS = _quidef.QUI__INTERVENING_JOBS

_quidef.QUI__JOB_COPIES_swigconstant(_quidef)
QUI__JOB_COPIES = _quidef.QUI__JOB_COPIES

_quidef.QUI__JOB_COPIES_CHKPT_swigconstant(_quidef)
QUI__JOB_COPIES_CHKPT = _quidef.QUI__JOB_COPIES_CHKPT

_quidef.QUI__JOB_COPIES_DONE_swigconstant(_quidef)
QUI__JOB_COPIES_DONE = _quidef.QUI__JOB_COPIES_DONE

_quidef.QUI__JOB_FLAGS_swigconstant(_quidef)
QUI__JOB_FLAGS = _quidef.QUI__JOB_FLAGS

_quidef.QUI__JOB_LIMIT_swigconstant(_quidef)
QUI__JOB_LIMIT = _quidef.QUI__JOB_LIMIT

_quidef.QUI__JOB_NAME_swigconstant(_quidef)
QUI__JOB_NAME = _quidef.QUI__JOB_NAME

_quidef.QUI__JOB_RESET_MODULES_swigconstant(_quidef)
QUI__JOB_RESET_MODULES = _quidef.QUI__JOB_RESET_MODULES

_quidef.QUI__JOB_SIZE_swigconstant(_quidef)
QUI__JOB_SIZE = _quidef.QUI__JOB_SIZE

_quidef.QUI__JOB_SIZE_MAXIMUM_swigconstant(_quidef)
QUI__JOB_SIZE_MAXIMUM = _quidef.QUI__JOB_SIZE_MAXIMUM

_quidef.QUI__JOB_SIZE_MINIMUM_swigconstant(_quidef)
QUI__JOB_SIZE_MINIMUM = _quidef.QUI__JOB_SIZE_MINIMUM

_quidef.QUI__JOB_STATUS_swigconstant(_quidef)
QUI__JOB_STATUS = _quidef.QUI__JOB_STATUS

_quidef.QUI__LAST_PAGE_swigconstant(_quidef)
QUI__LAST_PAGE = _quidef.QUI__LAST_PAGE

_quidef.QUI__LIBRARY_SPECIFICATION_swigconstant(_quidef)
QUI__LIBRARY_SPECIFICATION = _quidef.QUI__LIBRARY_SPECIFICATION

_quidef.QUI__LOG_QUEUE_swigconstant(_quidef)
QUI__LOG_QUEUE = _quidef.QUI__LOG_QUEUE

_quidef.QUI__LOG_SPECIFICATION_swigconstant(_quidef)
QUI__LOG_SPECIFICATION = _quidef.QUI__LOG_SPECIFICATION

_quidef.QUI__NOTE_swigconstant(_quidef)
QUI__NOTE = _quidef.QUI__NOTE

_quidef.QUI__OPERATOR_REQUEST_swigconstant(_quidef)
QUI__OPERATOR_REQUEST = _quidef.QUI__OPERATOR_REQUEST

_quidef.QUI__OWNER_UIC_swigconstant(_quidef)
QUI__OWNER_UIC = _quidef.QUI__OWNER_UIC

_quidef.QUI__PAGE_SETUP_MODULES_swigconstant(_quidef)
QUI__PAGE_SETUP_MODULES = _quidef.QUI__PAGE_SETUP_MODULES

_quidef.QUI__PARAMETER_1_swigconstant(_quidef)
QUI__PARAMETER_1 = _quidef.QUI__PARAMETER_1

_quidef.QUI__PARAMETER_2_swigconstant(_quidef)
QUI__PARAMETER_2 = _quidef.QUI__PARAMETER_2

_quidef.QUI__PARAMETER_3_swigconstant(_quidef)
QUI__PARAMETER_3 = _quidef.QUI__PARAMETER_3

_quidef.QUI__PARAMETER_4_swigconstant(_quidef)
QUI__PARAMETER_4 = _quidef.QUI__PARAMETER_4

_quidef.QUI__PARAMETER_5_swigconstant(_quidef)
QUI__PARAMETER_5 = _quidef.QUI__PARAMETER_5

_quidef.QUI__PARAMETER_6_swigconstant(_quidef)
QUI__PARAMETER_6 = _quidef.QUI__PARAMETER_6

_quidef.QUI__PARAMETER_7_swigconstant(_quidef)
QUI__PARAMETER_7 = _quidef.QUI__PARAMETER_7

_quidef.QUI__PARAMETER_8_swigconstant(_quidef)
QUI__PARAMETER_8 = _quidef.QUI__PARAMETER_8

_quidef.QUI__PRIORITY_swigconstant(_quidef)
QUI__PRIORITY = _quidef.QUI__PRIORITY

_quidef.QUI__PROCESSOR_swigconstant(_quidef)
QUI__PROCESSOR = _quidef.QUI__PROCESSOR

_quidef.QUI__PROTECTION_swigconstant(_quidef)
QUI__PROTECTION = _quidef.QUI__PROTECTION

_quidef.QUI__QUEUE_FLAGS_swigconstant(_quidef)
QUI__QUEUE_FLAGS = _quidef.QUI__QUEUE_FLAGS

_quidef.QUI__QUEUE_NAME_swigconstant(_quidef)
QUI__QUEUE_NAME = _quidef.QUI__QUEUE_NAME

_quidef.QUI__QUEUE_STATUS_swigconstant(_quidef)
QUI__QUEUE_STATUS = _quidef.QUI__QUEUE_STATUS

_quidef.QUI__REFUSAL_REASON_swigconstant(_quidef)
QUI__REFUSAL_REASON = _quidef.QUI__REFUSAL_REASON

_quidef.QUI__REQUEUE_PRIORITY_swigconstant(_quidef)
QUI__REQUEUE_PRIORITY = _quidef.QUI__REQUEUE_PRIORITY

_quidef.QUI__REQUEUE_QUEUE_NAME_swigconstant(_quidef)
QUI__REQUEUE_QUEUE_NAME = _quidef.QUI__REQUEUE_QUEUE_NAME

_quidef.QUI__SCSNODE_NAME_swigconstant(_quidef)
QUI__SCSNODE_NAME = _quidef.QUI__SCSNODE_NAME

_quidef.QUI__SEARCH_FLAGS_swigconstant(_quidef)
QUI__SEARCH_FLAGS = _quidef.QUI__SEARCH_FLAGS

_quidef.QUI__SEARCH_NAME_swigconstant(_quidef)
QUI__SEARCH_NAME = _quidef.QUI__SEARCH_NAME

_quidef.QUI__SEARCH_NUMBER_swigconstant(_quidef)
QUI__SEARCH_NUMBER = _quidef.QUI__SEARCH_NUMBER

_quidef.QUI__SUBMISSION_TIME_swigconstant(_quidef)
QUI__SUBMISSION_TIME = _quidef.QUI__SUBMISSION_TIME

_quidef.QUI__UIC_swigconstant(_quidef)
QUI__UIC = _quidef.QUI__UIC

_quidef.QUI__USERNAME_swigconstant(_quidef)
QUI__USERNAME = _quidef.QUI__USERNAME

_quidef.QUI__WSDEFAULT_swigconstant(_quidef)
QUI__WSDEFAULT = _quidef.QUI__WSDEFAULT

_quidef.QUI__WSEXTENT_swigconstant(_quidef)
QUI__WSEXTENT = _quidef.QUI__WSEXTENT

_quidef.QUI__WSQUOTA_swigconstant(_quidef)
QUI__WSQUOTA = _quidef.QUI__WSQUOTA

_quidef.QUI__RAD_swigconstant(_quidef)
QUI__RAD = _quidef.QUI__RAD

_quidef.QUI__RESERVED_OUTPUT_86_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_86 = _quidef.QUI__RESERVED_OUTPUT_86

_quidef.QUI__JOB_CONTROL_GQC_swigconstant(_quidef)
QUI__JOB_CONTROL_GQC = _quidef.QUI__JOB_CONTROL_GQC

_quidef.QUI__SEARCH_USERNAME_swigconstant(_quidef)
QUI__SEARCH_USERNAME = _quidef.QUI__SEARCH_USERNAME

_quidef.QUI__DEFAULT_FORM_NAME_swigconstant(_quidef)
QUI__DEFAULT_FORM_NAME = _quidef.QUI__DEFAULT_FORM_NAME

_quidef.QUI__DEFAULT_FORM_NUMBER_swigconstant(_quidef)
QUI__DEFAULT_FORM_NUMBER = _quidef.QUI__DEFAULT_FORM_NUMBER

_quidef.QUI__DEFAULT_FORM_STOCK_swigconstant(_quidef)
QUI__DEFAULT_FORM_STOCK = _quidef.QUI__DEFAULT_FORM_STOCK

_quidef.QUI__JOB_PID_swigconstant(_quidef)
QUI__JOB_PID = _quidef.QUI__JOB_PID

_quidef.QUI__FILE_IDENTIFICATION_swigconstant(_quidef)
QUI__FILE_IDENTIFICATION = _quidef.QUI__FILE_IDENTIFICATION

_quidef.QUI__PENDING_JOB_BLOCK_COUNT_swigconstant(_quidef)
QUI__PENDING_JOB_BLOCK_COUNT = _quidef.QUI__PENDING_JOB_BLOCK_COUNT

_quidef.QUI__JOB_RETENTION_TIME_swigconstant(_quidef)
QUI__JOB_RETENTION_TIME = _quidef.QUI__JOB_RETENTION_TIME

_quidef.QUI__JOB_COMPLETION_TIME_swigconstant(_quidef)
QUI__JOB_COMPLETION_TIME = _quidef.QUI__JOB_COMPLETION_TIME

_quidef.QUI__JOB_COMPLETION_QUEUE_swigconstant(_quidef)
QUI__JOB_COMPLETION_QUEUE = _quidef.QUI__JOB_COMPLETION_QUEUE

_quidef.QUI__RESERVED_OUTPUT_98_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_98 = _quidef.QUI__RESERVED_OUTPUT_98

_quidef.QUI__RESERVED_OUTPUT_99_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_99 = _quidef.QUI__RESERVED_OUTPUT_99

_quidef.QUI__RESERVED_OUTPUT_100_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_100 = _quidef.QUI__RESERVED_OUTPUT_100

_quidef.QUI__RESERVED_OUTPUT_101_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_101 = _quidef.QUI__RESERVED_OUTPUT_101

_quidef.QUI__RESERVED_OUTPUT_102_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_102 = _quidef.QUI__RESERVED_OUTPUT_102

_quidef.QUI__SEARCH_BATCH_EPID_swigconstant(_quidef)
QUI__SEARCH_BATCH_EPID = _quidef.QUI__SEARCH_BATCH_EPID

_quidef.QUI__SEARCH_JOB_NAME_swigconstant(_quidef)
QUI__SEARCH_JOB_NAME = _quidef.QUI__SEARCH_JOB_NAME

_quidef.QUI__RESERVED_INPUT_105_swigconstant(_quidef)
QUI__RESERVED_INPUT_105 = _quidef.QUI__RESERVED_INPUT_105

_quidef.QUI__RESERVED_INPUT_106_swigconstant(_quidef)
QUI__RESERVED_INPUT_106 = _quidef.QUI__RESERVED_INPUT_106

_quidef.QUI__EXECUTING_JOB_COUNT_swigconstant(_quidef)
QUI__EXECUTING_JOB_COUNT = _quidef.QUI__EXECUTING_JOB_COUNT

_quidef.QUI__HOLDING_JOB_COUNT_swigconstant(_quidef)
QUI__HOLDING_JOB_COUNT = _quidef.QUI__HOLDING_JOB_COUNT

_quidef.QUI__TIMED_RELEASE_JOB_COUNT_swigconstant(_quidef)
QUI__TIMED_RELEASE_JOB_COUNT = _quidef.QUI__TIMED_RELEASE_JOB_COUNT

_quidef.QUI__PENDING_JOB_REASON_swigconstant(_quidef)
QUI__PENDING_JOB_REASON = _quidef.QUI__PENDING_JOB_REASON

_quidef.QUI__ORB_swigconstant(_quidef)
QUI__ORB = _quidef.QUI__ORB

_quidef.QUI__QUEUE_DESCRIPTION_swigconstant(_quidef)
QUI__QUEUE_DESCRIPTION = _quidef.QUI__QUEUE_DESCRIPTION

_quidef.QUI__SYMBIONT_FLAGS_swigconstant(_quidef)
QUI__SYMBIONT_FLAGS = _quidef.QUI__SYMBIONT_FLAGS

_quidef.QUI__JOB_ACCESS_CLASS_swigconstant(_quidef)
QUI__JOB_ACCESS_CLASS = _quidef.QUI__JOB_ACCESS_CLASS

_quidef.QUI__ORB_LOCK_KEY_swigconstant(_quidef)
QUI__ORB_LOCK_KEY = _quidef.QUI__ORB_LOCK_KEY

_quidef.QUI__CHECKPOINT_FREQUENCY_swigconstant(_quidef)
QUI__CHECKPOINT_FREQUENCY = _quidef.QUI__CHECKPOINT_FREQUENCY

_quidef.QUI__PENDING_JOB_COUNT_swigconstant(_quidef)
QUI__PENDING_JOB_COUNT = _quidef.QUI__PENDING_JOB_COUNT

_quidef.QUI__RETAINED_JOB_COUNT_swigconstant(_quidef)
QUI__RETAINED_JOB_COUNT = _quidef.QUI__RETAINED_JOB_COUNT

_quidef.QUI__RESTART_QUEUE_NAME_swigconstant(_quidef)
QUI__RESTART_QUEUE_NAME = _quidef.QUI__RESTART_QUEUE_NAME

_quidef.QUI__FILE_COUNT_swigconstant(_quidef)
QUI__FILE_COUNT = _quidef.QUI__FILE_COUNT

_quidef.QUI__ATTRIBUTES_swigconstant(_quidef)
QUI__ATTRIBUTES = _quidef.QUI__ATTRIBUTES

_quidef.QUI__ATTRIBUTES_SIZE_swigconstant(_quidef)
QUI__ATTRIBUTES_SIZE = _quidef.QUI__ATTRIBUTES_SIZE

_quidef.QUI__QUEUE_SUPPORT_swigconstant(_quidef)
QUI__QUEUE_SUPPORT = _quidef.QUI__QUEUE_SUPPORT

_quidef.QUI__QUEUE_ATTRIBUTES_swigconstant(_quidef)
QUI__QUEUE_ATTRIBUTES = _quidef.QUI__QUEUE_ATTRIBUTES

_quidef.QUI__QUEUE_ATTRIBUTES_SIZE_swigconstant(_quidef)
QUI__QUEUE_ATTRIBUTES_SIZE = _quidef.QUI__QUEUE_ATTRIBUTES_SIZE

_quidef.QUI__JOB_ATTRIBUTES_swigconstant(_quidef)
QUI__JOB_ATTRIBUTES = _quidef.QUI__JOB_ATTRIBUTES

_quidef.QUI__JOB_ATTRIBUTES_SIZE_swigconstant(_quidef)
QUI__JOB_ATTRIBUTES_SIZE = _quidef.QUI__JOB_ATTRIBUTES_SIZE

_quidef.QUI__FILE_ATTRIBUTES_swigconstant(_quidef)
QUI__FILE_ATTRIBUTES = _quidef.QUI__FILE_ATTRIBUTES

_quidef.QUI__FILE_ATTRIBUTES_SIZE_swigconstant(_quidef)
QUI__FILE_ATTRIBUTES_SIZE = _quidef.QUI__FILE_ATTRIBUTES_SIZE

_quidef.QUI__AUTOSTART_ON_swigconstant(_quidef)
QUI__AUTOSTART_ON = _quidef.QUI__AUTOSTART_ON

_quidef.QUI__AGENT_PROFILE_swigconstant(_quidef)
QUI__AGENT_PROFILE = _quidef.QUI__AGENT_PROFILE

_quidef.QUI__MANAGER_NAME_swigconstant(_quidef)
QUI__MANAGER_NAME = _quidef.QUI__MANAGER_NAME

_quidef.QUI__MANAGER_STATUS_swigconstant(_quidef)
QUI__MANAGER_STATUS = _quidef.QUI__MANAGER_STATUS

_quidef.QUI__RESERVED_OUTPUT_134_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_134 = _quidef.QUI__RESERVED_OUTPUT_134

_quidef.QUI__MANAGER_NODES_swigconstant(_quidef)
QUI__MANAGER_NODES = _quidef.QUI__MANAGER_NODES

_quidef.QUI__MANAGER_AUTOSTART_swigconstant(_quidef)
QUI__MANAGER_AUTOSTART = _quidef.QUI__MANAGER_AUTOSTART

_quidef.QUI__QUEUE_DIRECTORY_swigconstant(_quidef)
QUI__QUEUE_DIRECTORY = _quidef.QUI__QUEUE_DIRECTORY

_quidef.QUI__RESERVED_OUTPUT_138_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_138 = _quidef.QUI__RESERVED_OUTPUT_138

_quidef.QUI__RESERVED_OUTPUT_139_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_139 = _quidef.QUI__RESERVED_OUTPUT_139

_quidef.QUI__RESERVED_OUTPUT_140_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_140 = _quidef.QUI__RESERVED_OUTPUT_140

_quidef.QUI__RESERVED_OUTPUT_141_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_141 = _quidef.QUI__RESERVED_OUTPUT_141

_quidef.QUI__RESERVED_OUTPUT_142_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_142 = _quidef.QUI__RESERVED_OUTPUT_142

_quidef.QUI__RESERVED_OUTPUT_143_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_143 = _quidef.QUI__RESERVED_OUTPUT_143

_quidef.QUI__RESERVED_OUTPUT_144_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_144 = _quidef.QUI__RESERVED_OUTPUT_144

_quidef.QUI__RESERVED_OUTPUT_145_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_145 = _quidef.QUI__RESERVED_OUTPUT_145

_quidef.QUI__RESERVED_OUTPUT_146_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_146 = _quidef.QUI__RESERVED_OUTPUT_146

_quidef.QUI__RESERVED_OUTPUT_147_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_147 = _quidef.QUI__RESERVED_OUTPUT_147

_quidef.QUI__RESERVED_OUTPUT_148_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_148 = _quidef.QUI__RESERVED_OUTPUT_148

_quidef.QUI__RESERVED_OUTPUT_149_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_149 = _quidef.QUI__RESERVED_OUTPUT_149

_quidef.QUI__RESERVED_OUTPUT_150_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_150 = _quidef.QUI__RESERVED_OUTPUT_150

_quidef.QUI__RESERVED_OUTPUT_151_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_151 = _quidef.QUI__RESERVED_OUTPUT_151

_quidef.QUI__RESERVED_OUTPUT_152_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_152 = _quidef.QUI__RESERVED_OUTPUT_152

_quidef.QUI__RESERVED_OUTPUT_153_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_153 = _quidef.QUI__RESERVED_OUTPUT_153

_quidef.QUI__RESERVED_OUTPUT_154_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_154 = _quidef.QUI__RESERVED_OUTPUT_154

_quidef.QUI__RESERVED_OUTPUT_155_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_155 = _quidef.QUI__RESERVED_OUTPUT_155

_quidef.QUI__RESERVED_OUTPUT_156_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_156 = _quidef.QUI__RESERVED_OUTPUT_156

_quidef.QUI__RESERVED_OUTPUT_157_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_157 = _quidef.QUI__RESERVED_OUTPUT_157

_quidef.QUI__RESERVED_OUTPUT_158_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_158 = _quidef.QUI__RESERVED_OUTPUT_158

_quidef.QUI__RESERVED_OUTPUT_159_swigconstant(_quidef)
QUI__RESERVED_OUTPUT_159 = _quidef.QUI__RESERVED_OUTPUT_159

_quidef.QUI__RESERVED_INPUT_160_swigconstant(_quidef)
QUI__RESERVED_INPUT_160 = _quidef.QUI__RESERVED_INPUT_160

_quidef.QUI__RESERVED_INPUT_161_swigconstant(_quidef)
QUI__RESERVED_INPUT_161 = _quidef.QUI__RESERVED_INPUT_161

_quidef.QUI__RESERVED_INPUT_162_swigconstant(_quidef)
QUI__RESERVED_INPUT_162 = _quidef.QUI__RESERVED_INPUT_162

_quidef.QUI__RESERVED_INPUT_163_swigconstant(_quidef)
QUI__RESERVED_INPUT_163 = _quidef.QUI__RESERVED_INPUT_163

_quidef.QUI__RESERVED_INPUT_164_swigconstant(_quidef)
QUI__RESERVED_INPUT_164 = _quidef.QUI__RESERVED_INPUT_164

_quidef.QUI__RESERVED_INPUT_165_swigconstant(_quidef)
QUI__RESERVED_INPUT_165 = _quidef.QUI__RESERVED_INPUT_165

_quidef.QUI_K_MIN_ITEM_swigconstant(_quidef)
QUI_K_MIN_ITEM = _quidef.QUI_K_MIN_ITEM

_quidef.QUI_K_MAX_ITEM_swigconstant(_quidef)
QUI_K_MAX_ITEM = _quidef.QUI_K_MAX_ITEM

_quidef.QUI__CHARGE_CODE_swigconstant(_quidef)
QUI__CHARGE_CODE = _quidef.QUI__CHARGE_CODE

_quidef.QUI_M_FILE_BURST_swigconstant(_quidef)
QUI_M_FILE_BURST = _quidef.QUI_M_FILE_BURST

_quidef.QUI_M_FILE_BURST_EXP_swigconstant(_quidef)
QUI_M_FILE_BURST_EXP = _quidef.QUI_M_FILE_BURST_EXP

_quidef.QUI_M_FILE_DELETE_swigconstant(_quidef)
QUI_M_FILE_DELETE = _quidef.QUI_M_FILE_DELETE

_quidef.QUI_M_FILE_DOUBLE_SPACE_swigconstant(_quidef)
QUI_M_FILE_DOUBLE_SPACE = _quidef.QUI_M_FILE_DOUBLE_SPACE

_quidef.QUI_M_FILE_FLAG_swigconstant(_quidef)
QUI_M_FILE_FLAG = _quidef.QUI_M_FILE_FLAG

_quidef.QUI_M_FILE_FLAG_EXP_swigconstant(_quidef)
QUI_M_FILE_FLAG_EXP = _quidef.QUI_M_FILE_FLAG_EXP

_quidef.QUI_M_FILE_TRAILER_swigconstant(_quidef)
QUI_M_FILE_TRAILER = _quidef.QUI_M_FILE_TRAILER

_quidef.QUI_M_FILE_TRAILER_EXP_swigconstant(_quidef)
QUI_M_FILE_TRAILER_EXP = _quidef.QUI_M_FILE_TRAILER_EXP

_quidef.QUI_M_FILE_PAGE_HEADER_swigconstant(_quidef)
QUI_M_FILE_PAGE_HEADER = _quidef.QUI_M_FILE_PAGE_HEADER

_quidef.QUI_M_FILE_PAGINATE_swigconstant(_quidef)
QUI_M_FILE_PAGINATE = _quidef.QUI_M_FILE_PAGINATE

_quidef.QUI_M_FILE_PASSALL_swigconstant(_quidef)
QUI_M_FILE_PASSALL = _quidef.QUI_M_FILE_PASSALL

_quidef.QUI_M_FILE_PAGINATE_EXP_swigconstant(_quidef)
QUI_M_FILE_PAGINATE_EXP = _quidef.QUI_M_FILE_PAGINATE_EXP

_quidef.QUI_M_FILE_DELETE_ALWAYS_swigconstant(_quidef)
QUI_M_FILE_DELETE_ALWAYS = _quidef.QUI_M_FILE_DELETE_ALWAYS

_quidef.QUI_S_FILE_FLAGS_swigconstant(_quidef)
QUI_S_FILE_FLAGS = _quidef.QUI_S_FILE_FLAGS

_quidef.QUI_M_FILE_CHECKPOINTED_swigconstant(_quidef)
QUI_M_FILE_CHECKPOINTED = _quidef.QUI_M_FILE_CHECKPOINTED

_quidef.QUI_M_FILE_EXECUTING_swigconstant(_quidef)
QUI_M_FILE_EXECUTING = _quidef.QUI_M_FILE_EXECUTING

_quidef.QUI_S_FILE_STATUS_swigconstant(_quidef)
QUI_S_FILE_STATUS = _quidef.QUI_S_FILE_STATUS

_quidef.QUI_M_FORM_SHEET_FEED_swigconstant(_quidef)
QUI_M_FORM_SHEET_FEED = _quidef.QUI_M_FORM_SHEET_FEED

_quidef.QUI_M_FORM_TRUNCATE_swigconstant(_quidef)
QUI_M_FORM_TRUNCATE = _quidef.QUI_M_FORM_TRUNCATE

_quidef.QUI_M_FORM_WRAP_swigconstant(_quidef)
QUI_M_FORM_WRAP = _quidef.QUI_M_FORM_WRAP

_quidef.QUI_S_FORM_FLAGS_swigconstant(_quidef)
QUI_S_FORM_FLAGS = _quidef.QUI_S_FORM_FLAGS

_quidef.QUI_M_JOB_CPU_LIMIT_swigconstant(_quidef)
QUI_M_JOB_CPU_LIMIT = _quidef.QUI_M_JOB_CPU_LIMIT

_quidef.QUI_M_JOB_FILE_BURST_swigconstant(_quidef)
QUI_M_JOB_FILE_BURST = _quidef.QUI_M_JOB_FILE_BURST

_quidef.QUI_M_JOB_FILE_BURST_ONE_swigconstant(_quidef)
QUI_M_JOB_FILE_BURST_ONE = _quidef.QUI_M_JOB_FILE_BURST_ONE

_quidef.QUI_M_JOB_FILE_BURST_EXP_swigconstant(_quidef)
QUI_M_JOB_FILE_BURST_EXP = _quidef.QUI_M_JOB_FILE_BURST_EXP

_quidef.QUI_M_JOB_FILE_FLAG_swigconstant(_quidef)
QUI_M_JOB_FILE_FLAG = _quidef.QUI_M_JOB_FILE_FLAG

_quidef.QUI_M_JOB_FILE_FLAG_ONE_swigconstant(_quidef)
QUI_M_JOB_FILE_FLAG_ONE = _quidef.QUI_M_JOB_FILE_FLAG_ONE

_quidef.QUI_M_JOB_FILE_FLAG_EXP_swigconstant(_quidef)
QUI_M_JOB_FILE_FLAG_EXP = _quidef.QUI_M_JOB_FILE_FLAG_EXP

_quidef.QUI_M_JOB_FILE_TRAILER_swigconstant(_quidef)
QUI_M_JOB_FILE_TRAILER = _quidef.QUI_M_JOB_FILE_TRAILER

_quidef.QUI_M_JOB_FILE_TRAILER_ONE_swigconstant(_quidef)
QUI_M_JOB_FILE_TRAILER_ONE = _quidef.QUI_M_JOB_FILE_TRAILER_ONE

_quidef.QUI_M_JOB_FILE_TRAILER_EXP_swigconstant(_quidef)
QUI_M_JOB_FILE_TRAILER_EXP = _quidef.QUI_M_JOB_FILE_TRAILER_EXP

_quidef.QUI_M_JOB_LOG_DELETE_swigconstant(_quidef)
QUI_M_JOB_LOG_DELETE = _quidef.QUI_M_JOB_LOG_DELETE

_quidef.QUI_M_JOB_LOG_NULL_swigconstant(_quidef)
QUI_M_JOB_LOG_NULL = _quidef.QUI_M_JOB_LOG_NULL

_quidef.QUI_M_JOB_LOG_SPOOL_swigconstant(_quidef)
QUI_M_JOB_LOG_SPOOL = _quidef.QUI_M_JOB_LOG_SPOOL

_quidef.QUI_M_JOB_LOWERCASE_swigconstant(_quidef)
QUI_M_JOB_LOWERCASE = _quidef.QUI_M_JOB_LOWERCASE

_quidef.QUI_M_JOB_NOTIFY_swigconstant(_quidef)
QUI_M_JOB_NOTIFY = _quidef.QUI_M_JOB_NOTIFY

_quidef.QUI_M_JOB_RESTART_swigconstant(_quidef)
QUI_M_JOB_RESTART = _quidef.QUI_M_JOB_RESTART

_quidef.QUI_M_JOB_WSDEFAULT_swigconstant(_quidef)
QUI_M_JOB_WSDEFAULT = _quidef.QUI_M_JOB_WSDEFAULT

_quidef.QUI_M_JOB_WSEXTENT_swigconstant(_quidef)
QUI_M_JOB_WSEXTENT = _quidef.QUI_M_JOB_WSEXTENT

_quidef.QUI_M_JOB_WSQUOTA_swigconstant(_quidef)
QUI_M_JOB_WSQUOTA = _quidef.QUI_M_JOB_WSQUOTA

_quidef.QUI_M_JOB_FILE_PAGINATE_swigconstant(_quidef)
QUI_M_JOB_FILE_PAGINATE = _quidef.QUI_M_JOB_FILE_PAGINATE

_quidef.QUI_M_JOB_FILE_PAGINATE_EXP_swigconstant(_quidef)
QUI_M_JOB_FILE_PAGINATE_EXP = _quidef.QUI_M_JOB_FILE_PAGINATE_EXP

_quidef.QUI_M_JOB_RETENTION_swigconstant(_quidef)
QUI_M_JOB_RETENTION = _quidef.QUI_M_JOB_RETENTION

_quidef.QUI_M_JOB_ERROR_RETENTION_swigconstant(_quidef)
QUI_M_JOB_ERROR_RETENTION = _quidef.QUI_M_JOB_ERROR_RETENTION

_quidef.QUI_M_JOB_RAD_swigconstant(_quidef)
QUI_M_JOB_RAD = _quidef.QUI_M_JOB_RAD

_quidef.QUI_S_JOB_FLAGS_swigconstant(_quidef)
QUI_S_JOB_FLAGS = _quidef.QUI_S_JOB_FLAGS

_quidef.QUI_M_JOB_ABORTING_swigconstant(_quidef)
QUI_M_JOB_ABORTING = _quidef.QUI_M_JOB_ABORTING

_quidef.QUI_M_JOB_EXECUTING_swigconstant(_quidef)
QUI_M_JOB_EXECUTING = _quidef.QUI_M_JOB_EXECUTING

_quidef.QUI_M_JOB_HOLDING_swigconstant(_quidef)
QUI_M_JOB_HOLDING = _quidef.QUI_M_JOB_HOLDING

_quidef.QUI_M_JOB_INACCESSIBLE_swigconstant(_quidef)
QUI_M_JOB_INACCESSIBLE = _quidef.QUI_M_JOB_INACCESSIBLE

_quidef.QUI_M_JOB_REFUSED_swigconstant(_quidef)
QUI_M_JOB_REFUSED = _quidef.QUI_M_JOB_REFUSED

_quidef.QUI_M_JOB_REQUEUE_swigconstant(_quidef)
QUI_M_JOB_REQUEUE = _quidef.QUI_M_JOB_REQUEUE

_quidef.QUI_M_JOB_RESTARTING_swigconstant(_quidef)
QUI_M_JOB_RESTARTING = _quidef.QUI_M_JOB_RESTARTING

_quidef.QUI_M_JOB_RETAINED_swigconstant(_quidef)
QUI_M_JOB_RETAINED = _quidef.QUI_M_JOB_RETAINED

_quidef.QUI_M_JOB_STARTING_swigconstant(_quidef)
QUI_M_JOB_STARTING = _quidef.QUI_M_JOB_STARTING

_quidef.QUI_M_JOB_TIMED_RELEASE_swigconstant(_quidef)
QUI_M_JOB_TIMED_RELEASE = _quidef.QUI_M_JOB_TIMED_RELEASE

_quidef.QUI_M_JOB_SUSPENDED_swigconstant(_quidef)
QUI_M_JOB_SUSPENDED = _quidef.QUI_M_JOB_SUSPENDED

_quidef.QUI_M_JOB_PENDING_swigconstant(_quidef)
QUI_M_JOB_PENDING = _quidef.QUI_M_JOB_PENDING

_quidef.QUI_M_JOB_UNDEFINED_swigconstant(_quidef)
QUI_M_JOB_UNDEFINED = _quidef.QUI_M_JOB_UNDEFINED

_quidef.QUI_M_JOB_STALLED_swigconstant(_quidef)
QUI_M_JOB_STALLED = _quidef.QUI_M_JOB_STALLED

_quidef.QUI_M_JOB_INCOMPLETE_swigconstant(_quidef)
QUI_M_JOB_INCOMPLETE = _quidef.QUI_M_JOB_INCOMPLETE

_quidef.QUI_M_JOB_COMPLETING_swigconstant(_quidef)
QUI_M_JOB_COMPLETING = _quidef.QUI_M_JOB_COMPLETING

_quidef.QUI_S_JOB_STATUS_swigconstant(_quidef)
QUI_S_JOB_STATUS = _quidef.QUI_S_JOB_STATUS

_quidef.QUI_V_JOB_TIMED_swigconstant(_quidef)
QUI_V_JOB_TIMED = _quidef.QUI_V_JOB_TIMED

_quidef.QUI_M_JOB_TIMED_swigconstant(_quidef)
QUI_M_JOB_TIMED = _quidef.QUI_M_JOB_TIMED

_quidef.QUI_M_PEND_CHAR_MISMATCH_swigconstant(_quidef)
QUI_M_PEND_CHAR_MISMATCH = _quidef.QUI_M_PEND_CHAR_MISMATCH

_quidef.QUI_M_PEND_JOB_SIZE_MAX_swigconstant(_quidef)
QUI_M_PEND_JOB_SIZE_MAX = _quidef.QUI_M_PEND_JOB_SIZE_MAX

_quidef.QUI_M_PEND_JOB_SIZE_MIN_swigconstant(_quidef)
QUI_M_PEND_JOB_SIZE_MIN = _quidef.QUI_M_PEND_JOB_SIZE_MIN

_quidef.QUI_M_PEND_LOWERCASE_MISMATCH_swigconstant(_quidef)
QUI_M_PEND_LOWERCASE_MISMATCH = _quidef.QUI_M_PEND_LOWERCASE_MISMATCH

_quidef.QUI_M_PEND_NO_ACCESS_swigconstant(_quidef)
QUI_M_PEND_NO_ACCESS = _quidef.QUI_M_PEND_NO_ACCESS

_quidef.QUI_M_PEND_QUEUE_BUSY_swigconstant(_quidef)
QUI_M_PEND_QUEUE_BUSY = _quidef.QUI_M_PEND_QUEUE_BUSY

_quidef.QUI_M_PEND_QUEUE_STATE_swigconstant(_quidef)
QUI_M_PEND_QUEUE_STATE = _quidef.QUI_M_PEND_QUEUE_STATE

_quidef.QUI_M_PEND_STOCK_MISMATCH_swigconstant(_quidef)
QUI_M_PEND_STOCK_MISMATCH = _quidef.QUI_M_PEND_STOCK_MISMATCH

_quidef.QUI_S_PENDING_JOB_REASON_swigconstant(_quidef)
QUI_S_PENDING_JOB_REASON = _quidef.QUI_S_PENDING_JOB_REASON

_quidef.QUI_M_QUEUE_BATCH_swigconstant(_quidef)
QUI_M_QUEUE_BATCH = _quidef.QUI_M_QUEUE_BATCH

_quidef.QUI_M_QUEUE_CPU_DEFAULT_swigconstant(_quidef)
QUI_M_QUEUE_CPU_DEFAULT = _quidef.QUI_M_QUEUE_CPU_DEFAULT

_quidef.QUI_M_QUEUE_CPU_LIMIT_swigconstant(_quidef)
QUI_M_QUEUE_CPU_LIMIT = _quidef.QUI_M_QUEUE_CPU_LIMIT

_quidef.QUI_M_QUEUE_FILE_BURST_swigconstant(_quidef)
QUI_M_QUEUE_FILE_BURST = _quidef.QUI_M_QUEUE_FILE_BURST

_quidef.QUI_M_QUEUE_FILE_BURST_ONE_swigconstant(_quidef)
QUI_M_QUEUE_FILE_BURST_ONE = _quidef.QUI_M_QUEUE_FILE_BURST_ONE

_quidef.QUI_M_QUEUE_FILE_FLAG_swigconstant(_quidef)
QUI_M_QUEUE_FILE_FLAG = _quidef.QUI_M_QUEUE_FILE_FLAG

_quidef.QUI_M_QUEUE_FILE_FLAG_ONE_swigconstant(_quidef)
QUI_M_QUEUE_FILE_FLAG_ONE = _quidef.QUI_M_QUEUE_FILE_FLAG_ONE

_quidef.QUI_M_QUEUE_FILE_TRAILER_swigconstant(_quidef)
QUI_M_QUEUE_FILE_TRAILER = _quidef.QUI_M_QUEUE_FILE_TRAILER

_quidef.QUI_M_QUEUE_FILE_TRAILER_ONE_swigconstant(_quidef)
QUI_M_QUEUE_FILE_TRAILER_ONE = _quidef.QUI_M_QUEUE_FILE_TRAILER_ONE

_quidef.QUI_M_QUEUE_GENERIC_swigconstant(_quidef)
QUI_M_QUEUE_GENERIC = _quidef.QUI_M_QUEUE_GENERIC

_quidef.QUI_M_QUEUE_GENERIC_SELECTION_swigconstant(_quidef)
QUI_M_QUEUE_GENERIC_SELECTION = _quidef.QUI_M_QUEUE_GENERIC_SELECTION

_quidef.QUI_M_QUEUE_JOB_BURST_swigconstant(_quidef)
QUI_M_QUEUE_JOB_BURST = _quidef.QUI_M_QUEUE_JOB_BURST

_quidef.QUI_M_QUEUE_JOB_FLAG_swigconstant(_quidef)
QUI_M_QUEUE_JOB_FLAG = _quidef.QUI_M_QUEUE_JOB_FLAG

_quidef.QUI_M_QUEUE_JOB_SIZE_SCHED_swigconstant(_quidef)
QUI_M_QUEUE_JOB_SIZE_SCHED = _quidef.QUI_M_QUEUE_JOB_SIZE_SCHED

_quidef.QUI_M_QUEUE_JOB_TRAILER_swigconstant(_quidef)
QUI_M_QUEUE_JOB_TRAILER = _quidef.QUI_M_QUEUE_JOB_TRAILER

_quidef.QUI_M_QUEUE_RETAIN_ALL_swigconstant(_quidef)
QUI_M_QUEUE_RETAIN_ALL = _quidef.QUI_M_QUEUE_RETAIN_ALL

_quidef.QUI_M_QUEUE_RETAIN_ERROR_swigconstant(_quidef)
QUI_M_QUEUE_RETAIN_ERROR = _quidef.QUI_M_QUEUE_RETAIN_ERROR

_quidef.QUI_M_QUEUE_SWAP_swigconstant(_quidef)
QUI_M_QUEUE_SWAP = _quidef.QUI_M_QUEUE_SWAP

_quidef.QUI_M_QUEUE_TERMINAL_swigconstant(_quidef)
QUI_M_QUEUE_TERMINAL = _quidef.QUI_M_QUEUE_TERMINAL

_quidef.QUI_M_QUEUE_WSDEFAULT_swigconstant(_quidef)
QUI_M_QUEUE_WSDEFAULT = _quidef.QUI_M_QUEUE_WSDEFAULT

_quidef.QUI_M_QUEUE_WSEXTENT_swigconstant(_quidef)
QUI_M_QUEUE_WSEXTENT = _quidef.QUI_M_QUEUE_WSEXTENT

_quidef.QUI_M_QUEUE_WSQUOTA_swigconstant(_quidef)
QUI_M_QUEUE_WSQUOTA = _quidef.QUI_M_QUEUE_WSQUOTA

_quidef.QUI_M_QUEUE_FILE_PAGINATE_swigconstant(_quidef)
QUI_M_QUEUE_FILE_PAGINATE = _quidef.QUI_M_QUEUE_FILE_PAGINATE

_quidef.QUI_M_QUEUE_RECORD_BLOCKING_swigconstant(_quidef)
QUI_M_QUEUE_RECORD_BLOCKING = _quidef.QUI_M_QUEUE_RECORD_BLOCKING

_quidef.QUI_M_QUEUE_PRINTER_swigconstant(_quidef)
QUI_M_QUEUE_PRINTER = _quidef.QUI_M_QUEUE_PRINTER

_quidef.QUI_M_QUEUE_ACL_SPECIFIED_swigconstant(_quidef)
QUI_M_QUEUE_ACL_SPECIFIED = _quidef.QUI_M_QUEUE_ACL_SPECIFIED

_quidef.QUI_M_QUEUE_NOTIFY_ON_INTERRUPT_swigconstant(_quidef)
QUI_M_QUEUE_NOTIFY_ON_INTERRUPT = _quidef.QUI_M_QUEUE_NOTIFY_ON_INTERRUPT

_quidef.QUI_M_QUEUE_CHECKPOINT_FREQ_swigconstant(_quidef)
QUI_M_QUEUE_CHECKPOINT_FREQ = _quidef.QUI_M_QUEUE_CHECKPOINT_FREQ

_quidef.QUI_M_QUEUE_AUTOSTART_swigconstant(_quidef)
QUI_M_QUEUE_AUTOSTART = _quidef.QUI_M_QUEUE_AUTOSTART

_quidef.QUI_M_SECURITY_INACCESSIBLE_swigconstant(_quidef)
QUI_M_SECURITY_INACCESSIBLE = _quidef.QUI_M_SECURITY_INACCESSIBLE

_quidef.QUI_M_QUEUE_NO_INITIAL_FF_swigconstant(_quidef)
QUI_M_QUEUE_NO_INITIAL_FF = _quidef.QUI_M_QUEUE_NO_INITIAL_FF

_quidef.QUI_M_QUEUE_RAD_swigconstant(_quidef)
QUI_M_QUEUE_RAD = _quidef.QUI_M_QUEUE_RAD

_quidef.QUI_S_QUEUE_FLAGS_swigconstant(_quidef)
QUI_S_QUEUE_FLAGS = _quidef.QUI_S_QUEUE_FLAGS

_quidef.QUI_M_QUEUE_ALIGNING_swigconstant(_quidef)
QUI_M_QUEUE_ALIGNING = _quidef.QUI_M_QUEUE_ALIGNING

_quidef.QUI_M_QUEUE_IDLE_swigconstant(_quidef)
QUI_M_QUEUE_IDLE = _quidef.QUI_M_QUEUE_IDLE

_quidef.QUI_M_QUEUE_LOWERCASE_swigconstant(_quidef)
QUI_M_QUEUE_LOWERCASE = _quidef.QUI_M_QUEUE_LOWERCASE

_quidef.QUI_M_QUEUE_OPERATOR_REQUEST_swigconstant(_quidef)
QUI_M_QUEUE_OPERATOR_REQUEST = _quidef.QUI_M_QUEUE_OPERATOR_REQUEST

_quidef.QUI_M_QUEUE_PAUSED_swigconstant(_quidef)
QUI_M_QUEUE_PAUSED = _quidef.QUI_M_QUEUE_PAUSED

_quidef.QUI_M_QUEUE_PAUSING_swigconstant(_quidef)
QUI_M_QUEUE_PAUSING = _quidef.QUI_M_QUEUE_PAUSING

_quidef.QUI_M_QUEUE_REMOTE_swigconstant(_quidef)
QUI_M_QUEUE_REMOTE = _quidef.QUI_M_QUEUE_REMOTE

_quidef.QUI_M_QUEUE_RESETTING_swigconstant(_quidef)
QUI_M_QUEUE_RESETTING = _quidef.QUI_M_QUEUE_RESETTING

_quidef.QUI_M_QUEUE_RESUMING_swigconstant(_quidef)
QUI_M_QUEUE_RESUMING = _quidef.QUI_M_QUEUE_RESUMING

_quidef.QUI_M_QUEUE_SERVER_swigconstant(_quidef)
QUI_M_QUEUE_SERVER = _quidef.QUI_M_QUEUE_SERVER

_quidef.QUI_M_QUEUE_STALLED_swigconstant(_quidef)
QUI_M_QUEUE_STALLED = _quidef.QUI_M_QUEUE_STALLED

_quidef.QUI_M_QUEUE_STARTING_swigconstant(_quidef)
QUI_M_QUEUE_STARTING = _quidef.QUI_M_QUEUE_STARTING

_quidef.QUI_M_QUEUE_STOPPED_swigconstant(_quidef)
QUI_M_QUEUE_STOPPED = _quidef.QUI_M_QUEUE_STOPPED

_quidef.QUI_M_QUEUE_STOPPING_swigconstant(_quidef)
QUI_M_QUEUE_STOPPING = _quidef.QUI_M_QUEUE_STOPPING

_quidef.QUI_M_QUEUE_UNAVAILABLE_swigconstant(_quidef)
QUI_M_QUEUE_UNAVAILABLE = _quidef.QUI_M_QUEUE_UNAVAILABLE

_quidef.QUI_M_QUEUE_CLOSED_swigconstant(_quidef)
QUI_M_QUEUE_CLOSED = _quidef.QUI_M_QUEUE_CLOSED

_quidef.QUI_M_QUEUE_BUSY_swigconstant(_quidef)
QUI_M_QUEUE_BUSY = _quidef.QUI_M_QUEUE_BUSY

_quidef.QUI_M_QUEUE_UNDEFINED_swigconstant(_quidef)
QUI_M_QUEUE_UNDEFINED = _quidef.QUI_M_QUEUE_UNDEFINED

_quidef.QUI_M_QUEUE_AVAILABLE_swigconstant(_quidef)
QUI_M_QUEUE_AVAILABLE = _quidef.QUI_M_QUEUE_AVAILABLE

_quidef.QUI_M_QUEUE_DISABLED_swigconstant(_quidef)
QUI_M_QUEUE_DISABLED = _quidef.QUI_M_QUEUE_DISABLED

_quidef.QUI_M_QUEUE_AUTOSTART_INACTIVE_swigconstant(_quidef)
QUI_M_QUEUE_AUTOSTART_INACTIVE = _quidef.QUI_M_QUEUE_AUTOSTART_INACTIVE

_quidef.QUI_M_QUEUE_STOP_PENDING_swigconstant(_quidef)
QUI_M_QUEUE_STOP_PENDING = _quidef.QUI_M_QUEUE_STOP_PENDING

_quidef.QUI_S_QUEUE_STATUS_swigconstant(_quidef)
QUI_S_QUEUE_STATUS = _quidef.QUI_S_QUEUE_STATUS

_quidef.QUI_M_SEARCH_ALL_JOBS_swigconstant(_quidef)
QUI_M_SEARCH_ALL_JOBS = _quidef.QUI_M_SEARCH_ALL_JOBS

_quidef.QUI_M_SEARCH_WILDCARD_swigconstant(_quidef)
QUI_M_SEARCH_WILDCARD = _quidef.QUI_M_SEARCH_WILDCARD

_quidef.QUI_M_SEARCH_BATCH_swigconstant(_quidef)
QUI_M_SEARCH_BATCH = _quidef.QUI_M_SEARCH_BATCH

_quidef.QUI_M_SEARCH_SYMBIONT_swigconstant(_quidef)
QUI_M_SEARCH_SYMBIONT = _quidef.QUI_M_SEARCH_SYMBIONT

_quidef.QUI_M_SEARCH_THIS_JOB_swigconstant(_quidef)
QUI_M_SEARCH_THIS_JOB = _quidef.QUI_M_SEARCH_THIS_JOB

_quidef.QUI_M_SEARCH_PRINTER_swigconstant(_quidef)
QUI_M_SEARCH_PRINTER = _quidef.QUI_M_SEARCH_PRINTER

_quidef.QUI_M_SEARCH_SERVER_swigconstant(_quidef)
QUI_M_SEARCH_SERVER = _quidef.QUI_M_SEARCH_SERVER

_quidef.QUI_M_SEARCH_TERMINAL_swigconstant(_quidef)
QUI_M_SEARCH_TERMINAL = _quidef.QUI_M_SEARCH_TERMINAL

_quidef.QUI_M_SEARCH_GENERIC_swigconstant(_quidef)
QUI_M_SEARCH_GENERIC = _quidef.QUI_M_SEARCH_GENERIC

_quidef.QUI_M_SEARCH_GENERIC_TARGET_swigconstant(_quidef)
QUI_M_SEARCH_GENERIC_TARGET = _quidef.QUI_M_SEARCH_GENERIC_TARGET

_quidef.QUI_M_SEARCH_PENDING_JOBS_swigconstant(_quidef)
QUI_M_SEARCH_PENDING_JOBS = _quidef.QUI_M_SEARCH_PENDING_JOBS

_quidef.QUI_M_SEARCH_EXECUTING_JOBS_swigconstant(_quidef)
QUI_M_SEARCH_EXECUTING_JOBS = _quidef.QUI_M_SEARCH_EXECUTING_JOBS

_quidef.QUI_M_SEARCH_TIMED_RELEASE_JOBS_swigconstant(_quidef)
QUI_M_SEARCH_TIMED_RELEASE_JOBS = _quidef.QUI_M_SEARCH_TIMED_RELEASE_JOBS

_quidef.QUI_M_SEARCH_HOLDING_JOBS_swigconstant(_quidef)
QUI_M_SEARCH_HOLDING_JOBS = _quidef.QUI_M_SEARCH_HOLDING_JOBS

_quidef.QUI_M_SEARCH_RETAINED_JOBS_swigconstant(_quidef)
QUI_M_SEARCH_RETAINED_JOBS = _quidef.QUI_M_SEARCH_RETAINED_JOBS

_quidef.QUI_M_SEARCH_FREEZE_CONTEXT_swigconstant(_quidef)
QUI_M_SEARCH_FREEZE_CONTEXT = _quidef.QUI_M_SEARCH_FREEZE_CONTEXT

_quidef.QUI_M_SEARCH_OPEN_JOBS_swigconstant(_quidef)
QUI_M_SEARCH_OPEN_JOBS = _quidef.QUI_M_SEARCH_OPEN_JOBS

_quidef.QUI_M_SEARCH_RESERVED_BIT1_swigconstant(_quidef)
QUI_M_SEARCH_RESERVED_BIT1 = _quidef.QUI_M_SEARCH_RESERVED_BIT1

_quidef.QUI_M_SEARCH_RESERVED_BIT2_swigconstant(_quidef)
QUI_M_SEARCH_RESERVED_BIT2 = _quidef.QUI_M_SEARCH_RESERVED_BIT2

_quidef.QUI_S_SEARCH_FLAGS_swigconstant(_quidef)
QUI_S_SEARCH_FLAGS = _quidef.QUI_S_SEARCH_FLAGS

_quidef.QUI_M_SYM_NOTIFIES_swigconstant(_quidef)
QUI_M_SYM_NOTIFIES = _quidef.QUI_M_SYM_NOTIFIES

_quidef.QUI_M_SYM_REQUESTS_OPER_swigconstant(_quidef)
QUI_M_SYM_REQUESTS_OPER = _quidef.QUI_M_SYM_REQUESTS_OPER

_quidef.QUI_M_SYM_COPIES_FILE_swigconstant(_quidef)
QUI_M_SYM_COPIES_FILE = _quidef.QUI_M_SYM_COPIES_FILE

_quidef.QUI_M_SYM_COPIES_JOB_swigconstant(_quidef)
QUI_M_SYM_COPIES_JOB = _quidef.QUI_M_SYM_COPIES_JOB

_quidef.QUI_M_SYM_ACCEPTS_ALL_FORMS_swigconstant(_quidef)
QUI_M_SYM_ACCEPTS_ALL_FORMS = _quidef.QUI_M_SYM_ACCEPTS_ALL_FORMS

_quidef.QUI_M_SYM_NO_JOB_CHECKPOINT_swigconstant(_quidef)
QUI_M_SYM_NO_JOB_CHECKPOINT = _quidef.QUI_M_SYM_NO_JOB_CHECKPOINT

_quidef.QUI_S_SYMBIONT_FLAGS_swigconstant(_quidef)
QUI_S_SYMBIONT_FLAGS = _quidef.QUI_S_SYMBIONT_FLAGS

_quidef.QUI_M_MANAGER_START_PENDING_swigconstant(_quidef)
QUI_M_MANAGER_START_PENDING = _quidef.QUI_M_MANAGER_START_PENDING

_quidef.QUI_M_MANAGER_STARTING_swigconstant(_quidef)
QUI_M_MANAGER_STARTING = _quidef.QUI_M_MANAGER_STARTING

_quidef.QUI_M_MANAGER_RUNNING_swigconstant(_quidef)
QUI_M_MANAGER_RUNNING = _quidef.QUI_M_MANAGER_RUNNING

_quidef.QUI_M_MANAGER_FAILOVER_swigconstant(_quidef)
QUI_M_MANAGER_FAILOVER = _quidef.QUI_M_MANAGER_FAILOVER

_quidef.QUI_M_MANAGER_STOPPING_swigconstant(_quidef)
QUI_M_MANAGER_STOPPING = _quidef.QUI_M_MANAGER_STOPPING

_quidef.QUI_M_MANAGER_STOPPED_swigconstant(_quidef)
QUI_M_MANAGER_STOPPED = _quidef.QUI_M_MANAGER_STOPPED

_quidef.QUI_S_MANAGER_STATUS_swigconstant(_quidef)
QUI_S_MANAGER_STATUS = _quidef.QUI_S_MANAGER_STATUS
# This file is compatible with both classic and new-style classes.


