# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_iodef', [dirname(__file__)])
        except ImportError:
            import _iodef
            return _iodef
        if fp is not None:
            try:
                _mod = imp.load_module('_iodef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _iodef = swig_import_helper()
    del swig_import_helper
else:
    import _iodef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_iodef.IO__NOP_swigconstant(_iodef)
IO__NOP = _iodef.IO__NOP

_iodef.IO__UNLOAD_swigconstant(_iodef)
IO__UNLOAD = _iodef.IO__UNLOAD

_iodef.IO__LOADMCODE_swigconstant(_iodef)
IO__LOADMCODE = _iodef.IO__LOADMCODE

_iodef.IO__START_BUS_swigconstant(_iodef)
IO__START_BUS = _iodef.IO__START_BUS

_iodef.IO__SEEK_swigconstant(_iodef)
IO__SEEK = _iodef.IO__SEEK

_iodef.IO__SPACEFILE_swigconstant(_iodef)
IO__SPACEFILE = _iodef.IO__SPACEFILE

_iodef.IO__STARTMPROC_swigconstant(_iodef)
IO__STARTMPROC = _iodef.IO__STARTMPROC

_iodef.IO__STOP_BUS_swigconstant(_iodef)
IO__STOP_BUS = _iodef.IO__STOP_BUS

_iodef.IO__RECAL_swigconstant(_iodef)
IO__RECAL = _iodef.IO__RECAL

_iodef.IO__DUPLEX_swigconstant(_iodef)
IO__DUPLEX = _iodef.IO__DUPLEX

_iodef.IO__STOP_swigconstant(_iodef)
IO__STOP = _iodef.IO__STOP

_iodef.IO__DEF_COMP_swigconstant(_iodef)
IO__DEF_COMP = _iodef.IO__DEF_COMP

_iodef.IO__DRVCLR_swigconstant(_iodef)
IO__DRVCLR = _iodef.IO__DRVCLR

_iodef.IO__INITIALIZE_swigconstant(_iodef)
IO__INITIALIZE = _iodef.IO__INITIALIZE

_iodef.IO__MIMIC_swigconstant(_iodef)
IO__MIMIC = _iodef.IO__MIMIC

_iodef.IO__DEF_COMP_LIST_swigconstant(_iodef)
IO__DEF_COMP_LIST = _iodef.IO__DEF_COMP_LIST

_iodef.IO__FLUSH_ERROR_swigconstant(_iodef)
IO__FLUSH_ERROR = _iodef.IO__FLUSH_ERROR

_iodef.IO__RELEASE_swigconstant(_iodef)
IO__RELEASE = _iodef.IO__RELEASE

_iodef.IO__SETCLOCKP_swigconstant(_iodef)
IO__SETCLOCKP = _iodef.IO__SETCLOCKP

_iodef.IO__START_ANALYSIS_swigconstant(_iodef)
IO__START_ANALYSIS = _iodef.IO__START_ANALYSIS

_iodef.IO__BIND_swigconstant(_iodef)
IO__BIND = _iodef.IO__BIND

_iodef.IO__PATH_VERIFY_swigconstant(_iodef)
IO__PATH_VERIFY = _iodef.IO__PATH_VERIFY

_iodef.IO__OFFSET_swigconstant(_iodef)
IO__OFFSET = _iodef.IO__OFFSET

_iodef.IO__ERASETAPE_swigconstant(_iodef)
IO__ERASETAPE = _iodef.IO__ERASETAPE

_iodef.IO__STARTDATAP_swigconstant(_iodef)
IO__STARTDATAP = _iodef.IO__STARTDATAP

_iodef.IO__STOP_ANALYSIS_swigconstant(_iodef)
IO__STOP_ANALYSIS = _iodef.IO__STOP_ANALYSIS

_iodef.IO__UNBIND_swigconstant(_iodef)
IO__UNBIND = _iodef.IO__UNBIND

_iodef.IO__RETCENTER_swigconstant(_iodef)
IO__RETCENTER = _iodef.IO__RETCENTER

_iodef.IO__QSTOP_swigconstant(_iodef)
IO__QSTOP = _iodef.IO__QSTOP

_iodef.IO__START_MONITOR_swigconstant(_iodef)
IO__START_MONITOR = _iodef.IO__START_MONITOR

_iodef.IO__CREDISK_swigconstant(_iodef)
IO__CREDISK = _iodef.IO__CREDISK

_iodef.IO__LOCAL_DRAIN_swigconstant(_iodef)
IO__LOCAL_DRAIN = _iodef.IO__LOCAL_DRAIN

_iodef.IO__PACKACK_swigconstant(_iodef)
IO__PACKACK = _iodef.IO__PACKACK

_iodef.IO__STOP_MONITOR_swigconstant(_iodef)
IO__STOP_MONITOR = _iodef.IO__STOP_MONITOR

_iodef.IO__SEARCH_swigconstant(_iodef)
IO__SEARCH = _iodef.IO__SEARCH

_iodef.IO__SPACERECORD_swigconstant(_iodef)
IO__SPACERECORD = _iodef.IO__SPACERECORD

_iodef.IO__READRCT_swigconstant(_iodef)
IO__READRCT = _iodef.IO__READRCT

_iodef.IO__REMDISK_swigconstant(_iodef)
IO__REMDISK = _iodef.IO__REMDISK

_iodef.IO__WRITECHECK_swigconstant(_iodef)
IO__WRITECHECK = _iodef.IO__WRITECHECK

_iodef.IO__EXPORT_swigconstant(_iodef)
IO__EXPORT = _iodef.IO__EXPORT

_iodef.IO__WRITEPBLK_swigconstant(_iodef)
IO__WRITEPBLK = _iodef.IO__WRITEPBLK

_iodef.IO__READPBLK_swigconstant(_iodef)
IO__READPBLK = _iodef.IO__READPBLK

_iodef.IO__WRITEHEAD_swigconstant(_iodef)
IO__WRITEHEAD = _iodef.IO__WRITEHEAD

_iodef.IO__RDSTATS_swigconstant(_iodef)
IO__RDSTATS = _iodef.IO__RDSTATS

_iodef.IO__CRESHAD_swigconstant(_iodef)
IO__CRESHAD = _iodef.IO__CRESHAD

_iodef.IO__READHEAD_swigconstant(_iodef)
IO__READHEAD = _iodef.IO__READHEAD

_iodef.IO__ADDSHAD_swigconstant(_iodef)
IO__ADDSHAD = _iodef.IO__ADDSHAD

_iodef.IO__WRITETRACKD_swigconstant(_iodef)
IO__WRITETRACKD = _iodef.IO__WRITETRACKD

_iodef.IO__COPYSHAD_swigconstant(_iodef)
IO__COPYSHAD = _iodef.IO__COPYSHAD

_iodef.IO__READTRACKD_swigconstant(_iodef)
IO__READTRACKD = _iodef.IO__READTRACKD

_iodef.IO__REMSHAD_swigconstant(_iodef)
IO__REMSHAD = _iodef.IO__REMSHAD

_iodef.IO__AVAILABLE_swigconstant(_iodef)
IO__AVAILABLE = _iodef.IO__AVAILABLE

_iodef.IO__SETPRFPATH_swigconstant(_iodef)
IO__SETPRFPATH = _iodef.IO__SETPRFPATH

_iodef.IO__DISPLAY_swigconstant(_iodef)
IO__DISPLAY = _iodef.IO__DISPLAY

_iodef.IO__REMSHADMBR_swigconstant(_iodef)
IO__REMSHADMBR = _iodef.IO__REMSHADMBR

_iodef.IO__DSE_swigconstant(_iodef)
IO__DSE = _iodef.IO__DSE

_iodef.IO__REREADN_swigconstant(_iodef)
IO__REREADN = _iodef.IO__REREADN

_iodef.IO__DISK_COPY_DATA_swigconstant(_iodef)
IO__DISK_COPY_DATA = _iodef.IO__DISK_COPY_DATA

_iodef.IO__MOUNTSHAD_swigconstant(_iodef)
IO__MOUNTSHAD = _iodef.IO__MOUNTSHAD

_iodef.IO__REREADP_swigconstant(_iodef)
IO__REREADP = _iodef.IO__REREADP

_iodef.IO__WHM_swigconstant(_iodef)
IO__WHM = _iodef.IO__WHM

_iodef.IO__AS_SETCHAR_swigconstant(_iodef)
IO__AS_SETCHAR = _iodef.IO__AS_SETCHAR

_iodef.IO__WRITERET_swigconstant(_iodef)
IO__WRITERET = _iodef.IO__WRITERET

_iodef.IO__WRITECHECKH_swigconstant(_iodef)
IO__WRITECHECKH = _iodef.IO__WRITECHECKH

_iodef.IO__AS_SENSECHAR_swigconstant(_iodef)
IO__AS_SENSECHAR = _iodef.IO__AS_SENSECHAR

_iodef.IO__ADDSHADMBR_swigconstant(_iodef)
IO__ADDSHADMBR = _iodef.IO__ADDSHADMBR

_iodef.IO__READPRESET_swigconstant(_iodef)
IO__READPRESET = _iodef.IO__READPRESET

_iodef.IO__STARTSPNDL_swigconstant(_iodef)
IO__STARTSPNDL = _iodef.IO__STARTSPNDL

_iodef.IO__SETCHAR_swigconstant(_iodef)
IO__SETCHAR = _iodef.IO__SETCHAR

_iodef.IO__SENSECHAR_swigconstant(_iodef)
IO__SENSECHAR = _iodef.IO__SENSECHAR

_iodef.IO__WRITEMARK_swigconstant(_iodef)
IO__WRITEMARK = _iodef.IO__WRITEMARK

_iodef.IO__COPYMEM_swigconstant(_iodef)
IO__COPYMEM = _iodef.IO__COPYMEM

_iodef.IO__PSXSETCHAR_swigconstant(_iodef)
IO__PSXSETCHAR = _iodef.IO__PSXSETCHAR

_iodef.IO__WRTTMKR_swigconstant(_iodef)
IO__WRTTMKR = _iodef.IO__WRTTMKR

_iodef.IO__DIAGNOSE_swigconstant(_iodef)
IO__DIAGNOSE = _iodef.IO__DIAGNOSE

_iodef.IO__SHADMV_swigconstant(_iodef)
IO__SHADMV = _iodef.IO__SHADMV

_iodef.IO__PSXSENSECHAR_swigconstant(_iodef)
IO__PSXSENSECHAR = _iodef.IO__PSXSENSECHAR

_iodef.IO__FORMAT_swigconstant(_iodef)
IO__FORMAT = _iodef.IO__FORMAT

_iodef.IO__CLEAN_swigconstant(_iodef)
IO__CLEAN = _iodef.IO__CLEAN

_iodef.IO__UPSHAD_swigconstant(_iodef)
IO__UPSHAD = _iodef.IO__UPSHAD

_iodef.IO__PHYSICAL_swigconstant(_iodef)
IO__PHYSICAL = _iodef.IO__PHYSICAL

_iodef.IO__WRITELBLK_swigconstant(_iodef)
IO__WRITELBLK = _iodef.IO__WRITELBLK

_iodef.IO__READLBLK_swigconstant(_iodef)
IO__READLBLK = _iodef.IO__READLBLK

_iodef.IO__REWINDOFF_swigconstant(_iodef)
IO__REWINDOFF = _iodef.IO__REWINDOFF

_iodef.IO__READRCTL_swigconstant(_iodef)
IO__READRCTL = _iodef.IO__READRCTL

_iodef.IO__SETMODE_swigconstant(_iodef)
IO__SETMODE = _iodef.IO__SETMODE

_iodef.IO__REWIND_swigconstant(_iodef)
IO__REWIND = _iodef.IO__REWIND

_iodef.IO__SKIPFILE_swigconstant(_iodef)
IO__SKIPFILE = _iodef.IO__SKIPFILE

_iodef.IO__PSXSETMODE_swigconstant(_iodef)
IO__PSXSETMODE = _iodef.IO__PSXSETMODE

_iodef.IO__SKIPRECORD_swigconstant(_iodef)
IO__SKIPRECORD = _iodef.IO__SKIPRECORD

_iodef.IO__PSXSENSEMODE_swigconstant(_iodef)
IO__PSXSENSEMODE = _iodef.IO__PSXSENSEMODE

_iodef.IO__SENSEMODE_swigconstant(_iodef)
IO__SENSEMODE = _iodef.IO__SENSEMODE

_iodef.IO__WRITEOF_swigconstant(_iodef)
IO__WRITEOF = _iodef.IO__WRITEOF

_iodef.IO__TTY_PORT_BUFIO_swigconstant(_iodef)
IO__TTY_PORT_BUFIO = _iodef.IO__TTY_PORT_BUFIO

_iodef.IO__TTY_PORT_swigconstant(_iodef)
IO__TTY_PORT = _iodef.IO__TTY_PORT

_iodef.IO__FREECAP_swigconstant(_iodef)
IO__FREECAP = _iodef.IO__FREECAP

_iodef.IO__FLUSH_swigconstant(_iodef)
IO__FLUSH = _iodef.IO__FLUSH

_iodef.IO__AS_SETMODE_swigconstant(_iodef)
IO__AS_SETMODE = _iodef.IO__AS_SETMODE

_iodef.IO__READLCHUNK_swigconstant(_iodef)
IO__READLCHUNK = _iodef.IO__READLCHUNK

_iodef.IO__AS_SENSEMODE_swigconstant(_iodef)
IO__AS_SENSEMODE = _iodef.IO__AS_SENSEMODE

_iodef.IO__WRITELCHUNK_swigconstant(_iodef)
IO__WRITELCHUNK = _iodef.IO__WRITELCHUNK

_iodef.IO__LOGICAL_swigconstant(_iodef)
IO__LOGICAL = _iodef.IO__LOGICAL

_iodef.IO__WRITEVBLK_swigconstant(_iodef)
IO__WRITEVBLK = _iodef.IO__WRITEVBLK

_iodef.IO__READVBLK_swigconstant(_iodef)
IO__READVBLK = _iodef.IO__READVBLK

_iodef.IO__ACCESS_swigconstant(_iodef)
IO__ACCESS = _iodef.IO__ACCESS

_iodef.IO__PSXWRITEVBLK_swigconstant(_iodef)
IO__PSXWRITEVBLK = _iodef.IO__PSXWRITEVBLK

_iodef.IO__CREATE_swigconstant(_iodef)
IO__CREATE = _iodef.IO__CREATE

_iodef.IO__DEACCESS_swigconstant(_iodef)
IO__DEACCESS = _iodef.IO__DEACCESS

_iodef.IO__PSXREADVBLK_swigconstant(_iodef)
IO__PSXREADVBLK = _iodef.IO__PSXREADVBLK

_iodef.IO__DELETE_swigconstant(_iodef)
IO__DELETE = _iodef.IO__DELETE

_iodef.IO__MODIFY_swigconstant(_iodef)
IO__MODIFY = _iodef.IO__MODIFY

_iodef.IO__NETCONTROL_swigconstant(_iodef)
IO__NETCONTROL = _iodef.IO__NETCONTROL

_iodef.IO__READPROMPT_swigconstant(_iodef)
IO__READPROMPT = _iodef.IO__READPROMPT

_iodef.IO__SETCLOCK_swigconstant(_iodef)
IO__SETCLOCK = _iodef.IO__SETCLOCK

_iodef.IO__AUDIO_swigconstant(_iodef)
IO__AUDIO = _iodef.IO__AUDIO

_iodef.IO__ACPCONTROL_swigconstant(_iodef)
IO__ACPCONTROL = _iodef.IO__ACPCONTROL

_iodef.IO__STARTDATA_swigconstant(_iodef)
IO__STARTDATA = _iodef.IO__STARTDATA

_iodef.IO__IOCTLV_swigconstant(_iodef)
IO__IOCTLV = _iodef.IO__IOCTLV

_iodef.IO__MANAGE_swigconstant(_iodef)
IO__MANAGE = _iodef.IO__MANAGE

_iodef.IO__MOUNT_swigconstant(_iodef)
IO__MOUNT = _iodef.IO__MOUNT

_iodef.IO__TTYREADALL_swigconstant(_iodef)
IO__TTYREADALL = _iodef.IO__TTYREADALL

_iodef.IO__DISMOUNT_swigconstant(_iodef)
IO__DISMOUNT = _iodef.IO__DISMOUNT

_iodef.IO__TTYREADPALL_swigconstant(_iodef)
IO__TTYREADPALL = _iodef.IO__TTYREADPALL

_iodef.IO__USBATTR_swigconstant(_iodef)
IO__USBATTR = _iodef.IO__USBATTR

_iodef.IO__CONINTREAD_swigconstant(_iodef)
IO__CONINTREAD = _iodef.IO__CONINTREAD

_iodef.IO__CONINTWRITE_swigconstant(_iodef)
IO__CONINTWRITE = _iodef.IO__CONINTWRITE

_iodef.IO__READDIR_swigconstant(_iodef)
IO__READDIR = _iodef.IO__READDIR

_iodef.IO__VIRTUAL_swigconstant(_iodef)
IO__VIRTUAL = _iodef.IO__VIRTUAL

_iodef.IO_M_FCODE_swigconstant(_iodef)
IO_M_FCODE = _iodef.IO_M_FCODE

_iodef.IO_M_FMODIFIERS_swigconstant(_iodef)
IO_M_FMODIFIERS = _iodef.IO_M_FMODIFIERS

_iodef.IO_M_INHERLOG_swigconstant(_iodef)
IO_M_INHERLOG = _iodef.IO_M_INHERLOG

_iodef.IO_M_ERASE_swigconstant(_iodef)
IO_M_ERASE = _iodef.IO_M_ERASE

_iodef.IO_M_EXFUNC_swigconstant(_iodef)
IO_M_EXFUNC = _iodef.IO_M_EXFUNC

_iodef.IO_M_DATACHECK_swigconstant(_iodef)
IO_M_DATACHECK = _iodef.IO_M_DATACHECK

_iodef.IO_M_INHRETRY_swigconstant(_iodef)
IO_M_INHRETRY = _iodef.IO_M_INHRETRY

_iodef.IO_M_SYNCSTS_swigconstant(_iodef)
IO_M_SYNCSTS = _iodef.IO_M_SYNCSTS

_iodef.IO_M_NOVCACHE_swigconstant(_iodef)
IO_M_NOVCACHE = _iodef.IO_M_NOVCACHE

_iodef.IO_M_BUFOBJ_swigconstant(_iodef)
IO_M_BUFOBJ = _iodef.IO_M_BUFOBJ

_iodef.IO_M_TRUSTED_swigconstant(_iodef)
IO_M_TRUSTED = _iodef.IO_M_TRUSTED

_iodef.IO_M_FILE_FLUSH_swigconstant(_iodef)
IO_M_FILE_FLUSH = _iodef.IO_M_FILE_FLUSH

_iodef.IO_M_BARRIER_swigconstant(_iodef)
IO_M_BARRIER = _iodef.IO_M_BARRIER

_iodef.IO_M_RAH_HINT_swigconstant(_iodef)
IO_M_RAH_HINT = _iodef.IO_M_RAH_HINT

_iodef.IO_M_INHSEEK_swigconstant(_iodef)
IO_M_INHSEEK = _iodef.IO_M_INHSEEK

_iodef.IO_M_READ_TO_EOF_swigconstant(_iodef)
IO_M_READ_TO_EOF = _iodef.IO_M_READ_TO_EOF

_iodef.IO_M_REVERSE_swigconstant(_iodef)
IO_M_REVERSE = _iodef.IO_M_REVERSE

_iodef.IO_M_NOWAIT_swigconstant(_iodef)
IO_M_NOWAIT = _iodef.IO_M_NOWAIT

_iodef.IO_M_INHEXTGAP_swigconstant(_iodef)
IO_M_INHEXTGAP = _iodef.IO_M_INHEXTGAP

_iodef.IO_M_RETENSION_swigconstant(_iodef)
IO_M_RETENSION = _iodef.IO_M_RETENSION

_iodef.IO_M_ALLOWFAST_swigconstant(_iodef)
IO_M_ALLOWFAST = _iodef.IO_M_ALLOWFAST

_iodef.IO_M_MT3_DENSITY_swigconstant(_iodef)
IO_M_MT3_DENSITY = _iodef.IO_M_MT3_DENSITY

_iodef.IO_M_MSCPMODIFS_swigconstant(_iodef)
IO_M_MSCPMODIFS = _iodef.IO_M_MSCPMODIFS

_iodef.IO_M_SHADOW_swigconstant(_iodef)
IO_M_SHADOW = _iodef.IO_M_SHADOW

_iodef.IO_M_LOCATE_swigconstant(_iodef)
IO_M_LOCATE = _iodef.IO_M_LOCATE

_iodef.IO_M_MSCP_FORMAT_swigconstant(_iodef)
IO_M_MSCP_FORMAT = _iodef.IO_M_MSCP_FORMAT

_iodef.IO_M_ALLHOSTS_swigconstant(_iodef)
IO_M_ALLHOSTS = _iodef.IO_M_ALLHOSTS

_iodef.IO_M_DISSOLVE_swigconstant(_iodef)
IO_M_DISSOLVE = _iodef.IO_M_DISSOLVE

_iodef.IO_M_NOCLEANUP_swigconstant(_iodef)
IO_M_NOCLEANUP = _iodef.IO_M_NOCLEANUP

_iodef.IO_M_SPINDOWN_swigconstant(_iodef)
IO_M_SPINDOWN = _iodef.IO_M_SPINDOWN

_iodef.IO_M_EST_COM_PATH_swigconstant(_iodef)
IO_M_EST_COM_PATH = _iodef.IO_M_EST_COM_PATH

_iodef.IO_M_LCL_SRC_UNIT_swigconstant(_iodef)
IO_M_LCL_SRC_UNIT = _iodef.IO_M_LCL_SRC_UNIT

_iodef.IO_M_RTN_COM_PATH_swigconstant(_iodef)
IO_M_RTN_COM_PATH = _iodef.IO_M_RTN_COM_PATH

_iodef.IO_M_DEALC_ALL_swigconstant(_iodef)
IO_M_DEALC_ALL = _iodef.IO_M_DEALC_ALL

_iodef.IO_M_DEALC_HRN_swigconstant(_iodef)
IO_M_DEALC_HRN = _iodef.IO_M_DEALC_HRN

_iodef.IO_M_DEALC_ENTLOC_swigconstant(_iodef)
IO_M_DEALC_ENTLOC = _iodef.IO_M_DEALC_ENTLOC

_iodef.IO_M_DECR_AFC_swigconstant(_iodef)
IO_M_DECR_AFC = _iodef.IO_M_DECR_AFC

_iodef.IO_M_READ_ALL_swigconstant(_iodef)
IO_M_READ_ALL = _iodef.IO_M_READ_ALL

_iodef.IO_M_READ_HRN_swigconstant(_iodef)
IO_M_READ_HRN = _iodef.IO_M_READ_HRN

_iodef.IO_M_BREAK_CONN_swigconstant(_iodef)
IO_M_BREAK_CONN = _iodef.IO_M_BREAK_CONN

_iodef.IO_M_STEPOVER_swigconstant(_iodef)
IO_M_STEPOVER = _iodef.IO_M_STEPOVER

_iodef.IO_M_COPYOP_swigconstant(_iodef)
IO_M_COPYOP = _iodef.IO_M_COPYOP

_iodef.IO_M_EXISTS_swigconstant(_iodef)
IO_M_EXISTS = _iodef.IO_M_EXISTS

_iodef.IO_M_CBS_swigconstant(_iodef)
IO_M_CBS = _iodef.IO_M_CBS

_iodef.IO_M_BOOTING_swigconstant(_iodef)
IO_M_BOOTING = _iodef.IO_M_BOOTING

_iodef.IO_M_REQ_MINICOPY_swigconstant(_iodef)
IO_M_REQ_MINICOPY = _iodef.IO_M_REQ_MINICOPY

_iodef.IO_M_OPT_MINICOPY_swigconstant(_iodef)
IO_M_OPT_MINICOPY = _iodef.IO_M_OPT_MINICOPY

_iodef.IO_M_NOMINICOPY_swigconstant(_iodef)
IO_M_NOMINICOPY = _iodef.IO_M_NOMINICOPY

_iodef.IO_M_EXPECT_MOUNT_DONE_swigconstant(_iodef)
IO_M_EXPECT_MOUNT_DONE = _iodef.IO_M_EXPECT_MOUNT_DONE

_iodef.IO_M_VUEX_FC_swigconstant(_iodef)
IO_M_VUEX_FC = _iodef.IO_M_VUEX_FC

_iodef.IO_M_WRITE_SCB_swigconstant(_iodef)
IO_M_WRITE_SCB = _iodef.IO_M_WRITE_SCB

_iodef.IO_M_UPD_SCBLBN_swigconstant(_iodef)
IO_M_UPD_SCBLBN = _iodef.IO_M_UPD_SCBLBN

_iodef.IO_M_FORCEPATH_swigconstant(_iodef)
IO_M_FORCEPATH = _iodef.IO_M_FORCEPATH

_iodef.IO_M_PREFERRED_CPU_swigconstant(_iodef)
IO_M_PREFERRED_CPU = _iodef.IO_M_PREFERRED_CPU

_iodef.IO_M_SYS_ASSIGNABLE_swigconstant(_iodef)
IO_M_SYS_ASSIGNABLE = _iodef.IO_M_SYS_ASSIGNABLE

_iodef.IO_M_COMMOD_swigconstant(_iodef)
IO_M_COMMOD = _iodef.IO_M_COMMOD

_iodef.IO_M_MOVETRACKD_swigconstant(_iodef)
IO_M_MOVETRACKD = _iodef.IO_M_MOVETRACKD

_iodef.IO_M_DIAGNOSTIC_swigconstant(_iodef)
IO_M_DIAGNOSTIC = _iodef.IO_M_DIAGNOSTIC

_iodef.IO_M_SKPSECINH_swigconstant(_iodef)
IO_M_SKPSECINH = _iodef.IO_M_SKPSECINH

_iodef.IO_M_DELDATA_swigconstant(_iodef)
IO_M_DELDATA = _iodef.IO_M_DELDATA

_iodef.IO_M_NOMRSP_swigconstant(_iodef)
IO_M_NOMRSP = _iodef.IO_M_NOMRSP

_iodef.IO_M_SWAP_swigconstant(_iodef)
IO_M_SWAP = _iodef.IO_M_SWAP

_iodef.IO_M_OPPOSITE_swigconstant(_iodef)
IO_M_OPPOSITE = _iodef.IO_M_OPPOSITE

_iodef.IO_M_CLSEREXCP_swigconstant(_iodef)
IO_M_CLSEREXCP = _iodef.IO_M_CLSEREXCP

_iodef.IO_M_CHUNKDIAG_swigconstant(_iodef)
IO_M_CHUNKDIAG = _iodef.IO_M_CHUNKDIAG

_iodef.IO_M_TBC_swigconstant(_iodef)
IO_M_TBC = _iodef.IO_M_TBC

_iodef.IO_M_ENAREP_swigconstant(_iodef)
IO_M_ENAREP = _iodef.IO_M_ENAREP

_iodef.IO_M_ACCESS_swigconstant(_iodef)
IO_M_ACCESS = _iodef.IO_M_ACCESS

_iodef.IO_M_CREATE_swigconstant(_iodef)
IO_M_CREATE = _iodef.IO_M_CREATE

_iodef.IO_M_DELETE_swigconstant(_iodef)
IO_M_DELETE = _iodef.IO_M_DELETE

_iodef.IO_M_MOUNT_swigconstant(_iodef)
IO_M_MOUNT = _iodef.IO_M_MOUNT

_iodef.IO_M_DMOUNT_swigconstant(_iodef)
IO_M_DMOUNT = _iodef.IO_M_DMOUNT

_iodef.IO_M_REMOUNT_swigconstant(_iodef)
IO_M_REMOUNT = _iodef.IO_M_REMOUNT

_iodef.IO_M_MOVEFILE_swigconstant(_iodef)
IO_M_MOVEFILE = _iodef.IO_M_MOVEFILE

_iodef.IO_M_RWSHELVED_swigconstant(_iodef)
IO_M_RWSHELVED = _iodef.IO_M_RWSHELVED

_iodef.IO_M_SETDIR_swigconstant(_iodef)
IO_M_SETDIR = _iodef.IO_M_SETDIR

_iodef.IO_M_BINARY_swigconstant(_iodef)
IO_M_BINARY = _iodef.IO_M_BINARY

_iodef.IO_M_PACKED_swigconstant(_iodef)
IO_M_PACKED = _iodef.IO_M_PACKED

_iodef.IO_M_NOW_swigconstant(_iodef)
IO_M_NOW = _iodef.IO_M_NOW

_iodef.IO_M_STREAM_swigconstant(_iodef)
IO_M_STREAM = _iodef.IO_M_STREAM

_iodef.IO_M_READERCHECK_swigconstant(_iodef)
IO_M_READERCHECK = _iodef.IO_M_READERCHECK

_iodef.IO_M_WRITERCHECK_swigconstant(_iodef)
IO_M_WRITERCHECK = _iodef.IO_M_WRITERCHECK

_iodef.IO_M_NORSWAIT_swigconstant(_iodef)
IO_M_NORSWAIT = _iodef.IO_M_NORSWAIT

_iodef.IO_M_MB_ROOM_NOTIFY_swigconstant(_iodef)
IO_M_MB_ROOM_NOTIFY = _iodef.IO_M_MB_ROOM_NOTIFY

_iodef.IO_M_READATTN_swigconstant(_iodef)
IO_M_READATTN = _iodef.IO_M_READATTN

_iodef.IO_M_WRTATTN_swigconstant(_iodef)
IO_M_WRTATTN = _iodef.IO_M_WRTATTN

_iodef.IO_M_SETPROT_swigconstant(_iodef)
IO_M_SETPROT = _iodef.IO_M_SETPROT

_iodef.IO_M_READERWAIT_swigconstant(_iodef)
IO_M_READERWAIT = _iodef.IO_M_READERWAIT

_iodef.IO_M_WRITERWAIT_swigconstant(_iodef)
IO_M_WRITERWAIT = _iodef.IO_M_WRITERWAIT

_iodef.IO_M_NOECHO_swigconstant(_iodef)
IO_M_NOECHO = _iodef.IO_M_NOECHO

_iodef.IO_M_TIMED_swigconstant(_iodef)
IO_M_TIMED = _iodef.IO_M_TIMED

_iodef.IO_M_CVTLOW_swigconstant(_iodef)
IO_M_CVTLOW = _iodef.IO_M_CVTLOW

_iodef.IO_M_NOFILTR_swigconstant(_iodef)
IO_M_NOFILTR = _iodef.IO_M_NOFILTR

_iodef.IO_M_DSABLMBX_swigconstant(_iodef)
IO_M_DSABLMBX = _iodef.IO_M_DSABLMBX

_iodef.IO_M_PURGE_swigconstant(_iodef)
IO_M_PURGE = _iodef.IO_M_PURGE

_iodef.IO_M_TRMNOECHO_swigconstant(_iodef)
IO_M_TRMNOECHO = _iodef.IO_M_TRMNOECHO

_iodef.IO_M_REFRESH_swigconstant(_iodef)
IO_M_REFRESH = _iodef.IO_M_REFRESH

_iodef.IO_M_ESCAPE_swigconstant(_iodef)
IO_M_ESCAPE = _iodef.IO_M_ESCAPE

_iodef.IO_M_EXTEND_swigconstant(_iodef)
IO_M_EXTEND = _iodef.IO_M_EXTEND

_iodef.IO_M_CANCTRLO_swigconstant(_iodef)
IO_M_CANCTRLO = _iodef.IO_M_CANCTRLO

_iodef.IO_M_ENABLMBX_swigconstant(_iodef)
IO_M_ENABLMBX = _iodef.IO_M_ENABLMBX

_iodef.IO_M_NOFORMAT_swigconstant(_iodef)
IO_M_NOFORMAT = _iodef.IO_M_NOFORMAT

_iodef.IO_M_BREAKTHRU_swigconstant(_iodef)
IO_M_BREAKTHRU = _iodef.IO_M_BREAKTHRU

_iodef.IO_M_NEWLINE_swigconstant(_iodef)
IO_M_NEWLINE = _iodef.IO_M_NEWLINE

_iodef.IO_M_TYPEAHDCNT_swigconstant(_iodef)
IO_M_TYPEAHDCNT = _iodef.IO_M_TYPEAHDCNT

_iodef.IO_M_MAINT_swigconstant(_iodef)
IO_M_MAINT = _iodef.IO_M_MAINT

_iodef.IO_M_CTRLYAST_swigconstant(_iodef)
IO_M_CTRLYAST = _iodef.IO_M_CTRLYAST

_iodef.IO_M_CTRLCAST_swigconstant(_iodef)
IO_M_CTRLCAST = _iodef.IO_M_CTRLCAST

_iodef.IO_M_HANGUP_swigconstant(_iodef)
IO_M_HANGUP = _iodef.IO_M_HANGUP

_iodef.IO_M_OUTBAND_swigconstant(_iodef)
IO_M_OUTBAND = _iodef.IO_M_OUTBAND

_iodef.IO_M_TT_CONNECT_swigconstant(_iodef)
IO_M_TT_CONNECT = _iodef.IO_M_TT_CONNECT

_iodef.IO_M_TT_DISCON_swigconstant(_iodef)
IO_M_TT_DISCON = _iodef.IO_M_TT_DISCON

_iodef.IO_M_TT_PROCESS_swigconstant(_iodef)
IO_M_TT_PROCESS = _iodef.IO_M_TT_PROCESS

_iodef.IO_M_BRDCST_swigconstant(_iodef)
IO_M_BRDCST = _iodef.IO_M_BRDCST

_iodef.IO_M_LOOP_swigconstant(_iodef)
IO_M_LOOP = _iodef.IO_M_LOOP

_iodef.IO_M_UNLOOP_swigconstant(_iodef)
IO_M_UNLOOP = _iodef.IO_M_UNLOOP

_iodef.IO_M_LINE_OFF_swigconstant(_iodef)
IO_M_LINE_OFF = _iodef.IO_M_LINE_OFF

_iodef.IO_M_SET_MODEM_swigconstant(_iodef)
IO_M_SET_MODEM = _iodef.IO_M_SET_MODEM

_iodef.IO_M_LINE_ON_swigconstant(_iodef)
IO_M_LINE_ON = _iodef.IO_M_LINE_ON

_iodef.IO_M_LOOP_EXT_swigconstant(_iodef)
IO_M_LOOP_EXT = _iodef.IO_M_LOOP_EXT

_iodef.IO_M_AUTXOF_ENA_swigconstant(_iodef)
IO_M_AUTXOF_ENA = _iodef.IO_M_AUTXOF_ENA

_iodef.IO_M_AUTXOF_DIS_swigconstant(_iodef)
IO_M_AUTXOF_DIS = _iodef.IO_M_AUTXOF_DIS

_iodef.IO_M_INCLUDE_swigconstant(_iodef)
IO_M_INCLUDE = _iodef.IO_M_INCLUDE

_iodef.IO_M_TT_ABORT_swigconstant(_iodef)
IO_M_TT_ABORT = _iodef.IO_M_TT_ABORT

_iodef.IO_M_POSIXINIT_swigconstant(_iodef)
IO_M_POSIXINIT = _iodef.IO_M_POSIXINIT

_iodef.IO_M_POSIXFLOW_swigconstant(_iodef)
IO_M_POSIXFLOW = _iodef.IO_M_POSIXFLOW

_iodef.IO_M_SET_POSIX_swigconstant(_iodef)
IO_M_SET_POSIX = _iodef.IO_M_SET_POSIX

_iodef.IO_M_CLEAR_POSIX_swigconstant(_iodef)
IO_M_CLEAR_POSIX = _iodef.IO_M_CLEAR_POSIX

_iodef.IO_M_SET_TERMIOS_swigconstant(_iodef)
IO_M_SET_TERMIOS = _iodef.IO_M_SET_TERMIOS

_iodef.IO_M_SET_PTC_swigconstant(_iodef)
IO_M_SET_PTC = _iodef.IO_M_SET_PTC

_iodef.IO_M_CLEAR_PTC_swigconstant(_iodef)
IO_M_CLEAR_PTC = _iodef.IO_M_CLEAR_PTC

_iodef.IO_M_FLUSH_TAB_swigconstant(_iodef)
IO_M_FLUSH_TAB = _iodef.IO_M_FLUSH_TAB

_iodef.IO_M_FLUSH_OUTPUT_swigconstant(_iodef)
IO_M_FLUSH_OUTPUT = _iodef.IO_M_FLUSH_OUTPUT

_iodef.IO_M_UPDATE_PTC_swigconstant(_iodef)
IO_M_UPDATE_PTC = _iodef.IO_M_UPDATE_PTC

_iodef.IO_M_OUT_XOFF_swigconstant(_iodef)
IO_M_OUT_XOFF = _iodef.IO_M_OUT_XOFF

_iodef.IO_M_OUT_XON_swigconstant(_iodef)
IO_M_OUT_XON = _iodef.IO_M_OUT_XON

_iodef.IO_M_IN_XOFF_swigconstant(_iodef)
IO_M_IN_XOFF = _iodef.IO_M_IN_XOFF

_iodef.IO_M_IN_XON_swigconstant(_iodef)
IO_M_IN_XON = _iodef.IO_M_IN_XON

_iodef.IO_M_O_NONBLOCK_swigconstant(_iodef)
IO_M_O_NONBLOCK = _iodef.IO_M_O_NONBLOCK

_iodef.IO_M_INTERRUPT_swigconstant(_iodef)
IO_M_INTERRUPT = _iodef.IO_M_INTERRUPT

_iodef.IO_M_MULTIPLE_swigconstant(_iodef)
IO_M_MULTIPLE = _iodef.IO_M_MULTIPLE

_iodef.IO_M_LOCKBUF_swigconstant(_iodef)
IO_M_LOCKBUF = _iodef.IO_M_LOCKBUF

_iodef.IO_M_NOBLOCK_swigconstant(_iodef)
IO_M_NOBLOCK = _iodef.IO_M_NOBLOCK

_iodef.IO_M_ABORT_swigconstant(_iodef)
IO_M_ABORT = _iodef.IO_M_ABORT

_iodef.IO_M_SYNCH_swigconstant(_iodef)
IO_M_SYNCH = _iodef.IO_M_SYNCH

_iodef.IO_M_RESPONSE_swigconstant(_iodef)
IO_M_RESPONSE = _iodef.IO_M_RESPONSE

_iodef.IO_M_STARTUP_swigconstant(_iodef)
IO_M_STARTUP = _iodef.IO_M_STARTUP

_iodef.IO_M_SHUTDOWN_swigconstant(_iodef)
IO_M_SHUTDOWN = _iodef.IO_M_SHUTDOWN

_iodef.IO_M_ATTNAST_swigconstant(_iodef)
IO_M_ATTNAST = _iodef.IO_M_ATTNAST

_iodef.IO_M_CTRL_swigconstant(_iodef)
IO_M_CTRL = _iodef.IO_M_CTRL

_iodef.IO_M_SET_MAC_swigconstant(_iodef)
IO_M_SET_MAC = _iodef.IO_M_SET_MAC

_iodef.IO_M_UPDATE_MAP_swigconstant(_iodef)
IO_M_UPDATE_MAP = _iodef.IO_M_UPDATE_MAP

_iodef.IO_M_ROUTE_swigconstant(_iodef)
IO_M_ROUTE = _iodef.IO_M_ROUTE

_iodef.IO_M_RD_MEM_swigconstant(_iodef)
IO_M_RD_MEM = _iodef.IO_M_RD_MEM

_iodef.IO_M_RD_MODEM_swigconstant(_iodef)
IO_M_RD_MODEM = _iodef.IO_M_RD_MODEM

_iodef.IO_M_RD_COUNT_swigconstant(_iodef)
IO_M_RD_COUNT = _iodef.IO_M_RD_COUNT

_iodef.IO_M_CLR_COUNT_swigconstant(_iodef)
IO_M_CLR_COUNT = _iodef.IO_M_CLR_COUNT

_iodef.IO_M_SENSE_MAC_swigconstant(_iodef)
IO_M_SENSE_MAC = _iodef.IO_M_SENSE_MAC

_iodef.IO_M_SHOW_MAP_swigconstant(_iodef)
IO_M_SHOW_MAP = _iodef.IO_M_SHOW_MAP

_iodef.IO_M_SHOW_ROUTE_swigconstant(_iodef)
IO_M_SHOW_ROUTE = _iodef.IO_M_SHOW_ROUTE

_iodef.IO_K_SRRUNOUT_swigconstant(_iodef)
IO_K_SRRUNOUT = _iodef.IO_K_SRRUNOUT

_iodef.IO_K_PTPBSC_swigconstant(_iodef)
IO_K_PTPBSC = _iodef.IO_K_PTPBSC

_iodef.IO_K_LOOPTEST_swigconstant(_iodef)
IO_K_LOOPTEST = _iodef.IO_K_LOOPTEST

_iodef.IO_M_MORE_swigconstant(_iodef)
IO_M_MORE = _iodef.IO_M_MORE

_iodef.IO_M_QUALIFIED_swigconstant(_iodef)
IO_M_QUALIFIED = _iodef.IO_M_QUALIFIED

_iodef.IO_M_REDIRECT_swigconstant(_iodef)
IO_M_REDIRECT = _iodef.IO_M_REDIRECT

_iodef.IO_M_ACCEPT_swigconstant(_iodef)
IO_M_ACCEPT = _iodef.IO_M_ACCEPT

_iodef.IO_M_SETEVF_swigconstant(_iodef)
IO_M_SETEVF = _iodef.IO_M_SETEVF

_iodef.IO_M_WORD_swigconstant(_iodef)
IO_M_WORD = _iodef.IO_M_WORD

_iodef.IO_M_SETFNCT_swigconstant(_iodef)
IO_M_SETFNCT = _iodef.IO_M_SETFNCT

_iodef.IO_M_DATAPATH_swigconstant(_iodef)
IO_M_DATAPATH = _iodef.IO_M_DATAPATH

_iodef.IO_M_CYCLE_swigconstant(_iodef)
IO_M_CYCLE = _iodef.IO_M_CYCLE

_iodef.IO_M_RESET_swigconstant(_iodef)
IO_M_RESET = _iodef.IO_M_RESET

_iodef.IO_M_SETCUADR_swigconstant(_iodef)
IO_M_SETCUADR = _iodef.IO_M_SETCUADR

_iodef.IO_M_SETBSIZE_swigconstant(_iodef)
IO_M_SETBSIZE = _iodef.IO_M_SETBSIZE

_iodef.IO_M_SETPOOLSZ_swigconstant(_iodef)
IO_M_SETPOOLSZ = _iodef.IO_M_SETPOOLSZ

_iodef.IO_M_SETENQCNT_swigconstant(_iodef)
IO_M_SETENQCNT = _iodef.IO_M_SETENQCNT

_iodef.IO_M_CLEAR_swigconstant(_iodef)
IO_M_CLEAR = _iodef.IO_M_CLEAR

_iodef.IO_M_LPBEXT_swigconstant(_iodef)
IO_M_LPBEXT = _iodef.IO_M_LPBEXT

_iodef.IO_M_LPBINT_swigconstant(_iodef)
IO_M_LPBINT = _iodef.IO_M_LPBINT

_iodef.IO_M_READCSR_swigconstant(_iodef)
IO_M_READCSR = _iodef.IO_M_READCSR

_iodef.IO_M_NOCTSWAIT_swigconstant(_iodef)
IO_M_NOCTSWAIT = _iodef.IO_M_NOCTSWAIT

_iodef.IO_M_SLAVLOOP_swigconstant(_iodef)
IO_M_SLAVLOOP = _iodef.IO_M_SLAVLOOP

_iodef.IO_M_NODSRWAIT_swigconstant(_iodef)
IO_M_NODSRWAIT = _iodef.IO_M_NODSRWAIT

_iodef.IO_M_MAINTLOOP_swigconstant(_iodef)
IO_M_MAINTLOOP = _iodef.IO_M_MAINTLOOP

_iodef.IO_M_LASTBLOCK_swigconstant(_iodef)
IO_M_LASTBLOCK = _iodef.IO_M_LASTBLOCK

_iodef.IO_M_INTCLOCK_swigconstant(_iodef)
IO_M_INTCLOCK = _iodef.IO_M_INTCLOCK

_iodef.IO_M_LT_CONNECT_swigconstant(_iodef)
IO_M_LT_CONNECT = _iodef.IO_M_LT_CONNECT

_iodef.IO_M_LT_DISCON_swigconstant(_iodef)
IO_M_LT_DISCON = _iodef.IO_M_LT_DISCON

_iodef.IO_M_LT_READPORT_swigconstant(_iodef)
IO_M_LT_READPORT = _iodef.IO_M_LT_READPORT

_iodef.IO_M_LT_MAP_PORT_swigconstant(_iodef)
IO_M_LT_MAP_PORT = _iodef.IO_M_LT_MAP_PORT

_iodef.IO_M_LT_RATING_swigconstant(_iodef)
IO_M_LT_RATING = _iodef.IO_M_LT_RATING

_iodef.IO_M_LT_SOL_INFO_swigconstant(_iodef)
IO_M_LT_SOL_INFO = _iodef.IO_M_LT_SOL_INFO

_iodef.IO_M_LT_RCV_INFO_swigconstant(_iodef)
IO_M_LT_RCV_INFO = _iodef.IO_M_LT_RCV_INFO

_iodef.IO_M_LT_SETMODE_swigconstant(_iodef)
IO_M_LT_SETMODE = _iodef.IO_M_LT_SETMODE

_iodef.IO_M_LT_SENSEMODE_swigconstant(_iodef)
IO_M_LT_SENSEMODE = _iodef.IO_M_LT_SENSEMODE

_iodef.IO_M_LT_QUE_CHG_NOTIF_swigconstant(_iodef)
IO_M_LT_QUE_CHG_NOTIF = _iodef.IO_M_LT_QUE_CHG_NOTIF

_iodef.IO_M_LT_MAP_FILLER_swigconstant(_iodef)
IO_M_LT_MAP_FILLER = _iodef.IO_M_LT_MAP_FILLER

_iodef.IO_M_LT_MAP_NODNAM_swigconstant(_iodef)
IO_M_LT_MAP_NODNAM = _iodef.IO_M_LT_MAP_NODNAM

_iodef.IO_M_LT_MAP_PORNAM_swigconstant(_iodef)
IO_M_LT_MAP_PORNAM = _iodef.IO_M_LT_MAP_PORNAM

_iodef.IO_M_LT_MAP_SRVNAM_swigconstant(_iodef)
IO_M_LT_MAP_SRVNAM = _iodef.IO_M_LT_MAP_SRVNAM

_iodef.IO_M_LT_MAP_LNKNAM_swigconstant(_iodef)
IO_M_LT_MAP_LNKNAM = _iodef.IO_M_LT_MAP_LNKNAM

_iodef.IO_M_LT_MAP_NETADR_swigconstant(_iodef)
IO_M_LT_MAP_NETADR = _iodef.IO_M_LT_MAP_NETADR

_iodef.IO_M_FLUSH_swigconstant(_iodef)
IO_M_FLUSH = _iodef.IO_M_FLUSH

_iodef.IO_M_WRITE_BARRIER_swigconstant(_iodef)
IO_M_WRITE_BARRIER = _iodef.IO_M_WRITE_BARRIER

_iodef.IO_M_MKFILL1_swigconstant(_iodef)
IO_M_MKFILL1 = _iodef.IO_M_MKFILL1

_iodef.IO_M_ALLOWFAST_NEVER_swigconstant(_iodef)
IO_M_ALLOWFAST_NEVER = _iodef.IO_M_ALLOWFAST_NEVER

_iodef.IO_M_ALLOWFAST_PER_IO_swigconstant(_iodef)
IO_M_ALLOWFAST_PER_IO = _iodef.IO_M_ALLOWFAST_PER_IO

_iodef.IO_M_ALLOWFAST_ALWAYS_swigconstant(_iodef)
IO_M_ALLOWFAST_ALWAYS = _iodef.IO_M_ALLOWFAST_ALWAYS

_iodef.IO_M_ADD_swigconstant(_iodef)
IO_M_ADD = _iodef.IO_M_ADD

_iodef.IO_M_IDSTRING_swigconstant(_iodef)
IO_M_IDSTRING = _iodef.IO_M_IDSTRING

_iodef.IO_M_SERIALNUM_swigconstant(_iodef)
IO_M_SERIALNUM = _iodef.IO_M_SERIALNUM

_iodef.IO_M_BYPASS_VALID_CHK_swigconstant(_iodef)
IO_M_BYPASS_VALID_CHK = _iodef.IO_M_BYPASS_VALID_CHK

_iodef.IO_S_IODEF_swigconstant(_iodef)
IO_S_IODEF = _iodef.IO_S_IODEF

_iodef.IO_S_FCODE_swigconstant(_iodef)
IO_S_FCODE = _iodef.IO_S_FCODE

_iodef.IO_S_FMODIFIERS_swigconstant(_iodef)
IO_S_FMODIFIERS = _iodef.IO_S_FMODIFIERS
# This file is compatible with both classic and new-style classes.


