# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_kgbdef', [dirname(__file__)])
        except ImportError:
            import _kgbdef
            return _kgbdef
        if fp is not None:
            try:
                _mod = imp.load_module('_kgbdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _kgbdef = swig_import_helper()
    del swig_import_helper
else:
    import _kgbdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_kgbdef.KGB_M_RESOURCE_swigconstant(_kgbdef)
KGB_M_RESOURCE = _kgbdef.KGB_M_RESOURCE

_kgbdef.KGB_M_DYNAMIC_swigconstant(_kgbdef)
KGB_M_DYNAMIC = _kgbdef.KGB_M_DYNAMIC

_kgbdef.KGB_M_NOACCESS_swigconstant(_kgbdef)
KGB_M_NOACCESS = _kgbdef.KGB_M_NOACCESS

_kgbdef.KGB_M_SUBSYSTEM_swigconstant(_kgbdef)
KGB_M_SUBSYSTEM = _kgbdef.KGB_M_SUBSYSTEM

_kgbdef.KGB_M_IMPERSONATE_swigconstant(_kgbdef)
KGB_M_IMPERSONATE = _kgbdef.KGB_M_IMPERSONATE

_kgbdef.KGB_M_HOLDER_HIDDEN_swigconstant(_kgbdef)
KGB_M_HOLDER_HIDDEN = _kgbdef.KGB_M_HOLDER_HIDDEN

_kgbdef.KGB_M_NAME_HIDDEN_swigconstant(_kgbdef)
KGB_M_NAME_HIDDEN = _kgbdef.KGB_M_NAME_HIDDEN

_kgbdef.KGB_K_HOLD_RECORD_swigconstant(_kgbdef)
KGB_K_HOLD_RECORD = _kgbdef.KGB_K_HOLD_RECORD

_kgbdef.KGB_K_IDENT_RECORD_swigconstant(_kgbdef)
KGB_K_IDENT_RECORD = _kgbdef.KGB_K_IDENT_RECORD

_kgbdef.KGB_K_LEVEL1_swigconstant(_kgbdef)
KGB_K_LEVEL1 = _kgbdef.KGB_K_LEVEL1

_kgbdef.KGB_K_MAINT_RECORD_swigconstant(_kgbdef)
KGB_K_MAINT_RECORD = _kgbdef.KGB_K_MAINT_RECORD

_kgbdef.KGB_K_NUMBER_OF_ATTRIBUTES_swigconstant(_kgbdef)
KGB_K_NUMBER_OF_ATTRIBUTES = _kgbdef.KGB_K_NUMBER_OF_ATTRIBUTES

_kgbdef.KGB_S_KGBDEF_swigconstant(_kgbdef)
KGB_S_KGBDEF = _kgbdef.KGB_S_KGBDEF

_kgbdef.KGB_S_HOLDER_swigconstant(_kgbdef)
KGB_S_HOLDER = _kgbdef.KGB_S_HOLDER

_kgbdef.KGB_S_NAME_swigconstant(_kgbdef)
KGB_S_NAME = _kgbdef.KGB_S_NAME

_kgbdef.KGB_S_SYS_ID_swigconstant(_kgbdef)
KGB_S_SYS_ID = _kgbdef.KGB_S_SYS_ID

_kgbdef.KGB_K_BATCH_ID_swigconstant(_kgbdef)
KGB_K_BATCH_ID = _kgbdef.KGB_K_BATCH_ID

_kgbdef.KGB_K_DIALUP_ID_swigconstant(_kgbdef)
KGB_K_DIALUP_ID = _kgbdef.KGB_K_DIALUP_ID

_kgbdef.KGB_K_INTERACTIVE_ID_swigconstant(_kgbdef)
KGB_K_INTERACTIVE_ID = _kgbdef.KGB_K_INTERACTIVE_ID

_kgbdef.KGB_K_LOCAL_ID_swigconstant(_kgbdef)
KGB_K_LOCAL_ID = _kgbdef.KGB_K_LOCAL_ID

_kgbdef.KGB_K_NETWORK_ID_swigconstant(_kgbdef)
KGB_K_NETWORK_ID = _kgbdef.KGB_K_NETWORK_ID

_kgbdef.KGB_K_REMOTE_ID_swigconstant(_kgbdef)
KGB_K_REMOTE_ID = _kgbdef.KGB_K_REMOTE_ID

_kgbdef.KGB_K_DECWINDOWS_ID_swigconstant(_kgbdef)
KGB_K_DECWINDOWS_ID = _kgbdef.KGB_K_DECWINDOWS_ID

_kgbdef.KGB_K_BOBUSER_ID_swigconstant(_kgbdef)
KGB_K_BOBUSER_ID = _kgbdef.KGB_K_BOBUSER_ID

_kgbdef.KGB_K_MRES_USER_ID_swigconstant(_kgbdef)
KGB_K_MRES_USER_ID = _kgbdef.KGB_K_MRES_USER_ID

_kgbdef.KGB_K_SAT_ACCESS_ID_swigconstant(_kgbdef)
KGB_K_SAT_ACCESS_ID = _kgbdef.KGB_K_SAT_ACCESS_ID

_kgbdef.KGB_K_LAST_ENV_ID_swigconstant(_kgbdef)
KGB_K_LAST_ENV_ID = _kgbdef.KGB_K_LAST_ENV_ID

_kgbdef.KGB_K_BASE_ENV_ID_swigconstant(_kgbdef)
KGB_K_BASE_ENV_ID = _kgbdef.KGB_K_BASE_ENV_ID

_kgbdef.KGB_K_NUMBER_OF_ENV_IDS_swigconstant(_kgbdef)
KGB_K_NUMBER_OF_ENV_IDS = _kgbdef.KGB_K_NUMBER_OF_ENV_IDS

_kgbdef.KGB_K_RESTRICTED_RANGE_swigconstant(_kgbdef)
KGB_K_RESTRICTED_RANGE = _kgbdef.KGB_K_RESTRICTED_RANGE

_kgbdef.KGB_K_SEC_LEVEL_BASE_swigconstant(_kgbdef)
KGB_K_SEC_LEVEL_BASE = _kgbdef.KGB_K_SEC_LEVEL_BASE

_kgbdef.KGB_K_INT_LEVEL_BASE_swigconstant(_kgbdef)
KGB_K_INT_LEVEL_BASE = _kgbdef.KGB_K_INT_LEVEL_BASE

_kgbdef.KGB_K_SEC_CATEGORY_BASE_swigconstant(_kgbdef)
KGB_K_SEC_CATEGORY_BASE = _kgbdef.KGB_K_SEC_CATEGORY_BASE

_kgbdef.KGB_K_INT_CATEGORY_BASE_swigconstant(_kgbdef)
KGB_K_INT_CATEGORY_BASE = _kgbdef.KGB_K_INT_CATEGORY_BASE

_kgbdef.KGB_K_SEC_ACCESS_CLASS_BASE_swigconstant(_kgbdef)
KGB_K_SEC_ACCESS_CLASS_BASE = _kgbdef.KGB_K_SEC_ACCESS_CLASS_BASE

_kgbdef.KGB_K_SEC_ACCESS_CLASS_END_swigconstant(_kgbdef)
KGB_K_SEC_ACCESS_CLASS_END = _kgbdef.KGB_K_SEC_ACCESS_CLASS_END

_kgbdef.KGB_K_PROCESS_swigconstant(_kgbdef)
KGB_K_PROCESS = _kgbdef.KGB_K_PROCESS

_kgbdef.KGB_K_SYSTEM_swigconstant(_kgbdef)
KGB_K_SYSTEM = _kgbdef.KGB_K_SYSTEM

_kgbdef.KGB_K_EXTENDED_swigconstant(_kgbdef)
KGB_K_EXTENDED = _kgbdef.KGB_K_EXTENDED

_kgbdef.KGB_K_IMAGE_swigconstant(_kgbdef)
KGB_K_IMAGE = _kgbdef.KGB_K_IMAGE

_kgbdef.KGB_K_MAX_SEG_swigconstant(_kgbdef)
KGB_K_MAX_SEG = _kgbdef.KGB_K_MAX_SEG

_kgbdef.KGB_K_SUBSYSTEM_swigconstant(_kgbdef)
KGB_K_SUBSYSTEM = _kgbdef.KGB_K_SUBSYSTEM
# This file is compatible with both classic and new-style classes.


