# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pxbdef', [dirname(__file__)])
        except ImportError:
            import _pxbdef
            return _pxbdef
        if fp is not None:
            try:
                _mod = imp.load_module('_pxbdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pxbdef = swig_import_helper()
    del swig_import_helper
else:
    import _pxbdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_pxbdef.PXB_S_PXB_swigconstant(_pxbdef)
PXB_S_PXB = _pxbdef.PXB_S_PXB

_pxbdef.PXB_K_LENGTH_swigconstant(_pxbdef)
PXB_K_LENGTH = _pxbdef.PXB_K_LENGTH

_pxbdef.PXB_ARRAY_ELEMENTS_swigconstant(_pxbdef)
PXB_ARRAY_ELEMENTS = _pxbdef.PXB_ARRAY_ELEMENTS

_pxbdef.PXB_ARRAY_K_PXB_ARRAY_HEADER_swigconstant(_pxbdef)
PXB_ARRAY_K_PXB_ARRAY_HEADER = _pxbdef.PXB_ARRAY_K_PXB_ARRAY_HEADER

_pxbdef.PXB_ARRAY_S_PXB_ARRAY_swigconstant(_pxbdef)
PXB_ARRAY_S_PXB_ARRAY = _pxbdef.PXB_ARRAY_S_PXB_ARRAY

_pxbdef.PXB_ARRAY_S_ELEMENTS_swigconstant(_pxbdef)
PXB_ARRAY_S_ELEMENTS = _pxbdef.PXB_ARRAY_S_ELEMENTS

_pxbdef.DELBK_S_DELBK_swigconstant(_pxbdef)
DELBK_S_DELBK = _pxbdef.DELBK_S_DELBK

_pxbdef.DELBK_C_DELEGATE_BLOCK_SIZE_swigconstant(_pxbdef)
DELBK_C_DELEGATE_BLOCK_SIZE = _pxbdef.DELBK_C_DELEGATE_BLOCK_SIZE

_pxbdef.PXRB_S_PXRB_swigconstant(_pxbdef)
PXRB_S_PXRB = _pxbdef.PXRB_S_PXRB

_pxbdef.PXRB_S_NAME_DESC_swigconstant(_pxbdef)
PXRB_S_NAME_DESC = _pxbdef.PXRB_S_NAME_DESC

_pxbdef.PXRB_S_NAME_swigconstant(_pxbdef)
PXRB_S_NAME = _pxbdef.PXRB_S_NAME

_pxbdef.PXRB_K_LENGTH_swigconstant(_pxbdef)
PXRB_K_LENGTH = _pxbdef.PXRB_K_LENGTH

_pxbdef.PXDV_K_version_swigconstant(_pxbdef)
PXDV_K_version = _pxbdef.PXDV_K_version

_pxbdef.PXDV_K_min_version_swigconstant(_pxbdef)
PXDV_K_min_version = _pxbdef.PXDV_K_min_version

_pxbdef.PXDV_K_max_version_swigconstant(_pxbdef)
PXDV_K_max_version = _pxbdef.PXDV_K_max_version

_pxbdef.PXDV_S_PXDV_swigconstant(_pxbdef)
PXDV_S_PXDV = _pxbdef.PXDV_S_PXDV

_pxbdef.PXBNT_K_VERSION_1_swigconstant(_pxbdef)
PXBNT_K_VERSION_1 = _pxbdef.PXBNT_K_VERSION_1

_pxbdef.PXBNT_K_CURRENT_VERSION_swigconstant(_pxbdef)
PXBNT_K_CURRENT_VERSION = _pxbdef.PXBNT_K_CURRENT_VERSION

_pxbdef.PXBNT_M_CLONE_swigconstant(_pxbdef)
PXBNT_M_CLONE = _pxbdef.PXBNT_M_CLONE

_pxbdef.PXBNT_M_DELEGATE_swigconstant(_pxbdef)
PXBNT_M_DELEGATE = _pxbdef.PXBNT_M_DELEGATE

_pxbdef.PXBNT_M_FILL_3_swigconstant(_pxbdef)
PXBNT_M_FILL_3 = _pxbdef.PXBNT_M_FILL_3

_pxbdef.PXBNT_M_FILL_4_swigconstant(_pxbdef)
PXBNT_M_FILL_4 = _pxbdef.PXBNT_M_FILL_4

_pxbdef.PXBNT_M_FILL_5_swigconstant(_pxbdef)
PXBNT_M_FILL_5 = _pxbdef.PXBNT_M_FILL_5

_pxbdef.PXBNT_M_FILL_6_swigconstant(_pxbdef)
PXBNT_M_FILL_6 = _pxbdef.PXBNT_M_FILL_6

_pxbdef.PXBNT_M_FILL_7_swigconstant(_pxbdef)
PXBNT_M_FILL_7 = _pxbdef.PXBNT_M_FILL_7

_pxbdef.PXBNT_M_DEBIT_swigconstant(_pxbdef)
PXBNT_M_DEBIT = _pxbdef.PXBNT_M_DEBIT

_pxbdef.PXBNT_K_LENGTH_swigconstant(_pxbdef)
PXBNT_K_LENGTH = _pxbdef.PXBNT_K_LENGTH

_pxbdef.PXBNT_S_PXBNT_swigconstant(_pxbdef)
PXBNT_S_PXBNT = _pxbdef.PXBNT_S_PXBNT

_pxbdef.PXBNT_S_DOI_swigconstant(_pxbdef)
PXBNT_S_DOI = _pxbdef.PXBNT_S_DOI

_pxbdef.PXBNT_S_NT_OWF_PASSWORD_swigconstant(_pxbdef)
PXBNT_S_NT_OWF_PASSWORD = _pxbdef.PXBNT_S_NT_OWF_PASSWORD

_pxbdef.PXBNT_S_LM_OWF_PASSWORD_swigconstant(_pxbdef)
PXBNT_S_LM_OWF_PASSWORD = _pxbdef.PXBNT_S_LM_OWF_PASSWORD

_pxbdef.PXB_M_FILL_1_swigconstant(_pxbdef)
PXB_M_FILL_1 = _pxbdef.PXB_M_FILL_1

_pxbdef.PXB_M_FILL_2_swigconstant(_pxbdef)
PXB_M_FILL_2 = _pxbdef.PXB_M_FILL_2

_pxbdef.PXB_M_FILL_3_swigconstant(_pxbdef)
PXB_M_FILL_3 = _pxbdef.PXB_M_FILL_3

_pxbdef.PXB_M_FILL_4_swigconstant(_pxbdef)
PXB_M_FILL_4 = _pxbdef.PXB_M_FILL_4

_pxbdef.PXB_M_FILL_5_swigconstant(_pxbdef)
PXB_M_FILL_5 = _pxbdef.PXB_M_FILL_5

_pxbdef.PXB_M_FILL_6_swigconstant(_pxbdef)
PXB_M_FILL_6 = _pxbdef.PXB_M_FILL_6

_pxbdef.PXB_M_FILL_7_swigconstant(_pxbdef)
PXB_M_FILL_7 = _pxbdef.PXB_M_FILL_7

_pxbdef.PXB_M_DEBIT_swigconstant(_pxbdef)
PXB_M_DEBIT = _pxbdef.PXB_M_DEBIT

_pxbdef.PXB_S_PXB_FLAGS_swigconstant(_pxbdef)
PXB_S_PXB_FLAGS = _pxbdef.PXB_S_PXB_FLAGS

_pxbdef.PXB_M_PRIMARY_EXTENSION_swigconstant(_pxbdef)
PXB_M_PRIMARY_EXTENSION = _pxbdef.PXB_M_PRIMARY_EXTENSION

_pxbdef.PXB_S_CREATE_FLAGS_swigconstant(_pxbdef)
PXB_S_CREATE_FLAGS = _pxbdef.PXB_S_CREATE_FLAGS

_pxbdef.TOKEN_K_USERSESSIONKEY_OFFSET_swigconstant(_pxbdef)
TOKEN_K_USERSESSIONKEY_OFFSET = _pxbdef.TOKEN_K_USERSESSIONKEY_OFFSET

_pxbdef.TOKEN_K_USERSESSIONKEY_SIZE_swigconstant(_pxbdef)
TOKEN_K_USERSESSIONKEY_SIZE = _pxbdef.TOKEN_K_USERSESSIONKEY_SIZE

_pxbdef.TOKEN_K_LMSESSIONKEY_OFFSET_swigconstant(_pxbdef)
TOKEN_K_LMSESSIONKEY_OFFSET = _pxbdef.TOKEN_K_LMSESSIONKEY_OFFSET

_pxbdef.TOKEN_K_LMSESSIONKEY_SIZE_swigconstant(_pxbdef)
TOKEN_K_LMSESSIONKEY_SIZE = _pxbdef.TOKEN_K_LMSESSIONKEY_SIZE
# This file is compatible with both classic and new-style classes.


