# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_acrdef', [dirname(__file__)])
        except ImportError:
            import _acrdef
            return _acrdef
        if fp is not None:
            try:
                _mod = imp.load_module('_acrdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _acrdef = swig_import_helper()
    del swig_import_helper
else:
    import _acrdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_acrdef.ACR_K_VERSION2_swigconstant(_acrdef)
ACR_K_VERSION2 = _acrdef.ACR_K_VERSION2

_acrdef.ACR_K_VERSION3T_swigconstant(_acrdef)
ACR_K_VERSION3T = _acrdef.ACR_K_VERSION3T

_acrdef.ACR_K_VERSION3_swigconstant(_acrdef)
ACR_K_VERSION3 = _acrdef.ACR_K_VERSION3

_acrdef.ACR_K_VERSION4_swigconstant(_acrdef)
ACR_K_VERSION4 = _acrdef.ACR_K_VERSION4

_acrdef.ACR_K_CURVER_swigconstant(_acrdef)
ACR_K_CURVER = _acrdef.ACR_K_CURVER

_acrdef.ACR_M_PACKET_swigconstant(_acrdef)
ACR_M_PACKET = _acrdef.ACR_M_PACKET

_acrdef.ACR_M_TYPE_swigconstant(_acrdef)
ACR_M_TYPE = _acrdef.ACR_M_TYPE

_acrdef.ACR_M_SUBTYPE_swigconstant(_acrdef)
ACR_M_SUBTYPE = _acrdef.ACR_M_SUBTYPE

_acrdef.ACR_M_VERSION_swigconstant(_acrdef)
ACR_M_VERSION = _acrdef.ACR_M_VERSION

_acrdef.ACR_M_CUSTOMER_swigconstant(_acrdef)
ACR_M_CUSTOMER = _acrdef.ACR_M_CUSTOMER

_acrdef.ACR_K_PRCDEL_swigconstant(_acrdef)
ACR_K_PRCDEL = _acrdef.ACR_K_PRCDEL

_acrdef.ACR_K_PRCPUR_swigconstant(_acrdef)
ACR_K_PRCPUR = _acrdef.ACR_K_PRCPUR

_acrdef.ACR_K_IMGDEL_swigconstant(_acrdef)
ACR_K_IMGDEL = _acrdef.ACR_K_IMGDEL

_acrdef.ACR_K_IMGPUR_swigconstant(_acrdef)
ACR_K_IMGPUR = _acrdef.ACR_K_IMGPUR

_acrdef.ACR_K_SYSINIT_swigconstant(_acrdef)
ACR_K_SYSINIT = _acrdef.ACR_K_SYSINIT

_acrdef.ACR_K_SETTIME_swigconstant(_acrdef)
ACR_K_SETTIME = _acrdef.ACR_K_SETTIME

_acrdef.ACR_K_LOGFAIL_swigconstant(_acrdef)
ACR_K_LOGFAIL = _acrdef.ACR_K_LOGFAIL

_acrdef.ACR_K_PRINT_swigconstant(_acrdef)
ACR_K_PRINT = _acrdef.ACR_K_PRINT

_acrdef.ACR_K_USER_swigconstant(_acrdef)
ACR_K_USER = _acrdef.ACR_K_USER

_acrdef.ACR_K_ENABLE_swigconstant(_acrdef)
ACR_K_ENABLE = _acrdef.ACR_K_ENABLE

_acrdef.ACR_K_DISABLE_swigconstant(_acrdef)
ACR_K_DISABLE = _acrdef.ACR_K_DISABLE

_acrdef.ACR_K_ALTACM_swigconstant(_acrdef)
ACR_K_ALTACM = _acrdef.ACR_K_ALTACM

_acrdef.ACR_K_FILE_FL_swigconstant(_acrdef)
ACR_K_FILE_FL = _acrdef.ACR_K_FILE_FL

_acrdef.ACR_K_FILE_BL_swigconstant(_acrdef)
ACR_K_FILE_BL = _acrdef.ACR_K_FILE_BL

_acrdef.ACR_K_INTERACTIVE_swigconstant(_acrdef)
ACR_K_INTERACTIVE = _acrdef.ACR_K_INTERACTIVE

_acrdef.ACR_K_SUBPROCESS_swigconstant(_acrdef)
ACR_K_SUBPROCESS = _acrdef.ACR_K_SUBPROCESS

_acrdef.ACR_K_DETACHED_swigconstant(_acrdef)
ACR_K_DETACHED = _acrdef.ACR_K_DETACHED

_acrdef.ACR_K_BATCH_swigconstant(_acrdef)
ACR_K_BATCH = _acrdef.ACR_K_BATCH

_acrdef.ACR_K_NETWORK_swigconstant(_acrdef)
ACR_K_NETWORK = _acrdef.ACR_K_NETWORK

_acrdef.ACR_K_ID_swigconstant(_acrdef)
ACR_K_ID = _acrdef.ACR_K_ID

_acrdef.ACR_K_RESOURCE_swigconstant(_acrdef)
ACR_K_RESOURCE = _acrdef.ACR_K_RESOURCE

_acrdef.ACR_K_IMAGENAME_swigconstant(_acrdef)
ACR_K_IMAGENAME = _acrdef.ACR_K_IMAGENAME

_acrdef.ACR_K_FILENAME_swigconstant(_acrdef)
ACR_K_FILENAME = _acrdef.ACR_K_FILENAME

_acrdef.ACR_K_USER_DATA_swigconstant(_acrdef)
ACR_K_USER_DATA = _acrdef.ACR_K_USER_DATA

_acrdef.ACR_S_ACRDEF_swigconstant(_acrdef)
ACR_S_ACRDEF = _acrdef.ACR_S_ACRDEF

_acrdef.ACR_S_TYPE_swigconstant(_acrdef)
ACR_S_TYPE = _acrdef.ACR_S_TYPE

_acrdef.ACR_S_SUBTYPE_swigconstant(_acrdef)
ACR_S_SUBTYPE = _acrdef.ACR_S_SUBTYPE

_acrdef.ACR_S_VERSION_swigconstant(_acrdef)
ACR_S_VERSION = _acrdef.ACR_S_VERSION

_acrdef.ACR_K_HDRLEN_swigconstant(_acrdef)
ACR_K_HDRLEN = _acrdef.ACR_K_HDRLEN

_acrdef.ACR_C_HDRLEN_swigconstant(_acrdef)
ACR_C_HDRLEN = _acrdef.ACR_C_HDRLEN

_acrdef.ACR_S_ACRDEF1_swigconstant(_acrdef)
ACR_S_ACRDEF1 = _acrdef.ACR_S_ACRDEF1

_acrdef.ACR_S_SYSTIME_swigconstant(_acrdef)
ACR_S_SYSTIME = _acrdef.ACR_S_SYSTIME

_acrdef.ACR_M_FULLNAME_swigconstant(_acrdef)
ACR_M_FULLNAME = _acrdef.ACR_M_FULLNAME

_acrdef.ACR_M_UIDGID_swigconstant(_acrdef)
ACR_M_UIDGID = _acrdef.ACR_M_UIDGID

_acrdef.ACR_M_FILL_1_swigconstant(_acrdef)
ACR_M_FILL_1 = _acrdef.ACR_M_FILL_1

_acrdef.ACR_K_IDVAR_swigconstant(_acrdef)
ACR_K_IDVAR = _acrdef.ACR_K_IDVAR

_acrdef.ACR_C_IDVAR_swigconstant(_acrdef)
ACR_C_IDVAR = _acrdef.ACR_C_IDVAR

_acrdef.ACR_S_ACRDEF2_swigconstant(_acrdef)
ACR_S_ACRDEF2 = _acrdef.ACR_S_ACRDEF2

_acrdef.ACR_S_PRIV_swigconstant(_acrdef)
ACR_S_PRIV = _acrdef.ACR_S_PRIV

_acrdef.ACR_S_FILL_1_swigconstant(_acrdef)
ACR_S_FILL_1 = _acrdef.ACR_S_FILL_1

_acrdef.ACR_S_ACRDEF3_swigconstant(_acrdef)
ACR_S_ACRDEF3 = _acrdef.ACR_S_ACRDEF3

_acrdef.ACR_S_LOGIN_swigconstant(_acrdef)
ACR_S_LOGIN = _acrdef.ACR_S_LOGIN

_acrdef.ACR_S_ACRDEF4_swigconstant(_acrdef)
ACR_S_ACRDEF4 = _acrdef.ACR_S_ACRDEF4

_acrdef.ACR_S_IMAGENAME_swigconstant(_acrdef)
ACR_S_IMAGENAME = _acrdef.ACR_S_IMAGENAME

_acrdef.ACR_S_ACRDEF5_swigconstant(_acrdef)
ACR_S_ACRDEF5 = _acrdef.ACR_S_ACRDEF5

_acrdef.ACR_S_QUETIME_swigconstant(_acrdef)
ACR_S_QUETIME = _acrdef.ACR_S_QUETIME

_acrdef.ACR_S_BEGTIME_swigconstant(_acrdef)
ACR_S_BEGTIME = _acrdef.ACR_S_BEGTIME

_acrdef.ACR_S_ACRDEF6_swigconstant(_acrdef)
ACR_S_ACRDEF6 = _acrdef.ACR_S_ACRDEF6

_acrdef.ACR_S_FILENAME_swigconstant(_acrdef)
ACR_S_FILENAME = _acrdef.ACR_S_FILENAME

_acrdef.ACR_S_ACRDEF7_swigconstant(_acrdef)
ACR_S_ACRDEF7 = _acrdef.ACR_S_ACRDEF7

_acrdef.ACR_S_USER_DATA_swigconstant(_acrdef)
ACR_S_USER_DATA = _acrdef.ACR_S_USER_DATA
# This file is compatible with both classic and new-style classes.


