# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dtr', [dirname(__file__)])
        except ImportError:
            import _dtr
            return _dtr
        if fp is not None:
            try:
                _mod = imp.load_module('_dtr', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _dtr = swig_import_helper()
    del swig_import_helper
else:
    import _dtr
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_dtr._K_STL_CMD_swigconstant(_dtr)
_K_STL_CMD = _dtr._K_STL_CMD

_dtr._K_STL_PRMPT_swigconstant(_dtr)
_K_STL_PRMPT = _dtr._K_STL_PRMPT

_dtr._K_STL_LINE_swigconstant(_dtr)
_K_STL_LINE = _dtr._K_STL_LINE

_dtr._K_STL_MSG_swigconstant(_dtr)
_K_STL_MSG = _dtr._K_STL_MSG

_dtr._K_STL_PGET_swigconstant(_dtr)
_K_STL_PGET = _dtr._K_STL_PGET

_dtr._K_STL_PPUT_swigconstant(_dtr)
_K_STL_PPUT = _dtr._K_STL_PPUT

_dtr._K_STL_CONT_swigconstant(_dtr)
_K_STL_CONT = _dtr._K_STL_CONT

_dtr._K_STL_UDK_swigconstant(_dtr)
_K_STL_UDK = _dtr._K_STL_UDK

_dtr._K_STL_END_UDK_swigconstant(_dtr)
_K_STL_END_UDK = _dtr._K_STL_END_UDK

_dtr._K_SEMI_COLON_OPT_swigconstant(_dtr)
_K_SEMI_COLON_OPT = _dtr._K_SEMI_COLON_OPT

_dtr._K_UNQUOTED_LIT_swigconstant(_dtr)
_K_UNQUOTED_LIT = _dtr._K_UNQUOTED_LIT

_dtr._K_SYNTAX_PROMPT_swigconstant(_dtr)
_K_SYNTAX_PROMPT = _dtr._K_SYNTAX_PROMPT

_dtr._K_IMMED_RETURN_swigconstant(_dtr)
_K_IMMED_RETURN = _dtr._K_IMMED_RETURN

_dtr._K_FORMS_ENABLE_swigconstant(_dtr)
_K_FORMS_ENABLE = _dtr._K_FORMS_ENABLE

_dtr._K_VERIFY_swigconstant(_dtr)
_K_VERIFY = _dtr._K_VERIFY

_dtr._K_BIG_ENDIAN_swigconstant(_dtr)
_K_BIG_ENDIAN = _dtr._K_BIG_ENDIAN

_dtr._K_IEEE_FLOAT_swigconstant(_dtr)
_K_IEEE_FLOAT = _dtr._K_IEEE_FLOAT

_dtr._K_CONTEXT_SEARCH_swigconstant(_dtr)
_K_CONTEXT_SEARCH = _dtr._K_CONTEXT_SEARCH

_dtr._K_HYPHEN_DISABLED_swigconstant(_dtr)
_K_HYPHEN_DISABLED = _dtr._K_HYPHEN_DISABLED

_dtr._K_MORE_COMMANDS_swigconstant(_dtr)
_K_MORE_COMMANDS = _dtr._K_MORE_COMMANDS

_dtr._K_ABORT_swigconstant(_dtr)
_K_ABORT = _dtr._K_ABORT

_dtr._K_LOCK_WAIT_swigconstant(_dtr)
_K_LOCK_WAIT = _dtr._K_LOCK_WAIT

_dtr._K_FN_PORT_SUPPORT_swigconstant(_dtr)
_K_FN_PORT_SUPPORT = _dtr._K_FN_PORT_SUPPORT

_dtr._K_DATE_STR_swigconstant(_dtr)
_K_DATE_STR = _dtr._K_DATE_STR

_dtr._K_RET_ON_PRINT_ERROR_swigconstant(_dtr)
_K_RET_ON_PRINT_ERROR = _dtr._K_RET_ON_PRINT_ERROR

_dtr._K_GET_ROUTINES_SUPPORT_swigconstant(_dtr)
_K_GET_ROUTINES_SUPPORT = _dtr._K_GET_ROUTINES_SUPPORT

_dtr._M_OPT_CMD_swigconstant(_dtr)
_M_OPT_CMD = _dtr._M_OPT_CMD

_dtr._M_OPT_PRMPT_swigconstant(_dtr)
_M_OPT_PRMPT = _dtr._M_OPT_PRMPT

_dtr._M_OPT_LINE_swigconstant(_dtr)
_M_OPT_LINE = _dtr._M_OPT_LINE

_dtr._M_OPT_MSG_swigconstant(_dtr)
_M_OPT_MSG = _dtr._M_OPT_MSG

_dtr._M_OPT_PGET_swigconstant(_dtr)
_M_OPT_PGET = _dtr._M_OPT_PGET

_dtr._M_OPT_PPUT_swigconstant(_dtr)
_M_OPT_PPUT = _dtr._M_OPT_PPUT

_dtr._M_OPT_CONT_swigconstant(_dtr)
_M_OPT_CONT = _dtr._M_OPT_CONT

_dtr._M_OPT_UDK_swigconstant(_dtr)
_M_OPT_UDK = _dtr._M_OPT_UDK

_dtr._M_OPT_DTR_UDK_swigconstant(_dtr)
_M_OPT_DTR_UDK = _dtr._M_OPT_DTR_UDK

_dtr._M_OPT_END_UDK_swigconstant(_dtr)
_M_OPT_END_UDK = _dtr._M_OPT_END_UDK

_dtr._M_OPT_UNWIND_swigconstant(_dtr)
_M_OPT_UNWIND = _dtr._M_OPT_UNWIND

_dtr._M_OPT_CONTROL_C_swigconstant(_dtr)
_M_OPT_CONTROL_C = _dtr._M_OPT_CONTROL_C

_dtr._M_OPT_STARTUP_swigconstant(_dtr)
_M_OPT_STARTUP = _dtr._M_OPT_STARTUP

_dtr._M_OPT_FOREIGN_swigconstant(_dtr)
_M_OPT_FOREIGN = _dtr._M_OPT_FOREIGN

_dtr._M_OPT_BANNER_swigconstant(_dtr)
_M_OPT_BANNER = _dtr._M_OPT_BANNER

_dtr._M_OPT_REMOVE_CTLC_swigconstant(_dtr)
_M_OPT_REMOVE_CTLC = _dtr._M_OPT_REMOVE_CTLC

_dtr._M_OPT_KEYDEFS_swigconstant(_dtr)
_M_OPT_KEYDEFS = _dtr._M_OPT_KEYDEFS

_dtr._K_UDK_SET_swigconstant(_dtr)
_K_UDK_SET = _dtr._K_UDK_SET

_dtr._K_UDK_SET_NO_swigconstant(_dtr)
_K_UDK_SET_NO = _dtr._K_UDK_SET_NO

_dtr._K_UDK_SHOW_swigconstant(_dtr)
_K_UDK_SHOW = _dtr._K_UDK_SHOW

_dtr._K_UDK_STATEMENT_swigconstant(_dtr)
_K_UDK_STATEMENT = _dtr._K_UDK_STATEMENT

_dtr._K_UDK_COMMAND_swigconstant(_dtr)
_K_UDK_COMMAND = _dtr._K_UDK_COMMAND

_dtr._K_TOK_TOKEN_swigconstant(_dtr)
_K_TOK_TOKEN = _dtr._K_TOK_TOKEN

_dtr._K_TOK_PICTURE_swigconstant(_dtr)
_K_TOK_PICTURE = _dtr._K_TOK_PICTURE

_dtr._K_TOK_FILENAME_swigconstant(_dtr)
_K_TOK_FILENAME = _dtr._K_TOK_FILENAME

_dtr._K_TOK_COMMAND_swigconstant(_dtr)
_K_TOK_COMMAND = _dtr._K_TOK_COMMAND

_dtr._K_TOK_TEST_TOKEN_swigconstant(_dtr)
_K_TOK_TEST_TOKEN = _dtr._K_TOK_TEST_TOKEN

_dtr._K_TOK_LIST_ELEMENT_swigconstant(_dtr)
_K_TOK_LIST_ELEMENT = _dtr._K_TOK_LIST_ELEMENT

_dtr._K_TOK_TEST_EOL_swigconstant(_dtr)
_K_TOK_TEST_EOL = _dtr._K_TOK_TEST_EOL

_dtr._SUCCESS_swigconstant(_dtr)
_SUCCESS = _dtr._SUCCESS

_dtr._K_INF_TYPE_DOMAIN_swigconstant(_dtr)
_K_INF_TYPE_DOMAIN = _dtr._K_INF_TYPE_DOMAIN

_dtr._K_INF_TYPE_COLLECTION_swigconstant(_dtr)
_K_INF_TYPE_COLLECTION = _dtr._K_INF_TYPE_COLLECTION

_dtr._K_INF_TYPE_KEYWORD_swigconstant(_dtr)
_K_INF_TYPE_KEYWORD = _dtr._K_INF_TYPE_KEYWORD

_dtr._K_INF_TYPE_DIC_NAME_swigconstant(_dtr)
_K_INF_TYPE_DIC_NAME = _dtr._K_INF_TYPE_DIC_NAME

_dtr._K_INF_TYPE_GLV_swigconstant(_dtr)
_K_INF_TYPE_GLV = _dtr._K_INF_TYPE_GLV

_dtr._K_INF_TYPE_PLOT_swigconstant(_dtr)
_K_INF_TYPE_PLOT = _dtr._K_INF_TYPE_PLOT

_dtr._K_INF_DOM_FLD_swigconstant(_dtr)
_K_INF_DOM_FLD = _dtr._K_INF_DOM_FLD

_dtr._K_INF_DOM_FORM_swigconstant(_dtr)
_K_INF_DOM_FORM = _dtr._K_INF_DOM_FORM

_dtr._K_INF_DOM_SHARE_swigconstant(_dtr)
_K_INF_DOM_SHARE = _dtr._K_INF_DOM_SHARE

_dtr._K_INF_DOM_ACCESS_swigconstant(_dtr)
_K_INF_DOM_ACCESS = _dtr._K_INF_DOM_ACCESS

_dtr._K_INF_DOM_NAME_swigconstant(_dtr)
_K_INF_DOM_NAME = _dtr._K_INF_DOM_NAME

_dtr._K_INF_DOM_NEXT_DOM_swigconstant(_dtr)
_K_INF_DOM_NEXT_DOM = _dtr._K_INF_DOM_NEXT_DOM

_dtr._K_INF_DOM_SSC_swigconstant(_dtr)
_K_INF_DOM_SSC = _dtr._K_INF_DOM_SSC

_dtr._K_INF_DOM_REC_LEN_swigconstant(_dtr)
_K_INF_DOM_REC_LEN = _dtr._K_INF_DOM_REC_LEN

_dtr._K_INF_FLD_NAME_swigconstant(_dtr)
_K_INF_FLD_NAME = _dtr._K_INF_FLD_NAME

_dtr._K_INF_FLD_QNAME_swigconstant(_dtr)
_K_INF_FLD_QNAME = _dtr._K_INF_FLD_QNAME

_dtr._K_INF_FLD_PICTURE_swigconstant(_dtr)
_K_INF_FLD_PICTURE = _dtr._K_INF_FLD_PICTURE

_dtr._K_INF_FLD_EDIT_swigconstant(_dtr)
_K_INF_FLD_EDIT = _dtr._K_INF_FLD_EDIT

_dtr._K_INF_FLD_DTYPE_swigconstant(_dtr)
_K_INF_FLD_DTYPE = _dtr._K_INF_FLD_DTYPE

_dtr._K_INF_FLD_OFFSET_swigconstant(_dtr)
_K_INF_FLD_OFFSET = _dtr._K_INF_FLD_OFFSET

_dtr._K_INF_FLD_LENGTH_swigconstant(_dtr)
_K_INF_FLD_LENGTH = _dtr._K_INF_FLD_LENGTH

_dtr._K_INF_FLD_SCALE_swigconstant(_dtr)
_K_INF_FLD_SCALE = _dtr._K_INF_FLD_SCALE

_dtr._K_INF_FLD_CHILD_swigconstant(_dtr)
_K_INF_FLD_CHILD = _dtr._K_INF_FLD_CHILD

_dtr._K_INF_FLD_CNT_swigconstant(_dtr)
_K_INF_FLD_CNT = _dtr._K_INF_FLD_CNT

_dtr._K_INF_FLD_LIST_swigconstant(_dtr)
_K_INF_FLD_LIST = _dtr._K_INF_FLD_LIST

_dtr._K_INF_FLD_REDEFINES_swigconstant(_dtr)
_K_INF_FLD_REDEFINES = _dtr._K_INF_FLD_REDEFINES

_dtr._K_INF_FLD_VIRTUAL_swigconstant(_dtr)
_K_INF_FLD_VIRTUAL = _dtr._K_INF_FLD_VIRTUAL

_dtr._K_INF_FLD_FILLER_swigconstant(_dtr)
_K_INF_FLD_FILLER = _dtr._K_INF_FLD_FILLER

_dtr._K_INF_FLD_MISSING_swigconstant(_dtr)
_K_INF_FLD_MISSING = _dtr._K_INF_FLD_MISSING

_dtr._K_INF_FLD_MISSING_TXT_swigconstant(_dtr)
_K_INF_FLD_MISSING_TXT = _dtr._K_INF_FLD_MISSING_TXT

_dtr._K_INF_FLD_SEG_STRING_swigconstant(_dtr)
_K_INF_FLD_SEG_STRING = _dtr._K_INF_FLD_SEG_STRING

_dtr._K_INF_COL_CURSOR_swigconstant(_dtr)
_K_INF_COL_CURSOR = _dtr._K_INF_COL_CURSOR

_dtr._K_INF_COL_SIZE_swigconstant(_dtr)
_K_INF_COL_SIZE = _dtr._K_INF_COL_SIZE

_dtr._K_INF_COL_FLD_swigconstant(_dtr)
_K_INF_COL_FLD = _dtr._K_INF_COL_FLD

_dtr._K_INF_COL_DROPPED_swigconstant(_dtr)
_K_INF_COL_DROPPED = _dtr._K_INF_COL_DROPPED

_dtr._K_INF_COL_ERASED_swigconstant(_dtr)
_K_INF_COL_ERASED = _dtr._K_INF_COL_ERASED

_dtr._K_INF_COL_INVISIBLE_swigconstant(_dtr)
_K_INF_COL_INVISIBLE = _dtr._K_INF_COL_INVISIBLE

_dtr._K_INF_COL_NAME_swigconstant(_dtr)
_K_INF_COL_NAME = _dtr._K_INF_COL_NAME

_dtr._K_INF_COL_NEXT_COL_swigconstant(_dtr)
_K_INF_COL_NEXT_COL = _dtr._K_INF_COL_NEXT_COL

_dtr._K_INF_GLV_FIRST_DOM_swigconstant(_dtr)
_K_INF_GLV_FIRST_DOM = _dtr._K_INF_GLV_FIRST_DOM

_dtr._K_INF_GLV_FIRST_COL_swigconstant(_dtr)
_K_INF_GLV_FIRST_COL = _dtr._K_INF_GLV_FIRST_COL

_dtr._K_INF_GLV_FIRST_SSC_swigconstant(_dtr)
_K_INF_GLV_FIRST_SSC = _dtr._K_INF_GLV_FIRST_SSC

_dtr._K_INF_GLV_DEF_DIC_swigconstant(_dtr)
_K_INF_GLV_DEF_DIC = _dtr._K_INF_GLV_DEF_DIC

_dtr._K_INF_FRM_NAME_swigconstant(_dtr)
_K_INF_FRM_NAME = _dtr._K_INF_FRM_NAME

_dtr._K_INF_FRM_LIBRARY_swigconstant(_dtr)
_K_INF_FRM_LIBRARY = _dtr._K_INF_FRM_LIBRARY

_dtr._K_INF_SSC_NAME_swigconstant(_dtr)
_K_INF_SSC_NAME = _dtr._K_INF_SSC_NAME

_dtr._K_INF_SSC_SET_swigconstant(_dtr)
_K_INF_SSC_SET = _dtr._K_INF_SSC_SET

_dtr._K_INF_SSC_NEXT_swigconstant(_dtr)
_K_INF_SSC_NEXT = _dtr._K_INF_SSC_NEXT

_dtr._K_INF_SET_NAME_swigconstant(_dtr)
_K_INF_SET_NAME = _dtr._K_INF_SET_NAME

_dtr._K_INF_SET_NEXT_swigconstant(_dtr)
_K_INF_SET_NEXT = _dtr._K_INF_SET_NEXT

_dtr._K_INF_SET_SDP_swigconstant(_dtr)
_K_INF_SET_SDP = _dtr._K_INF_SET_SDP

_dtr._K_INF_SET_SINGULAR_swigconstant(_dtr)
_K_INF_SET_SINGULAR = _dtr._K_INF_SET_SINGULAR

_dtr._K_INF_SDP_NEXT_swigconstant(_dtr)
_K_INF_SDP_NEXT = _dtr._K_INF_SDP_NEXT

_dtr._K_INF_SDP_DOMAIN_swigconstant(_dtr)
_K_INF_SDP_DOMAIN = _dtr._K_INF_SDP_DOMAIN

_dtr._K_INF_SDP_TENANCY_swigconstant(_dtr)
_K_INF_SDP_TENANCY = _dtr._K_INF_SDP_TENANCY

_dtr._K_INF_SDP_INSERT_swigconstant(_dtr)
_K_INF_SDP_INSERT = _dtr._K_INF_SDP_INSERT

_dtr._K_INF_SDP_RETAIN_swigconstant(_dtr)
_K_INF_SDP_RETAIN = _dtr._K_INF_SDP_RETAIN

_dtr._K_INF_FLD_QHDR_swigconstant(_dtr)
_K_INF_FLD_QHDR = _dtr._K_INF_FLD_QHDR

_dtr._K_INF_HDR_CNT_swigconstant(_dtr)
_K_INF_HDR_CNT = _dtr._K_INF_HDR_CNT

_dtr._K_INF_HDR_STRING_swigconstant(_dtr)
_K_INF_HDR_STRING = _dtr._K_INF_HDR_STRING

_dtr._K_INF_GLV_STA_OBJ_swigconstant(_dtr)
_K_INF_GLV_STA_OBJ = _dtr._K_INF_GLV_STA_OBJ

_dtr._K_INF_GLV_STA_CNT_swigconstant(_dtr)
_K_INF_GLV_STA_CNT = _dtr._K_INF_GLV_STA_CNT

_dtr._K_INF_GLV_STA_LINE_swigconstant(_dtr)
_K_INF_GLV_STA_LINE = _dtr._K_INF_GLV_STA_LINE

_dtr._K_INF_PLO_CNT_swigconstant(_dtr)
_K_INF_PLO_CNT = _dtr._K_INF_PLO_CNT

_dtr._K_INF_PLO_PAI_swigconstant(_dtr)
_K_INF_PLO_PAI = _dtr._K_INF_PLO_PAI

_dtr._K_INF_PAI_PROMPT_swigconstant(_dtr)
_K_INF_PAI_PROMPT = _dtr._K_INF_PAI_PROMPT

_dtr._K_INF_PAI_DTYPE_swigconstant(_dtr)
_K_INF_PAI_DTYPE = _dtr._K_INF_PAI_DTYPE

_dtr._K_INF_DOM_ACCESS_READ_swigconstant(_dtr)
_K_INF_DOM_ACCESS_READ = _dtr._K_INF_DOM_ACCESS_READ

_dtr._K_INF_DOM_ACCESS_WRITE_swigconstant(_dtr)
_K_INF_DOM_ACCESS_WRITE = _dtr._K_INF_DOM_ACCESS_WRITE

_dtr._K_INF_DOM_ACCESS_MODIFY_swigconstant(_dtr)
_K_INF_DOM_ACCESS_MODIFY = _dtr._K_INF_DOM_ACCESS_MODIFY

_dtr._K_INF_DOM_ACCESS_EXTEND_swigconstant(_dtr)
_K_INF_DOM_ACCESS_EXTEND = _dtr._K_INF_DOM_ACCESS_EXTEND

_dtr._K_INF_DOM_SHARE_EXCLUSIVE_swigconstant(_dtr)
_K_INF_DOM_SHARE_EXCLUSIVE = _dtr._K_INF_DOM_SHARE_EXCLUSIVE

_dtr._K_INF_DOM_SHARE_SHARED_swigconstant(_dtr)
_K_INF_DOM_SHARE_SHARED = _dtr._K_INF_DOM_SHARE_SHARED

_dtr._K_INF_DOM_SHARE_PROTECT_swigconstant(_dtr)
_K_INF_DOM_SHARE_PROTECT = _dtr._K_INF_DOM_SHARE_PROTECT

_dtr._NTS_swigconstant(_dtr)
_NTS = _dtr._NTS

def command(arg1, arg2):
    return _dtr.command(arg1, arg2)
command = _dtr.command

def cont(arg1):
    return _dtr.cont(arg1)
cont = _dtr.cont

def create_udk(arg1, arg2, arg3, arg4):
    return _dtr.create_udk(arg1, arg2, arg3, arg4)
create_udk = _dtr.create_udk

def end_udk(arg1):
    return _dtr.end_udk(arg1)
end_udk = _dtr.end_udk

def finish(arg1):
    return _dtr.finish(arg1)
finish = _dtr.finish

def get_port(arg1, arg2):
    return _dtr.get_port(arg1, arg2)
get_port = _dtr.get_port

def get_string(arg1, arg2, arg4):
    return _dtr.get_string(arg1, arg2, arg4)
get_string = _dtr.get_string

def info(arg1, arg2, arg3, arg6):
    return _dtr.info(arg1, arg2, arg3, arg6)
info = _dtr.info

def init(arg2, arg3):
    return _dtr.init(arg2, arg3)
init = _dtr.init

def lookup(arg1, arg2, arg4):
    return _dtr.lookup(arg1, arg2, arg4)
lookup = _dtr.lookup

def port_eof(arg1):
    return _dtr.port_eof(arg1)
port_eof = _dtr.port_eof

def put_port(arg1, arg2):
    return _dtr.put_port(arg1, arg2)
put_port = _dtr.put_port

def put_value(arg1, arg2):
    return _dtr.put_value(arg1, arg2)
put_value = _dtr.put_value

def unwind(arg1):
    return _dtr.unwind(arg1)
unwind = _dtr.unwind

def condition(arg1):
    return _dtr.condition(arg1)
condition = _dtr.condition

def state(arg1):
    return _dtr.state(arg1)
state = _dtr.state

def msg_buf(arg1):
    return _dtr.msg_buf(arg1)
msg_buf = _dtr.msg_buf

def aux_buf(arg1):
    return _dtr.aux_buf(arg1)
aux_buf = _dtr.aux_buf

def get_options(arg1):
    return _dtr.get_options(arg1)
get_options = _dtr.get_options

def set_options(arg1, arg2):
    return _dtr.set_options(arg1, arg2)
set_options = _dtr.set_options

def clear_options(arg1, arg2):
    return _dtr.clear_options(arg1, arg2)
clear_options = _dtr.clear_options

def get_rec_len(arg1):
    return _dtr.get_rec_len(arg1)
get_rec_len = _dtr.get_rec_len

def get_flags(arg1):
    return _dtr.get_flags(arg1)
get_flags = _dtr.get_flags

def get_udk_index(arg1):
    return _dtr.get_udk_index(arg1)
get_udk_index = _dtr.get_udk_index

def dtr(arg1, arg2):
    return _dtr.dtr(arg1, arg2)
dtr = _dtr.dtr

def skip(arg1, arg2):
    return _dtr.skip(arg1, arg2)
skip = _dtr.skip

def row(arg1, arg2):
    return _dtr.row(arg1, arg2)
row = _dtr.row
# This file is compatible with both classic and new-style classes.


