# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pcbdef', [dirname(__file__)])
        except ImportError:
            import _pcbdef
            return _pcbdef
        if fp is not None:
            try:
                _mod = imp.load_module('_pcbdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pcbdef = swig_import_helper()
    del swig_import_helper
else:
    import _pcbdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_pcbdef.PCB_M_RES_swigconstant(_pcbdef)
PCB_M_RES = _pcbdef.PCB_M_RES

_pcbdef.PCB_M_DELPEN_swigconstant(_pcbdef)
PCB_M_DELPEN = _pcbdef.PCB_M_DELPEN

_pcbdef.PCB_M_FORCPEN_swigconstant(_pcbdef)
PCB_M_FORCPEN = _pcbdef.PCB_M_FORCPEN

_pcbdef.PCB_M_INQUAN_swigconstant(_pcbdef)
PCB_M_INQUAN = _pcbdef.PCB_M_INQUAN

_pcbdef.PCB_M_PSWAPM_swigconstant(_pcbdef)
PCB_M_PSWAPM = _pcbdef.PCB_M_PSWAPM

_pcbdef.PCB_M_RESPEN_swigconstant(_pcbdef)
PCB_M_RESPEN = _pcbdef.PCB_M_RESPEN

_pcbdef.PCB_M_SSFEXC_swigconstant(_pcbdef)
PCB_M_SSFEXC = _pcbdef.PCB_M_SSFEXC

_pcbdef.PCB_M_SSFEXCE_swigconstant(_pcbdef)
PCB_M_SSFEXCE = _pcbdef.PCB_M_SSFEXCE

_pcbdef.PCB_M_SSFEXCS_swigconstant(_pcbdef)
PCB_M_SSFEXCS = _pcbdef.PCB_M_SSFEXCS

_pcbdef.PCB_M_SSFEXCU_swigconstant(_pcbdef)
PCB_M_SSFEXCU = _pcbdef.PCB_M_SSFEXCU

_pcbdef.PCB_M_SSRWAIT_swigconstant(_pcbdef)
PCB_M_SSRWAIT = _pcbdef.PCB_M_SSRWAIT

_pcbdef.PCB_M_SUSPEN_swigconstant(_pcbdef)
PCB_M_SUSPEN = _pcbdef.PCB_M_SUSPEN

_pcbdef.PCB_M_WALL_swigconstant(_pcbdef)
PCB_M_WALL = _pcbdef.PCB_M_WALL

_pcbdef.PCB_M_BATCH_swigconstant(_pcbdef)
PCB_M_BATCH = _pcbdef.PCB_M_BATCH

_pcbdef.PCB_M_NOACNT_swigconstant(_pcbdef)
PCB_M_NOACNT = _pcbdef.PCB_M_NOACNT

_pcbdef.PCB_M_NOSUSPEND_swigconstant(_pcbdef)
PCB_M_NOSUSPEND = _pcbdef.PCB_M_NOSUSPEND

_pcbdef.PCB_M_ASTPEN_swigconstant(_pcbdef)
PCB_M_ASTPEN = _pcbdef.PCB_M_ASTPEN

_pcbdef.PCB_M_PHDRES_swigconstant(_pcbdef)
PCB_M_PHDRES = _pcbdef.PCB_M_PHDRES

_pcbdef.PCB_M_HIBER_swigconstant(_pcbdef)
PCB_M_HIBER = _pcbdef.PCB_M_HIBER

_pcbdef.PCB_M_LOGIN_swigconstant(_pcbdef)
PCB_M_LOGIN = _pcbdef.PCB_M_LOGIN

_pcbdef.PCB_M_NETWRK_swigconstant(_pcbdef)
PCB_M_NETWRK = _pcbdef.PCB_M_NETWRK

_pcbdef.PCB_M_PWRAST_swigconstant(_pcbdef)
PCB_M_PWRAST = _pcbdef.PCB_M_PWRAST

_pcbdef.PCB_M_NODELET_swigconstant(_pcbdef)
PCB_M_NODELET = _pcbdef.PCB_M_NODELET

_pcbdef.PCB_M_DISAWS_swigconstant(_pcbdef)
PCB_M_DISAWS = _pcbdef.PCB_M_DISAWS

_pcbdef.PCB_M_INTER_swigconstant(_pcbdef)
PCB_M_INTER = _pcbdef.PCB_M_INTER

_pcbdef.PCB_M_RECOVER_swigconstant(_pcbdef)
PCB_M_RECOVER = _pcbdef.PCB_M_RECOVER

_pcbdef.PCB_M_HARDAFF_swigconstant(_pcbdef)
PCB_M_HARDAFF = _pcbdef.PCB_M_HARDAFF

_pcbdef.PCB_M_ERDACT_swigconstant(_pcbdef)
PCB_M_ERDACT = _pcbdef.PCB_M_ERDACT

_pcbdef.PCB_M_SOFTSUSP_swigconstant(_pcbdef)
PCB_M_SOFTSUSP = _pcbdef.PCB_M_SOFTSUSP

_pcbdef.PCB_M_PREEMPTED_swigconstant(_pcbdef)
PCB_M_PREEMPTED = _pcbdef.PCB_M_PREEMPTED

_pcbdef.PCB_M_QUANTUM_RESCHED_swigconstant(_pcbdef)
PCB_M_QUANTUM_RESCHED = _pcbdef.PCB_M_QUANTUM_RESCHED

_pcbdef.PCB_M_DISABLE_PREEMPT_PKTA_LOCK_swigconstant(_pcbdef)
PCB_M_DISABLE_PREEMPT_PKTA_LOCK = _pcbdef.PCB_M_DISABLE_PREEMPT_PKTA_LOCK

_pcbdef.PCB_M_FREDLOCK_swigconstant(_pcbdef)
PCB_M_FREDLOCK = _pcbdef.PCB_M_FREDLOCK

_pcbdef.PCB_M_PHDLOCK_swigconstant(_pcbdef)
PCB_M_PHDLOCK = _pcbdef.PCB_M_PHDLOCK

_pcbdef.PCB_M_TCB_swigconstant(_pcbdef)
PCB_M_TCB = _pcbdef.PCB_M_TCB

_pcbdef.PCB_M_TBS_STATE_PENDING_swigconstant(_pcbdef)
PCB_M_TBS_STATE_PENDING = _pcbdef.PCB_M_TBS_STATE_PENDING

_pcbdef.PCB_M_SS_LOGGING_ENABLE_swigconstant(_pcbdef)
PCB_M_SS_LOGGING_ENABLE = _pcbdef.PCB_M_SS_LOGGING_ENABLE

_pcbdef.PCB_M_SS_LOGGING_PERM_swigconstant(_pcbdef)
PCB_M_SS_LOGGING_PERM = _pcbdef.PCB_M_SS_LOGGING_PERM

_pcbdef.PCB_M_BRK_RUNDOWN_LOADED_swigconstant(_pcbdef)
PCB_M_BRK_RUNDOWN_LOADED = _pcbdef.PCB_M_BRK_RUNDOWN_LOADED

_pcbdef.PCB_M_CLASS_SCHED_PERM_swigconstant(_pcbdef)
PCB_M_CLASS_SCHED_PERM = _pcbdef.PCB_M_CLASS_SCHED_PERM

_pcbdef.PCB_M_TERM_NOTIFY_swigconstant(_pcbdef)
PCB_M_TERM_NOTIFY = _pcbdef.PCB_M_TERM_NOTIFY

_pcbdef.PCB_M_BYTLM_LOAN_swigconstant(_pcbdef)
PCB_M_BYTLM_LOAN = _pcbdef.PCB_M_BYTLM_LOAN

_pcbdef.PCB_M_DISABLE_PREEMPT_swigconstant(_pcbdef)
PCB_M_DISABLE_PREEMPT = _pcbdef.PCB_M_DISABLE_PREEMPT

_pcbdef.PCB_M_NOUNSHELVE_swigconstant(_pcbdef)
PCB_M_NOUNSHELVE = _pcbdef.PCB_M_NOUNSHELVE

_pcbdef.PCB_M_SHELVING_RESERVED_swigconstant(_pcbdef)
PCB_M_SHELVING_RESERVED = _pcbdef.PCB_M_SHELVING_RESERVED

_pcbdef.PCB_M_CLASS_SCHEDULED_swigconstant(_pcbdef)
PCB_M_CLASS_SCHEDULED = _pcbdef.PCB_M_CLASS_SCHEDULED

_pcbdef.PCB_M_CLASS_SUPPLIED_swigconstant(_pcbdef)
PCB_M_CLASS_SUPPLIED = _pcbdef.PCB_M_CLASS_SUPPLIED

_pcbdef.PCB_M_IN_TBS_STATE_swigconstant(_pcbdef)
PCB_M_IN_TBS_STATE = _pcbdef.PCB_M_IN_TBS_STATE

_pcbdef.PCB_M_WINDFALL_swigconstant(_pcbdef)
PCB_M_WINDFALL = _pcbdef.PCB_M_WINDFALL

_pcbdef.PCB_M_NOTIFY_swigconstant(_pcbdef)
PCB_M_NOTIFY = _pcbdef.PCB_M_NOTIFY

_pcbdef.PCB_M_SINGLE_THREADED_swigconstant(_pcbdef)
PCB_M_SINGLE_THREADED = _pcbdef.PCB_M_SINGLE_THREADED

_pcbdef.PCB_M_RWAST_swigconstant(_pcbdef)
PCB_M_RWAST = _pcbdef.PCB_M_RWAST

_pcbdef.PCB_M_SOFT_SINGLE_THREAD_swigconstant(_pcbdef)
PCB_M_SOFT_SINGLE_THREAD = _pcbdef.PCB_M_SOFT_SINGLE_THREAD

_pcbdef.PCB_M_EPID_WILD_swigconstant(_pcbdef)
PCB_M_EPID_WILD = _pcbdef.PCB_M_EPID_WILD

_pcbdef.PCB_M_FORK_swigconstant(_pcbdef)
PCB_M_FORK = _pcbdef.PCB_M_FORK

_pcbdef.PCB_K_SCHED_OTHER_swigconstant(_pcbdef)
PCB_K_SCHED_OTHER = _pcbdef.PCB_K_SCHED_OTHER

_pcbdef.PCB_K_SCHED_FIFO_swigconstant(_pcbdef)
PCB_K_SCHED_FIFO = _pcbdef.PCB_K_SCHED_FIFO

_pcbdef.PCB_K_SCHED_RR_swigconstant(_pcbdef)
PCB_K_SCHED_RR = _pcbdef.PCB_K_SCHED_RR

_pcbdef.PCB_K_SCHED_POLICY_CNT_swigconstant(_pcbdef)
PCB_K_SCHED_POLICY_CNT = _pcbdef.PCB_K_SCHED_POLICY_CNT

_pcbdef.PCB_K_ALL_THREADS_swigconstant(_pcbdef)
PCB_K_ALL_THREADS = _pcbdef.PCB_K_ALL_THREADS

_pcbdef.PCB_K_MAX_KT_COUNT_swigconstant(_pcbdef)
PCB_K_MAX_KT_COUNT = _pcbdef.PCB_K_MAX_KT_COUNT

_pcbdef.PCB_M_EVENT_NO_FLAG_swigconstant(_pcbdef)
PCB_M_EVENT_NO_FLAG = _pcbdef.PCB_M_EVENT_NO_FLAG

_pcbdef.PCB_M_IN_DELPAG_swigconstant(_pcbdef)
PCB_M_IN_DELPAG = _pcbdef.PCB_M_IN_DELPAG

_pcbdef.PCB_M_WAKEPEN_swigconstant(_pcbdef)
PCB_M_WAKEPEN = _pcbdef.PCB_M_WAKEPEN

_pcbdef.PCB_M_SECAUDIT_swigconstant(_pcbdef)
PCB_M_SECAUDIT = _pcbdef.PCB_M_SECAUDIT

_pcbdef.PCB_M_UPCALL_AST_BLOCKED_swigconstant(_pcbdef)
PCB_M_UPCALL_AST_BLOCKED = _pcbdef.PCB_M_UPCALL_AST_BLOCKED

_pcbdef.PCB_M_SUGID_IMAGE_swigconstant(_pcbdef)
PCB_M_SUGID_IMAGE = _pcbdef.PCB_M_SUGID_IMAGE

_pcbdef.PCB_M_SUGID_PROCESS_swigconstant(_pcbdef)
PCB_M_SUGID_PROCESS = _pcbdef.PCB_M_SUGID_PROCESS

_pcbdef.PCB_S_PCB_swigconstant(_pcbdef)
PCB_S_PCB = _pcbdef.PCB_S_PCB

_pcbdef.PCB_S_PHYPCB_swigconstant(_pcbdef)
PCB_S_PHYPCB = _pcbdef.PCB_S_PHYPCB

_pcbdef.PCB_S_LEFC_SWAPPED_swigconstant(_pcbdef)
PCB_S_LEFC_SWAPPED = _pcbdef.PCB_S_LEFC_SWAPPED

_pcbdef.PCB_S_PRVASN_swigconstant(_pcbdef)
PCB_S_PRVASN = _pcbdef.PCB_S_PRVASN

_pcbdef.PCB_S_PRVASNSEQ_swigconstant(_pcbdef)
PCB_S_PRVASNSEQ = _pcbdef.PCB_S_PRVASNSEQ

_pcbdef.PCB_S_ONCPUCNT_swigconstant(_pcbdef)
PCB_S_ONCPUCNT = _pcbdef.PCB_S_ONCPUCNT

_pcbdef.PCB_S_SINGLE_THREADED_swigconstant(_pcbdef)
PCB_S_SINGLE_THREADED = _pcbdef.PCB_S_SINGLE_THREADED

_pcbdef.PCB_S_EPID_PROC_swigconstant(_pcbdef)
PCB_S_EPID_PROC = _pcbdef.PCB_S_EPID_PROC

_pcbdef.PCB_S_EPID_NODE_IDX_swigconstant(_pcbdef)
PCB_S_EPID_NODE_IDX = _pcbdef.PCB_S_EPID_NODE_IDX

_pcbdef.PCB_S_EPID_NODE_SEQ_swigconstant(_pcbdef)
PCB_S_EPID_NODE_SEQ = _pcbdef.PCB_S_EPID_NODE_SEQ

_pcbdef.PCB_S_PCBARB_swigconstant(_pcbdef)
PCB_S_PCBARB = _pcbdef.PCB_S_PCBARB

_pcbdef.PCB_S_PRIV_swigconstant(_pcbdef)
PCB_S_PRIV = _pcbdef.PCB_S_PRIV

_pcbdef.PCB_S_LNAME_swigconstant(_pcbdef)
PCB_S_LNAME = _pcbdef.PCB_S_LNAME

_pcbdef.PCB_S_CWPSSRV_QUEUE_swigconstant(_pcbdef)
PCB_S_CWPSSRV_QUEUE = _pcbdef.PCB_S_CWPSSRV_QUEUE

_pcbdef.PCB_S_BUFOBJ_LIST_swigconstant(_pcbdef)
PCB_S_BUFOBJ_LIST = _pcbdef.PCB_S_BUFOBJ_LIST

_pcbdef.PCB_S_XSCB_QUE_swigconstant(_pcbdef)
PCB_S_XSCB_QUE = _pcbdef.PCB_S_XSCB_QUE

_pcbdef.PCB_S_RMCB_QUE_swigconstant(_pcbdef)
PCB_S_RMCB_QUE = _pcbdef.PCB_S_RMCB_QUE

_pcbdef.PCB_S_CD_QUE_swigconstant(_pcbdef)
PCB_S_CD_QUE = _pcbdef.PCB_S_CD_QUE

_pcbdef.PCB_S_PSX_ACTPRM_swigconstant(_pcbdef)
PCB_S_PSX_ACTPRM = _pcbdef.PCB_S_PSX_ACTPRM

_pcbdef.PCB_S_RDPB_QUE_swigconstant(_pcbdef)
PCB_S_RDPB_QUE = _pcbdef.PCB_S_RDPB_QUE

_pcbdef.PCB_S_FILES_64_swigconstant(_pcbdef)
PCB_S_FILES_64 = _pcbdef.PCB_S_FILES_64

_pcbdef.PCB_S_KEEP_IN_WS_swigconstant(_pcbdef)
PCB_S_KEEP_IN_WS = _pcbdef.PCB_S_KEEP_IN_WS

_pcbdef.PCB_S_KEEP_IN_WS2_swigconstant(_pcbdef)
PCB_S_KEEP_IN_WS2 = _pcbdef.PCB_S_KEEP_IN_WS2

_pcbdef.PCB_S_POSTEF_swigconstant(_pcbdef)
PCB_S_POSTEF = _pcbdef.PCB_S_POSTEF

_pcbdef.PCB_S_ST_KT_ARRAY_swigconstant(_pcbdef)
PCB_S_ST_KT_ARRAY = _pcbdef.PCB_S_ST_KT_ARRAY

_pcbdef.PCB_S_LOCKQFL_swigconstant(_pcbdef)
PCB_S_LOCKQFL = _pcbdef.PCB_S_LOCKQFL

_pcbdef.PCB_S_LOCKQBL_swigconstant(_pcbdef)
PCB_S_LOCKQBL = _pcbdef.PCB_S_LOCKQBL

_pcbdef.PCB_S_TQE_FLAGS_swigconstant(_pcbdef)
PCB_S_TQE_FLAGS = _pcbdef.PCB_S_TQE_FLAGS

_pcbdef.PCB_S_CBB_PERM_CPU_AFFINITY_swigconstant(_pcbdef)
PCB_S_CBB_PERM_CPU_AFFINITY = _pcbdef.PCB_S_CBB_PERM_CPU_AFFINITY

_pcbdef.PCB_S_PERMANENT_CPU_AFFINITY_swigconstant(_pcbdef)
PCB_S_PERMANENT_CPU_AFFINITY = _pcbdef.PCB_S_PERMANENT_CPU_AFFINITY

_pcbdef.PCB_S_CBB_CURRENT_AFFINITY_swigconstant(_pcbdef)
PCB_S_CBB_CURRENT_AFFINITY = _pcbdef.PCB_S_CBB_CURRENT_AFFINITY

_pcbdef.PCB_S_CURRENT_AFFINITY_swigconstant(_pcbdef)
PCB_S_CURRENT_AFFINITY = _pcbdef.PCB_S_CURRENT_AFFINITY

_pcbdef.PCB_S_CBB_ACTIVE_CPUS_swigconstant(_pcbdef)
PCB_S_CBB_ACTIVE_CPUS = _pcbdef.PCB_S_CBB_ACTIVE_CPUS

_pcbdef.PCB_S_ACTIVE_CPUS_swigconstant(_pcbdef)
PCB_S_ACTIVE_CPUS = _pcbdef.PCB_S_ACTIVE_CPUS

_pcbdef.PCB_S_CBB_AFFINITIES_swigconstant(_pcbdef)
PCB_S_CBB_AFFINITIES = _pcbdef.PCB_S_CBB_AFFINITIES

_pcbdef.PCB_S_AFFINITIES_swigconstant(_pcbdef)
PCB_S_AFFINITIES = _pcbdef.PCB_S_AFFINITIES

_pcbdef.PCB_S_CBB_PERMANENT_AFFINITIES_swigconstant(_pcbdef)
PCB_S_CBB_PERMANENT_AFFINITIES = _pcbdef.PCB_S_CBB_PERMANENT_AFFINITIES

_pcbdef.PCB_S_PERMANENT_AFFINITIES_swigconstant(_pcbdef)
PCB_S_PERMANENT_AFFINITIES = _pcbdef.PCB_S_PERMANENT_AFFINITIES

_pcbdef.PCB_S_CBB_SAVED_AFFINITIES_swigconstant(_pcbdef)
PCB_S_CBB_SAVED_AFFINITIES = _pcbdef.PCB_S_CBB_SAVED_AFFINITIES

_pcbdef.PCB_S_SAVED_AFFINITIES_swigconstant(_pcbdef)
PCB_S_SAVED_AFFINITIES = _pcbdef.PCB_S_SAVED_AFFINITIES

_pcbdef.PCB_S_TERMINAL_swigconstant(_pcbdef)
PCB_S_TERMINAL = _pcbdef.PCB_S_TERMINAL

_pcbdef.PCB_S_KERNEL_COUNTER_FRAC_swigconstant(_pcbdef)
PCB_S_KERNEL_COUNTER_FRAC = _pcbdef.PCB_S_KERNEL_COUNTER_FRAC

_pcbdef.PCB_S_EXEC_COUNTER_FRAC_swigconstant(_pcbdef)
PCB_S_EXEC_COUNTER_FRAC = _pcbdef.PCB_S_EXEC_COUNTER_FRAC

_pcbdef.PCB_S_SUPER_COUNTER_FRAC_swigconstant(_pcbdef)
PCB_S_SUPER_COUNTER_FRAC = _pcbdef.PCB_S_SUPER_COUNTER_FRAC

_pcbdef.PCB_S_USER_COUNTER_FRAC_swigconstant(_pcbdef)
PCB_S_USER_COUNTER_FRAC = _pcbdef.PCB_S_USER_COUNTER_FRAC

_pcbdef.PCB_K_LENGTH_swigconstant(_pcbdef)
PCB_K_LENGTH = _pcbdef.PCB_K_LENGTH

_pcbdef.PCB_C_LENGTH_swigconstant(_pcbdef)
PCB_C_LENGTH = _pcbdef.PCB_C_LENGTH

_pcbdef.PCB_S_PCBDEF_swigconstant(_pcbdef)
PCB_S_PCBDEF = _pcbdef.PCB_S_PCBDEF

_pcbdef.KTB_M_RES_swigconstant(_pcbdef)
KTB_M_RES = _pcbdef.KTB_M_RES

_pcbdef.KTB_M_DELPEN_swigconstant(_pcbdef)
KTB_M_DELPEN = _pcbdef.KTB_M_DELPEN

_pcbdef.KTB_M_FORCPEN_swigconstant(_pcbdef)
KTB_M_FORCPEN = _pcbdef.KTB_M_FORCPEN

_pcbdef.KTB_M_INQUAN_swigconstant(_pcbdef)
KTB_M_INQUAN = _pcbdef.KTB_M_INQUAN

_pcbdef.KTB_M_PSWAPM_swigconstant(_pcbdef)
KTB_M_PSWAPM = _pcbdef.KTB_M_PSWAPM

_pcbdef.KTB_M_RESPEN_swigconstant(_pcbdef)
KTB_M_RESPEN = _pcbdef.KTB_M_RESPEN

_pcbdef.KTB_M_SSFEXC_swigconstant(_pcbdef)
KTB_M_SSFEXC = _pcbdef.KTB_M_SSFEXC

_pcbdef.KTB_M_SSFEXCE_swigconstant(_pcbdef)
KTB_M_SSFEXCE = _pcbdef.KTB_M_SSFEXCE

_pcbdef.KTB_M_SSFEXCS_swigconstant(_pcbdef)
KTB_M_SSFEXCS = _pcbdef.KTB_M_SSFEXCS

_pcbdef.KTB_M_SSFEXCU_swigconstant(_pcbdef)
KTB_M_SSFEXCU = _pcbdef.KTB_M_SSFEXCU

_pcbdef.KTB_M_SSRWAIT_swigconstant(_pcbdef)
KTB_M_SSRWAIT = _pcbdef.KTB_M_SSRWAIT

_pcbdef.KTB_M_SUSPEN_swigconstant(_pcbdef)
KTB_M_SUSPEN = _pcbdef.KTB_M_SUSPEN

_pcbdef.KTB_M_WALL_swigconstant(_pcbdef)
KTB_M_WALL = _pcbdef.KTB_M_WALL

_pcbdef.KTB_M_BATCH_swigconstant(_pcbdef)
KTB_M_BATCH = _pcbdef.KTB_M_BATCH

_pcbdef.KTB_M_NOACNT_swigconstant(_pcbdef)
KTB_M_NOACNT = _pcbdef.KTB_M_NOACNT

_pcbdef.KTB_M_NOSUSPEND_swigconstant(_pcbdef)
KTB_M_NOSUSPEND = _pcbdef.KTB_M_NOSUSPEND

_pcbdef.KTB_M_ASTPEN_swigconstant(_pcbdef)
KTB_M_ASTPEN = _pcbdef.KTB_M_ASTPEN

_pcbdef.KTB_M_PHDRES_swigconstant(_pcbdef)
KTB_M_PHDRES = _pcbdef.KTB_M_PHDRES

_pcbdef.KTB_M_HIBER_swigconstant(_pcbdef)
KTB_M_HIBER = _pcbdef.KTB_M_HIBER

_pcbdef.KTB_M_LOGIN_swigconstant(_pcbdef)
KTB_M_LOGIN = _pcbdef.KTB_M_LOGIN

_pcbdef.KTB_M_NETWRK_swigconstant(_pcbdef)
KTB_M_NETWRK = _pcbdef.KTB_M_NETWRK

_pcbdef.KTB_M_PWRAST_swigconstant(_pcbdef)
KTB_M_PWRAST = _pcbdef.KTB_M_PWRAST

_pcbdef.KTB_M_NODELET_swigconstant(_pcbdef)
KTB_M_NODELET = _pcbdef.KTB_M_NODELET

_pcbdef.KTB_M_DISAWS_swigconstant(_pcbdef)
KTB_M_DISAWS = _pcbdef.KTB_M_DISAWS

_pcbdef.KTB_M_INTER_swigconstant(_pcbdef)
KTB_M_INTER = _pcbdef.KTB_M_INTER

_pcbdef.KTB_M_RECOVER_swigconstant(_pcbdef)
KTB_M_RECOVER = _pcbdef.KTB_M_RECOVER

_pcbdef.KTB_M_HARDAFF_swigconstant(_pcbdef)
KTB_M_HARDAFF = _pcbdef.KTB_M_HARDAFF

_pcbdef.KTB_M_ERDACT_swigconstant(_pcbdef)
KTB_M_ERDACT = _pcbdef.KTB_M_ERDACT

_pcbdef.KTB_M_SOFTSUSP_swigconstant(_pcbdef)
KTB_M_SOFTSUSP = _pcbdef.KTB_M_SOFTSUSP

_pcbdef.KTB_M_PREEMPTED_swigconstant(_pcbdef)
KTB_M_PREEMPTED = _pcbdef.KTB_M_PREEMPTED

_pcbdef.KTB_M_QUANTUM_RESCHED_swigconstant(_pcbdef)
KTB_M_QUANTUM_RESCHED = _pcbdef.KTB_M_QUANTUM_RESCHED

_pcbdef.KTB_M_PHDLOCK_swigconstant(_pcbdef)
KTB_M_PHDLOCK = _pcbdef.KTB_M_PHDLOCK

_pcbdef.KTB_M_TCB_swigconstant(_pcbdef)
KTB_M_TCB = _pcbdef.KTB_M_TCB

_pcbdef.KTB_M_TBS_STATE_PENDING_swigconstant(_pcbdef)
KTB_M_TBS_STATE_PENDING = _pcbdef.KTB_M_TBS_STATE_PENDING

_pcbdef.KTB_M_CLASS_SCHED_PERM_swigconstant(_pcbdef)
KTB_M_CLASS_SCHED_PERM = _pcbdef.KTB_M_CLASS_SCHED_PERM

_pcbdef.KTB_M_TERM_NOTIFY_swigconstant(_pcbdef)
KTB_M_TERM_NOTIFY = _pcbdef.KTB_M_TERM_NOTIFY

_pcbdef.KTB_M_BYTLM_LOAN_swigconstant(_pcbdef)
KTB_M_BYTLM_LOAN = _pcbdef.KTB_M_BYTLM_LOAN

_pcbdef.KTB_M_NOUNSHELVE_swigconstant(_pcbdef)
KTB_M_NOUNSHELVE = _pcbdef.KTB_M_NOUNSHELVE

_pcbdef.KTB_M_SHELVING_RESERVED_swigconstant(_pcbdef)
KTB_M_SHELVING_RESERVED = _pcbdef.KTB_M_SHELVING_RESERVED

_pcbdef.KTB_M_CLASS_SCHEDULED_swigconstant(_pcbdef)
KTB_M_CLASS_SCHEDULED = _pcbdef.KTB_M_CLASS_SCHEDULED

_pcbdef.KTB_M_CLASS_SUPPLIED_swigconstant(_pcbdef)
KTB_M_CLASS_SUPPLIED = _pcbdef.KTB_M_CLASS_SUPPLIED

_pcbdef.KTB_M_IN_TBS_STATE_swigconstant(_pcbdef)
KTB_M_IN_TBS_STATE = _pcbdef.KTB_M_IN_TBS_STATE

_pcbdef.KTB_M_WINDFALL_swigconstant(_pcbdef)
KTB_M_WINDFALL = _pcbdef.KTB_M_WINDFALL

_pcbdef.KTB_M_NOTIFY_swigconstant(_pcbdef)
KTB_M_NOTIFY = _pcbdef.KTB_M_NOTIFY

_pcbdef.KTB_M_SINGLE_THREADED_swigconstant(_pcbdef)
KTB_M_SINGLE_THREADED = _pcbdef.KTB_M_SINGLE_THREADED

_pcbdef.KTB_M_EPID_WILD_swigconstant(_pcbdef)
KTB_M_EPID_WILD = _pcbdef.KTB_M_EPID_WILD

_pcbdef.KTB_K_SCHED_OTHER_swigconstant(_pcbdef)
KTB_K_SCHED_OTHER = _pcbdef.KTB_K_SCHED_OTHER

_pcbdef.KTB_K_SCHED_FIFO_swigconstant(_pcbdef)
KTB_K_SCHED_FIFO = _pcbdef.KTB_K_SCHED_FIFO

_pcbdef.KTB_K_SCHED_RR_swigconstant(_pcbdef)
KTB_K_SCHED_RR = _pcbdef.KTB_K_SCHED_RR

_pcbdef.KTB_K_SCHED_POLICY_CNT_swigconstant(_pcbdef)
KTB_K_SCHED_POLICY_CNT = _pcbdef.KTB_K_SCHED_POLICY_CNT

_pcbdef.KTB_M_WAKEPEN_swigconstant(_pcbdef)
KTB_M_WAKEPEN = _pcbdef.KTB_M_WAKEPEN

_pcbdef.KTB_M_SECAUDIT_swigconstant(_pcbdef)
KTB_M_SECAUDIT = _pcbdef.KTB_M_SECAUDIT

_pcbdef.KTB_M_UPCALL_AST_BLOCKED_swigconstant(_pcbdef)
KTB_M_UPCALL_AST_BLOCKED = _pcbdef.KTB_M_UPCALL_AST_BLOCKED

_pcbdef.KTB_M_DELETE_PENDING_swigconstant(_pcbdef)
KTB_M_DELETE_PENDING = _pcbdef.KTB_M_DELETE_PENDING

_pcbdef.KTB_M_SCHED_CONTEXT_SAVED_swigconstant(_pcbdef)
KTB_M_SCHED_CONTEXT_SAVED = _pcbdef.KTB_M_SCHED_CONTEXT_SAVED

_pcbdef.KTB_M_SINGLE_THREAD_ACT_swigconstant(_pcbdef)
KTB_M_SINGLE_THREAD_ACT = _pcbdef.KTB_M_SINGLE_THREAD_ACT

_pcbdef.KTB_M_TOLERANT_swigconstant(_pcbdef)
KTB_M_TOLERANT = _pcbdef.KTB_M_TOLERANT

_pcbdef.KTB_M_SOFT_RAD_AFFINITY_swigconstant(_pcbdef)
KTB_M_SOFT_RAD_AFFINITY = _pcbdef.KTB_M_SOFT_RAD_AFFINITY

_pcbdef.KTB_S_KTB_swigconstant(_pcbdef)
KTB_S_KTB = _pcbdef.KTB_S_KTB

_pcbdef.KTB_S_PHYPCB_swigconstant(_pcbdef)
KTB_S_PHYPCB = _pcbdef.KTB_S_PHYPCB

_pcbdef.KTB_S_SINGLE_THREADED_swigconstant(_pcbdef)
KTB_S_SINGLE_THREADED = _pcbdef.KTB_S_SINGLE_THREADED

_pcbdef.KTB_S_EPID_PROC_swigconstant(_pcbdef)
KTB_S_EPID_PROC = _pcbdef.KTB_S_EPID_PROC

_pcbdef.KTB_S_EPID_NODE_IDX_swigconstant(_pcbdef)
KTB_S_EPID_NODE_IDX = _pcbdef.KTB_S_EPID_NODE_IDX

_pcbdef.KTB_S_EPID_NODE_SEQ_swigconstant(_pcbdef)
KTB_S_EPID_NODE_SEQ = _pcbdef.KTB_S_EPID_NODE_SEQ

_pcbdef.KTB_S_SINGLE_THREAD_ACT_swigconstant(_pcbdef)
KTB_S_SINGLE_THREAD_ACT = _pcbdef.KTB_S_SINGLE_THREAD_ACT

_pcbdef.KTB_S_CAPABILITIES_swigconstant(_pcbdef)
KTB_S_CAPABILITIES = _pcbdef.KTB_S_CAPABILITIES

_pcbdef.KTB_S_PERMANENT_CAPABILITIES_swigconstant(_pcbdef)
KTB_S_PERMANENT_CAPABILITIES = _pcbdef.KTB_S_PERMANENT_CAPABILITIES

_pcbdef.KTB_S_SAVED_CAPABILITIES_swigconstant(_pcbdef)
KTB_S_SAVED_CAPABILITIES = _pcbdef.KTB_S_SAVED_CAPABILITIES

_pcbdef.KTB_S_VOL_WAITS_swigconstant(_pcbdef)
KTB_S_VOL_WAITS = _pcbdef.KTB_S_VOL_WAITS

_pcbdef.KTB_S_COMQ_WAIT_swigconstant(_pcbdef)
KTB_S_COMQ_WAIT = _pcbdef.KTB_S_COMQ_WAIT

_pcbdef.KTB_S_RUNTIME_START_swigconstant(_pcbdef)
KTB_S_RUNTIME_START = _pcbdef.KTB_S_RUNTIME_START

_pcbdef.KTB_S_INTTIME_START_swigconstant(_pcbdef)
KTB_S_INTTIME_START = _pcbdef.KTB_S_INTTIME_START

_pcbdef.KTB_S_ACC_RUN_swigconstant(_pcbdef)
KTB_S_ACC_RUN = _pcbdef.KTB_S_ACC_RUN

_pcbdef.KTB_S_ACC_WAIT_swigconstant(_pcbdef)
KTB_S_ACC_WAIT = _pcbdef.KTB_S_ACC_WAIT

_pcbdef.KTB_S_ACC_INTERRUPT_swigconstant(_pcbdef)
KTB_S_ACC_INTERRUPT = _pcbdef.KTB_S_ACC_INTERRUPT

_pcbdef.KTB_S_GLOCK_swigconstant(_pcbdef)
KTB_S_GLOCK = _pcbdef.KTB_S_GLOCK

_pcbdef.KTB_S_SCHED_COUNT_swigconstant(_pcbdef)
KTB_S_SCHED_COUNT = _pcbdef.KTB_S_SCHED_COUNT

_pcbdef.KTB_S_FRED_swigconstant(_pcbdef)
KTB_S_FRED = _pcbdef.KTB_S_FRED

_pcbdef.KTB_S_VIRPCB_swigconstant(_pcbdef)
KTB_S_VIRPCB = _pcbdef.KTB_S_VIRPCB

_pcbdef.KTB_S_TQE_FLAGS_swigconstant(_pcbdef)
KTB_S_TQE_FLAGS = _pcbdef.KTB_S_TQE_FLAGS

_pcbdef.KTB_S_CBB_PERM_CPU_AFFINITY_swigconstant(_pcbdef)
KTB_S_CBB_PERM_CPU_AFFINITY = _pcbdef.KTB_S_CBB_PERM_CPU_AFFINITY

_pcbdef.KTB_S_PERMANENT_CPU_AFFINITY_swigconstant(_pcbdef)
KTB_S_PERMANENT_CPU_AFFINITY = _pcbdef.KTB_S_PERMANENT_CPU_AFFINITY

_pcbdef.KTB_S_CBB_CURRENT_AFFINITY_swigconstant(_pcbdef)
KTB_S_CBB_CURRENT_AFFINITY = _pcbdef.KTB_S_CBB_CURRENT_AFFINITY

_pcbdef.KTB_S_CURRENT_AFFINITY_swigconstant(_pcbdef)
KTB_S_CURRENT_AFFINITY = _pcbdef.KTB_S_CURRENT_AFFINITY

_pcbdef.KTB_S_CBB_ACTIVE_CPUS_swigconstant(_pcbdef)
KTB_S_CBB_ACTIVE_CPUS = _pcbdef.KTB_S_CBB_ACTIVE_CPUS

_pcbdef.KTB_S_ACTIVE_CPUS_swigconstant(_pcbdef)
KTB_S_ACTIVE_CPUS = _pcbdef.KTB_S_ACTIVE_CPUS

_pcbdef.KTB_S_CBB_AFFINITIES_swigconstant(_pcbdef)
KTB_S_CBB_AFFINITIES = _pcbdef.KTB_S_CBB_AFFINITIES

_pcbdef.KTB_S_AFFINITIES_swigconstant(_pcbdef)
KTB_S_AFFINITIES = _pcbdef.KTB_S_AFFINITIES

_pcbdef.KTB_S_CBB_PERMANENT_AFFINITIES_swigconstant(_pcbdef)
KTB_S_CBB_PERMANENT_AFFINITIES = _pcbdef.KTB_S_CBB_PERMANENT_AFFINITIES

_pcbdef.KTB_S_PERMANENT_AFFINITIES_swigconstant(_pcbdef)
KTB_S_PERMANENT_AFFINITIES = _pcbdef.KTB_S_PERMANENT_AFFINITIES

_pcbdef.KTB_S_CBB_SAVED_AFFINITIES_swigconstant(_pcbdef)
KTB_S_CBB_SAVED_AFFINITIES = _pcbdef.KTB_S_CBB_SAVED_AFFINITIES

_pcbdef.KTB_S_SAVED_AFFINITIES_swigconstant(_pcbdef)
KTB_S_SAVED_AFFINITIES = _pcbdef.KTB_S_SAVED_AFFINITIES

_pcbdef.KTB_S_FP_DISABLED_ACTION_swigconstant(_pcbdef)
KTB_S_FP_DISABLED_ACTION = _pcbdef.KTB_S_FP_DISABLED_ACTION

_pcbdef.KTB_S_KT_KERNEL_COUNTER_FRAC_swigconstant(_pcbdef)
KTB_S_KT_KERNEL_COUNTER_FRAC = _pcbdef.KTB_S_KT_KERNEL_COUNTER_FRAC

_pcbdef.KTB_S_KT_EXEC_COUNTER_FRAC_swigconstant(_pcbdef)
KTB_S_KT_EXEC_COUNTER_FRAC = _pcbdef.KTB_S_KT_EXEC_COUNTER_FRAC

_pcbdef.KTB_S_KT_SUPER_COUNTER_FRAC_swigconstant(_pcbdef)
KTB_S_KT_SUPER_COUNTER_FRAC = _pcbdef.KTB_S_KT_SUPER_COUNTER_FRAC

_pcbdef.KTB_S_KT_USER_COUNTER_FRAC_swigconstant(_pcbdef)
KTB_S_KT_USER_COUNTER_FRAC = _pcbdef.KTB_S_KT_USER_COUNTER_FRAC

_pcbdef.KTB_S_FP_LOW_SEQUENCE_NUMBER_swigconstant(_pcbdef)
KTB_S_FP_LOW_SEQUENCE_NUMBER = _pcbdef.KTB_S_FP_LOW_SEQUENCE_NUMBER

_pcbdef.KTB_S_FP_HIGH_SEQUENCE_NUMBER_swigconstant(_pcbdef)
KTB_S_FP_HIGH_SEQUENCE_NUMBER = _pcbdef.KTB_S_FP_HIGH_SEQUENCE_NUMBER

_pcbdef.KTB_S_POWER_ACCOUNTING_swigconstant(_pcbdef)
KTB_S_POWER_ACCOUNTING = _pcbdef.KTB_S_POWER_ACCOUNTING

_pcbdef.KTB_S_DEF_SCHED_FKB_swigconstant(_pcbdef)
KTB_S_DEF_SCHED_FKB = _pcbdef.KTB_S_DEF_SCHED_FKB

_pcbdef.KTB_K_LENGTH_swigconstant(_pcbdef)
KTB_K_LENGTH = _pcbdef.KTB_K_LENGTH

_pcbdef.KTB_C_LENGTH_swigconstant(_pcbdef)
KTB_C_LENGTH = _pcbdef.KTB_C_LENGTH

_pcbdef.KTB_S_KTBDEF_swigconstant(_pcbdef)
KTB_S_KTBDEF = _pcbdef.KTB_S_KTBDEF
# This file is compatible with both classic and new-style classes.


