# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_brkdef', [dirname(__file__)])
        except ImportError:
            import _brkdef
            return _brkdef
        if fp is not None:
            try:
                _mod = imp.load_module('_brkdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _brkdef = swig_import_helper()
    del swig_import_helper
else:
    import _brkdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_brkdef.BRK_C_DEVICE_swigconstant(_brkdef)
BRK_C_DEVICE = _brkdef.BRK_C_DEVICE

_brkdef.BRK_C_USERNAME_swigconstant(_brkdef)
BRK_C_USERNAME = _brkdef.BRK_C_USERNAME

_brkdef.BRK_C_ALLUSERS_swigconstant(_brkdef)
BRK_C_ALLUSERS = _brkdef.BRK_C_ALLUSERS

_brkdef.BRK_C_ALLTERMS_swigconstant(_brkdef)
BRK_C_ALLTERMS = _brkdef.BRK_C_ALLTERMS

_brkdef.BRK_C_MAXSENDTYPE_swigconstant(_brkdef)
BRK_C_MAXSENDTYPE = _brkdef.BRK_C_MAXSENDTYPE

_brkdef.BRK_C_GENERAL_swigconstant(_brkdef)
BRK_C_GENERAL = _brkdef.BRK_C_GENERAL

_brkdef.BRK_C_PHONE_swigconstant(_brkdef)
BRK_C_PHONE = _brkdef.BRK_C_PHONE

_brkdef.BRK_C_MAIL_swigconstant(_brkdef)
BRK_C_MAIL = _brkdef.BRK_C_MAIL

_brkdef.BRK_C_QUEUE_swigconstant(_brkdef)
BRK_C_QUEUE = _brkdef.BRK_C_QUEUE

_brkdef.BRK_C_SHUTDOWN_swigconstant(_brkdef)
BRK_C_SHUTDOWN = _brkdef.BRK_C_SHUTDOWN

_brkdef.BRK_C_URGENT_swigconstant(_brkdef)
BRK_C_URGENT = _brkdef.BRK_C_URGENT

_brkdef.BRK_C_DCL_swigconstant(_brkdef)
BRK_C_DCL = _brkdef.BRK_C_DCL

_brkdef.BRK_C_OPCOM_swigconstant(_brkdef)
BRK_C_OPCOM = _brkdef.BRK_C_OPCOM

_brkdef.BRK_C_USER1_swigconstant(_brkdef)
BRK_C_USER1 = _brkdef.BRK_C_USER1

_brkdef.BRK_C_USER2_swigconstant(_brkdef)
BRK_C_USER2 = _brkdef.BRK_C_USER2

_brkdef.BRK_C_USER3_swigconstant(_brkdef)
BRK_C_USER3 = _brkdef.BRK_C_USER3

_brkdef.BRK_C_USER4_swigconstant(_brkdef)
BRK_C_USER4 = _brkdef.BRK_C_USER4

_brkdef.BRK_C_USER5_swigconstant(_brkdef)
BRK_C_USER5 = _brkdef.BRK_C_USER5

_brkdef.BRK_C_USER6_swigconstant(_brkdef)
BRK_C_USER6 = _brkdef.BRK_C_USER6

_brkdef.BRK_C_USER7_swigconstant(_brkdef)
BRK_C_USER7 = _brkdef.BRK_C_USER7

_brkdef.BRK_C_USER8_swigconstant(_brkdef)
BRK_C_USER8 = _brkdef.BRK_C_USER8

_brkdef.BRK_C_USER9_swigconstant(_brkdef)
BRK_C_USER9 = _brkdef.BRK_C_USER9

_brkdef.BRK_C_USER10_swigconstant(_brkdef)
BRK_C_USER10 = _brkdef.BRK_C_USER10

_brkdef.BRK_C_USER11_swigconstant(_brkdef)
BRK_C_USER11 = _brkdef.BRK_C_USER11

_brkdef.BRK_C_USER12_swigconstant(_brkdef)
BRK_C_USER12 = _brkdef.BRK_C_USER12

_brkdef.BRK_C_USER13_swigconstant(_brkdef)
BRK_C_USER13 = _brkdef.BRK_C_USER13

_brkdef.BRK_C_USER14_swigconstant(_brkdef)
BRK_C_USER14 = _brkdef.BRK_C_USER14

_brkdef.BRK_C_USER15_swigconstant(_brkdef)
BRK_C_USER15 = _brkdef.BRK_C_USER15

_brkdef.BRK_C_USER16_swigconstant(_brkdef)
BRK_C_USER16 = _brkdef.BRK_C_USER16

_brkdef.BRK_M_SCREEN_swigconstant(_brkdef)
BRK_M_SCREEN = _brkdef.BRK_M_SCREEN

_brkdef.BRK_M_BOTTOM_swigconstant(_brkdef)
BRK_M_BOTTOM = _brkdef.BRK_M_BOTTOM

_brkdef.BRK_M_NOREFRESH_swigconstant(_brkdef)
BRK_M_NOREFRESH = _brkdef.BRK_M_NOREFRESH

_brkdef.BRK_M_CLUSTER_swigconstant(_brkdef)
BRK_M_CLUSTER = _brkdef.BRK_M_CLUSTER

_brkdef.BRK_S_FLAGS_INPUT_swigconstant(_brkdef)
BRK_S_FLAGS_INPUT = _brkdef.BRK_S_FLAGS_INPUT

_brkdef.BRK_S_ERASE_LINES_swigconstant(_brkdef)
BRK_S_ERASE_LINES = _brkdef.BRK_S_ERASE_LINES
# This file is compatible with both classic and new-style classes.


