# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ossdef', [dirname(__file__)])
        except ImportError:
            import _ossdef
            return _ossdef
        if fp is not None:
            try:
                _mod = imp.load_module('_ossdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ossdef = swig_import_helper()
    del swig_import_helper
else:
    import _ossdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_ossdef.OSS_M_WLOCK_swigconstant(_ossdef)
OSS_M_WLOCK = _ossdef.OSS_M_WLOCK

_ossdef.OSS_M_RELCTX_swigconstant(_ossdef)
OSS_M_RELCTX = _ossdef.OSS_M_RELCTX

_ossdef.OSS_M_LOCAL_swigconstant(_ossdef)
OSS_M_LOCAL = _ossdef.OSS_M_LOCAL

_ossdef.OSS_S_OSSDEF_swigconstant(_ossdef)
OSS_S_OSSDEF = _ossdef.OSS_S_OSSDEF

_ossdef.OSS__ACCESS_NAMES_swigconstant(_ossdef)
OSS__ACCESS_NAMES = _ossdef.OSS__ACCESS_NAMES

_ossdef.OSS__ACCESS_NAMES_LENGTH_swigconstant(_ossdef)
OSS__ACCESS_NAMES_LENGTH = _ossdef.OSS__ACCESS_NAMES_LENGTH

_ossdef.OSS__ACL_ADD_ENTRY_swigconstant(_ossdef)
OSS__ACL_ADD_ENTRY = _ossdef.OSS__ACL_ADD_ENTRY

_ossdef.OSS__ACL_DELETE_ENTRY_swigconstant(_ossdef)
OSS__ACL_DELETE_ENTRY = _ossdef.OSS__ACL_DELETE_ENTRY

_ossdef.OSS__ACL_DELETE_swigconstant(_ossdef)
OSS__ACL_DELETE = _ossdef.OSS__ACL_DELETE

_ossdef.OSS__ACL_DELETE_ALL_swigconstant(_ossdef)
OSS__ACL_DELETE_ALL = _ossdef.OSS__ACL_DELETE_ALL

_ossdef.OSS__ACL_FIND_ENTRY_swigconstant(_ossdef)
OSS__ACL_FIND_ENTRY = _ossdef.OSS__ACL_FIND_ENTRY

_ossdef.OSS__ACL_FIND_NEXT_swigconstant(_ossdef)
OSS__ACL_FIND_NEXT = _ossdef.OSS__ACL_FIND_NEXT

_ossdef.OSS__ACL_FIND_TYPE_swigconstant(_ossdef)
OSS__ACL_FIND_TYPE = _ossdef.OSS__ACL_FIND_TYPE

_ossdef.OSS__ACL_GRANT_ACE_swigconstant(_ossdef)
OSS__ACL_GRANT_ACE = _ossdef.OSS__ACL_GRANT_ACE

_ossdef.OSS__ACL_LENGTH_swigconstant(_ossdef)
OSS__ACL_LENGTH = _ossdef.OSS__ACL_LENGTH

_ossdef.OSS__ACL_MODIFY_ENTRY_swigconstant(_ossdef)
OSS__ACL_MODIFY_ENTRY = _ossdef.OSS__ACL_MODIFY_ENTRY

_ossdef.OSS__ACL_POSITION_swigconstant(_ossdef)
OSS__ACL_POSITION = _ossdef.OSS__ACL_POSITION

_ossdef.OSS__ACL_POSITION_TOP_swigconstant(_ossdef)
OSS__ACL_POSITION_TOP = _ossdef.OSS__ACL_POSITION_TOP

_ossdef.OSS__ACL_POSITION_BOTTOM_swigconstant(_ossdef)
OSS__ACL_POSITION_BOTTOM = _ossdef.OSS__ACL_POSITION_BOTTOM

_ossdef.OSS__ACL_READ_ENTRY_swigconstant(_ossdef)
OSS__ACL_READ_ENTRY = _ossdef.OSS__ACL_READ_ENTRY

_ossdef.OSS__ACL_READ_swigconstant(_ossdef)
OSS__ACL_READ = _ossdef.OSS__ACL_READ

_ossdef.OSS__MAX_CLASS_swigconstant(_ossdef)
OSS__MAX_CLASS = _ossdef.OSS__MAX_CLASS

_ossdef.OSS__MIN_CLASS_swigconstant(_ossdef)
OSS__MIN_CLASS = _ossdef.OSS__MIN_CLASS

_ossdef.OSS__NEXT_OBJECT_swigconstant(_ossdef)
OSS__NEXT_OBJECT = _ossdef.OSS__NEXT_OBJECT

_ossdef.OSS__OWNER_swigconstant(_ossdef)
OSS__OWNER = _ossdef.OSS__OWNER

_ossdef.OSS__PROTECTION_swigconstant(_ossdef)
OSS__PROTECTION = _ossdef.OSS__PROTECTION

_ossdef.OSS__SYS_PROT_swigconstant(_ossdef)
OSS__SYS_PROT = _ossdef.OSS__SYS_PROT

_ossdef.OSS__OWN_PROT_swigconstant(_ossdef)
OSS__OWN_PROT = _ossdef.OSS__OWN_PROT

_ossdef.OSS__GRP_PROT_swigconstant(_ossdef)
OSS__GRP_PROT = _ossdef.OSS__GRP_PROT

_ossdef.OSS__WOR_PROT_swigconstant(_ossdef)
OSS__WOR_PROT = _ossdef.OSS__WOR_PROT

_ossdef.OSS__CLASS_NAME_swigconstant(_ossdef)
OSS__CLASS_NAME = _ossdef.OSS__CLASS_NAME

_ossdef.OSS__FIRST_TEMPLATE_swigconstant(_ossdef)
OSS__FIRST_TEMPLATE = _ossdef.OSS__FIRST_TEMPLATE

_ossdef.OSS__NEXT_TEMPLATE_swigconstant(_ossdef)
OSS__NEXT_TEMPLATE = _ossdef.OSS__NEXT_TEMPLATE

_ossdef.OSS__OBJECT_NAME_swigconstant(_ossdef)
OSS__OBJECT_NAME = _ossdef.OSS__OBJECT_NAME

_ossdef.OSS__ACCESS_CLASS_NAME_swigconstant(_ossdef)
OSS__ACCESS_CLASS_NAME = _ossdef.OSS__ACCESS_CLASS_NAME

_ossdef.OSS__DAMAGED_ACL_swigconstant(_ossdef)
OSS__DAMAGED_ACL = _ossdef.OSS__DAMAGED_ACL

_ossdef.OSS__IN_TRANSITION_swigconstant(_ossdef)
OSS__IN_TRANSITION = _ossdef.OSS__IN_TRANSITION

_ossdef.OSS__TRANQUILITY_COUNT_swigconstant(_ossdef)
OSS__TRANQUILITY_COUNT = _ossdef.OSS__TRANQUILITY_COUNT

_ossdef.OSS__POSIX_GID_swigconstant(_ossdef)
OSS__POSIX_GID = _ossdef.OSS__POSIX_GID

_ossdef.OSS__POSIX_GRP_MODE_swigconstant(_ossdef)
OSS__POSIX_GRP_MODE = _ossdef.OSS__POSIX_GRP_MODE

_ossdef.OSS__POSIX_MODE_swigconstant(_ossdef)
OSS__POSIX_MODE = _ossdef.OSS__POSIX_MODE

_ossdef.OSS__POSIX_SGID_swigconstant(_ossdef)
OSS__POSIX_SGID = _ossdef.OSS__POSIX_SGID

_ossdef.OSS__POSIX_SUID_swigconstant(_ossdef)
OSS__POSIX_SUID = _ossdef.OSS__POSIX_SUID

_ossdef.OSS__ACCESS_BITNAMES_swigconstant(_ossdef)
OSS__ACCESS_BITNAMES = _ossdef.OSS__ACCESS_BITNAMES

_ossdef.OSS__ACCESS_BITNAMES_LENGTH_swigconstant(_ossdef)
OSS__ACCESS_BITNAMES_LENGTH = _ossdef.OSS__ACCESS_BITNAMES_LENGTH

_ossdef.OSS__ACL_ADDACE_swigconstant(_ossdef)
OSS__ACL_ADDACE = _ossdef.OSS__ACL_ADDACE

_ossdef.OSS__ACL_DELACE_swigconstant(_ossdef)
OSS__ACL_DELACE = _ossdef.OSS__ACL_DELACE

_ossdef.OSS__ACL_FNDACE_swigconstant(_ossdef)
OSS__ACL_FNDACE = _ossdef.OSS__ACL_FNDACE

_ossdef.OSS__ACL_FNDNXT_swigconstant(_ossdef)
OSS__ACL_FNDNXT = _ossdef.OSS__ACL_FNDNXT

_ossdef.OSS__ACL_FNDTYP_swigconstant(_ossdef)
OSS__ACL_FNDTYP = _ossdef.OSS__ACL_FNDTYP

_ossdef.OSS__ACL_MODACE_swigconstant(_ossdef)
OSS__ACL_MODACE = _ossdef.OSS__ACL_MODACE

_ossdef.OSS__ACL_READACE_swigconstant(_ossdef)
OSS__ACL_READACE = _ossdef.OSS__ACL_READACE
# This file is compatible with both classic and new-style classes.


