# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_jbcmsgdef', [dirname(__file__)])
        except ImportError:
            import _jbcmsgdef
            return _jbcmsgdef
        if fp is not None:
            try:
                _mod = imp.load_module('_jbcmsgdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _jbcmsgdef = swig_import_helper()
    del swig_import_helper
else:
    import _jbcmsgdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_jbcmsgdef.JBC__FACILITY_swigconstant(_jbcmsgdef)
JBC__FACILITY = _jbcmsgdef.JBC__FACILITY

_jbcmsgdef.JBC__NORMAL_swigconstant(_jbcmsgdef)
JBC__NORMAL = _jbcmsgdef.JBC__NORMAL

_jbcmsgdef.JBC__NOCMKRNL_swigconstant(_jbcmsgdef)
JBC__NOCMKRNL = _jbcmsgdef.JBC__NOCMKRNL

_jbcmsgdef.JBC__NOOPER_swigconstant(_jbcmsgdef)
JBC__NOOPER = _jbcmsgdef.JBC__NOOPER

_jbcmsgdef.JBC__NOSYSNAM_swigconstant(_jbcmsgdef)
JBC__NOSYSNAM = _jbcmsgdef.JBC__NOSYSNAM

_jbcmsgdef.JBC__ILLDEVNAM_swigconstant(_jbcmsgdef)
JBC__ILLDEVNAM = _jbcmsgdef.JBC__ILLDEVNAM

_jbcmsgdef.JBC__UNSDEVTYP_swigconstant(_jbcmsgdef)
JBC__UNSDEVTYP = _jbcmsgdef.JBC__UNSDEVTYP

_jbcmsgdef.JBC__ILLFILNAM_swigconstant(_jbcmsgdef)
JBC__ILLFILNAM = _jbcmsgdef.JBC__ILLFILNAM

_jbcmsgdef.JBC__INVQUENAM_swigconstant(_jbcmsgdef)
JBC__INVQUENAM = _jbcmsgdef.JBC__INVQUENAM

_jbcmsgdef.JBC__NOPRIV_swigconstant(_jbcmsgdef)
JBC__NOPRIV = _jbcmsgdef.JBC__NOPRIV

_jbcmsgdef.JBC__NOQUEHDR_swigconstant(_jbcmsgdef)
JBC__NOQUEHDR = _jbcmsgdef.JBC__NOQUEHDR

_jbcmsgdef.JBC__NOQUESPACE_swigconstant(_jbcmsgdef)
JBC__NOQUESPACE = _jbcmsgdef.JBC__NOQUESPACE

_jbcmsgdef.JBC__NOSUCHQUE_swigconstant(_jbcmsgdef)
JBC__NOSUCHQUE = _jbcmsgdef.JBC__NOSUCHQUE

_jbcmsgdef.JBC__NOSUCHJOB_swigconstant(_jbcmsgdef)
JBC__NOSUCHJOB = _jbcmsgdef.JBC__NOSUCHJOB

_jbcmsgdef.JBC__NOOPENJOB_swigconstant(_jbcmsgdef)
JBC__NOOPENJOB = _jbcmsgdef.JBC__NOOPENJOB

_jbcmsgdef.JBC__REFERENCED_swigconstant(_jbcmsgdef)
JBC__REFERENCED = _jbcmsgdef.JBC__REFERENCED

_jbcmsgdef.JBC__STARTED_swigconstant(_jbcmsgdef)
JBC__STARTED = _jbcmsgdef.JBC__STARTED

_jbcmsgdef.JBC__INVITMCOD_swigconstant(_jbcmsgdef)
JBC__INVITMCOD = _jbcmsgdef.JBC__INVITMCOD

_jbcmsgdef.JBC__INVFUNCOD_swigconstant(_jbcmsgdef)
JBC__INVFUNCOD = _jbcmsgdef.JBC__INVFUNCOD

_jbcmsgdef.JBC__EMPTYJOB_swigconstant(_jbcmsgdef)
JBC__EMPTYJOB = _jbcmsgdef.JBC__EMPTYJOB

_jbcmsgdef.JBC__JOBQUEDIS_swigconstant(_jbcmsgdef)
JBC__JOBQUEDIS = _jbcmsgdef.JBC__JOBQUEDIS

_jbcmsgdef.JBC__JOBABORT_swigconstant(_jbcmsgdef)
JBC__JOBABORT = _jbcmsgdef.JBC__JOBABORT

_jbcmsgdef.JBC__ACMINVOP_swigconstant(_jbcmsgdef)
JBC__ACMINVOP = _jbcmsgdef.JBC__ACMINVOP

_jbcmsgdef.JBC__INVPARLEN_swigconstant(_jbcmsgdef)
JBC__INVPARLEN = _jbcmsgdef.JBC__INVPARLEN

_jbcmsgdef.JBC__TRMMBXUSE_swigconstant(_jbcmsgdef)
JBC__TRMMBXUSE = _jbcmsgdef.JBC__TRMMBXUSE

_jbcmsgdef.JBC__MAXSYMEXD_swigconstant(_jbcmsgdef)
JBC__MAXSYMEXD = _jbcmsgdef.JBC__MAXSYMEXD

_jbcmsgdef.JBC__SCTTABFUL_swigconstant(_jbcmsgdef)
JBC__SCTTABFUL = _jbcmsgdef.JBC__SCTTABFUL

_jbcmsgdef.JBC__CREPRCFAL_swigconstant(_jbcmsgdef)
JBC__CREPRCFAL = _jbcmsgdef.JBC__CREPRCFAL

_jbcmsgdef.JBC__SYMNTBFUL_swigconstant(_jbcmsgdef)
JBC__SYMNTBFUL = _jbcmsgdef.JBC__SYMNTBFUL

_jbcmsgdef.JBC__NODSTQUE_swigconstant(_jbcmsgdef)
JBC__NODSTQUE = _jbcmsgdef.JBC__NODSTQUE

_jbcmsgdef.JBC__INVDSTQUE_swigconstant(_jbcmsgdef)
JBC__INVDSTQUE = _jbcmsgdef.JBC__INVDSTQUE

_jbcmsgdef.JBC__JOBDELETE_swigconstant(_jbcmsgdef)
JBC__JOBDELETE = _jbcmsgdef.JBC__JOBDELETE

_jbcmsgdef.JBC__NORESTART_swigconstant(_jbcmsgdef)
JBC__NORESTART = _jbcmsgdef.JBC__NORESTART

_jbcmsgdef.JBC__JOBREQUEUE_swigconstant(_jbcmsgdef)
JBC__JOBREQUEUE = _jbcmsgdef.JBC__JOBREQUEUE

_jbcmsgdef.JBC__QUERESET_swigconstant(_jbcmsgdef)
JBC__QUERESET = _jbcmsgdef.JBC__QUERESET

_jbcmsgdef.JBC__SYSFAIL_swigconstant(_jbcmsgdef)
JBC__SYSFAIL = _jbcmsgdef.JBC__SYSFAIL

_jbcmsgdef.JBC__EXECUTING_swigconstant(_jbcmsgdef)
JBC__EXECUTING = _jbcmsgdef.JBC__EXECUTING

_jbcmsgdef.JBC__INVMSGBUF_swigconstant(_jbcmsgdef)
JBC__INVMSGBUF = _jbcmsgdef.JBC__INVMSGBUF

_jbcmsgdef.JBC__MISREQPAR_swigconstant(_jbcmsgdef)
JBC__MISREQPAR = _jbcmsgdef.JBC__MISREQPAR

_jbcmsgdef.JBC__INVPARVAL_swigconstant(_jbcmsgdef)
JBC__INVPARVAL = _jbcmsgdef.JBC__INVPARVAL

_jbcmsgdef.JBC__INCQUETYP_swigconstant(_jbcmsgdef)
JBC__INCQUETYP = _jbcmsgdef.JBC__INCQUETYP

_jbcmsgdef.JBC__INCDSTQUE_swigconstant(_jbcmsgdef)
JBC__INCDSTQUE = _jbcmsgdef.JBC__INCDSTQUE

_jbcmsgdef.JBC__JOBQUEENA_swigconstant(_jbcmsgdef)
JBC__JOBQUEENA = _jbcmsgdef.JBC__JOBQUEENA

_jbcmsgdef.JBC__NOTASSIGN_swigconstant(_jbcmsgdef)
JBC__NOTASSIGN = _jbcmsgdef.JBC__NOTASSIGN

_jbcmsgdef.JBC__INCOMPLETE_swigconstant(_jbcmsgdef)
JBC__INCOMPLETE = _jbcmsgdef.JBC__INCOMPLETE

_jbcmsgdef.JBC__INVCHANAM_swigconstant(_jbcmsgdef)
JBC__INVCHANAM = _jbcmsgdef.JBC__INVCHANAM

_jbcmsgdef.JBC__INVFORNAM_swigconstant(_jbcmsgdef)
JBC__INVFORNAM = _jbcmsgdef.JBC__INVFORNAM

_jbcmsgdef.JBC__NOSUCHCHAR_swigconstant(_jbcmsgdef)
JBC__NOSUCHCHAR = _jbcmsgdef.JBC__NOSUCHCHAR

_jbcmsgdef.JBC__NOSUCHFORM_swigconstant(_jbcmsgdef)
JBC__NOSUCHFORM = _jbcmsgdef.JBC__NOSUCHFORM

_jbcmsgdef.JBC__DUPFORM_swigconstant(_jbcmsgdef)
JBC__DUPFORM = _jbcmsgdef.JBC__DUPFORM

_jbcmsgdef.JBC__INCFORMPAR_swigconstant(_jbcmsgdef)
JBC__INCFORMPAR = _jbcmsgdef.JBC__INCFORMPAR

_jbcmsgdef.JBC__NOSUCHFILE_swigconstant(_jbcmsgdef)
JBC__NOSUCHFILE = _jbcmsgdef.JBC__NOSUCHFILE

_jbcmsgdef.JBC__DELACCESS_swigconstant(_jbcmsgdef)
JBC__DELACCESS = _jbcmsgdef.JBC__DELACCESS

_jbcmsgdef.JBC__QUENOTSTOP_swigconstant(_jbcmsgdef)
JBC__QUENOTSTOP = _jbcmsgdef.JBC__QUENOTSTOP

_jbcmsgdef.JBC__NOMORECHAR_swigconstant(_jbcmsgdef)
JBC__NOMORECHAR = _jbcmsgdef.JBC__NOMORECHAR

_jbcmsgdef.JBC__NOMOREFILE_swigconstant(_jbcmsgdef)
JBC__NOMOREFILE = _jbcmsgdef.JBC__NOMOREFILE

_jbcmsgdef.JBC__NOMOREFORM_swigconstant(_jbcmsgdef)
JBC__NOMOREFORM = _jbcmsgdef.JBC__NOMOREFORM

_jbcmsgdef.JBC__NOMOREJOB_swigconstant(_jbcmsgdef)
JBC__NOMOREJOB = _jbcmsgdef.JBC__NOMOREJOB

_jbcmsgdef.JBC__NOMOREQUE_swigconstant(_jbcmsgdef)
JBC__NOMOREQUE = _jbcmsgdef.JBC__NOMOREQUE

_jbcmsgdef.JBC__NOJOBCTX_swigconstant(_jbcmsgdef)
JBC__NOJOBCTX = _jbcmsgdef.JBC__NOJOBCTX

_jbcmsgdef.JBC__NOQUECTX_swigconstant(_jbcmsgdef)
JBC__NOQUECTX = _jbcmsgdef.JBC__NOQUECTX

_jbcmsgdef.JBC__NOSUCHNODE_swigconstant(_jbcmsgdef)
JBC__NOSUCHNODE = _jbcmsgdef.JBC__NOSUCHNODE

_jbcmsgdef.JBC__GEN_MAX_swigconstant(_jbcmsgdef)
JBC__GEN_MAX = _jbcmsgdef.JBC__GEN_MAX

_jbcmsgdef.JBC__QUE_CLOSED_swigconstant(_jbcmsgdef)
JBC__QUE_CLOSED = _jbcmsgdef.JBC__QUE_CLOSED

_jbcmsgdef.JBC__NOSUCHENT_swigconstant(_jbcmsgdef)
JBC__NOSUCHENT = _jbcmsgdef.JBC__NOSUCHENT

_jbcmsgdef.JBC__NOMOREENT_swigconstant(_jbcmsgdef)
JBC__NOMOREENT = _jbcmsgdef.JBC__NOMOREENT

_jbcmsgdef.JBC__JOBCTLABORT_swigconstant(_jbcmsgdef)
JBC__JOBCTLABORT = _jbcmsgdef.JBC__JOBCTLABORT

_jbcmsgdef.JBC__NOTSUPPORTED_swigconstant(_jbcmsgdef)
JBC__NOTSUPPORTED = _jbcmsgdef.JBC__NOTSUPPORTED

_jbcmsgdef.JBC__NOTMEANINGFUL_swigconstant(_jbcmsgdef)
JBC__NOTMEANINGFUL = _jbcmsgdef.JBC__NOTMEANINGFUL

_jbcmsgdef.JBC__QUEDISABLED_swigconstant(_jbcmsgdef)
JBC__QUEDISABLED = _jbcmsgdef.JBC__QUEDISABLED

_jbcmsgdef.JBC__NOTDISABLED_swigconstant(_jbcmsgdef)
JBC__NOTDISABLED = _jbcmsgdef.JBC__NOTDISABLED

_jbcmsgdef.JBC__NOTENAGEN_swigconstant(_jbcmsgdef)
JBC__NOTENAGEN = _jbcmsgdef.JBC__NOTENAGEN

_jbcmsgdef.JBC__ENABLEQUE_swigconstant(_jbcmsgdef)
JBC__ENABLEQUE = _jbcmsgdef.JBC__ENABLEQUE

_jbcmsgdef.JBC__QUENOTMOD_swigconstant(_jbcmsgdef)
JBC__QUENOTMOD = _jbcmsgdef.JBC__QUENOTMOD

_jbcmsgdef.JBC__ATT_MAX_swigconstant(_jbcmsgdef)
JBC__ATT_MAX = _jbcmsgdef.JBC__ATT_MAX

_jbcmsgdef.JBC__ATTNOTAVAIL_swigconstant(_jbcmsgdef)
JBC__ATTNOTAVAIL = _jbcmsgdef.JBC__ATTNOTAVAIL

_jbcmsgdef.JBC__QEXISTS_swigconstant(_jbcmsgdef)
JBC__QEXISTS = _jbcmsgdef.JBC__QEXISTS

_jbcmsgdef.JBC__NOSUCHQMGR_swigconstant(_jbcmsgdef)
JBC__NOSUCHQMGR = _jbcmsgdef.JBC__NOSUCHQMGR

_jbcmsgdef.JBC__JOBNOTEXEC_swigconstant(_jbcmsgdef)
JBC__JOBNOTEXEC = _jbcmsgdef.JBC__JOBNOTEXEC

_jbcmsgdef.JBC__DUPCHARNAME_swigconstant(_jbcmsgdef)
JBC__DUPCHARNAME = _jbcmsgdef.JBC__DUPCHARNAME

_jbcmsgdef.JBC__DUPCHARNUM_swigconstant(_jbcmsgdef)
JBC__DUPCHARNUM = _jbcmsgdef.JBC__DUPCHARNUM

_jbcmsgdef.JBC__DUPFORMNAME_swigconstant(_jbcmsgdef)
JBC__DUPFORMNAME = _jbcmsgdef.JBC__DUPFORMNAME

_jbcmsgdef.JBC__STKNOTCHANGE_swigconstant(_jbcmsgdef)
JBC__STKNOTCHANGE = _jbcmsgdef.JBC__STKNOTCHANGE

_jbcmsgdef.JBC__ITMREMOVED_swigconstant(_jbcmsgdef)
JBC__ITMREMOVED = _jbcmsgdef.JBC__ITMREMOVED

_jbcmsgdef.JBC__PRIOSMALL_swigconstant(_jbcmsgdef)
JBC__PRIOSMALL = _jbcmsgdef.JBC__PRIOSMALL

_jbcmsgdef.JBC__QMANMAX_swigconstant(_jbcmsgdef)
JBC__QMANMAX = _jbcmsgdef.JBC__QMANMAX

_jbcmsgdef.JBC__NOAUTOSTART_swigconstant(_jbcmsgdef)
JBC__NOAUTOSTART = _jbcmsgdef.JBC__NOAUTOSTART

_jbcmsgdef.JBC__NOTALLREQUE_swigconstant(_jbcmsgdef)
JBC__NOTALLREQUE = _jbcmsgdef.JBC__NOTALLREQUE

_jbcmsgdef.JBC__NULL1_swigconstant(_jbcmsgdef)
JBC__NULL1 = _jbcmsgdef.JBC__NULL1

_jbcmsgdef.JBC__TOOMUCHINFO_swigconstant(_jbcmsgdef)
JBC__TOOMUCHINFO = _jbcmsgdef.JBC__TOOMUCHINFO

_jbcmsgdef.JBC__AUTONOTSTART_swigconstant(_jbcmsgdef)
JBC__AUTONOTSTART = _jbcmsgdef.JBC__AUTONOTSTART

_jbcmsgdef.JBC__NULL2_swigconstant(_jbcmsgdef)
JBC__NULL2 = _jbcmsgdef.JBC__NULL2

_jbcmsgdef.JBC__QMANNOTSTARTED_swigconstant(_jbcmsgdef)
JBC__QMANNOTSTARTED = _jbcmsgdef.JBC__QMANNOTSTARTED

_jbcmsgdef.JBC__BUFTOOSMALL_swigconstant(_jbcmsgdef)
JBC__BUFTOOSMALL = _jbcmsgdef.JBC__BUFTOOSMALL

_jbcmsgdef.JBC__INTERNALERROR_swigconstant(_jbcmsgdef)
JBC__INTERNALERROR = _jbcmsgdef.JBC__INTERNALERROR

_jbcmsgdef.JBC__QMGREXISTS_swigconstant(_jbcmsgdef)
JBC__QMGREXISTS = _jbcmsgdef.JBC__QMGREXISTS

_jbcmsgdef.JBC__TWOQMGRS_swigconstant(_jbcmsgdef)
JBC__TWOQMGRS = _jbcmsgdef.JBC__TWOQMGRS

_jbcmsgdef.JBC__INVQMANNAM_swigconstant(_jbcmsgdef)
JBC__INVQMANNAM = _jbcmsgdef.JBC__INVQMANNAM

_jbcmsgdef.JBC__NOMOREQMGR_swigconstant(_jbcmsgdef)
JBC__NOMOREQMGR = _jbcmsgdef.JBC__NOMOREQMGR

_jbcmsgdef.JBC__QMANABORT_swigconstant(_jbcmsgdef)
JBC__QMANABORT = _jbcmsgdef.JBC__QMANABORT

_jbcmsgdef.JBC__ACCDISERR_swigconstant(_jbcmsgdef)
JBC__ACCDISERR = _jbcmsgdef.JBC__ACCDISERR

_jbcmsgdef.JBC__ALLOCMEM_swigconstant(_jbcmsgdef)
JBC__ALLOCMEM = _jbcmsgdef.JBC__ALLOCMEM

_jbcmsgdef.JBC__COMREMJBC_swigconstant(_jbcmsgdef)
JBC__COMREMJBC = _jbcmsgdef.JBC__COMREMJBC

_jbcmsgdef.JBC__INVBLOCK_swigconstant(_jbcmsgdef)
JBC__INVBLOCK = _jbcmsgdef.JBC__INVBLOCK

_jbcmsgdef.JBC__INVMSG_swigconstant(_jbcmsgdef)
JBC__INVMSG = _jbcmsgdef.JBC__INVMSG

_jbcmsgdef.JBC__NEWQUEUE_swigconstant(_jbcmsgdef)
JBC__NEWQUEUE = _jbcmsgdef.JBC__NEWQUEUE

_jbcmsgdef.JBC__OPEJBCMBX_swigconstant(_jbcmsgdef)
JBC__OPEJBCMBX = _jbcmsgdef.JBC__OPEJBCMBX

_jbcmsgdef.JBC__PRCREAT_swigconstant(_jbcmsgdef)
JBC__PRCREAT = _jbcmsgdef.JBC__PRCREAT

_jbcmsgdef.JBC__QUEFORMAT_swigconstant(_jbcmsgdef)
JBC__QUEFORMAT = _jbcmsgdef.JBC__QUEFORMAT

_jbcmsgdef.JBC__REAJBCMBX_swigconstant(_jbcmsgdef)
JBC__REAJBCMBX = _jbcmsgdef.JBC__REAJBCMBX

_jbcmsgdef.JBC__REQUEST_swigconstant(_jbcmsgdef)
JBC__REQUEST = _jbcmsgdef.JBC__REQUEST

_jbcmsgdef.JBC__SETIMR_swigconstant(_jbcmsgdef)
JBC__SETIMR = _jbcmsgdef.JBC__SETIMR

_jbcmsgdef.JBC__SYMCREPRC_swigconstant(_jbcmsgdef)
JBC__SYMCREPRC = _jbcmsgdef.JBC__SYMCREPRC

_jbcmsgdef.JBC__SYMDEL_swigconstant(_jbcmsgdef)
JBC__SYMDEL = _jbcmsgdef.JBC__SYMDEL

_jbcmsgdef.JBC__WRIRSPMSG_swigconstant(_jbcmsgdef)
JBC__WRIRSPMSG = _jbcmsgdef.JBC__WRIRSPMSG

_jbcmsgdef.JBC__WRISMBMBX_swigconstant(_jbcmsgdef)
JBC__WRISMBMBX = _jbcmsgdef.JBC__WRISMBMBX

_jbcmsgdef.JBC__NFY_COMPLETE_swigconstant(_jbcmsgdef)
JBC__NFY_COMPLETE = _jbcmsgdef.JBC__NFY_COMPLETE

_jbcmsgdef.JBC__NFY_CURRENT_swigconstant(_jbcmsgdef)
JBC__NFY_CURRENT = _jbcmsgdef.JBC__NFY_CURRENT

_jbcmsgdef.JBC__NFY_HOLD_swigconstant(_jbcmsgdef)
JBC__NFY_HOLD = _jbcmsgdef.JBC__NFY_HOLD

_jbcmsgdef.JBC__NFY_PENDING_swigconstant(_jbcmsgdef)
JBC__NFY_PENDING = _jbcmsgdef.JBC__NFY_PENDING

_jbcmsgdef.JBC__NFY_TIMER_swigconstant(_jbcmsgdef)
JBC__NFY_TIMER = _jbcmsgdef.JBC__NFY_TIMER

_jbcmsgdef.JBC__STRUCT_LEVEL_swigconstant(_jbcmsgdef)
JBC__STRUCT_LEVEL = _jbcmsgdef.JBC__STRUCT_LEVEL

_jbcmsgdef.JBC__DIAGNOSTIC_swigconstant(_jbcmsgdef)
JBC__DIAGNOSTIC = _jbcmsgdef.JBC__DIAGNOSTIC

_jbcmsgdef.JBC__DIAG_TEXT_swigconstant(_jbcmsgdef)
JBC__DIAG_TEXT = _jbcmsgdef.JBC__DIAG_TEXT

_jbcmsgdef.JBC__DIAG_DATA_swigconstant(_jbcmsgdef)
JBC__DIAG_DATA = _jbcmsgdef.JBC__DIAG_DATA

_jbcmsgdef.JBC__RESTRICT_swigconstant(_jbcmsgdef)
JBC__RESTRICT = _jbcmsgdef.JBC__RESTRICT

_jbcmsgdef.JBC__NFY_FAILURE_swigconstant(_jbcmsgdef)
JBC__NFY_FAILURE = _jbcmsgdef.JBC__NFY_FAILURE

_jbcmsgdef.JBC__NFY_CPULIM_swigconstant(_jbcmsgdef)
JBC__NFY_CPULIM = _jbcmsgdef.JBC__NFY_CPULIM

_jbcmsgdef.JBC__NFY_WSVAL_swigconstant(_jbcmsgdef)
JBC__NFY_WSVAL = _jbcmsgdef.JBC__NFY_WSVAL

_jbcmsgdef.JBC__RESTARTCOM_swigconstant(_jbcmsgdef)
JBC__RESTARTCOM = _jbcmsgdef.JBC__RESTARTCOM

_jbcmsgdef.JBC__NFY_NOACCESS_swigconstant(_jbcmsgdef)
JBC__NFY_NOACCESS = _jbcmsgdef.JBC__NFY_NOACCESS

_jbcmsgdef.JBC__NFY_CHARAC_swigconstant(_jbcmsgdef)
JBC__NFY_CHARAC = _jbcmsgdef.JBC__NFY_CHARAC

_jbcmsgdef.JBC__NFY_NOLOWER_swigconstant(_jbcmsgdef)
JBC__NFY_NOLOWER = _jbcmsgdef.JBC__NFY_NOLOWER

_jbcmsgdef.JBC__NFY_SIZE_MIN_swigconstant(_jbcmsgdef)
JBC__NFY_SIZE_MIN = _jbcmsgdef.JBC__NFY_SIZE_MIN

_jbcmsgdef.JBC__NFY_SIZE_MAX_swigconstant(_jbcmsgdef)
JBC__NFY_SIZE_MAX = _jbcmsgdef.JBC__NFY_SIZE_MAX

_jbcmsgdef.JBC__NFY_FORM_swigconstant(_jbcmsgdef)
JBC__NFY_FORM = _jbcmsgdef.JBC__NFY_FORM

_jbcmsgdef.JBC__NFY_QUESTATE_swigconstant(_jbcmsgdef)
JBC__NFY_QUESTATE = _jbcmsgdef.JBC__NFY_QUESTATE

_jbcmsgdef.JBC__FAILCREPRC_swigconstant(_jbcmsgdef)
JBC__FAILCREPRC = _jbcmsgdef.JBC__FAILCREPRC

_jbcmsgdef.JBC__QMANCREPRC_swigconstant(_jbcmsgdef)
JBC__QMANCREPRC = _jbcmsgdef.JBC__QMANCREPRC

_jbcmsgdef.JBC__INITFAIL_swigconstant(_jbcmsgdef)
JBC__INITFAIL = _jbcmsgdef.JBC__INITFAIL

_jbcmsgdef.JBC__QMANDEL_swigconstant(_jbcmsgdef)
JBC__QMANDEL = _jbcmsgdef.JBC__QMANDEL

_jbcmsgdef.JBC__NOTIMZONRUL_swigconstant(_jbcmsgdef)
JBC__NOTIMZONRUL = _jbcmsgdef.JBC__NOTIMZONRUL

_jbcmsgdef.JBC__LMFPRCFAIL_swigconstant(_jbcmsgdef)
JBC__LMFPRCFAIL = _jbcmsgdef.JBC__LMFPRCFAIL

_jbcmsgdef.JBC__LMFLICERR_swigconstant(_jbcmsgdef)
JBC__LMFLICERR = _jbcmsgdef.JBC__LMFLICERR

_jbcmsgdef.JBC__LMFERROR_swigconstant(_jbcmsgdef)
JBC__LMFERROR = _jbcmsgdef.JBC__LMFERROR

_jbcmsgdef.JBC__ACCNOTENB_swigconstant(_jbcmsgdef)
JBC__ACCNOTENB = _jbcmsgdef.JBC__ACCNOTENB
# This file is compatible with both classic and new-style classes.


