# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ssdef', [dirname(__file__)])
        except ImportError:
            import _ssdef
            return _ssdef
        if fp is not None:
            try:
                _mod = imp.load_module('_ssdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ssdef = swig_import_helper()
    del swig_import_helper
else:
    import _ssdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_ssdef.SYSTEM__FACILITY_swigconstant(_ssdef)
SYSTEM__FACILITY = _ssdef.SYSTEM__FACILITY

_ssdef.SS__NORMAL_swigconstant(_ssdef)
SS__NORMAL = _ssdef.SS__NORMAL

_ssdef.SS__CONTINUE_swigconstant(_ssdef)
SS__CONTINUE = _ssdef.SS__CONTINUE

_ssdef.SS__WASCLR_swigconstant(_ssdef)
SS__WASCLR = _ssdef.SS__WASCLR

_ssdef.SS__WASSET_swigconstant(_ssdef)
SS__WASSET = _ssdef.SS__WASSET

_ssdef.SS__REMEMBER_swigconstant(_ssdef)
SS__REMEMBER = _ssdef.SS__REMEMBER

_ssdef.SS__ACCVIO_swigconstant(_ssdef)
SS__ACCVIO = _ssdef.SS__ACCVIO

_ssdef.SS__BADPARAM_swigconstant(_ssdef)
SS__BADPARAM = _ssdef.SS__BADPARAM

_ssdef.SS__EXQUOTA_swigconstant(_ssdef)
SS__EXQUOTA = _ssdef.SS__EXQUOTA

_ssdef.SS__NOPRIV_swigconstant(_ssdef)
SS__NOPRIV = _ssdef.SS__NOPRIV

_ssdef.SS__ABORT_swigconstant(_ssdef)
SS__ABORT = _ssdef.SS__ABORT

_ssdef.SS__BADATTRIB_swigconstant(_ssdef)
SS__BADATTRIB = _ssdef.SS__BADATTRIB

_ssdef.SS__BADESCAPE_swigconstant(_ssdef)
SS__BADESCAPE = _ssdef.SS__BADESCAPE

_ssdef.SS__BADIMGHDR_swigconstant(_ssdef)
SS__BADIMGHDR = _ssdef.SS__BADIMGHDR

_ssdef.SS__CHANINTLK_swigconstant(_ssdef)
SS__CHANINTLK = _ssdef.SS__CHANINTLK

_ssdef.SS__CTRLERR_swigconstant(_ssdef)
SS__CTRLERR = _ssdef.SS__CTRLERR

_ssdef.SS__DATACHECK_swigconstant(_ssdef)
SS__DATACHECK = _ssdef.SS__DATACHECK

_ssdef.SS__DEVFOREIGN_swigconstant(_ssdef)
SS__DEVFOREIGN = _ssdef.SS__DEVFOREIGN

_ssdef.SS__DEVMOUNT_swigconstant(_ssdef)
SS__DEVMOUNT = _ssdef.SS__DEVMOUNT

_ssdef.SS__DEVNOTMBX_swigconstant(_ssdef)
SS__DEVNOTMBX = _ssdef.SS__DEVNOTMBX

_ssdef.SS__DEVNOTMOUNT_swigconstant(_ssdef)
SS__DEVNOTMOUNT = _ssdef.SS__DEVNOTMOUNT

_ssdef.SS__DEVOFFLINE_swigconstant(_ssdef)
SS__DEVOFFLINE = _ssdef.SS__DEVOFFLINE

_ssdef.SS__DRVERR_swigconstant(_ssdef)
SS__DRVERR = _ssdef.SS__DRVERR

_ssdef.SS__DUPLNAM_swigconstant(_ssdef)
SS__DUPLNAM = _ssdef.SS__DUPLNAM

_ssdef.SS__FILACCERR_swigconstant(_ssdef)
SS__FILACCERR = _ssdef.SS__FILACCERR

_ssdef.SS__FILALRACC_swigconstant(_ssdef)
SS__FILALRACC = _ssdef.SS__FILALRACC

_ssdef.SS__FILNOTACC_swigconstant(_ssdef)
SS__FILNOTACC = _ssdef.SS__FILNOTACC

_ssdef.SS__FILNOTEXP_swigconstant(_ssdef)
SS__FILNOTEXP = _ssdef.SS__FILNOTEXP

_ssdef.SS__FORMAT_swigconstant(_ssdef)
SS__FORMAT = _ssdef.SS__FORMAT

_ssdef.SS__GPTFULL_swigconstant(_ssdef)
SS__GPTFULL = _ssdef.SS__GPTFULL

_ssdef.SS__GSDFULL_swigconstant(_ssdef)
SS__GSDFULL = _ssdef.SS__GSDFULL

_ssdef.SS__LCKPAGFUL_swigconstant(_ssdef)
SS__LCKPAGFUL = _ssdef.SS__LCKPAGFUL

_ssdef.SS__ILLBLKNUM_swigconstant(_ssdef)
SS__ILLBLKNUM = _ssdef.SS__ILLBLKNUM

_ssdef.SS__ILLCNTRFUNC_swigconstant(_ssdef)
SS__ILLCNTRFUNC = _ssdef.SS__ILLCNTRFUNC

_ssdef.SS__ILLEFC_swigconstant(_ssdef)
SS__ILLEFC = _ssdef.SS__ILLEFC

_ssdef.SS__ILLIOFUNC_swigconstant(_ssdef)
SS__ILLIOFUNC = _ssdef.SS__ILLIOFUNC

_ssdef.SS__ILLPAGCNT_swigconstant(_ssdef)
SS__ILLPAGCNT = _ssdef.SS__ILLPAGCNT

_ssdef.SS__ILLSER_swigconstant(_ssdef)
SS__ILLSER = _ssdef.SS__ILLSER

_ssdef.SS__INCVOLLABEL_swigconstant(_ssdef)
SS__INCVOLLABEL = _ssdef.SS__INCVOLLABEL

_ssdef.SS__INSFARG_swigconstant(_ssdef)
SS__INSFARG = _ssdef.SS__INSFARG

_ssdef.SS__INSFWSL_swigconstant(_ssdef)
SS__INSFWSL = _ssdef.SS__INSFWSL

_ssdef.SS__INSFMEM_swigconstant(_ssdef)
SS__INSFMEM = _ssdef.SS__INSFMEM

_ssdef.SS__INSFRAME_swigconstant(_ssdef)
SS__INSFRAME = _ssdef.SS__INSFRAME

_ssdef.SS__IVADDR_swigconstant(_ssdef)
SS__IVADDR = _ssdef.SS__IVADDR

_ssdef.SS__IVCHAN_swigconstant(_ssdef)
SS__IVCHAN = _ssdef.SS__IVCHAN

_ssdef.SS__IVDEVNAM_swigconstant(_ssdef)
SS__IVDEVNAM = _ssdef.SS__IVDEVNAM

_ssdef.SS__IVGSDNAM_swigconstant(_ssdef)
SS__IVGSDNAM = _ssdef.SS__IVGSDNAM

_ssdef.SS__IVLOGNAM_swigconstant(_ssdef)
SS__IVLOGNAM = _ssdef.SS__IVLOGNAM

_ssdef.SS__IVLOGTAB_swigconstant(_ssdef)
SS__IVLOGTAB = _ssdef.SS__IVLOGTAB

_ssdef.SS__IVQUOTAL_swigconstant(_ssdef)
SS__IVQUOTAL = _ssdef.SS__IVQUOTAL

_ssdef.SS__IVSECFLG_swigconstant(_ssdef)
SS__IVSECFLG = _ssdef.SS__IVSECFLG

_ssdef.SS__IVSSRQ_swigconstant(_ssdef)
SS__IVSSRQ = _ssdef.SS__IVSSRQ

_ssdef.SS__IVSTSFLG_swigconstant(_ssdef)
SS__IVSTSFLG = _ssdef.SS__IVSTSFLG

_ssdef.SS__IVTIME_swigconstant(_ssdef)
SS__IVTIME = _ssdef.SS__IVTIME

_ssdef.SS__LENVIO_swigconstant(_ssdef)
SS__LENVIO = _ssdef.SS__LENVIO

_ssdef.SS__LKWSETFUL_swigconstant(_ssdef)
SS__LKWSETFUL = _ssdef.SS__LKWSETFUL

_ssdef.SS__MBTOOSML_swigconstant(_ssdef)
SS__MBTOOSML = _ssdef.SS__MBTOOSML

_ssdef.SS__MEDOFL_swigconstant(_ssdef)
SS__MEDOFL = _ssdef.SS__MEDOFL

_ssdef.SS__NODATA_swigconstant(_ssdef)
SS__NODATA = _ssdef.SS__NODATA

_ssdef.SS__NOIOCHAN_swigconstant(_ssdef)
SS__NOIOCHAN = _ssdef.SS__NOIOCHAN

_ssdef.SS__NOLOGNAM_swigconstant(_ssdef)
SS__NOLOGNAM = _ssdef.SS__NOLOGNAM

_ssdef.SS__NONEXDRV_swigconstant(_ssdef)
SS__NONEXDRV = _ssdef.SS__NONEXDRV

_ssdef.SS__NOTFILEDEV_swigconstant(_ssdef)
SS__NOTFILEDEV = _ssdef.SS__NOTFILEDEV

_ssdef.SS__NOTINTBLSZ_swigconstant(_ssdef)
SS__NOTINTBLSZ = _ssdef.SS__NOTINTBLSZ

_ssdef.SS__NOTLABELMT_swigconstant(_ssdef)
SS__NOTLABELMT = _ssdef.SS__NOTLABELMT

_ssdef.SS__NOTSQDEV_swigconstant(_ssdef)
SS__NOTSQDEV = _ssdef.SS__NOTSQDEV

_ssdef.SS__PAGOWNVIO_swigconstant(_ssdef)
SS__PAGOWNVIO = _ssdef.SS__PAGOWNVIO

_ssdef.SS__PARITY_swigconstant(_ssdef)
SS__PARITY = _ssdef.SS__PARITY

_ssdef.SS__PARTESCAPE_swigconstant(_ssdef)
SS__PARTESCAPE = _ssdef.SS__PARTESCAPE

_ssdef.SS__PFMBSY_swigconstant(_ssdef)
SS__PFMBSY = _ssdef.SS__PFMBSY

_ssdef.SS__PSTFULL_swigconstant(_ssdef)
SS__PSTFULL = _ssdef.SS__PSTFULL

_ssdef.SS__RESULTOVF_swigconstant(_ssdef)
SS__RESULTOVF = _ssdef.SS__RESULTOVF

_ssdef.SS__SECTBLFUL_swigconstant(_ssdef)
SS__SECTBLFUL = _ssdef.SS__SECTBLFUL

_ssdef.SS__TAPEPOSLOST_swigconstant(_ssdef)
SS__TAPEPOSLOST = _ssdef.SS__TAPEPOSLOST

_ssdef.SS__TIMEOUT_swigconstant(_ssdef)
SS__TIMEOUT = _ssdef.SS__TIMEOUT

_ssdef.SS__UNASEFC_swigconstant(_ssdef)
SS__UNASEFC = _ssdef.SS__UNASEFC

_ssdef.SS__UNSAFE_swigconstant(_ssdef)
SS__UNSAFE = _ssdef.SS__UNSAFE

_ssdef.SS__VASFULL_swigconstant(_ssdef)
SS__VASFULL = _ssdef.SS__VASFULL

_ssdef.SS__VECINUSE_swigconstant(_ssdef)
SS__VECINUSE = _ssdef.SS__VECINUSE

_ssdef.SS__VOLINV_swigconstant(_ssdef)
SS__VOLINV = _ssdef.SS__VOLINV

_ssdef.SS__WRITLCK_swigconstant(_ssdef)
SS__WRITLCK = _ssdef.SS__WRITLCK

_ssdef.SS__NOTAPEOP_swigconstant(_ssdef)
SS__NOTAPEOP = _ssdef.SS__NOTAPEOP

_ssdef.SS__IVCHNLSEC_swigconstant(_ssdef)
SS__IVCHNLSEC = _ssdef.SS__IVCHNLSEC

_ssdef.SS__NOMBX_swigconstant(_ssdef)
SS__NOMBX = _ssdef.SS__NOMBX

_ssdef.SS__NOLINKS_swigconstant(_ssdef)
SS__NOLINKS = _ssdef.SS__NOLINKS

_ssdef.SS__NOSOLICIT_swigconstant(_ssdef)
SS__NOSOLICIT = _ssdef.SS__NOSOLICIT

_ssdef.SS__NOSUCHNODE_swigconstant(_ssdef)
SS__NOSUCHNODE = _ssdef.SS__NOSUCHNODE

_ssdef.SS__REJECT_swigconstant(_ssdef)
SS__REJECT = _ssdef.SS__REJECT

_ssdef.SS__TOOMUCHDATA_swigconstant(_ssdef)
SS__TOOMUCHDATA = _ssdef.SS__TOOMUCHDATA

_ssdef.SS__BUGCHECK_swigconstant(_ssdef)
SS__BUGCHECK = _ssdef.SS__BUGCHECK

_ssdef.SS__FILNOTCNTG_swigconstant(_ssdef)
SS__FILNOTCNTG = _ssdef.SS__FILNOTCNTG

_ssdef.SS__BADSTACK_swigconstant(_ssdef)
SS__BADSTACK = _ssdef.SS__BADSTACK

_ssdef.SS__MCHECK_swigconstant(_ssdef)
SS__MCHECK = _ssdef.SS__MCHECK

_ssdef.SS__DEVACTIVE_swigconstant(_ssdef)
SS__DEVACTIVE = _ssdef.SS__DEVACTIVE

_ssdef.SS__HANGUP_swigconstant(_ssdef)
SS__HANGUP = _ssdef.SS__HANGUP

_ssdef.SS__OPINCOMPL_swigconstant(_ssdef)
SS__OPINCOMPL = _ssdef.SS__OPINCOMPL

_ssdef.SS__ILLSEQOP_swigconstant(_ssdef)
SS__ILLSEQOP = _ssdef.SS__ILLSEQOP

_ssdef.SS__IVSECIDCTL_swigconstant(_ssdef)
SS__IVSECIDCTL = _ssdef.SS__IVSECIDCTL

_ssdef.SS__NOTNETDEV_swigconstant(_ssdef)
SS__NOTNETDEV = _ssdef.SS__NOTNETDEV

_ssdef.SS__IVPROTECT_swigconstant(_ssdef)
SS__IVPROTECT = _ssdef.SS__IVPROTECT

_ssdef.SS__ACPVAFUL_swigconstant(_ssdef)
SS__ACPVAFUL = _ssdef.SS__ACPVAFUL

_ssdef.SS__MTLBLLONG_swigconstant(_ssdef)
SS__MTLBLLONG = _ssdef.SS__MTLBLLONG

_ssdef.SS__BUFBYTALI_swigconstant(_ssdef)
SS__BUFBYTALI = _ssdef.SS__BUFBYTALI

_ssdef.SS__NOAQB_swigconstant(_ssdef)
SS__NOAQB = _ssdef.SS__NOAQB

_ssdef.SS__WRONGACP_swigconstant(_ssdef)
SS__WRONGACP = _ssdef.SS__WRONGACP

_ssdef.SS__BUFNOTALIGN_swigconstant(_ssdef)
SS__BUFNOTALIGN = _ssdef.SS__BUFNOTALIGN

_ssdef.SS__DEVCMDERR_swigconstant(_ssdef)
SS__DEVCMDERR = _ssdef.SS__DEVCMDERR

_ssdef.SS__DEVREQERR_swigconstant(_ssdef)
SS__DEVREQERR = _ssdef.SS__DEVREQERR

_ssdef.SS__INSFBUFDP_swigconstant(_ssdef)
SS__INSFBUFDP = _ssdef.SS__INSFBUFDP

_ssdef.SS__INSFMAPREG_swigconstant(_ssdef)
SS__INSFMAPREG = _ssdef.SS__INSFMAPREG

_ssdef.SS__IVBUFLEN_swigconstant(_ssdef)
SS__IVBUFLEN = _ssdef.SS__IVBUFLEN

_ssdef.SS__IVMODE_swigconstant(_ssdef)
SS__IVMODE = _ssdef.SS__IVMODE

_ssdef.SS__MCNOTVALID_swigconstant(_ssdef)
SS__MCNOTVALID = _ssdef.SS__MCNOTVALID

_ssdef.SS__POWERFAIL_swigconstant(_ssdef)
SS__POWERFAIL = _ssdef.SS__POWERFAIL

_ssdef.SS__SHMGSNOTMAP_swigconstant(_ssdef)
SS__SHMGSNOTMAP = _ssdef.SS__SHMGSNOTMAP

_ssdef.SS__TOOMANYLNAM_swigconstant(_ssdef)
SS__TOOMANYLNAM = _ssdef.SS__TOOMANYLNAM

_ssdef.SS__SHMNOTCNCT_swigconstant(_ssdef)
SS__SHMNOTCNCT = _ssdef.SS__SHMNOTCNCT

_ssdef.SS__NOTCREATOR_swigconstant(_ssdef)
SS__NOTCREATOR = _ssdef.SS__NOTCREATOR

_ssdef.SS__INTERLOCK_swigconstant(_ssdef)
SS__INTERLOCK = _ssdef.SS__INTERLOCK

_ssdef.SS__BADQUEUEHDR_swigconstant(_ssdef)
SS__BADQUEUEHDR = _ssdef.SS__BADQUEUEHDR

_ssdef.SS__NOSLOT_swigconstant(_ssdef)
SS__NOSLOT = _ssdef.SS__NOSLOT

_ssdef.SS__SUSPENDED_swigconstant(_ssdef)
SS__SUSPENDED = _ssdef.SS__SUSPENDED

_ssdef.SS__EXPORTQUOTA_swigconstant(_ssdef)
SS__EXPORTQUOTA = _ssdef.SS__EXPORTQUOTA

_ssdef.SS__NOSHMBLOCK_swigconstant(_ssdef)
SS__NOSHMBLOCK = _ssdef.SS__NOSHMBLOCK

_ssdef.SS__BADQFILE_swigconstant(_ssdef)
SS__BADQFILE = _ssdef.SS__BADQFILE

_ssdef.SS__NOQFILE_swigconstant(_ssdef)
SS__NOQFILE = _ssdef.SS__NOQFILE

_ssdef.SS__QFACTIVE_swigconstant(_ssdef)
SS__QFACTIVE = _ssdef.SS__QFACTIVE

_ssdef.SS__QFNOTACT_swigconstant(_ssdef)
SS__QFNOTACT = _ssdef.SS__QFNOTACT

_ssdef.SS__DUPDSKQUOTA_swigconstant(_ssdef)
SS__DUPDSKQUOTA = _ssdef.SS__DUPDSKQUOTA

_ssdef.SS__NODISKQUOTA_swigconstant(_ssdef)
SS__NODISKQUOTA = _ssdef.SS__NODISKQUOTA

_ssdef.SS__EXDISKQUOTA_swigconstant(_ssdef)
SS__EXDISKQUOTA = _ssdef.SS__EXDISKQUOTA

_ssdef.SS__IDMISMATCH_swigconstant(_ssdef)
SS__IDMISMATCH = _ssdef.SS__IDMISMATCH

_ssdef.SS__NOWRT_swigconstant(_ssdef)
SS__NOWRT = _ssdef.SS__NOWRT

_ssdef.SS__BADISD_swigconstant(_ssdef)
SS__BADISD = _ssdef.SS__BADISD

_ssdef.SS__RELINK_swigconstant(_ssdef)
SS__RELINK = _ssdef.SS__RELINK

_ssdef.SS__NOTINSTALL_swigconstant(_ssdef)
SS__NOTINSTALL = _ssdef.SS__NOTINSTALL

_ssdef.SS__SHARTOOBIG_swigconstant(_ssdef)
SS__SHARTOOBIG = _ssdef.SS__SHARTOOBIG

_ssdef.SS__NOP1VA_swigconstant(_ssdef)
SS__NOP1VA = _ssdef.SS__NOP1VA

_ssdef.SS__MULTRMS_swigconstant(_ssdef)
SS__MULTRMS = _ssdef.SS__MULTRMS

_ssdef.SS__VECFULL_swigconstant(_ssdef)
SS__VECFULL = _ssdef.SS__VECFULL

_ssdef.SS__IVLVEC_swigconstant(_ssdef)
SS__IVLVEC = _ssdef.SS__IVLVEC

_ssdef.SS__INSFSPTS_swigconstant(_ssdef)
SS__INSFSPTS = _ssdef.SS__INSFSPTS

_ssdef.SS__DISCONNECT_swigconstant(_ssdef)
SS__DISCONNECT = _ssdef.SS__DISCONNECT

_ssdef.SS__PRIVINSTALL_swigconstant(_ssdef)
SS__PRIVINSTALL = _ssdef.SS__PRIVINSTALL

_ssdef.SS__PROTINSTALL_swigconstant(_ssdef)
SS__PROTINSTALL = _ssdef.SS__PROTINSTALL

_ssdef.SS__BADVEC_swigconstant(_ssdef)
SS__BADVEC = _ssdef.SS__BADVEC

_ssdef.SS__REMRSRC_swigconstant(_ssdef)
SS__REMRSRC = _ssdef.SS__REMRSRC

_ssdef.SS__PROTOCOL_swigconstant(_ssdef)
SS__PROTOCOL = _ssdef.SS__PROTOCOL

_ssdef.SS__THIRDPARTY_swigconstant(_ssdef)
SS__THIRDPARTY = _ssdef.SS__THIRDPARTY

_ssdef.SS__NOSUCHUSER_swigconstant(_ssdef)
SS__NOSUCHUSER = _ssdef.SS__NOSUCHUSER

_ssdef.SS__SHUT_swigconstant(_ssdef)
SS__SHUT = _ssdef.SS__SHUT

_ssdef.SS__UNREACHABLE_swigconstant(_ssdef)
SS__UNREACHABLE = _ssdef.SS__UNREACHABLE

_ssdef.SS__INVLOGIN_swigconstant(_ssdef)
SS__INVLOGIN = _ssdef.SS__INVLOGIN

_ssdef.SS__NOSUCHOBJ_swigconstant(_ssdef)
SS__NOSUCHOBJ = _ssdef.SS__NOSUCHOBJ

_ssdef.SS__EXCPUTIM_swigconstant(_ssdef)
SS__EXCPUTIM = _ssdef.SS__EXCPUTIM

_ssdef.SS__OPRABORT_swigconstant(_ssdef)
SS__OPRABORT = _ssdef.SS__OPRABORT

_ssdef.SS__SHRIDMISMAT_swigconstant(_ssdef)
SS__SHRIDMISMAT = _ssdef.SS__SHRIDMISMAT

_ssdef.SS__COMMHARD_swigconstant(_ssdef)
SS__COMMHARD = _ssdef.SS__COMMHARD

_ssdef.SS__IVCHAR_swigconstant(_ssdef)
SS__IVCHAR = _ssdef.SS__IVCHAR

_ssdef.SS__DEVINACT_swigconstant(_ssdef)
SS__DEVINACT = _ssdef.SS__DEVINACT

_ssdef.SS__CONNECFAIL_swigconstant(_ssdef)
SS__CONNECFAIL = _ssdef.SS__CONNECFAIL

_ssdef.SS__LINKABORT_swigconstant(_ssdef)
SS__LINKABORT = _ssdef.SS__LINKABORT

_ssdef.SS__LINKDISCON_swigconstant(_ssdef)
SS__LINKDISCON = _ssdef.SS__LINKDISCON

_ssdef.SS__LINKEXIT_swigconstant(_ssdef)
SS__LINKEXIT = _ssdef.SS__LINKEXIT

_ssdef.SS__PATHLOST_swigconstant(_ssdef)
SS__PATHLOST = _ssdef.SS__PATHLOST

_ssdef.SS__CLEARED_swigconstant(_ssdef)
SS__CLEARED = _ssdef.SS__CLEARED

_ssdef.SS__RESET_swigconstant(_ssdef)
SS__RESET = _ssdef.SS__RESET

_ssdef.SS__UNSOLICIT_swigconstant(_ssdef)
SS__UNSOLICIT = _ssdef.SS__UNSOLICIT

_ssdef.SS__TOOMANYREDS_swigconstant(_ssdef)
SS__TOOMANYREDS = _ssdef.SS__TOOMANYREDS

_ssdef.SS__IVLOCKID_swigconstant(_ssdef)
SS__IVLOCKID = _ssdef.SS__IVLOCKID

_ssdef.SS__SUBLOCKS_swigconstant(_ssdef)
SS__SUBLOCKS = _ssdef.SS__SUBLOCKS

_ssdef.SS__PARNOTGRANT_swigconstant(_ssdef)
SS__PARNOTGRANT = _ssdef.SS__PARNOTGRANT

_ssdef.SS__CVTUNGRANT_swigconstant(_ssdef)
SS__CVTUNGRANT = _ssdef.SS__CVTUNGRANT

_ssdef.SS__FORCEDERROR_swigconstant(_ssdef)
SS__FORCEDERROR = _ssdef.SS__FORCEDERROR

_ssdef.SS__ILLSELF_swigconstant(_ssdef)
SS__ILLSELF = _ssdef.SS__ILLSELF

_ssdef.SS__ILLCDTST_swigconstant(_ssdef)
SS__ILLCDTST = _ssdef.SS__ILLCDTST

_ssdef.SS__NOLISTENER_swigconstant(_ssdef)
SS__NOLISTENER = _ssdef.SS__NOLISTENER

_ssdef.SS__EXGBLPAGFIL_swigconstant(_ssdef)
SS__EXGBLPAGFIL = _ssdef.SS__EXGBLPAGFIL

_ssdef.SS__BADRCT_swigconstant(_ssdef)
SS__BADRCT = _ssdef.SS__BADRCT

_ssdef.SS__DIRNOTEMPTY_swigconstant(_ssdef)
SS__DIRNOTEMPTY = _ssdef.SS__DIRNOTEMPTY

_ssdef.SS__FORCEDEXIT_swigconstant(_ssdef)
SS__FORCEDEXIT = _ssdef.SS__FORCEDEXIT

_ssdef.SS__NOTPRINTED_swigconstant(_ssdef)
SS__NOTPRINTED = _ssdef.SS__NOTPRINTED

_ssdef.SS__JBCERROR_swigconstant(_ssdef)
SS__JBCERROR = _ssdef.SS__JBCERROR

_ssdef.SS__NOLICENSE_swigconstant(_ssdef)
SS__NOLICENSE = _ssdef.SS__NOLICENSE

_ssdef.SS__VCBROKEN_swigconstant(_ssdef)
SS__VCBROKEN = _ssdef.SS__VCBROKEN

_ssdef.SS__VCCLOSED_swigconstant(_ssdef)
SS__VCCLOSED = _ssdef.SS__VCCLOSED

_ssdef.SS__INSFCDT_swigconstant(_ssdef)
SS__INSFCDT = _ssdef.SS__INSFCDT

_ssdef.SS__DEVNOTDISM_swigconstant(_ssdef)
SS__DEVNOTDISM = _ssdef.SS__DEVNOTDISM

_ssdef.SS__NOSHRIMG_swigconstant(_ssdef)
SS__NOSHRIMG = _ssdef.SS__NOSHRIMG

_ssdef.SS__DUPUNIT_swigconstant(_ssdef)
SS__DUPUNIT = _ssdef.SS__DUPUNIT

_ssdef.SS__BADACLCTX_swigconstant(_ssdef)
SS__BADACLCTX = _ssdef.SS__BADACLCTX

_ssdef.SS__SERIOUSEXCP_swigconstant(_ssdef)
SS__SERIOUSEXCP = _ssdef.SS__SERIOUSEXCP

_ssdef.SS__TEMPLATEDEV_swigconstant(_ssdef)
SS__TEMPLATEDEV = _ssdef.SS__TEMPLATEDEV

_ssdef.SS__IVACL_swigconstant(_ssdef)
SS__IVACL = _ssdef.SS__IVACL

_ssdef.SS__NOSUCHID_swigconstant(_ssdef)
SS__NOSUCHID = _ssdef.SS__NOSUCHID

_ssdef.SS__NOLCLMEDA_swigconstant(_ssdef)
SS__NOLCLMEDA = _ssdef.SS__NOLCLMEDA

_ssdef.SS__NOREGAVIL_swigconstant(_ssdef)
SS__NOREGAVIL = _ssdef.SS__NOREGAVIL

_ssdef.SS__NOREGSUIT_swigconstant(_ssdef)
SS__NOREGSUIT = _ssdef.SS__NOREGSUIT

_ssdef.SS__NOSUCHPGM_swigconstant(_ssdef)
SS__NOSUCHPGM = _ssdef.SS__NOSUCHPGM

_ssdef.SS__PGMLDFAIL_swigconstant(_ssdef)
SS__PGMLDFAIL = _ssdef.SS__PGMLDFAIL

_ssdef.SS__PGMSTDALN_swigconstant(_ssdef)
SS__PGMSTDALN = _ssdef.SS__PGMSTDALN

_ssdef.SS__IVIDENT_swigconstant(_ssdef)
SS__IVIDENT = _ssdef.SS__IVIDENT

_ssdef.SS__DUPIDENT_swigconstant(_ssdef)
SS__DUPIDENT = _ssdef.SS__DUPIDENT

_ssdef.SS__INCSEGTRA_swigconstant(_ssdef)
SS__INCSEGTRA = _ssdef.SS__INCSEGTRA

_ssdef.SS__NODELEAVE_swigconstant(_ssdef)
SS__NODELEAVE = _ssdef.SS__NODELEAVE

_ssdef.SS__KERNELINV_swigconstant(_ssdef)
SS__KERNELINV = _ssdef.SS__KERNELINV

_ssdef.SS__EXLNMQUOTA_swigconstant(_ssdef)
SS__EXLNMQUOTA = _ssdef.SS__EXLNMQUOTA

_ssdef.SS__PARENT_DEL_swigconstant(_ssdef)
SS__PARENT_DEL = _ssdef.SS__PARENT_DEL

_ssdef.SS__PARNOTSYS_swigconstant(_ssdef)
SS__PARNOTSYS = _ssdef.SS__PARNOTSYS

_ssdef.SS__INSSWAPSPACE_swigconstant(_ssdef)
SS__INSSWAPSPACE = _ssdef.SS__INSSWAPSPACE

_ssdef.SS__VOLOERR_swigconstant(_ssdef)
SS__VOLOERR = _ssdef.SS__VOLOERR

_ssdef.SS__DATALATE_swigconstant(_ssdef)
SS__DATALATE = _ssdef.SS__DATALATE

_ssdef.SS__OVRMAXARG_swigconstant(_ssdef)
SS__OVRMAXARG = _ssdef.SS__OVRMAXARG

_ssdef.SS__SHACHASTA_swigconstant(_ssdef)
SS__SHACHASTA = _ssdef.SS__SHACHASTA

_ssdef.SS__TERMNETDEV_swigconstant(_ssdef)
SS__TERMNETDEV = _ssdef.SS__TERMNETDEV

_ssdef.SS__NOLOGTAB_swigconstant(_ssdef)
SS__NOLOGTAB = _ssdef.SS__NOLOGTAB

_ssdef.SS__WRONGNAME_swigconstant(_ssdef)
SS__WRONGNAME = _ssdef.SS__WRONGNAME

_ssdef.SS__NOVOLACC_swigconstant(_ssdef)
SS__NOVOLACC = _ssdef.SS__NOVOLACC

_ssdef.SS__NOFILACC_swigconstant(_ssdef)
SS__NOFILACC = _ssdef.SS__NOFILACC

_ssdef.SS__INVEXHLIST_swigconstant(_ssdef)
SS__INVEXHLIST = _ssdef.SS__INVEXHLIST

_ssdef.SS__NOACLSUPPORT_swigconstant(_ssdef)
SS__NOACLSUPPORT = _ssdef.SS__NOACLSUPPORT

_ssdef.SS__INVSECLASS_swigconstant(_ssdef)
SS__INVSECLASS = _ssdef.SS__INVSECLASS

_ssdef.SS__INCSHAMEM_swigconstant(_ssdef)
SS__INCSHAMEM = _ssdef.SS__INCSHAMEM

_ssdef.SS__DEVNOTSHR_swigconstant(_ssdef)
SS__DEVNOTSHR = _ssdef.SS__DEVNOTSHR

_ssdef.SS__RUCONFLICT_swigconstant(_ssdef)
SS__RUCONFLICT = _ssdef.SS__RUCONFLICT

_ssdef.SS__DATALOST_swigconstant(_ssdef)
SS__DATALOST = _ssdef.SS__DATALOST

_ssdef.SS__REMOTE_PROC_swigconstant(_ssdef)
SS__REMOTE_PROC = _ssdef.SS__REMOTE_PROC

_ssdef.SS__CPUNOTACT_swigconstant(_ssdef)
SS__CPUNOTACT = _ssdef.SS__CPUNOTACT

_ssdef.SS__SRVMMAT_swigconstant(_ssdef)
SS__SRVMMAT = _ssdef.SS__SRVMMAT

_ssdef.SS__EXLICENSE_swigconstant(_ssdef)
SS__EXLICENSE = _ssdef.SS__EXLICENSE

_ssdef.SS__INVLICENSE_swigconstant(_ssdef)
SS__INVLICENSE = _ssdef.SS__INVLICENSE

_ssdef.SS__LICENSE_LEVEL_swigconstant(_ssdef)
SS__LICENSE_LEVEL = _ssdef.SS__LICENSE_LEVEL

_ssdef.SS__INV_HW_ID_swigconstant(_ssdef)
SS__INV_HW_ID = _ssdef.SS__INV_HW_ID

_ssdef.SS__BADCONTEXT_swigconstant(_ssdef)
SS__BADCONTEXT = _ssdef.SS__BADCONTEXT

_ssdef.SS__TOOMUCHCTX_swigconstant(_ssdef)
SS__TOOMUCHCTX = _ssdef.SS__TOOMUCHCTX

_ssdef.SS__VA_IN_USE_swigconstant(_ssdef)
SS__VA_IN_USE = _ssdef.SS__VA_IN_USE

_ssdef.SS__NODELETE_swigconstant(_ssdef)
SS__NODELETE = _ssdef.SS__NODELETE

_ssdef.SS__NOSUCHCPU_swigconstant(_ssdef)
SS__NOSUCHCPU = _ssdef.SS__NOSUCHCPU

_ssdef.SS__IMGVEXC_swigconstant(_ssdef)
SS__IMGVEXC = _ssdef.SS__IMGVEXC

_ssdef.SS__NOSAVPEXC_swigconstant(_ssdef)
SS__NOSAVPEXC = _ssdef.SS__NOSAVPEXC

_ssdef.SS__NOSUCHTID_swigconstant(_ssdef)
SS__NOSUCHTID = _ssdef.SS__NOSUCHTID

_ssdef.SS__NOSUCHRM_swigconstant(_ssdef)
SS__NOSUCHRM = _ssdef.SS__NOSUCHRM

_ssdef.SS__NOCURTID_swigconstant(_ssdef)
SS__NOCURTID = _ssdef.SS__NOCURTID

_ssdef.SS__WRONGSTATE_swigconstant(_ssdef)
SS__WRONGSTATE = _ssdef.SS__WRONGSTATE

_ssdef.SS__VETO_swigconstant(_ssdef)
SS__VETO = _ssdef.SS__VETO

_ssdef.SS__PWDSYNTAX_swigconstant(_ssdef)
SS__PWDSYNTAX = _ssdef.SS__PWDSYNTAX

_ssdef.SS__PWDNOTDIF_swigconstant(_ssdef)
SS__PWDNOTDIF = _ssdef.SS__PWDNOTDIF

_ssdef.SS__INVPWDLEN_swigconstant(_ssdef)
SS__INVPWDLEN = _ssdef.SS__INVPWDLEN

_ssdef.SS__SYSVERDIF_swigconstant(_ssdef)
SS__SYSVERDIF = _ssdef.SS__SYSVERDIF

_ssdef.SS__HWM_STALL_swigconstant(_ssdef)
SS__HWM_STALL = _ssdef.SS__HWM_STALL

_ssdef.SS__NOSUSPEND_swigconstant(_ssdef)
SS__NOSUSPEND = _ssdef.SS__NOSUSPEND

_ssdef.SS__NOSUCHPART_swigconstant(_ssdef)
SS__NOSUCHPART = _ssdef.SS__NOSUCHPART

_ssdef.SS__RMALRDCL_swigconstant(_ssdef)
SS__RMALRDCL = _ssdef.SS__RMALRDCL

_ssdef.SS__ALRCURTID_swigconstant(_ssdef)
SS__ALRCURTID = _ssdef.SS__ALRCURTID

_ssdef.SS__INVLOG_swigconstant(_ssdef)
SS__INVLOG = _ssdef.SS__INVLOG

_ssdef.SS__BADLOGVER_swigconstant(_ssdef)
SS__BADLOGVER = _ssdef.SS__BADLOGVER

_ssdef.SS__OPINPROG_swigconstant(_ssdef)
SS__OPINPROG = _ssdef.SS__OPINPROG

_ssdef.SS__WRONGACMODE_swigconstant(_ssdef)
SS__WRONGACMODE = _ssdef.SS__WRONGACMODE

_ssdef.SS__SUBTRACED_swigconstant(_ssdef)
SS__SUBTRACED = _ssdef.SS__SUBTRACED

_ssdef.SS__ARCHIVING_swigconstant(_ssdef)
SS__ARCHIVING = _ssdef.SS__ARCHIVING

_ssdef.SS__ARCHIVED_swigconstant(_ssdef)
SS__ARCHIVED = _ssdef.SS__ARCHIVED

_ssdef.SS__SITEPWDFAIL_swigconstant(_ssdef)
SS__SITEPWDFAIL = _ssdef.SS__SITEPWDFAIL

_ssdef.SS__NOSUCHCPB_swigconstant(_ssdef)
SS__NOSUCHCPB = _ssdef.SS__NOSUCHCPB

_ssdef.SS__CPUCAP_swigconstant(_ssdef)
SS__CPUCAP = _ssdef.SS__CPUCAP

_ssdef.SS__LOADER_swigconstant(_ssdef)
SS__LOADER = _ssdef.SS__LOADER

_ssdef.SS__HSTBUFACC_swigconstant(_ssdef)
SS__HSTBUFACC = _ssdef.SS__HSTBUFACC

_ssdef.SS__INCONOLCK_swigconstant(_ssdef)
SS__INCONOLCK = _ssdef.SS__INCONOLCK

_ssdef.SS__INVEVENT_swigconstant(_ssdef)
SS__INVEVENT = _ssdef.SS__INVEVENT

_ssdef.SS__NOSUCHFAC_swigconstant(_ssdef)
SS__NOSUCHFAC = _ssdef.SS__NOSUCHFAC

_ssdef.SS__NOCALLPRIV_swigconstant(_ssdef)
SS__NOCALLPRIV = _ssdef.SS__NOCALLPRIV

_ssdef.SS__INSFLPGS_swigconstant(_ssdef)
SS__INSFLPGS = _ssdef.SS__INSFLPGS

_ssdef.SS__INSFRPGS_swigconstant(_ssdef)
SS__INSFRPGS = _ssdef.SS__INSFRPGS

_ssdef.SS__BADREASON_swigconstant(_ssdef)
SS__BADREASON = _ssdef.SS__BADREASON

_ssdef.SS__NOSUCHBID_swigconstant(_ssdef)
SS__NOSUCHBID = _ssdef.SS__NOSUCHBID

_ssdef.SS__NOTORIGIN_swigconstant(_ssdef)
SS__NOTORIGIN = _ssdef.SS__NOTORIGIN

_ssdef.SS__NOLOG_swigconstant(_ssdef)
SS__NOLOG = _ssdef.SS__NOLOG

_ssdef.SS__TPDISABLED_swigconstant(_ssdef)
SS__TPDISABLED = _ssdef.SS__TPDISABLED

_ssdef.SS__BRANCHENDED_swigconstant(_ssdef)
SS__BRANCHENDED = _ssdef.SS__BRANCHENDED

_ssdef.SS__BRANCHSTARTED_swigconstant(_ssdef)
SS__BRANCHSTARTED = _ssdef.SS__BRANCHSTARTED

_ssdef.SS__NOSUCHREPORT_swigconstant(_ssdef)
SS__NOSUCHREPORT = _ssdef.SS__NOSUCHREPORT

_ssdef.SS__BADTIME_swigconstant(_ssdef)
SS__BADTIME = _ssdef.SS__BADTIME

_ssdef.SS__PARTJOINED_swigconstant(_ssdef)
SS__PARTJOINED = _ssdef.SS__PARTJOINED

_ssdef.SS__NOPRESUME_swigconstant(_ssdef)
SS__NOPRESUME = _ssdef.SS__NOPRESUME

_ssdef.SS__RECOVERCANCEL_swigconstant(_ssdef)
SS__RECOVERCANCEL = _ssdef.SS__RECOVERCANCEL

_ssdef.SS__CURTIDCHANGE_swigconstant(_ssdef)
SS__CURTIDCHANGE = _ssdef.SS__CURTIDCHANGE

_ssdef.SS__NOREADER_swigconstant(_ssdef)
SS__NOREADER = _ssdef.SS__NOREADER

_ssdef.SS__NOWRITER_swigconstant(_ssdef)
SS__NOWRITER = _ssdef.SS__NOWRITER

_ssdef.SS__DEVNOTWS_swigconstant(_ssdef)
SS__DEVNOTWS = _ssdef.SS__DEVNOTWS

_ssdef.SS__NOCLASS_swigconstant(_ssdef)
SS__NOCLASS = _ssdef.SS__NOCLASS

_ssdef.SS__CONTEXTSKEW_swigconstant(_ssdef)
SS__CONTEXTSKEW = _ssdef.SS__CONTEXTSKEW

_ssdef.SS__BADFORGEDB_swigconstant(_ssdef)
SS__BADFORGEDB = _ssdef.SS__BADFORGEDB

_ssdef.SS__NODOMAIN_swigconstant(_ssdef)
SS__NODOMAIN = _ssdef.SS__NODOMAIN

_ssdef.SS__OVRMAXAUD_swigconstant(_ssdef)
SS__OVRMAXAUD = _ssdef.SS__OVRMAXAUD

_ssdef.SS__BADCHAIN_swigconstant(_ssdef)
SS__BADCHAIN = _ssdef.SS__BADCHAIN

_ssdef.SS__BADBUFLEN_swigconstant(_ssdef)
SS__BADBUFLEN = _ssdef.SS__BADBUFLEN

_ssdef.SS__BADITMCOD_swigconstant(_ssdef)
SS__BADITMCOD = _ssdef.SS__BADITMCOD

_ssdef.SS__BADBUFADR_swigconstant(_ssdef)
SS__BADBUFADR = _ssdef.SS__BADBUFADR

_ssdef.SS__BADRETLEN_swigconstant(_ssdef)
SS__BADRETLEN = _ssdef.SS__BADRETLEN

_ssdef.SS__SSINOTHELD_swigconstant(_ssdef)
SS__SSINOTHELD = _ssdef.SS__SSINOTHELD

_ssdef.SS__SSAMISSING_swigconstant(_ssdef)
SS__SSAMISSING = _ssdef.SS__SSAMISSING

_ssdef.SS__SSANOTAUTH_swigconstant(_ssdef)
SS__SSANOTAUTH = _ssdef.SS__SSANOTAUTH

_ssdef.SS__BADOWNER_swigconstant(_ssdef)
SS__BADOWNER = _ssdef.SS__BADOWNER

_ssdef.SS__NAMESERVCOMMERR_swigconstant(_ssdef)
SS__NAMESERVCOMMERR = _ssdef.SS__NAMESERVCOMMERR

_ssdef.SS__IVNODNAM_swigconstant(_ssdef)
SS__IVNODNAM = _ssdef.SS__IVNODNAM

_ssdef.SS__CONFIG_SYNTAX_swigconstant(_ssdef)
SS__CONFIG_SYNTAX = _ssdef.SS__CONFIG_SYNTAX

_ssdef.SS__SHELVED_swigconstant(_ssdef)
SS__SHELVED = _ssdef.SS__SHELVED

_ssdef.SS__DRVNOTVALID_swigconstant(_ssdef)
SS__DRVNOTVALID = _ssdef.SS__DRVNOTVALID

_ssdef.SS__SLICING_DISABLED_swigconstant(_ssdef)
SS__SLICING_DISABLED = _ssdef.SS__SLICING_DISABLED

_ssdef.SS__NOCALLTRANS_swigconstant(_ssdef)
SS__NOCALLTRANS = _ssdef.SS__NOCALLTRANS

_ssdef.SS__TRANSCALLER_swigconstant(_ssdef)
SS__TRANSCALLER = _ssdef.SS__TRANSCALLER

_ssdef.SS__ILLPRIPOL_swigconstant(_ssdef)
SS__ILLPRIPOL = _ssdef.SS__ILLPRIPOL

_ssdef.SS__ILLPOLICY_swigconstant(_ssdef)
SS__ILLPOLICY = _ssdef.SS__ILLPOLICY

_ssdef.SS__INSFRSPID_swigconstant(_ssdef)
SS__INSFRSPID = _ssdef.SS__INSFRSPID

_ssdef.SS__INSFCREDITL_swigconstant(_ssdef)
SS__INSFCREDITL = _ssdef.SS__INSFCREDITL

_ssdef.SS__INSFCREDITH_swigconstant(_ssdef)
SS__INSFCREDITH = _ssdef.SS__INSFCREDITH

_ssdef.SS__INSFMAP_swigconstant(_ssdef)
SS__INSFMAP = _ssdef.SS__INSFMAP

_ssdef.SS__SIG_INVARGTYPE_swigconstant(_ssdef)
SS__SIG_INVARGTYPE = _ssdef.SS__SIG_INVARGTYPE

_ssdef.SS__SIG_INVFLTARG_swigconstant(_ssdef)
SS__SIG_INVFLTARG = _ssdef.SS__SIG_INVFLTARG

_ssdef.SS__SIG_INVARGLIST_swigconstant(_ssdef)
SS__SIG_INVARGLIST = _ssdef.SS__SIG_INVARGLIST

_ssdef.SS__SIG_INVFUNCTYPE_swigconstant(_ssdef)
SS__SIG_INVFUNCTYPE = _ssdef.SS__SIG_INVFUNCTYPE

_ssdef.SS__SIG_ARGMISMATCH_swigconstant(_ssdef)
SS__SIG_ARGMISMATCH = _ssdef.SS__SIG_ARGMISMATCH

_ssdef.SS__NOTRANQUIL_swigconstant(_ssdef)
SS__NOTRANQUIL = _ssdef.SS__NOTRANQUIL

_ssdef.SS__NOCALLTRANS_SUP_swigconstant(_ssdef)
SS__NOCALLTRANS_SUP = _ssdef.SS__NOCALLTRANS_SUP

_ssdef.SS__DEVLISTFULL_swigconstant(_ssdef)
SS__DEVLISTFULL = _ssdef.SS__DEVLISTFULL

_ssdef.SS__INSFP1POOL_swigconstant(_ssdef)
SS__INSFP1POOL = _ssdef.SS__INSFP1POOL

_ssdef.SS__SIGNAL64_swigconstant(_ssdef)
SS__SIGNAL64 = _ssdef.SS__SIGNAL64

_ssdef.SS__ZEROALLOCLS_swigconstant(_ssdef)
SS__ZEROALLOCLS = _ssdef.SS__ZEROALLOCLS

_ssdef.SS__QUEUE_FULL_swigconstant(_ssdef)
SS__QUEUE_FULL = _ssdef.SS__QUEUE_FULL

_ssdef.SS__DEVICE_RESET_swigconstant(_ssdef)
SS__DEVICE_RESET = _ssdef.SS__DEVICE_RESET

_ssdef.SS__ACA_ACTIVE_swigconstant(_ssdef)
SS__ACA_ACTIVE = _ssdef.SS__ACA_ACTIVE

_ssdef.SS__BUS_PHASE_ERROR_swigconstant(_ssdef)
SS__BUS_PHASE_ERROR = _ssdef.SS__BUS_PHASE_ERROR

_ssdef.SS__NOMULTITHREAD_swigconstant(_ssdef)
SS__NOMULTITHREAD = _ssdef.SS__NOMULTITHREAD

_ssdef.SS__MTHREADACTIVE_swigconstant(_ssdef)
SS__MTHREADACTIVE = _ssdef.SS__MTHREADACTIVE

_ssdef.SS__MAXKTHREADS_swigconstant(_ssdef)
SS__MAXKTHREADS = _ssdef.SS__MAXKTHREADS

_ssdef.SS__NOSUCHTHREAD_swigconstant(_ssdef)
SS__NOSUCHTHREAD = _ssdef.SS__NOSUCHTHREAD

_ssdef.SS__NOTHREADMAN_swigconstant(_ssdef)
SS__NOTHREADMAN = _ssdef.SS__NOTHREADMAN

_ssdef.SS__NOSUCHUPCALL_swigconstant(_ssdef)
SS__NOSUCHUPCALL = _ssdef.SS__NOSUCHUPCALL

_ssdef.SS__BADFANDLE_swigconstant(_ssdef)
SS__BADFANDLE = _ssdef.SS__BADFANDLE

_ssdef.SS__FANDLEBUSY_swigconstant(_ssdef)
SS__FANDLEBUSY = _ssdef.SS__FANDLEBUSY

_ssdef.SS__UNALIGNED_swigconstant(_ssdef)
SS__UNALIGNED = _ssdef.SS__UNALIGNED

_ssdef.SS__BADIOSADR_swigconstant(_ssdef)
SS__BADIOSADR = _ssdef.SS__BADIOSADR

_ssdef.SS__ILLBUFOBJ_swigconstant(_ssdef)
SS__ILLBUFOBJ = _ssdef.SS__ILLBUFOBJ

_ssdef.SS__ILLMODIFIER_swigconstant(_ssdef)
SS__ILLMODIFIER = _ssdef.SS__ILLMODIFIER

_ssdef.SS__NOCCBBUFFOBJ_swigconstant(_ssdef)
SS__NOCCBBUFFOBJ = _ssdef.SS__NOCCBBUFFOBJ

_ssdef.SS__NORDACC_swigconstant(_ssdef)
SS__NORDACC = _ssdef.SS__NORDACC

_ssdef.SS__NOWRTACC_swigconstant(_ssdef)
SS__NOWRTACC = _ssdef.SS__NOWRTACC

_ssdef.SS__NOTNOCNVRT_swigconstant(_ssdef)
SS__NOTNOCNVRT = _ssdef.SS__NOTNOCNVRT

_ssdef.SS__UNSUPVOLSET_swigconstant(_ssdef)
SS__UNSUPVOLSET = _ssdef.SS__UNSUPVOLSET

_ssdef.SS__ARG_GTR_32_BITS_swigconstant(_ssdef)
SS__ARG_GTR_32_BITS = _ssdef.SS__ARG_GTR_32_BITS

_ssdef.SS__NOT64DEVFUNC_swigconstant(_ssdef)
SS__NOT64DEVFUNC = _ssdef.SS__NOT64DEVFUNC

_ssdef.SS__CHANVIO_swigconstant(_ssdef)
SS__CHANVIO = _ssdef.SS__CHANVIO

_ssdef.SS__GBLSEC_MISMATCH_swigconstant(_ssdef)
SS__GBLSEC_MISMATCH = _ssdef.SS__GBLSEC_MISMATCH

_ssdef.SS__ILLRELPAG_swigconstant(_ssdef)
SS__ILLRELPAG = _ssdef.SS__ILLRELPAG

_ssdef.SS__IVACMODE_swigconstant(_ssdef)
SS__IVACMODE = _ssdef.SS__IVACMODE

_ssdef.SS__IVREGFLG_swigconstant(_ssdef)
SS__IVREGFLG = _ssdef.SS__IVREGFLG

_ssdef.SS__IVREGID_swigconstant(_ssdef)
SS__IVREGID = _ssdef.SS__IVREGID

_ssdef.SS__IVREGPROT_swigconstant(_ssdef)
SS__IVREGPROT = _ssdef.SS__IVREGPROT

_ssdef.SS__IVVAFLG_swigconstant(_ssdef)
SS__IVVAFLG = _ssdef.SS__IVVAFLG

_ssdef.SS__LEN_NOTBLKMULT_swigconstant(_ssdef)
SS__LEN_NOTBLKMULT = _ssdef.SS__LEN_NOTBLKMULT

_ssdef.SS__LEN_NOTPAGMULT_swigconstant(_ssdef)
SS__LEN_NOTPAGMULT = _ssdef.SS__LEN_NOTPAGMULT

_ssdef.SS__NOT_PROCESS_VA_swigconstant(_ssdef)
SS__NOT_PROCESS_VA = _ssdef.SS__NOT_PROCESS_VA

_ssdef.SS__OFF_NOTBLKALGN_swigconstant(_ssdef)
SS__OFF_NOTBLKALGN = _ssdef.SS__OFF_NOTBLKALGN

_ssdef.SS__OFF_NOTPAGALGN_swigconstant(_ssdef)
SS__OFF_NOTPAGALGN = _ssdef.SS__OFF_NOTPAGALGN

_ssdef.SS__OFFSET_TOO_BIG_swigconstant(_ssdef)
SS__OFFSET_TOO_BIG = _ssdef.SS__OFFSET_TOO_BIG

_ssdef.SS__REGOWNVIO_swigconstant(_ssdef)
SS__REGOWNVIO = _ssdef.SS__REGOWNVIO

_ssdef.SS__PROTVIO_swigconstant(_ssdef)
SS__PROTVIO = _ssdef.SS__PROTVIO

_ssdef.SS__TOO_MANY_ARGS_swigconstant(_ssdef)
SS__TOO_MANY_ARGS = _ssdef.SS__TOO_MANY_ARGS

_ssdef.SS__VA_NOTPAGALGN_swigconstant(_ssdef)
SS__VA_NOTPAGALGN = _ssdef.SS__VA_NOTPAGALGN

_ssdef.SS__NOEXTAUTH_swigconstant(_ssdef)
SS__NOEXTAUTH = _ssdef.SS__NOEXTAUTH

_ssdef.SS__AUTHFAIL_swigconstant(_ssdef)
SS__AUTHFAIL = _ssdef.SS__AUTHFAIL

_ssdef.SS__INVUSER_swigconstant(_ssdef)
SS__INVUSER = _ssdef.SS__INVUSER

_ssdef.SS__ERRMAPAUTH_swigconstant(_ssdef)
SS__ERRMAPAUTH = _ssdef.SS__ERRMAPAUTH

_ssdef.SS__NORAD50_swigconstant(_ssdef)
SS__NORAD50 = _ssdef.SS__NORAD50

_ssdef.SS__BADMEDIA_swigconstant(_ssdef)
SS__BADMEDIA = _ssdef.SS__BADMEDIA

_ssdef.SS__UNRECOVRDER_swigconstant(_ssdef)
SS__UNRECOVRDER = _ssdef.SS__UNRECOVRDER

_ssdef.SS__IVFORMAT_swigconstant(_ssdef)
SS__IVFORMAT = _ssdef.SS__IVFORMAT

_ssdef.SS__IVUNITFLAG_swigconstant(_ssdef)
SS__IVUNITFLAG = _ssdef.SS__IVUNITFLAG

_ssdef.SS__IVPARAM_swigconstant(_ssdef)
SS__IVPARAM = _ssdef.SS__IVPARAM

_ssdef.SS__NOSUCHENTRY_swigconstant(_ssdef)
SS__NOSUCHENTRY = _ssdef.SS__NOSUCHENTRY

_ssdef.SS__ALLOCFAILED_swigconstant(_ssdef)
SS__ALLOCFAILED = _ssdef.SS__ALLOCFAILED

_ssdef.SS__SHMEM_INCON_swigconstant(_ssdef)
SS__SHMEM_INCON = _ssdef.SS__SHMEM_INCON

_ssdef.SS__IVLOCKOP_swigconstant(_ssdef)
SS__IVLOCKOP = _ssdef.SS__IVLOCKOP

_ssdef.SS__IVLOCKTBL_swigconstant(_ssdef)
SS__IVLOCKTBL = _ssdef.SS__IVLOCKTBL

_ssdef.SS__LOCKINUSE_swigconstant(_ssdef)
SS__LOCKINUSE = _ssdef.SS__LOCKINUSE

_ssdef.SS__LOCK_TIMEOUT_swigconstant(_ssdef)
SS__LOCK_TIMEOUT = _ssdef.SS__LOCK_TIMEOUT

_ssdef.SS__BADLCKTBL_swigconstant(_ssdef)
SS__BADLCKTBL = _ssdef.SS__BADLCKTBL

_ssdef.SS__NOBREAK_swigconstant(_ssdef)
SS__NOBREAK = _ssdef.SS__NOBREAK

_ssdef.SS__IVPROTOCOL_swigconstant(_ssdef)
SS__IVPROTOCOL = _ssdef.SS__IVPROTOCOL

_ssdef.SS__NOWAIT_swigconstant(_ssdef)
SS__NOWAIT = _ssdef.SS__NOWAIT

_ssdef.SS__PLHLDR_swigconstant(_ssdef)
SS__PLHLDR = _ssdef.SS__PLHLDR

_ssdef.SS__ASTFLT_swigconstant(_ssdef)
SS__ASTFLT = _ssdef.SS__ASTFLT

_ssdef.SS__BREAK_swigconstant(_ssdef)
SS__BREAK = _ssdef.SS__BREAK

_ssdef.SS__CMODSUPR_swigconstant(_ssdef)
SS__CMODSUPR = _ssdef.SS__CMODSUPR

_ssdef.SS__CMODUSER_swigconstant(_ssdef)
SS__CMODUSER = _ssdef.SS__CMODUSER

_ssdef.SS__COMPAT_swigconstant(_ssdef)
SS__COMPAT = _ssdef.SS__COMPAT

_ssdef.SS__OPCCUS_swigconstant(_ssdef)
SS__OPCCUS = _ssdef.SS__OPCCUS

_ssdef.SS__OPCDEC_swigconstant(_ssdef)
SS__OPCDEC = _ssdef.SS__OPCDEC

_ssdef.SS__PAGRDERR_swigconstant(_ssdef)
SS__PAGRDERR = _ssdef.SS__PAGRDERR

_ssdef.SS__RADRMOD_swigconstant(_ssdef)
SS__RADRMOD = _ssdef.SS__RADRMOD

_ssdef.SS__ROPRAND_swigconstant(_ssdef)
SS__ROPRAND = _ssdef.SS__ROPRAND

_ssdef.SS__SSFAIL_swigconstant(_ssdef)
SS__SSFAIL = _ssdef.SS__SSFAIL

_ssdef.SS__TBIT_swigconstant(_ssdef)
SS__TBIT = _ssdef.SS__TBIT

_ssdef.SS__DEBUG_swigconstant(_ssdef)
SS__DEBUG = _ssdef.SS__DEBUG

_ssdef.SS__ARTRES_swigconstant(_ssdef)
SS__ARTRES = _ssdef.SS__ARTRES

_ssdef.SS__INTOVF_swigconstant(_ssdef)
SS__INTOVF = _ssdef.SS__INTOVF

_ssdef.SS__INTDIV_swigconstant(_ssdef)
SS__INTDIV = _ssdef.SS__INTDIV

_ssdef.SS__FLTOVF_swigconstant(_ssdef)
SS__FLTOVF = _ssdef.SS__FLTOVF

_ssdef.SS__FLTDIV_swigconstant(_ssdef)
SS__FLTDIV = _ssdef.SS__FLTDIV

_ssdef.SS__FLTUND_swigconstant(_ssdef)
SS__FLTUND = _ssdef.SS__FLTUND

_ssdef.SS__DECOVF_swigconstant(_ssdef)
SS__DECOVF = _ssdef.SS__DECOVF

_ssdef.SS__SUBRNG_swigconstant(_ssdef)
SS__SUBRNG = _ssdef.SS__SUBRNG

_ssdef.SS__FLTOVF_F_swigconstant(_ssdef)
SS__FLTOVF_F = _ssdef.SS__FLTOVF_F

_ssdef.SS__FLTDIV_F_swigconstant(_ssdef)
SS__FLTDIV_F = _ssdef.SS__FLTDIV_F

_ssdef.SS__FLTUND_F_swigconstant(_ssdef)
SS__FLTUND_F = _ssdef.SS__FLTUND_F

_ssdef.SS__INHCHMK_swigconstant(_ssdef)
SS__INHCHMK = _ssdef.SS__INHCHMK

_ssdef.SS__INHCHME_swigconstant(_ssdef)
SS__INHCHME = _ssdef.SS__INHCHME

_ssdef.SS__VECDIS_swigconstant(_ssdef)
SS__VECDIS = _ssdef.SS__VECDIS

_ssdef.SS__VARITH_swigconstant(_ssdef)
SS__VARITH = _ssdef.SS__VARITH

_ssdef.SS__ILLVECOP_swigconstant(_ssdef)
SS__ILLVECOP = _ssdef.SS__ILLVECOP

_ssdef.SS__VECALIGN_swigconstant(_ssdef)
SS__VECALIGN = _ssdef.SS__VECALIGN

_ssdef.SS__IMGDMP_swigconstant(_ssdef)
SS__IMGDMP = _ssdef.SS__IMGDMP

_ssdef.SS__HPARITH_swigconstant(_ssdef)
SS__HPARITH = _ssdef.SS__HPARITH

_ssdef.SS__ALIGN_swigconstant(_ssdef)
SS__ALIGN = _ssdef.SS__ALIGN

_ssdef.SS__UNALIGN_SP_LOAD_swigconstant(_ssdef)
SS__UNALIGN_SP_LOAD = _ssdef.SS__UNALIGN_SP_LOAD

_ssdef.SS__GENTRAP_swigconstant(_ssdef)
SS__GENTRAP = _ssdef.SS__GENTRAP

_ssdef.SS__FLTINV_swigconstant(_ssdef)
SS__FLTINV = _ssdef.SS__FLTINV

_ssdef.SS__FLTINE_swigconstant(_ssdef)
SS__FLTINE = _ssdef.SS__FLTINE

_ssdef.SS__DECDIV_swigconstant(_ssdef)
SS__DECDIV = _ssdef.SS__DECDIV

_ssdef.SS__DECINV_swigconstant(_ssdef)
SS__DECINV = _ssdef.SS__DECINV

_ssdef.SS__ASSERTERR_swigconstant(_ssdef)
SS__ASSERTERR = _ssdef.SS__ASSERTERR

_ssdef.SS__NULPTRERR_swigconstant(_ssdef)
SS__NULPTRERR = _ssdef.SS__NULPTRERR

_ssdef.SS__STKOVF_swigconstant(_ssdef)
SS__STKOVF = _ssdef.SS__STKOVF

_ssdef.SS__STRLENERR_swigconstant(_ssdef)
SS__STRLENERR = _ssdef.SS__STRLENERR

_ssdef.SS__SUBSTRERR_swigconstant(_ssdef)
SS__SUBSTRERR = _ssdef.SS__SUBSTRERR

_ssdef.SS__RANGEERR_swigconstant(_ssdef)
SS__RANGEERR = _ssdef.SS__RANGEERR

_ssdef.SS__SUBRNG1_swigconstant(_ssdef)
SS__SUBRNG1 = _ssdef.SS__SUBRNG1

_ssdef.SS__SUBRNG2_swigconstant(_ssdef)
SS__SUBRNG2 = _ssdef.SS__SUBRNG2

_ssdef.SS__SUBRNG3_swigconstant(_ssdef)
SS__SUBRNG3 = _ssdef.SS__SUBRNG3

_ssdef.SS__SUBRNG4_swigconstant(_ssdef)
SS__SUBRNG4 = _ssdef.SS__SUBRNG4

_ssdef.SS__SUBRNG5_swigconstant(_ssdef)
SS__SUBRNG5 = _ssdef.SS__SUBRNG5

_ssdef.SS__SUBRNG6_swigconstant(_ssdef)
SS__SUBRNG6 = _ssdef.SS__SUBRNG6

_ssdef.SS__SUBRNG7_swigconstant(_ssdef)
SS__SUBRNG7 = _ssdef.SS__SUBRNG7

_ssdef.SS__PAGRDERRXM_swigconstant(_ssdef)
SS__PAGRDERRXM = _ssdef.SS__PAGRDERRXM

_ssdef.SS__ILLEGAL_SHADOW_swigconstant(_ssdef)
SS__ILLEGAL_SHADOW = _ssdef.SS__ILLEGAL_SHADOW

_ssdef.SS__FLTINV_F_swigconstant(_ssdef)
SS__FLTINV_F = _ssdef.SS__FLTINV_F

_ssdef.SS__FLTINE_F_swigconstant(_ssdef)
SS__FLTINE_F = _ssdef.SS__FLTINE_F

_ssdef.SS__INTOVF_F_swigconstant(_ssdef)
SS__INTOVF_F = _ssdef.SS__INTOVF_F

_ssdef.SS__NATFAULT_swigconstant(_ssdef)
SS__NATFAULT = _ssdef.SS__NATFAULT

_ssdef.SS__FLTDENORMAL_swigconstant(_ssdef)
SS__FLTDENORMAL = _ssdef.SS__FLTDENORMAL

_ssdef.SS__BREAK_SYS_swigconstant(_ssdef)
SS__BREAK_SYS = _ssdef.SS__BREAK_SYS

_ssdef.SS__BREAK_ARCH_swigconstant(_ssdef)
SS__BREAK_ARCH = _ssdef.SS__BREAK_ARCH

_ssdef.SS__BUFFEROVF_swigconstant(_ssdef)
SS__BUFFEROVF = _ssdef.SS__BUFFEROVF

_ssdef.SS__CONTROLO_swigconstant(_ssdef)
SS__CONTROLO = _ssdef.SS__CONTROLO

_ssdef.SS__CONTROLY_swigconstant(_ssdef)
SS__CONTROLY = _ssdef.SS__CONTROLY

_ssdef.SS__CREATED_swigconstant(_ssdef)
SS__CREATED = _ssdef.SS__CREATED

_ssdef.SS__MSGNOTFND_swigconstant(_ssdef)
SS__MSGNOTFND = _ssdef.SS__MSGNOTFND

_ssdef.SS__NOTRAN_swigconstant(_ssdef)
SS__NOTRAN = _ssdef.SS__NOTRAN

_ssdef.SS__SUPERSEDE_swigconstant(_ssdef)
SS__SUPERSEDE = _ssdef.SS__SUPERSEDE

_ssdef.SS__WASECC_swigconstant(_ssdef)
SS__WASECC = _ssdef.SS__WASECC

_ssdef.SS__DEVALRALLOC_swigconstant(_ssdef)
SS__DEVALRALLOC = _ssdef.SS__DEVALRALLOC

_ssdef.SS__REMOTE_swigconstant(_ssdef)
SS__REMOTE = _ssdef.SS__REMOTE

_ssdef.SS__CONTROLC_swigconstant(_ssdef)
SS__CONTROLC = _ssdef.SS__CONTROLC

_ssdef.SS__NOTMODIFIED_swigconstant(_ssdef)
SS__NOTMODIFIED = _ssdef.SS__NOTMODIFIED

_ssdef.SS__RDDELDATA_swigconstant(_ssdef)
SS__RDDELDATA = _ssdef.SS__RDDELDATA

_ssdef.SS__OVRDSKQUOTA_swigconstant(_ssdef)
SS__OVRDSKQUOTA = _ssdef.SS__OVRDSKQUOTA

_ssdef.SS__OBSOLETE_1_swigconstant(_ssdef)
SS__OBSOLETE_1 = _ssdef.SS__OBSOLETE_1

_ssdef.SS__FILEPURGED_swigconstant(_ssdef)
SS__FILEPURGED = _ssdef.SS__FILEPURGED

_ssdef.SS__NOTALLPRIV_swigconstant(_ssdef)
SS__NOTALLPRIV = _ssdef.SS__NOTALLPRIV

_ssdef.SS__SYNCH_swigconstant(_ssdef)
SS__SYNCH = _ssdef.SS__SYNCH

_ssdef.SS__CONCEALED_swigconstant(_ssdef)
SS__CONCEALED = _ssdef.SS__CONCEALED

_ssdef.SS__INCOMPAT_swigconstant(_ssdef)
SS__INCOMPAT = _ssdef.SS__INCOMPAT

_ssdef.SS__DBGOPCREQ_swigconstant(_ssdef)
SS__DBGOPCREQ = _ssdef.SS__DBGOPCREQ

_ssdef.SS__ALRDYCLOSED_swigconstant(_ssdef)
SS__ALRDYCLOSED = _ssdef.SS__ALRDYCLOSED

_ssdef.SS__LNMCREATED_swigconstant(_ssdef)
SS__LNMCREATED = _ssdef.SS__LNMCREATED

_ssdef.SS__ACEIDMATCH_swigconstant(_ssdef)
SS__ACEIDMATCH = _ssdef.SS__ACEIDMATCH

_ssdef.SS__DBGEVENT_swigconstant(_ssdef)
SS__DBGEVENT = _ssdef.SS__DBGEVENT

_ssdef.SS__REMOVED_swigconstant(_ssdef)
SS__REMOVED = _ssdef.SS__REMOVED

_ssdef.SS__QUEUED_swigconstant(_ssdef)
SS__QUEUED = _ssdef.SS__QUEUED

_ssdef.SS__SUBDISABLED_swigconstant(_ssdef)
SS__SUBDISABLED = _ssdef.SS__SUBDISABLED

_ssdef.SS__FORGET_swigconstant(_ssdef)
SS__FORGET = _ssdef.SS__FORGET

_ssdef.SS__PREPARED_swigconstant(_ssdef)
SS__PREPARED = _ssdef.SS__PREPARED

_ssdef.SS__NOMOREITEMS_swigconstant(_ssdef)
SS__NOMOREITEMS = _ssdef.SS__NOMOREITEMS

_ssdef.SS__VOLATILE_swigconstant(_ssdef)
SS__VOLATILE = _ssdef.SS__VOLATILE

_ssdef.SS__CLASSUPER_swigconstant(_ssdef)
SS__CLASSUPER = _ssdef.SS__CLASSUPER

_ssdef.SS__CONTINUE_64_swigconstant(_ssdef)
SS__CONTINUE_64 = _ssdef.SS__CONTINUE_64

_ssdef.SS__THREAD_UPCALL_swigconstant(_ssdef)
SS__THREAD_UPCALL = _ssdef.SS__THREAD_UPCALL

_ssdef.SS__CREATED_SHPT_swigconstant(_ssdef)
SS__CREATED_SHPT = _ssdef.SS__CREATED_SHPT

_ssdef.SS__PERSONADELPEND_swigconstant(_ssdef)
SS__PERSONADELPEND = _ssdef.SS__PERSONADELPEND

_ssdef.SS__DEVAVAIL_swigconstant(_ssdef)
SS__DEVAVAIL = _ssdef.SS__DEVAVAIL

_ssdef.SS__LONGGAP_swigconstant(_ssdef)
SS__LONGGAP = _ssdef.SS__LONGGAP

_ssdef.SS__BROKEN_swigconstant(_ssdef)
SS__BROKEN = _ssdef.SS__BROKEN

_ssdef.SS__QPOOL_DEL_INIT_swigconstant(_ssdef)
SS__QPOOL_DEL_INIT = _ssdef.SS__QPOOL_DEL_INIT

_ssdef.SS__UNUSED_1_swigconstant(_ssdef)
SS__UNUSED_1 = _ssdef.SS__UNUSED_1

_ssdef.SS__LOWPREC_swigconstant(_ssdef)
SS__LOWPREC = _ssdef.SS__LOWPREC

_ssdef.SS__ACCONFLICT_swigconstant(_ssdef)
SS__ACCONFLICT = _ssdef.SS__ACCONFLICT

_ssdef.SS__BADCHKSUM_swigconstant(_ssdef)
SS__BADCHKSUM = _ssdef.SS__BADCHKSUM

_ssdef.SS__BADFILEHDR_swigconstant(_ssdef)
SS__BADFILEHDR = _ssdef.SS__BADFILEHDR

_ssdef.SS__BADFILENAME_swigconstant(_ssdef)
SS__BADFILENAME = _ssdef.SS__BADFILENAME

_ssdef.SS__BADFILEVER_swigconstant(_ssdef)
SS__BADFILEVER = _ssdef.SS__BADFILEVER

_ssdef.SS__BADIRECTORY_swigconstant(_ssdef)
SS__BADIRECTORY = _ssdef.SS__BADIRECTORY

_ssdef.SS__CANCEL_swigconstant(_ssdef)
SS__CANCEL = _ssdef.SS__CANCEL

_ssdef.SS__DATAOVERUN_swigconstant(_ssdef)
SS__DATAOVERUN = _ssdef.SS__DATAOVERUN

_ssdef.SS__DEVALLOC_swigconstant(_ssdef)
SS__DEVALLOC = _ssdef.SS__DEVALLOC

_ssdef.SS__DEVASSIGN_swigconstant(_ssdef)
SS__DEVASSIGN = _ssdef.SS__DEVASSIGN

_ssdef.SS__DEVICEFULL_swigconstant(_ssdef)
SS__DEVICEFULL = _ssdef.SS__DEVICEFULL

_ssdef.SS__DEVNOTALLOC_swigconstant(_ssdef)
SS__DEVNOTALLOC = _ssdef.SS__DEVNOTALLOC

_ssdef.SS__DIRFULL_swigconstant(_ssdef)
SS__DIRFULL = _ssdef.SS__DIRFULL

_ssdef.SS__DUPFILENAME_swigconstant(_ssdef)
SS__DUPFILENAME = _ssdef.SS__DUPFILENAME

_ssdef.SS__ENDOFFILE_swigconstant(_ssdef)
SS__ENDOFFILE = _ssdef.SS__ENDOFFILE

_ssdef.SS__ENDOFTAPE_swigconstant(_ssdef)
SS__ENDOFTAPE = _ssdef.SS__ENDOFTAPE

_ssdef.SS__TMACTIVE_swigconstant(_ssdef)
SS__TMACTIVE = _ssdef.SS__TMACTIVE

_ssdef.SS__FCPREADERR_swigconstant(_ssdef)
SS__FCPREADERR = _ssdef.SS__FCPREADERR

_ssdef.SS__FCPREWNDERR_swigconstant(_ssdef)
SS__FCPREWNDERR = _ssdef.SS__FCPREWNDERR

_ssdef.SS__FCPSPACERR_swigconstant(_ssdef)
SS__FCPSPACERR = _ssdef.SS__FCPSPACERR

_ssdef.SS__FCPWRITERR_swigconstant(_ssdef)
SS__FCPWRITERR = _ssdef.SS__FCPWRITERR

_ssdef.SS__FILELOCKED_swigconstant(_ssdef)
SS__FILELOCKED = _ssdef.SS__FILELOCKED

_ssdef.SS__FILENUMCHK_swigconstant(_ssdef)
SS__FILENUMCHK = _ssdef.SS__FILENUMCHK

_ssdef.SS__FILESEQCHK_swigconstant(_ssdef)
SS__FILESEQCHK = _ssdef.SS__FILESEQCHK

_ssdef.SS__FILESTRUCT_swigconstant(_ssdef)
SS__FILESTRUCT = _ssdef.SS__FILESTRUCT

_ssdef.SS__HEADERFULL_swigconstant(_ssdef)
SS__HEADERFULL = _ssdef.SS__HEADERFULL

_ssdef.SS__IDXFILEFULL_swigconstant(_ssdef)
SS__IDXFILEFULL = _ssdef.SS__IDXFILEFULL

_ssdef.SS__MBFULL_swigconstant(_ssdef)
SS__MBFULL = _ssdef.SS__MBFULL

_ssdef.SS__NOHOMEBLK_swigconstant(_ssdef)
SS__NOHOMEBLK = _ssdef.SS__NOHOMEBLK

_ssdef.SS__NONEXPR_swigconstant(_ssdef)
SS__NONEXPR = _ssdef.SS__NONEXPR

_ssdef.SS__NONLOCAL_swigconstant(_ssdef)
SS__NONLOCAL = _ssdef.SS__NONLOCAL

_ssdef.SS__NOHANDLER_swigconstant(_ssdef)
SS__NOHANDLER = _ssdef.SS__NOHANDLER

_ssdef.SS__NOSIGNAL_swigconstant(_ssdef)
SS__NOSIGNAL = _ssdef.SS__NOSIGNAL

_ssdef.SS__NOSUCHDEV_swigconstant(_ssdef)
SS__NOSUCHDEV = _ssdef.SS__NOSUCHDEV

_ssdef.SS__NOSUCHFILE_swigconstant(_ssdef)
SS__NOSUCHFILE = _ssdef.SS__NOSUCHFILE

_ssdef.SS__RESIGNAL_swigconstant(_ssdef)
SS__RESIGNAL = _ssdef.SS__RESIGNAL

_ssdef.SS__UNWIND_swigconstant(_ssdef)
SS__UNWIND = _ssdef.SS__UNWIND

_ssdef.SS__UNWINDING_swigconstant(_ssdef)
SS__UNWINDING = _ssdef.SS__UNWINDING

_ssdef.SS__NOMOREFILES_swigconstant(_ssdef)
SS__NOMOREFILES = _ssdef.SS__NOMOREFILES

_ssdef.SS__BEGOFFILE_swigconstant(_ssdef)
SS__BEGOFFILE = _ssdef.SS__BEGOFFILE

_ssdef.SS__BLOCKCNTERR_swigconstant(_ssdef)
SS__BLOCKCNTERR = _ssdef.SS__BLOCKCNTERR

_ssdef.SS__MUSTCLOSEFL_swigconstant(_ssdef)
SS__MUSTCLOSEFL = _ssdef.SS__MUSTCLOSEFL

_ssdef.SS__WAITUSRLBL_swigconstant(_ssdef)
SS__WAITUSRLBL = _ssdef.SS__WAITUSRLBL

_ssdef.SS__ILLUSRLBLRD_swigconstant(_ssdef)
SS__ILLUSRLBLRD = _ssdef.SS__ILLUSRLBLRD

_ssdef.SS__ILLUSRLBLWT_swigconstant(_ssdef)
SS__ILLUSRLBLWT = _ssdef.SS__ILLUSRLBLWT

_ssdef.SS__ILLLBLAST_swigconstant(_ssdef)
SS__ILLLBLAST = _ssdef.SS__ILLLBLAST

_ssdef.SS__ENDOFUSRLBL_swigconstant(_ssdef)
SS__ENDOFUSRLBL = _ssdef.SS__ENDOFUSRLBL

_ssdef.SS__NOSUCHSEC_swigconstant(_ssdef)
SS__NOSUCHSEC = _ssdef.SS__NOSUCHSEC

_ssdef.SS__CLIFRCEXT_swigconstant(_ssdef)
SS__CLIFRCEXT = _ssdef.SS__CLIFRCEXT

_ssdef.SS__FCPREPSTN_swigconstant(_ssdef)
SS__FCPREPSTN = _ssdef.SS__FCPREPSTN

_ssdef.SS__TOOMANYVER_swigconstant(_ssdef)
SS__TOOMANYVER = _ssdef.SS__TOOMANYVER

_ssdef.SS__NOTVOLSET_swigconstant(_ssdef)
SS__NOTVOLSET = _ssdef.SS__NOTVOLSET

_ssdef.SS__ENDOFVOLUME_swigconstant(_ssdef)
SS__ENDOFVOLUME = _ssdef.SS__ENDOFVOLUME

_ssdef.SS__NOMOREPROC_swigconstant(_ssdef)
SS__NOMOREPROC = _ssdef.SS__NOMOREPROC

_ssdef.SS__NODEVAVL_swigconstant(_ssdef)
SS__NODEVAVL = _ssdef.SS__NODEVAVL

_ssdef.SS__NOTQUEUED_swigconstant(_ssdef)
SS__NOTQUEUED = _ssdef.SS__NOTQUEUED

_ssdef.SS__DGQINCOMP_swigconstant(_ssdef)
SS__DGQINCOMP = _ssdef.SS__DGQINCOMP

_ssdef.SS__DIRALLOC_swigconstant(_ssdef)
SS__DIRALLOC = _ssdef.SS__DIRALLOC

_ssdef.SS__ACLEMPTY_swigconstant(_ssdef)
SS__ACLEMPTY = _ssdef.SS__ACLEMPTY

_ssdef.SS__NOENTRY_swigconstant(_ssdef)
SS__NOENTRY = _ssdef.SS__NOENTRY

_ssdef.SS__NOMOREACE_swigconstant(_ssdef)
SS__NOMOREACE = _ssdef.SS__NOMOREACE

_ssdef.SS__RIGHTSFULL_swigconstant(_ssdef)
SS__RIGHTSFULL = _ssdef.SS__RIGHTSFULL

_ssdef.SS__VALNOTVALID_swigconstant(_ssdef)
SS__VALNOTVALID = _ssdef.SS__VALNOTVALID

_ssdef.SS__ACLFULL_swigconstant(_ssdef)
SS__ACLFULL = _ssdef.SS__ACLFULL

_ssdef.SS__NOMORENODE_swigconstant(_ssdef)
SS__NOMORENODE = _ssdef.SS__NOMORENODE

_ssdef.SS__NOMORELOCK_swigconstant(_ssdef)
SS__NOMORELOCK = _ssdef.SS__NOMORELOCK

_ssdef.SS__BEGOFTAPE_swigconstant(_ssdef)
SS__BEGOFTAPE = _ssdef.SS__BEGOFTAPE

_ssdef.SS__OBJLOCKHELD_swigconstant(_ssdef)
SS__OBJLOCKHELD = _ssdef.SS__OBJLOCKHELD

_ssdef.SS__CPUSTARTIP_swigconstant(_ssdef)
SS__CPUSTARTIP = _ssdef.SS__CPUSTARTIP

_ssdef.SS__ALLSTARTED_swigconstant(_ssdef)
SS__ALLSTARTED = _ssdef.SS__ALLSTARTED

_ssdef.SS__ALRDYSTRT_swigconstant(_ssdef)
SS__ALRDYSTRT = _ssdef.SS__ALRDYSTRT

_ssdef.SS__ALRDYSTPPD_swigconstant(_ssdef)
SS__ALRDYSTPPD = _ssdef.SS__ALRDYSTPPD

_ssdef.SS__NSTPPD_swigconstant(_ssdef)
SS__NSTPPD = _ssdef.SS__NSTPPD

_ssdef.SS__UNKRESULT_swigconstant(_ssdef)
SS__UNKRESULT = _ssdef.SS__UNKRESULT

_ssdef.SS__ITEMNOTFOUND_swigconstant(_ssdef)
SS__ITEMNOTFOUND = _ssdef.SS__ITEMNOTFOUND

_ssdef.SS__NOMOREDEV_swigconstant(_ssdef)
SS__NOMOREDEV = _ssdef.SS__NOMOREDEV

_ssdef.SS__EFNOTSET_swigconstant(_ssdef)
SS__EFNOTSET = _ssdef.SS__EFNOTSET

_ssdef.SS__PRIMNOSTP_swigconstant(_ssdef)
SS__PRIMNOSTP = _ssdef.SS__PRIMNOSTP

_ssdef.SS__BOOTREJECT_swigconstant(_ssdef)
SS__BOOTREJECT = _ssdef.SS__BOOTREJECT

_ssdef.SS__RMTPATH_swigconstant(_ssdef)
SS__RMTPATH = _ssdef.SS__RMTPATH

_ssdef.SS__OBJECT_EXISTS_swigconstant(_ssdef)
SS__OBJECT_EXISTS = _ssdef.SS__OBJECT_EXISTS

_ssdef.SS__NOSUCHOBJECT_swigconstant(_ssdef)
SS__NOSUCHOBJECT = _ssdef.SS__NOSUCHOBJECT

_ssdef.SS__NOVOLDESC_swigconstant(_ssdef)
SS__NOVOLDESC = _ssdef.SS__NOVOLDESC

_ssdef.SS__NOPTBLDIR_swigconstant(_ssdef)
SS__NOPTBLDIR = _ssdef.SS__NOPTBLDIR

_ssdef.SS__DRVEXISTS_swigconstant(_ssdef)
SS__DRVEXISTS = _ssdef.SS__DRVEXISTS

_ssdef.SS__DEVEXISTS_swigconstant(_ssdef)
SS__DEVEXISTS = _ssdef.SS__DEVEXISTS

_ssdef.SS__GOTO_UNWIND_swigconstant(_ssdef)
SS__GOTO_UNWIND = _ssdef.SS__GOTO_UNWIND

_ssdef.SS__EXIT_UNWIND_swigconstant(_ssdef)
SS__EXIT_UNWIND = _ssdef.SS__EXIT_UNWIND

_ssdef.SS__SMALLHEADER_swigconstant(_ssdef)
SS__SMALLHEADER = _ssdef.SS__SMALLHEADER

_ssdef.SS__FDT_COMPL_swigconstant(_ssdef)
SS__FDT_COMPL = _ssdef.SS__FDT_COMPL

_ssdef.SS__TARGET_UNWIND_swigconstant(_ssdef)
SS__TARGET_UNWIND = _ssdef.SS__TARGET_UNWIND

_ssdef.SS__TARGET_GOTO_UNWIND_swigconstant(_ssdef)
SS__TARGET_GOTO_UNWIND = _ssdef.SS__TARGET_GOTO_UNWIND

_ssdef.SS__RESIGNAL_64_swigconstant(_ssdef)
SS__RESIGNAL_64 = _ssdef.SS__RESIGNAL_64

_ssdef.SS__NOMOREREG_swigconstant(_ssdef)
SS__NOMOREREG = _ssdef.SS__NOMOREREG

_ssdef.SS__PAGNOTINREG_swigconstant(_ssdef)
SS__PAGNOTINREG = _ssdef.SS__PAGNOTINREG

_ssdef.SS__REGISFULL_swigconstant(_ssdef)
SS__REGISFULL = _ssdef.SS__REGISFULL

_ssdef.SS__PAGTYPVIO_swigconstant(_ssdef)
SS__PAGTYPVIO = _ssdef.SS__PAGTYPVIO

_ssdef.SS__NOSUCHPAG_swigconstant(_ssdef)
SS__NOSUCHPAG = _ssdef.SS__NOSUCHPAG

_ssdef.SS__PAGNOTWRITE_swigconstant(_ssdef)
SS__PAGNOTWRITE = _ssdef.SS__PAGNOTWRITE

_ssdef.SS__NOMORETHREAD_swigconstant(_ssdef)
SS__NOMORETHREAD = _ssdef.SS__NOMORETHREAD

_ssdef.SS__NOTF11ODS5_swigconstant(_ssdef)
SS__NOTF11ODS5 = _ssdef.SS__NOTF11ODS5

_ssdef.SS__NOCONVJNL_swigconstant(_ssdef)
SS__NOCONVJNL = _ssdef.SS__NOCONVJNL

_ssdef.SS__MPDEVBUSY_swigconstant(_ssdef)
SS__MPDEVBUSY = _ssdef.SS__MPDEVBUSY

_ssdef.SS__MPDEVUSERDISABLE_swigconstant(_ssdef)
SS__MPDEVUSERDISABLE = _ssdef.SS__MPDEVUSERDISABLE

_ssdef.SS__NOCPUMATCH_swigconstant(_ssdef)
SS__NOCPUMATCH = _ssdef.SS__NOCPUMATCH

_ssdef.SS__NOMORECLIENTS_swigconstant(_ssdef)
SS__NOMORECLIENTS = _ssdef.SS__NOMORECLIENTS

_ssdef.SS__NOMOREDEVICES_swigconstant(_ssdef)
SS__NOMOREDEVICES = _ssdef.SS__NOMOREDEVICES

_ssdef.SS__NOMOREFILTERS_swigconstant(_ssdef)
SS__NOMOREFILTERS = _ssdef.SS__NOMOREFILTERS

_ssdef.SS__NOMOREPATHS_swigconstant(_ssdef)
SS__NOMOREPATHS = _ssdef.SS__NOMOREPATHS

_ssdef.SS__NOMORESERVERS_swigconstant(_ssdef)
SS__NOMORESERVERS = _ssdef.SS__NOMORESERVERS

_ssdef.SS__FISH_swigconstant(_ssdef)
SS__FISH = _ssdef.SS__FISH

_ssdef.SS__FILENOTCACHED_swigconstant(_ssdef)
SS__FILENOTCACHED = _ssdef.SS__FILENOTCACHED

_ssdef.SS__INSF_SHM_REG_swigconstant(_ssdef)
SS__INSF_SHM_REG = _ssdef.SS__INSF_SHM_REG

_ssdef.SS__HBMMNOTENABLED_swigconstant(_ssdef)
SS__HBMMNOTENABLED = _ssdef.SS__HBMMNOTENABLED

_ssdef.SS__HBMMALREADYON_swigconstant(_ssdef)
SS__HBMMALREADYON = _ssdef.SS__HBMMALREADYON

_ssdef.SS__NODEVPOL_swigconstant(_ssdef)
SS__NODEVPOL = _ssdef.SS__NODEVPOL

_ssdef.SS__NONAMPOL_swigconstant(_ssdef)
SS__NONAMPOL = _ssdef.SS__NONAMPOL

_ssdef.SS__XVALNOTVALID_swigconstant(_ssdef)
SS__XVALNOTVALID = _ssdef.SS__XVALNOTVALID

_ssdef.SS__FILEFULL_swigconstant(_ssdef)
SS__FILEFULL = _ssdef.SS__FILEFULL

_ssdef.SS__REMINDER_swigconstant(_ssdef)
SS__REMINDER = _ssdef.SS__REMINDER

_ssdef.SS__EOTIN_swigconstant(_ssdef)
SS__EOTIN = _ssdef.SS__EOTIN

_ssdef.SS__CHAINW_swigconstant(_ssdef)
SS__CHAINW = _ssdef.SS__CHAINW

_ssdef.SS__NOTINSEC_swigconstant(_ssdef)
SS__NOTINSEC = _ssdef.SS__NOTINSEC

_ssdef.SS__NONXPAG_swigconstant(_ssdef)
SS__NONXPAG = _ssdef.SS__NONXPAG

_ssdef.SS__LOGNAME_swigconstant(_ssdef)
SS__LOGNAME = _ssdef.SS__LOGNAME

_ssdef.SS__CPUSTARTD_swigconstant(_ssdef)
SS__CPUSTARTD = _ssdef.SS__CPUSTARTD

_ssdef.SS__CPUSTOPPING_swigconstant(_ssdef)
SS__CPUSTOPPING = _ssdef.SS__CPUSTOPPING

_ssdef.SS__NOTALLCANCELED_swigconstant(_ssdef)
SS__NOTALLCANCELED = _ssdef.SS__NOTALLCANCELED

_ssdef.SS__NOTHINGDONE_swigconstant(_ssdef)
SS__NOTHINGDONE = _ssdef.SS__NOTHINGDONE

_ssdef.SS__EVTNOTENAB_swigconstant(_ssdef)
SS__EVTNOTENAB = _ssdef.SS__EVTNOTENAB

_ssdef.SS__NOPATHTBL_swigconstant(_ssdef)
SS__NOPATHTBL = _ssdef.SS__NOPATHTBL

_ssdef.SS__RESELECTION_swigconstant(_ssdef)
SS__RESELECTION = _ssdef.SS__RESELECTION

_ssdef.SS__EMULATED_swigconstant(_ssdef)
SS__EMULATED = _ssdef.SS__EMULATED

_ssdef.SS__REMDONE_swigconstant(_ssdef)
SS__REMDONE = _ssdef.SS__REMDONE

_ssdef.SS__REMINPROG_swigconstant(_ssdef)
SS__REMINPROG = _ssdef.SS__REMINPROG

_ssdef.SS__DEVCON_swigconstant(_ssdef)
SS__DEVCON = _ssdef.SS__DEVCON

_ssdef.SS__DEVNOTCON_swigconstant(_ssdef)
SS__DEVNOTCON = _ssdef.SS__DEVNOTCON

_ssdef.SS__CPUSELECTED_swigconstant(_ssdef)
SS__CPUSELECTED = _ssdef.SS__CPUSELECTED

_ssdef.SS__QPOOL_DEL_INPRG_swigconstant(_ssdef)
SS__QPOOL_DEL_INPRG = _ssdef.SS__QPOOL_DEL_INPRG

_ssdef.SS__PRESTO_swigconstant(_ssdef)
SS__PRESTO = _ssdef.SS__PRESTO

_ssdef.SS__TAKEN_BRANCH_swigconstant(_ssdef)
SS__TAKEN_BRANCH = _ssdef.SS__TAKEN_BRANCH

_ssdef.SS__IA32_TRAP_swigconstant(_ssdef)
SS__IA32_TRAP = _ssdef.SS__IA32_TRAP

_ssdef.SS__DEBUG_FAULT_swigconstant(_ssdef)
SS__DEBUG_FAULT = _ssdef.SS__DEBUG_FAULT

_ssdef.SS__BREAK_APPL_swigconstant(_ssdef)
SS__BREAK_APPL = _ssdef.SS__BREAK_APPL

_ssdef.SS__TIE_GET_FRAMES_swigconstant(_ssdef)
SS__TIE_GET_FRAMES = _ssdef.SS__TIE_GET_FRAMES

_ssdef.SS__TIE_PRE_UNWIND_swigconstant(_ssdef)
SS__TIE_PRE_UNWIND = _ssdef.SS__TIE_PRE_UNWIND

_ssdef.SS__TIE_UNWIND_swigconstant(_ssdef)
SS__TIE_UNWIND = _ssdef.SS__TIE_UNWIND

_ssdef.SS__TIE_GOTO_UNWIND_swigconstant(_ssdef)
SS__TIE_GOTO_UNWIND = _ssdef.SS__TIE_GOTO_UNWIND

_ssdef.SS__HBMMCREPOSTMRG_swigconstant(_ssdef)
SS__HBMMCREPOSTMRG = _ssdef.SS__HBMMCREPOSTMRG

_ssdef.SS__FPMODECTL_swigconstant(_ssdef)
SS__FPMODECTL = _ssdef.SS__FPMODECTL

_ssdef.SS__FPMODEPC_swigconstant(_ssdef)
SS__FPMODEPC = _ssdef.SS__FPMODEPC

_ssdef.SS__FPMODERC_swigconstant(_ssdef)
SS__FPMODERC = _ssdef.SS__FPMODERC

_ssdef.SS__ARGTYP1_swigconstant(_ssdef)
SS__ARGTYP1 = _ssdef.SS__ARGTYP1

_ssdef.SS__ARGTYP2_swigconstant(_ssdef)
SS__ARGTYP2 = _ssdef.SS__ARGTYP2

_ssdef.SS__ARGTYP3_swigconstant(_ssdef)
SS__ARGTYP3 = _ssdef.SS__ARGTYP3

_ssdef.SS__ARGTYP4_swigconstant(_ssdef)
SS__ARGTYP4 = _ssdef.SS__ARGTYP4

_ssdef.SS__ARGTYP5_swigconstant(_ssdef)
SS__ARGTYP5 = _ssdef.SS__ARGTYP5

_ssdef.SS__ARGTYP6_swigconstant(_ssdef)
SS__ARGTYP6 = _ssdef.SS__ARGTYP6

_ssdef.SS__ARGTYP7_swigconstant(_ssdef)
SS__ARGTYP7 = _ssdef.SS__ARGTYP7

_ssdef.SS__ARGTYP8_swigconstant(_ssdef)
SS__ARGTYP8 = _ssdef.SS__ARGTYP8

_ssdef.SS__DEFER_ASTS_swigconstant(_ssdef)
SS__DEFER_ASTS = _ssdef.SS__DEFER_ASTS

_ssdef.SS__COWBOYUP_swigconstant(_ssdef)
SS__COWBOYUP = _ssdef.SS__COWBOYUP

_ssdef.SS__LINEABRT_swigconstant(_ssdef)
SS__LINEABRT = _ssdef.SS__LINEABRT

_ssdef.SS__DEADLOCK_swigconstant(_ssdef)
SS__DEADLOCK = _ssdef.SS__DEADLOCK

_ssdef.SS__NOLOCKID_swigconstant(_ssdef)
SS__NOLOCKID = _ssdef.SS__NOLOCKID

_ssdef.SS__EXDEPTH_swigconstant(_ssdef)
SS__EXDEPTH = _ssdef.SS__EXDEPTH

_ssdef.SS__PARTMAPPED_swigconstant(_ssdef)
SS__PARTMAPPED = _ssdef.SS__PARTMAPPED

_ssdef.SS__CANCELGRANT_swigconstant(_ssdef)
SS__CANCELGRANT = _ssdef.SS__CANCELGRANT

_ssdef.SS__RETRY_swigconstant(_ssdef)
SS__RETRY = _ssdef.SS__RETRY

_ssdef.SS__BADACL_swigconstant(_ssdef)
SS__BADACL = _ssdef.SS__BADACL

_ssdef.SS__ACEEXISTS_swigconstant(_ssdef)
SS__ACEEXISTS = _ssdef.SS__ACEEXISTS

_ssdef.SS__UNSUPPORTED_swigconstant(_ssdef)
SS__UNSUPPORTED = _ssdef.SS__UNSUPPORTED

_ssdef.SS__NORIGHTSDB_swigconstant(_ssdef)
SS__NORIGHTSDB = _ssdef.SS__NORIGHTSDB

_ssdef.SS__LOGSTALL_swigconstant(_ssdef)
SS__LOGSTALL = _ssdef.SS__LOGSTALL

_ssdef.SS__LOGFULL_swigconstant(_ssdef)
SS__LOGFULL = _ssdef.SS__LOGFULL

_ssdef.SS__PWDINDIC_swigconstant(_ssdef)
SS__PWDINDIC = _ssdef.SS__PWDINDIC

_ssdef.SS__PWDINHIS_swigconstant(_ssdef)
SS__PWDINHIS = _ssdef.SS__PWDINHIS

_ssdef.SS__PWDWEAK_swigconstant(_ssdef)
SS__PWDWEAK = _ssdef.SS__PWDWEAK

_ssdef.SS__USEGENPWD_swigconstant(_ssdef)
SS__USEGENPWD = _ssdef.SS__USEGENPWD

_ssdef.SS__INVBUSNAM_swigconstant(_ssdef)
SS__INVBUSNAM = _ssdef.SS__INVBUSNAM

_ssdef.SS__INVCOMPTYPE_swigconstant(_ssdef)
SS__INVCOMPTYPE = _ssdef.SS__INVCOMPTYPE

_ssdef.SS__INVCOMPID_swigconstant(_ssdef)
SS__INVCOMPID = _ssdef.SS__INVCOMPID

_ssdef.SS__INVCOMPLIST_swigconstant(_ssdef)
SS__INVCOMPLIST = _ssdef.SS__INVCOMPLIST

_ssdef.SS__NOCOMPLSTS_swigconstant(_ssdef)
SS__NOCOMPLSTS = _ssdef.SS__NOCOMPLSTS

_ssdef.SS__INVSECDOMAIN_swigconstant(_ssdef)
SS__INVSECDOMAIN = _ssdef.SS__INVSECDOMAIN

_ssdef.SS__BADCHECKSUM_swigconstant(_ssdef)
SS__BADCHECKSUM = _ssdef.SS__BADCHECKSUM

_ssdef.SS__ARBTOOBIG_swigconstant(_ssdef)
SS__ARBTOOBIG = _ssdef.SS__ARBTOOBIG

_ssdef.SS__ORBTOOBIG_swigconstant(_ssdef)
SS__ORBTOOBIG = _ssdef.SS__ORBTOOBIG

_ssdef.SS__INVAJLNAM_swigconstant(_ssdef)
SS__INVAJLNAM = _ssdef.SS__INVAJLNAM

_ssdef.SS__TOOMANYAJL_swigconstant(_ssdef)
SS__TOOMANYAJL = _ssdef.SS__TOOMANYAJL

_ssdef.SS__RSDMINUSE_swigconstant(_ssdef)
SS__RSDMINUSE = _ssdef.SS__RSDMINUSE

_ssdef.SS__RSDMNOTFOU_swigconstant(_ssdef)
SS__RSDMNOTFOU = _ssdef.SS__RSDMNOTFOU

_ssdef.SS__INVUICGRP_swigconstant(_ssdef)
SS__INVUICGRP = _ssdef.SS__INVUICGRP

_ssdef.SS__RSDM_ACTIVE_swigconstant(_ssdef)
SS__RSDM_ACTIVE = _ssdef.SS__RSDM_ACTIVE

_ssdef.SS__OBJLOCKED_swigconstant(_ssdef)
SS__OBJLOCKED = _ssdef.SS__OBJLOCKED

_ssdef.SS__NOTMPNAM_swigconstant(_ssdef)
SS__NOTMPNAM = _ssdef.SS__NOTMPNAM

_ssdef.SS__INVCLSITM_swigconstant(_ssdef)
SS__INVCLSITM = _ssdef.SS__INVCLSITM

_ssdef.SS__NOTSHRTBL_swigconstant(_ssdef)
SS__NOTSHRTBL = _ssdef.SS__NOTSHRTBL

_ssdef.SS__MMATORB_swigconstant(_ssdef)
SS__MMATORB = _ssdef.SS__MMATORB

_ssdef.SS__NOSUCHVOL_swigconstant(_ssdef)
SS__NOSUCHVOL = _ssdef.SS__NOSUCHVOL

_ssdef.SS__OBJNOTLOCKED_swigconstant(_ssdef)
SS__OBJNOTLOCKED = _ssdef.SS__OBJNOTLOCKED

_ssdef.SS__ILLRSDM_swigconstant(_ssdef)
SS__ILLRSDM = _ssdef.SS__ILLRSDM

_ssdef.SS__NOCLASSSUPPORT_swigconstant(_ssdef)
SS__NOCLASSSUPPORT = _ssdef.SS__NOCLASSSUPPORT

_ssdef.SS__INVSECOPER_swigconstant(_ssdef)
SS__INVSECOPER = _ssdef.SS__INVSECOPER

_ssdef.SS__NODELJNLACT_swigconstant(_ssdef)
SS__NODELJNLACT = _ssdef.SS__NODELJNLACT

_ssdef.SS__INVFILFOROP_swigconstant(_ssdef)
SS__INVFILFOROP = _ssdef.SS__INVFILFOROP

_ssdef.SS__NOOBJSRV_swigconstant(_ssdef)
SS__NOOBJSRV = _ssdef.SS__NOOBJSRV

_ssdef.SS__NOFILEACCESS_swigconstant(_ssdef)
SS__NOFILEACCESS = _ssdef.SS__NOFILEACCESS

_ssdef.SS__BADFILESIZE_swigconstant(_ssdef)
SS__BADFILESIZE = _ssdef.SS__BADFILESIZE

_ssdef.SS__NOTFULLYMAPPED_swigconstant(_ssdef)
SS__NOTFULLYMAPPED = _ssdef.SS__NOTFULLYMAPPED

_ssdef.SS__BADWINCNT_swigconstant(_ssdef)
SS__BADWINCNT = _ssdef.SS__BADWINCNT

_ssdef.SS__BADWINLBN_swigconstant(_ssdef)
SS__BADWINLBN = _ssdef.SS__BADWINLBN

_ssdef.SS__BADWINRVN_swigconstant(_ssdef)
SS__BADWINRVN = _ssdef.SS__BADWINRVN

_ssdef.SS__EXTRAWINDOW_swigconstant(_ssdef)
SS__EXTRAWINDOW = _ssdef.SS__EXTRAWINDOW

_ssdef.SS__REVISED_swigconstant(_ssdef)
SS__REVISED = _ssdef.SS__REVISED

_ssdef.SS__TIMENOTSET_swigconstant(_ssdef)
SS__TIMENOTSET = _ssdef.SS__TIMENOTSET

_ssdef.SS__WAIT_CALLERS_MODE_swigconstant(_ssdef)
SS__WAIT_CALLERS_MODE = _ssdef.SS__WAIT_CALLERS_MODE

_ssdef.SS__NOT_LOADED_swigconstant(_ssdef)
SS__NOT_LOADED = _ssdef.SS__NOT_LOADED

_ssdef.SS__DRV_NOUNLOAD_swigconstant(_ssdef)
SS__DRV_NOUNLOAD = _ssdef.SS__DRV_NOUNLOAD

_ssdef.SS__INVARG_swigconstant(_ssdef)
SS__INVARG = _ssdef.SS__INVARG

_ssdef.SS__QIO_CROCK_swigconstant(_ssdef)
SS__QIO_CROCK = _ssdef.SS__QIO_CROCK

_ssdef.SS__ALTER_swigconstant(_ssdef)
SS__ALTER = _ssdef.SS__ALTER

_ssdef.SS__AFR_ENABLED_swigconstant(_ssdef)
SS__AFR_ENABLED = _ssdef.SS__AFR_ENABLED

_ssdef.SS__AFR_NOT_ENABLED_swigconstant(_ssdef)
SS__AFR_NOT_ENABLED = _ssdef.SS__AFR_NOT_ENABLED

_ssdef.SS__SHELFERROR_swigconstant(_ssdef)
SS__SHELFERROR = _ssdef.SS__SHELFERROR

_ssdef.SS__PERSONANONGRATA_swigconstant(_ssdef)
SS__PERSONANONGRATA = _ssdef.SS__PERSONANONGRATA

_ssdef.SS__NOPRIVSTRT_swigconstant(_ssdef)
SS__NOPRIVSTRT = _ssdef.SS__NOPRIVSTRT

_ssdef.SS__NODETACH_swigconstant(_ssdef)
SS__NODETACH = _ssdef.SS__NODETACH

_ssdef.SS__NOCMKRNL_swigconstant(_ssdef)
SS__NOCMKRNL = _ssdef.SS__NOCMKRNL

_ssdef.SS__NOCMEXEC_swigconstant(_ssdef)
SS__NOCMEXEC = _ssdef.SS__NOCMEXEC

_ssdef.SS__NOSYSNAM_swigconstant(_ssdef)
SS__NOSYSNAM = _ssdef.SS__NOSYSNAM

_ssdef.SS__NOGRPNAM_swigconstant(_ssdef)
SS__NOGRPNAM = _ssdef.SS__NOGRPNAM

_ssdef.SS__NOALLSPOOL_swigconstant(_ssdef)
SS__NOALLSPOOL = _ssdef.SS__NOALLSPOOL

_ssdef.SS__NOIMPERSONATE_swigconstant(_ssdef)
SS__NOIMPERSONATE = _ssdef.SS__NOIMPERSONATE

_ssdef.SS__NODIAGNOSE_swigconstant(_ssdef)
SS__NODIAGNOSE = _ssdef.SS__NODIAGNOSE

_ssdef.SS__NOLOG_IO_swigconstant(_ssdef)
SS__NOLOG_IO = _ssdef.SS__NOLOG_IO

_ssdef.SS__NOGROUP_swigconstant(_ssdef)
SS__NOGROUP = _ssdef.SS__NOGROUP

_ssdef.SS__NOACNT_swigconstant(_ssdef)
SS__NOACNT = _ssdef.SS__NOACNT

_ssdef.SS__NOPRMCEB_swigconstant(_ssdef)
SS__NOPRMCEB = _ssdef.SS__NOPRMCEB

_ssdef.SS__NOPRMMBX_swigconstant(_ssdef)
SS__NOPRMMBX = _ssdef.SS__NOPRMMBX

_ssdef.SS__NOPSWAPM_swigconstant(_ssdef)
SS__NOPSWAPM = _ssdef.SS__NOPSWAPM

_ssdef.SS__NOALTPRI_swigconstant(_ssdef)
SS__NOALTPRI = _ssdef.SS__NOALTPRI

_ssdef.SS__NOSETPRV_swigconstant(_ssdef)
SS__NOSETPRV = _ssdef.SS__NOSETPRV

_ssdef.SS__NOTMPMBX_swigconstant(_ssdef)
SS__NOTMPMBX = _ssdef.SS__NOTMPMBX

_ssdef.SS__NOWORLD_swigconstant(_ssdef)
SS__NOWORLD = _ssdef.SS__NOWORLD

_ssdef.SS__NOMOUNT_swigconstant(_ssdef)
SS__NOMOUNT = _ssdef.SS__NOMOUNT

_ssdef.SS__NOOPER_swigconstant(_ssdef)
SS__NOOPER = _ssdef.SS__NOOPER

_ssdef.SS__NOEXQUOTA_swigconstant(_ssdef)
SS__NOEXQUOTA = _ssdef.SS__NOEXQUOTA

_ssdef.SS__NONETMBX_swigconstant(_ssdef)
SS__NONETMBX = _ssdef.SS__NONETMBX

_ssdef.SS__NOVOLPRO_swigconstant(_ssdef)
SS__NOVOLPRO = _ssdef.SS__NOVOLPRO

_ssdef.SS__NOPHY_IO_swigconstant(_ssdef)
SS__NOPHY_IO = _ssdef.SS__NOPHY_IO

_ssdef.SS__NOBUGCHK_swigconstant(_ssdef)
SS__NOBUGCHK = _ssdef.SS__NOBUGCHK

_ssdef.SS__NOPRMGBL_swigconstant(_ssdef)
SS__NOPRMGBL = _ssdef.SS__NOPRMGBL

_ssdef.SS__NOSYSGBL_swigconstant(_ssdef)
SS__NOSYSGBL = _ssdef.SS__NOSYSGBL

_ssdef.SS__NOPFNMAP_swigconstant(_ssdef)
SS__NOPFNMAP = _ssdef.SS__NOPFNMAP

_ssdef.SS__NOSHMEM_swigconstant(_ssdef)
SS__NOSHMEM = _ssdef.SS__NOSHMEM

_ssdef.SS__NOSYSPRV_swigconstant(_ssdef)
SS__NOSYSPRV = _ssdef.SS__NOSYSPRV

_ssdef.SS__NOBYPASS_swigconstant(_ssdef)
SS__NOBYPASS = _ssdef.SS__NOBYPASS

_ssdef.SS__NOSYSLCK_swigconstant(_ssdef)
SS__NOSYSLCK = _ssdef.SS__NOSYSLCK

_ssdef.SS__NOSHARE_swigconstant(_ssdef)
SS__NOSHARE = _ssdef.SS__NOSHARE

_ssdef.SS__NOUPGRADE_swigconstant(_ssdef)
SS__NOUPGRADE = _ssdef.SS__NOUPGRADE

_ssdef.SS__NODOWNGRADE_swigconstant(_ssdef)
SS__NODOWNGRADE = _ssdef.SS__NODOWNGRADE

_ssdef.SS__NOGRPPRV_swigconstant(_ssdef)
SS__NOGRPPRV = _ssdef.SS__NOGRPPRV

_ssdef.SS__NOREADALL_swigconstant(_ssdef)
SS__NOREADALL = _ssdef.SS__NOREADALL

_ssdef.SS__NOIMPORT_swigconstant(_ssdef)
SS__NOIMPORT = _ssdef.SS__NOIMPORT

_ssdef.SS__NOAUDIT_swigconstant(_ssdef)
SS__NOAUDIT = _ssdef.SS__NOAUDIT

_ssdef.SS__NOSECURITY_swigconstant(_ssdef)
SS__NOSECURITY = _ssdef.SS__NOSECURITY

_ssdef.SS__NOPRIVEND_swigconstant(_ssdef)
SS__NOPRIVEND = _ssdef.SS__NOPRIVEND

_ssdef.SS__EXQUOTASTRT_swigconstant(_ssdef)
SS__EXQUOTASTRT = _ssdef.SS__EXQUOTASTRT

_ssdef.SS__EXASTLM_swigconstant(_ssdef)
SS__EXASTLM = _ssdef.SS__EXASTLM

_ssdef.SS__EXBIOLM_swigconstant(_ssdef)
SS__EXBIOLM = _ssdef.SS__EXBIOLM

_ssdef.SS__EXBYTLM_swigconstant(_ssdef)
SS__EXBYTLM = _ssdef.SS__EXBYTLM

_ssdef.SS__EXDIOLM_swigconstant(_ssdef)
SS__EXDIOLM = _ssdef.SS__EXDIOLM

_ssdef.SS__EXFILLM_swigconstant(_ssdef)
SS__EXFILLM = _ssdef.SS__EXFILLM

_ssdef.SS__EXPGFLQUOTA_swigconstant(_ssdef)
SS__EXPGFLQUOTA = _ssdef.SS__EXPGFLQUOTA

_ssdef.SS__EXPRCLM_swigconstant(_ssdef)
SS__EXPRCLM = _ssdef.SS__EXPRCLM

_ssdef.SS__EXTQELM_swigconstant(_ssdef)
SS__EXTQELM = _ssdef.SS__EXTQELM

_ssdef.SS__EXENQLM_swigconstant(_ssdef)
SS__EXENQLM = _ssdef.SS__EXENQLM

_ssdef.SS__EXBUFOBJLM_swigconstant(_ssdef)
SS__EXBUFOBJLM = _ssdef.SS__EXBUFOBJLM

_ssdef.SS__EXQUOTAEND_swigconstant(_ssdef)
SS__EXQUOTAEND = _ssdef.SS__EXQUOTAEND

_ssdef.SS__MMSFAILED_swigconstant(_ssdef)
SS__MMSFAILED = _ssdef.SS__MMSFAILED

_ssdef.SS__QPOOL_DEL_BUSY_swigconstant(_ssdef)
SS__QPOOL_DEL_BUSY = _ssdef.SS__QPOOL_DEL_BUSY

_ssdef.SS__TOOFEWDEV_swigconstant(_ssdef)
SS__TOOFEWDEV = _ssdef.SS__TOOFEWDEV

_ssdef.SS__AVRWAIT_swigconstant(_ssdef)
SS__AVRWAIT = _ssdef.SS__AVRWAIT

_ssdef.SS__NO_MMS_swigconstant(_ssdef)
SS__NO_MMS = _ssdef.SS__NO_MMS

_ssdef.SS__MMSREADY_swigconstant(_ssdef)
SS__MMSREADY = _ssdef.SS__MMSREADY

_ssdef.SS__MMSNOTREADY_swigconstant(_ssdef)
SS__MMSNOTREADY = _ssdef.SS__MMSNOTREADY

_ssdef.SS__SKIP_CHECKS_swigconstant(_ssdef)
SS__SKIP_CHECKS = _ssdef.SS__SKIP_CHECKS

_ssdef.SS__NO_NOTIFY_swigconstant(_ssdef)
SS__NO_NOTIFY = _ssdef.SS__NO_NOTIFY

_ssdef.SS__SKIP_EXPIRATION_swigconstant(_ssdef)
SS__SKIP_EXPIRATION = _ssdef.SS__SKIP_EXPIRATION

_ssdef.SS__NOTATBOT_swigconstant(_ssdef)
SS__NOTATBOT = _ssdef.SS__NOTATBOT

_ssdef.SS__PREVDENS_swigconstant(_ssdef)
SS__PREVDENS = _ssdef.SS__PREVDENS

_ssdef.SS__RDBERR_swigconstant(_ssdef)
SS__RDBERR = _ssdef.SS__RDBERR

_ssdef.SS__MDMSERR_swigconstant(_ssdef)
SS__MDMSERR = _ssdef.SS__MDMSERR

_ssdef.SS__IVMEDTYP_swigconstant(_ssdef)
SS__IVMEDTYP = _ssdef.SS__IVMEDTYP

_ssdef.SS__IVDENS_swigconstant(_ssdef)
SS__IVDENS = _ssdef.SS__IVDENS

_ssdef.SS__IVPOOL_swigconstant(_ssdef)
SS__IVPOOL = _ssdef.SS__IVPOOL

_ssdef.SS__IVEXPDAT_swigconstant(_ssdef)
SS__IVEXPDAT = _ssdef.SS__IVEXPDAT

_ssdef.SS__NOCONFMEDIA_swigconstant(_ssdef)
SS__NOCONFMEDIA = _ssdef.SS__NOCONFMEDIA

_ssdef.SS__PTE_NOT_EMPTY_swigconstant(_ssdef)
SS__PTE_NOT_EMPTY = _ssdef.SS__PTE_NOT_EMPTY

_ssdef.SS__CPUNOTAVAIL_swigconstant(_ssdef)
SS__CPUNOTAVAIL = _ssdef.SS__CPUNOTAVAIL

_ssdef.SS__NOFASTPATH_swigconstant(_ssdef)
SS__NOFASTPATH = _ssdef.SS__NOFASTPATH

_ssdef.SS__EXITFORCED_swigconstant(_ssdef)
SS__EXITFORCED = _ssdef.SS__EXITFORCED

_ssdef.SS__FORCEX_swigconstant(_ssdef)
SS__FORCEX = _ssdef.SS__FORCEX

_ssdef.SS__NOTASSUMING_swigconstant(_ssdef)
SS__NOTASSUMING = _ssdef.SS__NOTASSUMING

_ssdef.SS__ALREADYASSUMING_swigconstant(_ssdef)
SS__ALREADYASSUMING = _ssdef.SS__ALREADYASSUMING

_ssdef.SS__INUSE_swigconstant(_ssdef)
SS__INUSE = _ssdef.SS__INUSE

_ssdef.SS__USERDISABLED_swigconstant(_ssdef)
SS__USERDISABLED = _ssdef.SS__USERDISABLED

_ssdef.SS__NOCHJIB_swigconstant(_ssdef)
SS__NOCHJIB = _ssdef.SS__NOCHJIB

_ssdef.SS__NOTSUPFS_swigconstant(_ssdef)
SS__NOTSUPFS = _ssdef.SS__NOTSUPFS

_ssdef.SS__INSFTHREADS_swigconstant(_ssdef)
SS__INSFTHREADS = _ssdef.SS__INSFTHREADS

_ssdef.SS__NOBUFOBJID_swigconstant(_ssdef)
SS__NOBUFOBJID = _ssdef.SS__NOBUFOBJID

_ssdef.SS__NODELPERMANENT_swigconstant(_ssdef)
SS__NODELPERMANENT = _ssdef.SS__NODELPERMANENT

_ssdef.SS__NOMEMRESID_swigconstant(_ssdef)
SS__NOMEMRESID = _ssdef.SS__NOMEMRESID

_ssdef.SS__MRES_PFNSMALL_swigconstant(_ssdef)
SS__MRES_PFNSMALL = _ssdef.SS__MRES_PFNSMALL

_ssdef.SS__MRES_INCON_swigconstant(_ssdef)
SS__MRES_INCON = _ssdef.SS__MRES_INCON

_ssdef.SS__NORESERVEDMEM_swigconstant(_ssdef)
SS__NORESERVEDMEM = _ssdef.SS__NORESERVEDMEM

_ssdef.SS__RESERVEDMEMUSED_swigconstant(_ssdef)
SS__RESERVEDMEMUSED = _ssdef.SS__RESERVEDMEMUSED

_ssdef.SS__RES_MEM_INCON_swigconstant(_ssdef)
SS__RES_MEM_INCON = _ssdef.SS__RES_MEM_INCON

_ssdef.SS__NOSHPTS_swigconstant(_ssdef)
SS__NOSHPTS = _ssdef.SS__NOSHPTS

_ssdef.SS__FLUSHFAIL_swigconstant(_ssdef)
SS__FLUSHFAIL = _ssdef.SS__FLUSHFAIL

_ssdef.SS__NOTINSTALLED_swigconstant(_ssdef)
SS__NOTINSTALLED = _ssdef.SS__NOTINSTALLED

_ssdef.SS__POOLDEVEXISTS_swigconstant(_ssdef)
SS__POOLDEVEXISTS = _ssdef.SS__POOLDEVEXISTS

_ssdef.SS__NOUNITS_swigconstant(_ssdef)
SS__NOUNITS = _ssdef.SS__NOUNITS

_ssdef.SS__NOTAPOOL_swigconstant(_ssdef)
SS__NOTAPOOL = _ssdef.SS__NOTAPOOL

_ssdef.SS__MISSINGUNITS_swigconstant(_ssdef)
SS__MISSINGUNITS = _ssdef.SS__MISSINGUNITS

_ssdef.SS__DISKDEVEXISTS_swigconstant(_ssdef)
SS__DISKDEVEXISTS = _ssdef.SS__DISKDEVEXISTS

_ssdef.SS__TOOMANYUNITS_swigconstant(_ssdef)
SS__TOOMANYUNITS = _ssdef.SS__TOOMANYUNITS

_ssdef.SS__NOTINPOOL_swigconstant(_ssdef)
SS__NOTINPOOL = _ssdef.SS__NOTINPOOL

_ssdef.SS__WRONGPOOL_swigconstant(_ssdef)
SS__WRONGPOOL = _ssdef.SS__WRONGPOOL

_ssdef.SS__ALRBOUND_swigconstant(_ssdef)
SS__ALRBOUND = _ssdef.SS__ALRBOUND

_ssdef.SS__NOTPOOLMOUNTED_swigconstant(_ssdef)
SS__NOTPOOLMOUNTED = _ssdef.SS__NOTPOOLMOUNTED

_ssdef.SS__POOLINUSE_swigconstant(_ssdef)
SS__POOLINUSE = _ssdef.SS__POOLINUSE

_ssdef.SS__DISKINUSE_swigconstant(_ssdef)
SS__DISKINUSE = _ssdef.SS__DISKINUSE

_ssdef.SS__SDDISABLED_swigconstant(_ssdef)
SS__SDDISABLED = _ssdef.SS__SDDISABLED

_ssdef.SS__UNITINPOOL_swigconstant(_ssdef)
SS__UNITINPOOL = _ssdef.SS__UNITINPOOL

_ssdef.SS__FAMILYTOOBIG_swigconstant(_ssdef)
SS__FAMILYTOOBIG = _ssdef.SS__FAMILYTOOBIG

_ssdef.SS__NODISKNAME_swigconstant(_ssdef)
SS__NODISKNAME = _ssdef.SS__NODISKNAME

_ssdef.SS__DISKNAMEEXISTS_swigconstant(_ssdef)
SS__DISKNAMEEXISTS = _ssdef.SS__DISKNAMEEXISTS

_ssdef.SS__INSUFFREESEGS_swigconstant(_ssdef)
SS__INSUFFREESEGS = _ssdef.SS__INSUFFREESEGS

_ssdef.SS__NOTBOUND_swigconstant(_ssdef)
SS__NOTBOUND = _ssdef.SS__NOTBOUND

_ssdef.SS__TOOMANYFRAGS_swigconstant(_ssdef)
SS__TOOMANYFRAGS = _ssdef.SS__TOOMANYFRAGS

_ssdef.SS__TOOMANYFAMILIES_swigconstant(_ssdef)
SS__TOOMANYFAMILIES = _ssdef.SS__TOOMANYFAMILIES

_ssdef.SS__DISKISBOUND_swigconstant(_ssdef)
SS__DISKISBOUND = _ssdef.SS__DISKISBOUND

_ssdef.SS__SNAPINFAM_swigconstant(_ssdef)
SS__SNAPINFAM = _ssdef.SS__SNAPINFAM

_ssdef.SS__CHKSNAPVER_swigconstant(_ssdef)
SS__CHKSNAPVER = _ssdef.SS__CHKSNAPVER

_ssdef.SS__BADSNAPVER_swigconstant(_ssdef)
SS__BADSNAPVER = _ssdef.SS__BADSNAPVER

_ssdef.SS__SD_RESERVED4_swigconstant(_ssdef)
SS__SD_RESERVED4 = _ssdef.SS__SD_RESERVED4

_ssdef.SS__SD_RESERVED5_swigconstant(_ssdef)
SS__SD_RESERVED5 = _ssdef.SS__SD_RESERVED5

_ssdef.SS__SECREFOVF_swigconstant(_ssdef)
SS__SECREFOVF = _ssdef.SS__SECREFOVF

_ssdef.SS__DATAERR_swigconstant(_ssdef)
SS__DATAERR = _ssdef.SS__DATAERR

_ssdef.SS__INVPFN_swigconstant(_ssdef)
SS__INVPFN = _ssdef.SS__INVPFN

_ssdef.SS__INV_SHMEM_swigconstant(_ssdef)
SS__INV_SHMEM = _ssdef.SS__INV_SHMEM

_ssdef.SS__INV_SHM_CPP_swigconstant(_ssdef)
SS__INV_SHM_CPP = _ssdef.SS__INV_SHM_CPP

_ssdef.SS__INV_SHM_REG_swigconstant(_ssdef)
SS__INV_SHM_REG = _ssdef.SS__INV_SHM_REG

_ssdef.SS__ONEMAPPER_swigconstant(_ssdef)
SS__ONEMAPPER = _ssdef.SS__ONEMAPPER

_ssdef.SS__NOSUCHEXT_swigconstant(_ssdef)
SS__NOSUCHEXT = _ssdef.SS__NOSUCHEXT

_ssdef.SS__CBKEXISTS_swigconstant(_ssdef)
SS__CBKEXISTS = _ssdef.SS__CBKEXISTS

_ssdef.SS__NOSUCHCBK_swigconstant(_ssdef)
SS__NOSUCHCBK = _ssdef.SS__NOSUCHCBK

_ssdef.SS__NOTAMEMBER_swigconstant(_ssdef)
SS__NOTAMEMBER = _ssdef.SS__NOTAMEMBER

_ssdef.SS__GLXSPIUNAVAIL_swigconstant(_ssdef)
SS__GLXSPIUNAVAIL = _ssdef.SS__GLXSPIUNAVAIL

_ssdef.SS__MPDEVILLCURPATH_swigconstant(_ssdef)
SS__MPDEVILLCURPATH = _ssdef.SS__MPDEVILLCURPATH

_ssdef.SS__MPDEVINCOMPAT_swigconstant(_ssdef)
SS__MPDEVINCOMPAT = _ssdef.SS__MPDEVINCOMPAT

_ssdef.SS__MPDEVNOT_swigconstant(_ssdef)
SS__MPDEVNOT = _ssdef.SS__MPDEVNOT

_ssdef.SS__MPDEVNOTCONF_swigconstant(_ssdef)
SS__MPDEVNOTCONF = _ssdef.SS__MPDEVNOTCONF

_ssdef.SS__PERSONARESERVED_swigconstant(_ssdef)
SS__PERSONARESERVED = _ssdef.SS__PERSONARESERVED

_ssdef.SS__WRONGDRV_swigconstant(_ssdef)
SS__WRONGDRV = _ssdef.SS__WRONGDRV

_ssdef.SS__BADRAD_swigconstant(_ssdef)
SS__BADRAD = _ssdef.SS__BADRAD

_ssdef.SS__INVQSRFNC_swigconstant(_ssdef)
SS__INVQSRFNC = _ssdef.SS__INVQSRFNC

_ssdef.SS__NOQIOSERVER_swigconstant(_ssdef)
SS__NOQIOSERVER = _ssdef.SS__NOQIOSERVER

_ssdef.SS__INCLASS_swigconstant(_ssdef)
SS__INCLASS = _ssdef.SS__INCLASS

_ssdef.SS__INVBOOTDEV_swigconstant(_ssdef)
SS__INVBOOTDEV = _ssdef.SS__INVBOOTDEV

_ssdef.SS__CLIENT_UNAVAILABLE_swigconstant(_ssdef)
SS__CLIENT_UNAVAILABLE = _ssdef.SS__CLIENT_UNAVAILABLE

_ssdef.SS__CONFIGFILE_ERROR_swigconstant(_ssdef)
SS__CONFIGFILE_ERROR = _ssdef.SS__CONFIGFILE_ERROR

_ssdef.SS__INVDEVALLOC_swigconstant(_ssdef)
SS__INVDEVALLOC = _ssdef.SS__INVDEVALLOC

_ssdef.SS__DEVICE_UNAVAILABLE_swigconstant(_ssdef)
SS__DEVICE_UNAVAILABLE = _ssdef.SS__DEVICE_UNAVAILABLE

_ssdef.SS__INVDEVMOUNT_swigconstant(_ssdef)
SS__INVDEVMOUNT = _ssdef.SS__INVDEVMOUNT

_ssdef.SS__LOGGING_DISABLED_swigconstant(_ssdef)
SS__LOGGING_DISABLED = _ssdef.SS__LOGGING_DISABLED

_ssdef.SS__NOSUCHCLIENT_swigconstant(_ssdef)
SS__NOSUCHCLIENT = _ssdef.SS__NOSUCHCLIENT

_ssdef.SS__NOSUCHDEVICE_swigconstant(_ssdef)
SS__NOSUCHDEVICE = _ssdef.SS__NOSUCHDEVICE

_ssdef.SS__NOSUCHFILTER_swigconstant(_ssdef)
SS__NOSUCHFILTER = _ssdef.SS__NOSUCHFILTER

_ssdef.SS__NOSUCHPATH_swigconstant(_ssdef)
SS__NOSUCHPATH = _ssdef.SS__NOSUCHPATH

_ssdef.SS__NOSUCHSERVER_swigconstant(_ssdef)
SS__NOSUCHSERVER = _ssdef.SS__NOSUCHSERVER

_ssdef.SS__RQSTIMOUT_swigconstant(_ssdef)
SS__RQSTIMOUT = _ssdef.SS__RQSTIMOUT

_ssdef.SS__SERVER_UNAVAILABLE_swigconstant(_ssdef)
SS__SERVER_UNAVAILABLE = _ssdef.SS__SERVER_UNAVAILABLE

_ssdef.SS__QSRVINTERR_swigconstant(_ssdef)
SS__QSRVINTERR = _ssdef.SS__QSRVINTERR

_ssdef.SS__NOADD_swigconstant(_ssdef)
SS__NOADD = _ssdef.SS__NOADD

_ssdef.SS__SYSTEMUIC_swigconstant(_ssdef)
SS__SYSTEMUIC = _ssdef.SS__SYSTEMUIC

_ssdef.SS__NOSUCHQPOOLID_swigconstant(_ssdef)
SS__NOSUCHQPOOLID = _ssdef.SS__NOSUCHQPOOLID

_ssdef.SS__PATHAMBIG_swigconstant(_ssdef)
SS__PATHAMBIG = _ssdef.SS__PATHAMBIG

_ssdef.SS__INVMVIP_swigconstant(_ssdef)
SS__INVMVIP = _ssdef.SS__INVMVIP

_ssdef.SS__NOPATHAVAIL_swigconstant(_ssdef)
SS__NOPATHAVAIL = _ssdef.SS__NOPATHAVAIL

_ssdef.SS__NOENACURINV_swigconstant(_ssdef)
SS__NOENACURINV = _ssdef.SS__NOENACURINV

_ssdef.SS__TRUSTCONF_swigconstant(_ssdef)
SS__TRUSTCONF = _ssdef.SS__TRUSTCONF

_ssdef.SS__QIO_FAULT_swigconstant(_ssdef)
SS__QIO_FAULT = _ssdef.SS__QIO_FAULT

_ssdef.SS__HBVS_REDO_IO_swigconstant(_ssdef)
SS__HBVS_REDO_IO = _ssdef.SS__HBVS_REDO_IO

_ssdef.SS__TOOMANYPERSONA_swigconstant(_ssdef)
SS__TOOMANYPERSONA = _ssdef.SS__TOOMANYPERSONA

_ssdef.SS__INVKTLIM_swigconstant(_ssdef)
SS__INVKTLIM = _ssdef.SS__INVKTLIM

_ssdef.SS__MAXNAMPOL_swigconstant(_ssdef)
SS__MAXNAMPOL = _ssdef.SS__MAXNAMPOL

_ssdef.SS__HBMMENABLED_swigconstant(_ssdef)
SS__HBMMENABLED = _ssdef.SS__HBMMENABLED

_ssdef.SS__NOMODNONEPOL_swigconstant(_ssdef)
SS__NOMODNONEPOL = _ssdef.SS__NOMODNONEPOL

_ssdef.SS__SHADFEATNOMNT_swigconstant(_ssdef)
SS__SHADFEATNOMNT = _ssdef.SS__SHADFEATNOMNT

_ssdef.SS__NOTSUPALLNODES_swigconstant(_ssdef)
SS__NOTSUPALLNODES = _ssdef.SS__NOTSUPALLNODES

_ssdef.SS__WLGCANTHBMM_swigconstant(_ssdef)
SS__WLGCANTHBMM = _ssdef.SS__WLGCANTHBMM

_ssdef.SS__CALLUNDEFSYM_swigconstant(_ssdef)
SS__CALLUNDEFSYM = _ssdef.SS__CALLUNDEFSYM

_ssdef.SS__NOADDMCPYMBR_swigconstant(_ssdef)
SS__NOADDMCPYMBR = _ssdef.SS__NOADDMCPYMBR

_ssdef.SS__CANTDODDS_swigconstant(_ssdef)
SS__CANTDODDS = _ssdef.SS__CANTDODDS

_ssdef.SS__TOOMANYMBRS_swigconstant(_ssdef)
SS__TOOMANYMBRS = _ssdef.SS__TOOMANYMBRS

_ssdef.SS__SCBREADFAIL_swigconstant(_ssdef)
SS__SCBREADFAIL = _ssdef.SS__SCBREADFAIL

_ssdef.SS__SCBWRITEFAIL_swigconstant(_ssdef)
SS__SCBWRITEFAIL = _ssdef.SS__SCBWRITEFAIL

_ssdef.SS__NOMEMFORWBM_swigconstant(_ssdef)
SS__NOMEMFORWBM = _ssdef.SS__NOMEMFORWBM

_ssdef.SS__MUSTDMTVU_swigconstant(_ssdef)
SS__MUSTDMTVU = _ssdef.SS__MUSTDMTVU

_ssdef.SS__ONLYSRCMUSTSTAY_swigconstant(_ssdef)
SS__ONLYSRCMUSTSTAY = _ssdef.SS__ONLYSRCMUSTSTAY

_ssdef.SS__NOWBMDURINGCOPY_swigconstant(_ssdef)
SS__NOWBMDURINGCOPY = _ssdef.SS__NOWBMDURINGCOPY

_ssdef.SS__WBMERR_swigconstant(_ssdef)
SS__WBMERR = _ssdef.SS__WBMERR

_ssdef.SS__BADPOLCHAR_swigconstant(_ssdef)
SS__BADPOLCHAR = _ssdef.SS__BADPOLCHAR

_ssdef.SS__HBMMVERSIONBAD_swigconstant(_ssdef)
SS__HBMMVERSIONBAD = _ssdef.SS__HBMMVERSIONBAD

_ssdef.SS__ANADSKSHDBBLK_swigconstant(_ssdef)
SS__ANADSKSHDBBLK = _ssdef.SS__ANADSKSHDBBLK

_ssdef.SS__HBMMBADPOLSPEC_swigconstant(_ssdef)
SS__HBMMBADPOLSPEC = _ssdef.SS__HBMMBADPOLSPEC

_ssdef.SS__NOSHADOWSERVER_swigconstant(_ssdef)
SS__NOSHADOWSERVER = _ssdef.SS__NOSHADOWSERVER

_ssdef.SS__GAMEOVER_swigconstant(_ssdef)
SS__GAMEOVER = _ssdef.SS__GAMEOVER

_ssdef.SS__SYSAPMIN_swigconstant(_ssdef)
SS__SYSAPMIN = _ssdef.SS__SYSAPMIN

_ssdef.SS__SYSAPMAX_swigconstant(_ssdef)
SS__SYSAPMAX = _ssdef.SS__SYSAPMAX
# This file is compatible with both classic and new-style classes.


