# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_chpdef', [dirname(__file__)])
        except ImportError:
            import _chpdef
            return _chpdef
        if fp is not None:
            try:
                _mod = imp.load_module('_chpdef', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _chpdef = swig_import_helper()
    del swig_import_helper
else:
    import _chpdef
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_chpdef.CHP__END_swigconstant(_chpdef)
CHP__END = _chpdef.CHP__END

_chpdef.CHP__ACCESS_swigconstant(_chpdef)
CHP__ACCESS = _chpdef.CHP__ACCESS

_chpdef.CHP__FLAGS_swigconstant(_chpdef)
CHP__FLAGS = _chpdef.CHP__FLAGS

_chpdef.CHP__PRIV_swigconstant(_chpdef)
CHP__PRIV = _chpdef.CHP__PRIV

_chpdef.CHP__ACMODE_swigconstant(_chpdef)
CHP__ACMODE = _chpdef.CHP__ACMODE

_chpdef.CHP__ACCLASS_swigconstant(_chpdef)
CHP__ACCLASS = _chpdef.CHP__ACCLASS

_chpdef.CHP__RIGHTS_swigconstant(_chpdef)
CHP__RIGHTS = _chpdef.CHP__RIGHTS

_chpdef.CHP__ADD_RIGHTS_swigconstant(_chpdef)
CHP__ADD_RIGHTS = _chpdef.CHP__ADD_RIGHTS

_chpdef.CHP__MODE_swigconstant(_chpdef)
CHP__MODE = _chpdef.CHP__MODE

_chpdef.CHP__MODES_swigconstant(_chpdef)
CHP__MODES = _chpdef.CHP__MODES

_chpdef.CHP__MIN_CLASS_swigconstant(_chpdef)
CHP__MIN_CLASS = _chpdef.CHP__MIN_CLASS

_chpdef.CHP__MAX_CLASS_swigconstant(_chpdef)
CHP__MAX_CLASS = _chpdef.CHP__MAX_CLASS

_chpdef.CHP__OWNER_swigconstant(_chpdef)
CHP__OWNER = _chpdef.CHP__OWNER

_chpdef.CHP__PROT_swigconstant(_chpdef)
CHP__PROT = _chpdef.CHP__PROT

_chpdef.CHP__ACL_swigconstant(_chpdef)
CHP__ACL = _chpdef.CHP__ACL

_chpdef.CHP__AUDIT_NAME_swigconstant(_chpdef)
CHP__AUDIT_NAME = _chpdef.CHP__AUDIT_NAME

_chpdef.CHP__ALARM_NAME_swigconstant(_chpdef)
CHP__ALARM_NAME = _chpdef.CHP__ALARM_NAME

_chpdef.CHP__MATCHED_ACE_swigconstant(_chpdef)
CHP__MATCHED_ACE = _chpdef.CHP__MATCHED_ACE

_chpdef.CHP__PRIVUSED_swigconstant(_chpdef)
CHP__PRIVUSED = _chpdef.CHP__PRIVUSED

_chpdef.CHP__AUDIT_LIST_swigconstant(_chpdef)
CHP__AUDIT_LIST = _chpdef.CHP__AUDIT_LIST

_chpdef.CHP__OBJECT_NAME_swigconstant(_chpdef)
CHP__OBJECT_NAME = _chpdef.CHP__OBJECT_NAME

_chpdef.CHP__OBJECT_CLASS_swigconstant(_chpdef)
CHP__OBJECT_CLASS = _chpdef.CHP__OBJECT_CLASS

_chpdef.CHP__UIC_swigconstant(_chpdef)
CHP__UIC = _chpdef.CHP__UIC

_chpdef.CHP__OBJECT_SPECIFIC_swigconstant(_chpdef)
CHP__OBJECT_SPECIFIC = _chpdef.CHP__OBJECT_SPECIFIC

_chpdef.CHP__MAX_CODE_swigconstant(_chpdef)
CHP__MAX_CODE = _chpdef.CHP__MAX_CODE

_chpdef.CHP__ADDRIGHTS_swigconstant(_chpdef)
CHP__ADDRIGHTS = _chpdef.CHP__ADDRIGHTS

_chpdef.CHP__MINCLASS_swigconstant(_chpdef)
CHP__MINCLASS = _chpdef.CHP__MINCLASS

_chpdef.CHP__MAXCLASS_swigconstant(_chpdef)
CHP__MAXCLASS = _chpdef.CHP__MAXCLASS

_chpdef.CHP__AUDITNAME_swigconstant(_chpdef)
CHP__AUDITNAME = _chpdef.CHP__AUDITNAME

_chpdef.CHP__ALARMNAME_swigconstant(_chpdef)
CHP__ALARMNAME = _chpdef.CHP__ALARMNAME

_chpdef.CHP__MATCHEDACE_swigconstant(_chpdef)
CHP__MATCHEDACE = _chpdef.CHP__MATCHEDACE

_chpdef.CHP__CLASS_swigconstant(_chpdef)
CHP__CLASS = _chpdef.CHP__CLASS

_chpdef.CHP_K_MATCHED_ACE_LENGTH_swigconstant(_chpdef)
CHP_K_MATCHED_ACE_LENGTH = _chpdef.CHP_K_MATCHED_ACE_LENGTH

_chpdef.CHP_K_ALARM_LENGTH_swigconstant(_chpdef)
CHP_K_ALARM_LENGTH = _chpdef.CHP_K_ALARM_LENGTH

_chpdef.CHP_K_AUDIT_LENGTH_swigconstant(_chpdef)
CHP_K_AUDIT_LENGTH = _chpdef.CHP_K_AUDIT_LENGTH

_chpdef.CHP_M_SYSPRV_swigconstant(_chpdef)
CHP_M_SYSPRV = _chpdef.CHP_M_SYSPRV

_chpdef.CHP_M_BYPASS_swigconstant(_chpdef)
CHP_M_BYPASS = _chpdef.CHP_M_BYPASS

_chpdef.CHP_M_UPGRADE_swigconstant(_chpdef)
CHP_M_UPGRADE = _chpdef.CHP_M_UPGRADE

_chpdef.CHP_M_DOWNGRADE_swigconstant(_chpdef)
CHP_M_DOWNGRADE = _chpdef.CHP_M_DOWNGRADE

_chpdef.CHP_M_GRPPRV_swigconstant(_chpdef)
CHP_M_GRPPRV = _chpdef.CHP_M_GRPPRV

_chpdef.CHP_M_READALL_swigconstant(_chpdef)
CHP_M_READALL = _chpdef.CHP_M_READALL

_chpdef.CHP_M_OPER_swigconstant(_chpdef)
CHP_M_OPER = _chpdef.CHP_M_OPER

_chpdef.CHP_M_GRPNAM_swigconstant(_chpdef)
CHP_M_GRPNAM = _chpdef.CHP_M_GRPNAM

_chpdef.CHP_M_SYSNAM_swigconstant(_chpdef)
CHP_M_SYSNAM = _chpdef.CHP_M_SYSNAM

_chpdef.CHP_M_GROUP_swigconstant(_chpdef)
CHP_M_GROUP = _chpdef.CHP_M_GROUP

_chpdef.CHP_M_WORLD_swigconstant(_chpdef)
CHP_M_WORLD = _chpdef.CHP_M_WORLD

_chpdef.CHP_M_PRMCEB_swigconstant(_chpdef)
CHP_M_PRMCEB = _chpdef.CHP_M_PRMCEB

_chpdef.CHP_K_NUMBER_OF_PRIVS_swigconstant(_chpdef)
CHP_K_NUMBER_OF_PRIVS = _chpdef.CHP_K_NUMBER_OF_PRIVS

_chpdef.CHP_S_PRIVS_USED_BITS_swigconstant(_chpdef)
CHP_S_PRIVS_USED_BITS = _chpdef.CHP_S_PRIVS_USED_BITS

_chpdef.CHP_M_OBSERVE_swigconstant(_chpdef)
CHP_M_OBSERVE = _chpdef.CHP_M_OBSERVE

_chpdef.CHP_M_ALTER_swigconstant(_chpdef)
CHP_M_ALTER = _chpdef.CHP_M_ALTER

_chpdef.CHP_M_READ_swigconstant(_chpdef)
CHP_M_READ = _chpdef.CHP_M_READ

_chpdef.CHP_M_WRITE_swigconstant(_chpdef)
CHP_M_WRITE = _chpdef.CHP_M_WRITE

_chpdef.CHP_M_USEREADALL_swigconstant(_chpdef)
CHP_M_USEREADALL = _chpdef.CHP_M_USEREADALL

_chpdef.CHP_M_AUDIT_swigconstant(_chpdef)
CHP_M_AUDIT = _chpdef.CHP_M_AUDIT

_chpdef.CHP_M_NOFAILAUD_swigconstant(_chpdef)
CHP_M_NOFAILAUD = _chpdef.CHP_M_NOFAILAUD

_chpdef.CHP_M_NOSUCCAUD_swigconstant(_chpdef)
CHP_M_NOSUCCAUD = _chpdef.CHP_M_NOSUCCAUD

_chpdef.CHP_M_DELETE_swigconstant(_chpdef)
CHP_M_DELETE = _chpdef.CHP_M_DELETE

_chpdef.CHP_M_MANDATORY_swigconstant(_chpdef)
CHP_M_MANDATORY = _chpdef.CHP_M_MANDATORY

_chpdef.CHP_M_FLUSH_swigconstant(_chpdef)
CHP_M_FLUSH = _chpdef.CHP_M_FLUSH

_chpdef.CHP_M_CREATE_swigconstant(_chpdef)
CHP_M_CREATE = _chpdef.CHP_M_CREATE

_chpdef.CHP_M_INTERNAL_swigconstant(_chpdef)
CHP_M_INTERNAL = _chpdef.CHP_M_INTERNAL

_chpdef.CHP_M_SERVER_swigconstant(_chpdef)
CHP_M_SERVER = _chpdef.CHP_M_SERVER

_chpdef.CHP_S_FLAG_BITS_swigconstant(_chpdef)
CHP_S_FLAG_BITS = _chpdef.CHP_S_FLAG_BITS

_chpdef.CHP_M_NOACCESS_swigconstant(_chpdef)
CHP_M_NOACCESS = _chpdef.CHP_M_NOACCESS

_chpdef.CHP_M_REMDUPID_swigconstant(_chpdef)
CHP_M_REMDUPID = _chpdef.CHP_M_REMDUPID

_chpdef.CHP_M_INCSYSID_swigconstant(_chpdef)
CHP_M_INCSYSID = _chpdef.CHP_M_INCSYSID

_chpdef.CHP_M_INCIMGID_swigconstant(_chpdef)
CHP_M_INCIMGID = _chpdef.CHP_M_INCIMGID

_chpdef.CHP_M_DEFPRIV_swigconstant(_chpdef)
CHP_M_DEFPRIV = _chpdef.CHP_M_DEFPRIV

_chpdef.CHP_M_DEFCLASS_swigconstant(_chpdef)
CHP_M_DEFCLASS = _chpdef.CHP_M_DEFCLASS

_chpdef.CHP_S_PROFILE_FLAGS_swigconstant(_chpdef)
CHP_S_PROFILE_FLAGS = _chpdef.CHP_S_PROFILE_FLAGS
# This file is compatible with both classic and new-style classes.


